// VOCABLY-TZ.md §17.3 (SEO) — "Har so'z uchun ochiq sahifa: /lugat/resilient —
// 'resilient tarjimasi, talaffuzi, misollar' → uzun dumli qidiruv trafigi".
//
// MUHIM ARXITEKTURA IZOHI: bu ro'yxat foydalanuvchining shaxsiy so'z bazasi
// (User.categories[].words[], FAZA1'da qaror qilinganidek — har foydalanuvchida
// alohida saqlanadi) BILAN ALOQASI YO'Q. Bu — faqat marketing/SEO maqsadida,
// qo'lda tanlangan, statik kontent (hech qanday DB so'rovisiz, to'liq statik
// generatsiya qilinadi). Global "so'z banki" infratuzilmasi qurilmadi — bu
// FAZA1 qaroriga zid bo'lardi; shu o'rniga chegaralangan, boshqarish oson bo'lgan
// statik ro'yxat tanlandi. Ko'proq so'z qo'shish uchun shu massivga yangi obyekt
// qo'shish kifoya (src/app/lugat/[word]/page.jsx generateStaticParams shu yerdan o'qiydi).
export const SEO_WORDS = [
  {
    word: 'resilient',
    slug: 'resilient',
    pos: 'adjective',
    ipa: '/rɪˈzɪliənt/',
    translations: ['bardoshli', 'chidamli', 'tez tiklanadigan'],
    definitionEn: 'able to recover quickly from difficult conditions',
    definitionUz: "qiyinchilikdan tez qayta tiklana oladigan",
    examples: [
      { en: 'Children are remarkably resilient.', uz: 'Bolalar hayratlanarli darajada bardoshli.' },
      { en: 'The economy proved resilient to the shock.', uz: 'Iqtisodiyot zarbaga bardoshli chiqdi.' },
    ],
    collocations: ['highly resilient', 'resilient economy', 'prove resilient'],
    wordFamily: [{ form: 'resilience', pos: 'noun' }, { form: 'resiliently', pos: 'adverb' }],
    synonymsEn: ['tough', 'durable', 'hardy'],
    antonyms: ['fragile', 'vulnerable'],
    cefr: 'B2',
    mnemonicUz: "RE-SILIENT — 'RE' qayta + 'SILIENT' sakramoq → qiyinchilikdan qayta sakraydigan",
  },
  {
    word: 'mitigate',
    slug: 'mitigate',
    pos: 'verb',
    ipa: '/ˈmɪtɪɡeɪt/',
    translations: ['yumshatmoq', 'kamaytirmoq', 'yengillashtirmoq'],
    definitionEn: 'to make something less severe, serious, or painful',
    definitionUz: "biror narsaning og'irligini yoki ta'sirini kamaytirmoq",
    examples: [
      { en: 'The new policy aims to mitigate the effects of climate change.', uz: "Yangi siyosat iqlim o'zgarishi ta'sirini yumshatishga qaratilgan." },
      { en: 'They took steps to mitigate the risk of flooding.', uz: "Ular suv toshqini xavfini kamaytirish uchun chora ko'rdilar." },
    ],
    collocations: ['mitigate the risk', 'mitigate against', 'help mitigate'],
    wordFamily: [{ form: 'mitigation', pos: 'noun' }],
    synonymsEn: ['alleviate', 'reduce', 'ease'],
    antonyms: ['aggravate', 'worsen'],
    cefr: 'C1',
    mnemonicUz: "MITIGATE — 'miti(ng) gate' — kichraytiruvchi darvoza, muammoning kattaligini kichraytiradi",
  },
  {
    word: 'unprecedented',
    slug: 'unprecedented',
    pos: 'adjective',
    ipa: '/ʌnˈpresɪdentɪd/',
    translations: ["misli ko'rilmagan", 'tengsiz', 'ilgari bo\'lmagan'],
    definitionEn: 'never having happened or existed before',
    definitionUz: "ilgari hech qachon bo'lmagan, misli ko'rilmagan",
    examples: [
      { en: 'The city faced unprecedented levels of rainfall.', uz: "Shahar misli ko'rilmagan darajadagi yomg'irga duch keldi." },
      { en: 'It was an unprecedented decision for the company.', uz: "Bu kompaniya uchun ilgari bo'lmagan qaror edi." },
    ],
    collocations: ['unprecedented levels', 'unprecedented growth', 'an unprecedented move'],
    wordFamily: [{ form: 'precedent', pos: 'noun' }, { form: 'precedented', pos: 'adjective' }],
    synonymsEn: ['unparalleled', 'unheard-of', 'novel'],
    antonyms: ['common', 'usual'],
    cefr: 'C1',
    mnemonicUz: "UN-PRECEDENTED — 'precedent' (misol/hujjat) YO'Q, demak oldin bo'lmagan",
  },
  {
    word: 'arise',
    slug: 'arise',
    pos: 'verb',
    ipa: '/əˈraɪz/',
    translations: ["paydo bo'lmoq", 'yuzaga kelmoq'],
    definitionEn: 'to begin to happen or come into existence',
    definitionUz: "vujudga kelmoq, boshlanmoq",
    examples: [
      { en: 'A problem arose during the meeting.', uz: "Yig'ilish davomida muammo yuzaga keldi." },
      { en: 'Opportunities like this rarely arise.', uz: "Bunday imkoniyatlar kamdan-kam paydo bo'ladi." },
    ],
    collocations: ['arise from', 'a problem arises', 'the need arises'],
    wordFamily: [{ form: 'arisen', pos: 'verb (o\'tgan zamon sifatdoshi)' }],
    synonymsEn: ['emerge', 'occur', 'appear'],
    antonyms: ['disappear', 'vanish'],
    cefr: 'B1',
    mnemonicUz: "A-RISE — 'rise' ko'tarilmoq, muammo 'ko'tarilib' yuzaga chiqadi",
  },
  {
    word: 'thorough',
    slug: 'thorough',
    pos: 'adjective',
    ipa: '/ˈθʌrə/',
    translations: ['puxta', 'atroflicha', "to'liq"],
    definitionEn: 'complete, with great attention to every detail',
    definitionUz: "har bir detalga e'tibor berilgan, puxta",
    examples: [
      { en: 'She did a thorough review of the report.', uz: "U hisobotni puxta ko'rib chiqdi." },
      { en: 'The police conducted a thorough investigation.', uz: "Politsiya atroflicha tergov o'tkazdi." },
    ],
    collocations: ['thorough review', 'thorough investigation', 'thorough understanding'],
    wordFamily: [{ form: 'thoroughly', pos: 'adverb' }, { form: 'thoroughness', pos: 'noun' }],
    synonymsEn: ['comprehensive', 'meticulous', 'exhaustive'],
    antonyms: ['careless', 'superficial'],
    cefr: 'B2',
    mnemonicUz: "THOROUGH — 'through' (orqali) so'ziga o'xshaydi — muammoni oxirigacha, har tomondan ko'rib chiqadi",
  },
  {
    word: 'ambiguous',
    slug: 'ambiguous',
    pos: 'adjective',
    ipa: '/æmˈbɪɡjuəs/',
    translations: ['noaniq', "ikki ma'noli"],
    definitionEn: 'having more than one possible meaning; unclear',
    definitionUz: "aniq bir ma'noga ega bo'lmagan, ikki xil talqin qilinadigan",
    examples: [
      { en: 'His answer was deliberately ambiguous.', uz: 'Uning javobi ataylab noaniq edi.' },
      { en: 'The instructions were ambiguous and confused everyone.', uz: "Ko'rsatmalar noaniq bo'lib, hammani chalg'itdi." },
    ],
    collocations: ['deliberately ambiguous', 'morally ambiguous', 'remain ambiguous'],
    wordFamily: [{ form: 'ambiguity', pos: 'noun' }, { form: 'ambiguously', pos: 'adverb' }],
    synonymsEn: ['unclear', 'vague', 'equivocal'],
    antonyms: ['clear', 'unambiguous'],
    cefr: 'C1',
    mnemonicUz: "AMBI-GUOUS — 'ambi' ikkilamchi (masalan 'ambidextrous' ikki qo'l) → ikki ma'noli",
  },
  {
    word: 'commence',
    slug: 'commence',
    pos: 'verb',
    ipa: '/kəˈmens/',
    translations: ['boshlamoq'],
    definitionEn: 'to begin; to start',
    definitionUz: 'boshlanmoq, boshlamoq (rasmiy uslubda)',
    examples: [
      { en: 'The ceremony will commence at noon.', uz: 'Marosim tush payti boshlanadi.' },
      { en: 'Construction is set to commence next month.', uz: "Qurilish keyingi oy boshlanadi."} ,
    ],
    collocations: ['commence proceedings', 'commence work', 'officially commence'],
    wordFamily: [{ form: 'commencement', pos: 'noun' }],
    synonymsEn: ['begin', 'start', 'initiate'],
    antonyms: ['end', 'conclude'],
    cefr: 'B2',
    mnemonicUz: "COMMENCE — 'commence' 'begin'ning rasmiy sinonimi, taklifnoma/marosim so'zi",
  },
  {
    word: 'inevitable',
    slug: 'inevitable',
    pos: 'adjective',
    ipa: '/ɪnˈevɪtəbl/',
    translations: ['muqarrar', "oldini olib bo'lmas"],
    definitionEn: 'certain to happen; unavoidable',
    definitionUz: "oldini olib bo'lmaydigan, muqarrar",
    examples: [
      { en: 'Change was inevitable in such a fast-growing company.', uz: "Bunday tez o'sayotgan kompaniyada o'zgarish muqarrar edi." },
      { en: 'It seems inevitable that prices will rise.', uz: "Narxlarning ko'tarilishi muqarrardek tuyuladi." },
    ],
    collocations: ['seem inevitable', 'an inevitable consequence', 'become inevitable'],
    wordFamily: [{ form: 'inevitably', pos: 'adverb' }, { form: 'inevitability', pos: 'noun' }],
    synonymsEn: ['unavoidable', 'certain', 'inescapable'],
    antonyms: ['avoidable', 'preventable'],
    cefr: 'C1',
    mnemonicUz: "IN-EVIT-ABLE — 'evitable' (oldini olsa bo'ladigan) EMAS ('in-') → muqarrar",
  },
  {
    word: 'compelling',
    slug: 'compelling',
    pos: 'adjective',
    ipa: '/kəmˈpelɪŋ/',
    translations: ['ishonarli', 'jozibali', "e'tiborni tortuvchi"],
    definitionEn: 'evoking interest or attention in a powerfully irresistible way',
    definitionUz: "kuchli ta'sir qiluvchi, ishonarli",
    examples: [
      { en: 'She gave a compelling argument for the new plan.', uz: 'U yangi reja uchun ishonarli dalil keltirdi.' },
      { en: 'It was a compelling story from start to finish.', uz: "Bu boshidan oxirigacha jozibali hikoya edi." },
    ],
    collocations: ['compelling argument', 'compelling evidence', 'find something compelling'],
    wordFamily: [{ form: 'compel', pos: 'verb' }, { form: 'compellingly', pos: 'adverb' }],
    synonymsEn: ['convincing', 'persuasive', 'gripping'],
    antonyms: ['unconvincing', 'boring'],
    cefr: 'C1',
    mnemonicUz: "COMPEL-LING — 'compel' majburlamoq → shu darajada kuchliki, sizni ishontirishga majbur qiladi",
  },
  {
    word: 'diligent',
    slug: 'diligent',
    pos: 'adjective',
    ipa: '/ˈdɪlɪdʒənt/',
    translations: ['tirishqoq', 'mehnatkash'],
    definitionEn: 'showing care and effort in your work or duties',
    definitionUz: "ishga g'amxo'rlik va tirishqoqlik bilan yondashuvchi",
    examples: [
      { en: 'He is a diligent student who never misses a class.', uz: "U hech qachon darsni qoldirmaydigan tirishqoq talaba." },
      { en: 'Diligent research led to the discovery.', uz: "Tirishqoqlik bilan olib borilgan tadqiqot kashfiyotga olib keldi." },
    ],
    collocations: ['diligent student', 'diligent research', 'remain diligent'],
    wordFamily: [{ form: 'diligence', pos: 'noun' }, { form: 'diligently', pos: 'adverb' }],
    synonymsEn: ['hardworking', 'industrious', 'conscientious'],
    antonyms: ['lazy', 'negligent'],
    cefr: 'B2',
    mnemonicUz: "DILIGENT — 'deal + agent' kabi eshitiladi — har ishga jiddiy 'agent' sifatida yondashadi",
  },
  {
    word: 'meticulous',
    slug: 'meticulous',
    pos: 'adjective',
    ipa: '/məˈtɪkjələs/',
    translations: ['puxta', 'ehtiyotkor', "diqqat bilan"],
    definitionEn: 'showing great attention to detail; very careful and precise',
    definitionUz: "har bir kichik detalga alohida e'tibor beruvchi",
    examples: [
      { en: 'She is meticulous about keeping records.', uz: "U hujjatlarni yuritishda juda puxta." },
      { en: 'The plan was prepared with meticulous care.', uz: "Reja katta ehtiyotkorlik bilan tayyorlangan." },
    ],
    collocations: ['meticulous attention to detail', 'meticulous planning', 'meticulously prepared'],
    wordFamily: [{ form: 'meticulously', pos: 'adverb' }, { form: 'meticulousness', pos: 'noun' }],
    synonymsEn: ['thorough', 'precise', 'painstaking'],
    antonyms: ['careless', 'sloppy'],
    cefr: 'C1',
    mnemonicUz: "METICULOUS — 'metr' o'lchov so'ziga o'xshaydi — hamma narsani millimetrigacha o'lchaydi",
  },
  {
    word: 'coherent',
    slug: 'coherent',
    pos: 'adjective',
    ipa: '/kəʊˈhɪərənt/',
    translations: ['izchil', 'mantiqan bog\'liq'],
    definitionEn: 'logical and consistent; easy to understand',
    definitionUz: "mantiqan izchil, tushunarli tarzda bog'langan",
    examples: [
      { en: 'He gave a coherent explanation of the process.', uz: "U jarayonni izchil tushuntirdi." },
      { en: 'The essay lacked a coherent structure.', uz: "Insho izchil tuzilishga ega emas edi." },
    ],
    collocations: ['coherent argument', 'coherent structure', 'remain coherent'],
    wordFamily: [{ form: 'coherence', pos: 'noun' }, { form: 'coherently', pos: 'adverb' }],
    synonymsEn: ['logical', 'consistent', 'clear'],
    antonyms: ['incoherent', 'confused'],
    cefr: 'C1',
    mnemonicUz: "CO-HERENT — 'co' birga + 'here' — fikrlar birga, bir joyda mantiqiy tutashadi",
  },
  {
    word: 'substantial',
    slug: 'substantial',
    pos: 'adjective',
    ipa: '/səbˈstænʃəl/',
    translations: ['sezilarli', "katta", "muhim"],
    definitionEn: 'of considerable importance, size, or worth',
    definitionUz: "hajmi yoki ahamiyati katta, sezilarli",
    examples: [
      { en: 'They made substantial progress this year.', uz: "Ular bu yil sezilarli yutuqqa erishdi." },
      { en: 'A substantial amount of money was spent.', uz: "Katta miqdordagi pul sarflandi." },
    ],
    collocations: ['substantial amount', 'substantial progress', 'substantial evidence'],
    wordFamily: [{ form: 'substance', pos: 'noun' }, { form: 'substantially', pos: 'adverb' }],
    synonymsEn: ['considerable', 'significant', 'sizeable'],
    antonyms: ['negligible', 'insignificant'],
    cefr: 'B2',
    mnemonicUz: "SUBSTANT-IAL — 'substance' (mazmun/modda) so'ziga bog'liq — jiddiy 'mazmun'ga ega",
  },
  {
    word: 'reluctant',
    slug: 'reluctant',
    pos: 'adjective',
    ipa: '/rɪˈlʌktənt/',
    translations: ['istamay', 'xohlamay'],
    definitionEn: 'unwilling and hesitant; disinclined',
    definitionUz: "biror narsani qilishni istamaydigan, ikkilanuvchi",
    examples: [
      { en: 'She was reluctant to share her opinion.', uz: "U o'z fikrini bildirishni istamadi." },
      { en: 'He seemed reluctant to leave.', uz: "U ketishni istamayotgandek tuyulardi." },
    ],
    collocations: ['reluctant to admit', 'increasingly reluctant', 'reluctant agreement'],
    wordFamily: [{ form: 'reluctance', pos: 'noun' }, { form: 'reluctantly', pos: 'adverb' }],
    synonymsEn: ['unwilling', 'hesitant', 'disinclined'],
    antonyms: ['willing', 'eager'],
    cefr: 'B2',
    mnemonicUz: "RE-LUCT-ANT — lotincha 'luctari' (kurashmoq) — ichingizda kurash bor, shuning uchun istamaysiz",
  },
  {
    word: 'versatile',
    slug: 'versatile',
    pos: 'adjective',
    ipa: '/ˈvɜːsətaɪl/',
    translations: ["ko'p qirrali", 'har tomonlama'],
    definitionEn: 'able to adapt or be adapted to many different functions',
    definitionUz: "ko'p vazifani bajara oladigan, har tomonlama moslashuvchan",
    examples: [
      { en: 'She is a versatile actress who can play any role.', uz: "U har qanday rolni o'ynay oladigan ko'p qirrali aktrisa." },
      { en: 'This tool is extremely versatile.', uz: "Bu asbob juda ko'p vazifali." },
    ],
    collocations: ['versatile player', 'highly versatile', 'versatile tool'],
    wordFamily: [{ form: 'versatility', pos: 'noun' }],
    synonymsEn: ['adaptable', 'flexible', 'multi-talented'],
    antonyms: ['limited', 'specialized'],
    cefr: 'B2',
    mnemonicUz: "VERS-ATILE — 'verse' (aylantirmoq) so'ziga bog'liq — turli tomonga 'aylanib', moslasha oladi",
  },
  {
    word: 'plausible',
    slug: 'plausible',
    pos: 'adjective',
    ipa: '/ˈplɔːzəbl/',
    translations: ['ishonarli', 'to\'g\'riga o\'xshash'],
    definitionEn: 'seeming reasonable or probable',
    definitionUz: "aqlga to'g'ri kelgan, ehtimoli borga o'xshagan",
    examples: [
      { en: 'It seems like a plausible explanation.', uz: "Bu ishonarli tushuntirishga o'xshaydi." },
      { en: 'The plan sounds plausible in theory.', uz: "Reja nazariy jihatdan ishonarli eshitiladi." },
    ],
    collocations: ['plausible explanation', 'sound plausible', 'entirely plausible'],
    wordFamily: [{ form: 'plausibility', pos: 'noun' }, { form: 'plausibly', pos: 'adverb' }],
    synonymsEn: ['credible', 'believable', 'reasonable'],
    antonyms: ['implausible', 'unlikely'],
    cefr: 'C1',
    mnemonicUz: "PLAUS-IBLE — 'applaud' (qarsak chalmoq) bilan bir o'zakdan — odamlar 'qarsak chaladigan', ishonadigan fikr",
  },
  {
    word: 'contemplate',
    slug: 'contemplate',
    pos: 'verb',
    ipa: '/ˈkɒntəmpleɪt/',
    translations: ['mulohaza qilmoq', "o'ylab ko'rmoq"],
    definitionEn: 'to think about something carefully for a long time',
    definitionUz: "biror narsa haqida chuqur va uzoq o'ylamoq",
    examples: [
      { en: 'She contemplated moving to a new city.', uz: "U yangi shaharga ko'chishni mulohaza qildi." },
      { en: 'He sat quietly, contemplating his next move.', uz: "U jim o'tirib, keyingi qadamini o'yladi." },
    ],
    collocations: ['contemplate the idea', 'contemplate leaving', 'quietly contemplate'],
    wordFamily: [{ form: 'contemplation', pos: 'noun' }, { form: 'contemplative', pos: 'adjective' }],
    synonymsEn: ['consider', 'ponder', 'reflect on'],
    antonyms: ['ignore', 'dismiss'],
    cefr: 'B2',
    mnemonicUz: "CON-TEMPLATE — 'temple' (ibodatxona) — ibodatxonada xuddi chuqur mulohaza qilingandek",
  },
];

export function getSeoWord(slug) {
  return SEO_WORDS.find((w) => w.slug === slug) || null;
}
