// Original IELTS-style practice content (NOT copied or paraphrased from any real
// Cambridge/IELTS book). Only the exam STRUCTURE follows a standard Academic test
// layout; every topic, passage, transcript, question and answer is written from scratch.
import { table, TFNG_INSTRUCTION, YNNG_INSTRUCTION, q, paras, mc, bank } from './_html.mjs';

export default {
  slug: 'vocably-practice-test-17',
  title: 'Vocably Practice Test 17',
  difficulty: 'medium',

  reading: {
    durationSec: 3600,
    passages: [
      {
        order: 1,
        title: 'The tallest living things',
        subtitle: 'Read the text and answer questions 1-13.',
        paragraphs: paras(
          ['A', `On a foggy ridge in northern California, a tree rises above its neighbours to a height of more than a hundred and fifteen metres, taller than a football pitch is long and higher than the Statue of Liberty. It is a coast redwood, and it is the tallest known living thing on Earth. Redwoods can also be astonishingly old: some have been growing for more than two thousand years, which means that they were already mature trees when the Roman Empire was at its height. They once covered a vast belt of the Pacific coast, and today, the surviving forests, though a fraction of their former size, are among the most impressive places in the natural world.`],
          ['B', `How does a tree lift water to a height of over a hundred metres? The answer lies in the physics of water. Inside the trunk runs a network of narrow tubes, known as xylem, through which water travels from the roots to the leaves. As water evaporates from the leaves, it pulls on the water behind it, and because water molecules cling to each other, the pull is transmitted all the way down the tube, like a chain. The system works brilliantly, but it has a limit. The higher the water is lifted, the greater the tension in the tubes, until air bubbles form and break the chain. Calculations suggest that this sets a maximum height of between a hundred and twenty and a hundred and thirty metres, and the tallest redwoods are approaching it.`],
          ['C', `Redwoods grow along a narrow strip of coast where the summers are dry but where fog rolls in from the Pacific on most mornings. The trees have adapted to make use of it. Their needles are covered with tiny structures that absorb moisture directly from the damp air, and droplets that collect on the foliage drip to the ground, where they soak into the soil. Studies suggest that in summer, when there is almost no rain, fog provides up to forty per cent of the water that the trees use. Scientists who study the region have noted that the natural range of redwoods matches the fog belt with remarkable precision.`],
          ['D', `High above the ground, the crowns of old redwoods support a world of their own. Over centuries, dead leaves and bark collect in the forks of the branches, turning slowly into thick mats of soil, in which ferns, shrubs and even small trees take root. The mats are home to insects and worms, and to a salamander that lives its entire life in the canopy, never descending to the ground. Its discovery astonished biologists, who had not expected to find an amphibian so far from water. The canopy, which was out of reach to scientists for most of the twentieth century, has been explored only since climbers developed ways of ascending the trees safely.`],
          ['E', `The story of the redwoods is also a story of destruction. Their wood is light, resistant to rot and easy to work, and from the middle of the nineteenth century, it was in great demand for building houses and railways. Loggers cut down the giants on a huge scale, and by the end of the twentieth century, more than ninety per cent of the original old-growth forest had been destroyed. The alarm was raised by a group of naturalists who, in 1918, founded the Save the Redwoods League, which raised money to buy groves and hand them over to the state, and its work led to the creation of a network of parks that now shelters most of what remains.`],
          ['F', `The future of the forests is not secure. Research suggests that the fog along the California coast has become less frequent over the last century, and if the trend continues, the trees could be deprived of the water on which they depend. At the same time, scientists have found that redwoods store more carbon per hectare than any other forest on Earth, and they are being studied as a possible aid in the fight against climate change. Planting new forests is one response, but the old ones cannot be replaced; a tree takes centuries to reach the size of its ancestors, and the great trees are a legacy that, once lost, is gone for ever.`]
        ),
        questionGroups: [
          {
            id: 't17-r1-headings',
            type: 'matching_headings',
            instructionHtml: 'Reading Passage 1 has six paragraphs, A-F. Choose the correct heading for paragraphs B-F from the list of headings below.<br/><em>Example: Paragraph A — viii</em>',
            bank: [
              { key: 'i', text: 'Drinking from the clouds' },
              { key: 'ii', text: 'Near destruction and the campaign to save the trees' },
              { key: 'iii', text: 'The use of redwood timber in building' },
              { key: 'iv', text: 'A world above the ground' },
              { key: 'v', text: 'The physical limit to a tree\'s height' },
              { key: 'vi', text: 'Redwoods in other parts of the world' },
              { key: 'vii', text: 'Threats from a changing climate' },
              { key: 'viii', text: 'Giants of the coast' },
            ],
            questions: [
              q(1, 'Paragraph B', 'v', 'Paragraph B: water is lifted through xylem, but "this sets a maximum height".', 'B'),
              q(2, 'Paragraph C', 'i', 'Paragraph C: fog provides up to forty per cent of summer water.', 'C'),
              q(3, 'Paragraph D', 'iv', 'Paragraph D: soil mats, ferns and a salamander in the canopy.', 'D'),
              q(4, 'Paragraph E', 'ii', 'Paragraph E: destruction of old-growth forest and the Save the Redwoods League.', 'E'),
              q(5, 'Paragraph F', 'vii', 'Paragraph F: less frequent fog threatens the trees.', 'F'),
            ],
          },
          {
            id: 't17-r1-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              q(6, 'The tallest known redwood is more than a hundred and ten metres high.', 'TRUE', 'Paragraph A: "more than a hundred and fifteen metres".', 'A'),
              q(7, 'Some redwoods have been growing for more than two thousand years.', 'TRUE', 'Paragraph A: "more than two thousand years".', 'A'),
              q(8, 'Fog provides all the water that redwoods use in summer.', 'FALSE', 'Paragraph C: "up to forty per cent".', 'C'),
              q(9, 'Several species of bird nest in the canopy of redwoods.', 'NOT GIVEN', 'Birds are not mentioned.'),
            ],
          },
          {
            id: 't17-r1-short',
            type: 'short_answer',
            instructionHtml: 'Answer the questions below. Choose <strong>NO MORE THAN THREE WORDS AND/OR A NUMBER</strong> from the passage for each answer.',
            wordLimit: { maxWords: 3, maxNumbers: 1, label: 'NO MORE THAN THREE WORDS AND/OR A NUMBER' },
            questions: [
              q(10, 'What name is given to the tubes that carry water from the roots to the leaves?', ['xylem'], 'Paragraph B: "known as xylem".', 'B'),
              q(11, 'What maximum percentage of summer water can fog provide?', ['40 per cent', '40%', 'forty per cent', '40', 'forty'], 'Paragraph C: "up to forty per cent".', 'C'),
              q(12, 'Which animal lives its whole life in the canopy?', ['a salamander', 'salamander', 'the salamander'], 'Paragraph D: "a salamander that lives its entire life in the canopy".', 'D'),
              q(13, 'In which year was the Save the Redwoods League founded?', ['1918'], 'Paragraph E: "in 1918".', 'E'),
            ],
          },
        ],
      },
      {
        order: 2,
        title: 'The long road to zero',
        subtitle: 'Read the text and answer questions 14-26.',
        paragraphs: paras(
          ['A', `Today, zero seems the most ordinary of numbers, and children meet it in their first year at school. It is hard to imagine how anyone managed without it. Yet for most of human history, nobody did use it, and calculating was a difficult and specialised skill. The Romans, for example, had no symbol for zero, and their numerals, in which XLVII stands for forty-seven, made even simple arithmetic laborious; merchants and officials relied on counting boards and beads, and only experts could multiply or divide large numbers. The story of how a symbol for nothing came to be accepted is a story of several cultures, separated by time and distance, each solving a part of the puzzle.`],
          ['B', `The first step was the placeholder. In Babylonian mathematics, numbers were written in a system based on sixty, in which the value of a symbol depends on its position, as in our own system. Originally, scribes simply left a space to show an empty position, which led to confusion, since a space could be overlooked. By about 300 BC, they had begun to use a special mark, made of two small wedges, but it was used only between digits, and never at the end of a number, and it was not treated as a number in its own right. The Maya of Central America, who developed an elaborate calendar, invented a symbol for zero in the form of a shell, which appears in inscriptions from about the fourth century AD. They seem to have done so entirely independently of the Old World.`],
          ['C', `The decisive step was taken in India. The oldest known written dot used as a zero appears on a birch-bark manuscript found in a village near Peshawar, which scientists have dated by radiocarbon to between the third and fourth centuries AD, several centuries earlier than had been thought. But the idea that zero is a number, which can be added, subtracted and multiplied like any other, was first set out clearly in 628 AD by the mathematician Brahmagupta. He gave rules for arithmetic with zero, stating that a number added to zero is unchanged and that a number subtracted from itself is zero. On division by zero, however, he was less successful, and his rule was later shown to be mistaken.`],
          ['D', `Indian numerals and the zero reached the Islamic world in the eighth century, and in the ninth, the Baghdad scholar al-Khwarizmi wrote a book explaining how to calculate with them. His name, in Latin form, gave us the word algorithm. The system reached Europe slowly. An Italian merchant's son named Leonardo of Pisa, better known as Fibonacci, who had learned it from Arab traders in North Africa, published a book in 1202 that explained its advantages over Roman numerals with examples drawn from commerce. Acceptance was far from immediate. In 1299, the city of Florence banned the use of the new numerals in banking, reportedly because the symbols, particularly the zero, could easily be altered to change a figure into a larger one, and it was not until the sixteenth century that they became standard.`],
          ['E', `The consequences were immense. A number system with a zero makes it easy to write very large numbers and to calculate with them on paper, and it opened the way to algebra and, in the seventeenth century, to calculus. But zero also raised difficult questions. What happens when a number is divided by zero? In ordinary arithmetic, the answer is that the operation is undefined, because no number can be multiplied by zero to give anything other than zero. Mathematicians have since found ways of working with the concept in more advanced fields, but in the arithmetic of everyday life, division by zero remains forbidden.`],
          ['F', `In the modern world, the zero has acquired a new importance. Every digital computer stores and processes information as a string of only two symbols, zero and one, and everything that happens on a screen, from a text message to a film, is ultimately a pattern of these two symbols. In physics, the idea of absolute zero, the lowest temperature that can theoretically be reached, has led to the discovery of strange states of matter. A symbol that was once regarded with suspicion has become one of the foundations of science and technology.`],
          ['G', `The history of zero is also a history of ideas about nothingness. Many ancient thinkers, including Aristotle, rejected the idea of a void, arguing that nature could not contain a place in which nothing existed, and this may have delayed acceptance of zero in the West. Indian thinkers, whose philosophies contained concepts of emptiness, seem to have found the idea less troubling. It is a reminder that mathematics does not develop in isolation from the broader beliefs of the societies that produce it.`]
        ),
        questionGroups: [
          {
            id: 't17-r2-ynng',
            type: 'yes_no_notgiven',
            instructionHtml: YNNG_INSTRUCTION,
            questions: [
              q(14, 'Roman numerals made arithmetic with large numbers easy.', 'NO', 'Paragraph A: "made even simple arithmetic laborious".', 'A'),
              q(15, 'The Maya developed the idea of zero independently of other cultures.', 'YES', 'Paragraph B: "entirely independently of the Old World".', 'B'),
              q(16, 'Brahmagupta was the first person ever to use a dot as a zero.', 'NO', 'Paragraph C: the dot on the birch-bark manuscript is centuries older.', 'C'),
              q(17, 'Fibonacci helped to introduce the new numerals to Europe.', 'YES', 'Paragraph D: he "published a book in 1202 that explained its advantages".', 'D'),
              q(18, 'The Florentine ban on the new numerals was unreasonable.', 'NOT GIVEN', 'The writer gives no opinion on the ban.', 'D'),
              q(19, 'Division by zero is permitted in ordinary arithmetic.', 'NO', 'Paragraph E: "division by zero remains forbidden".', 'E'),
            ],
          },
          {
            id: 't17-r2-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B, C or D</strong>.',
            questions: [
              mc(20, 'The Babylonian placeholder was', ['used at the end of numbers', 'used only between digits', 'treated as a number in its own right', 'written as a shell'], 'B', 'Paragraph B: "used only between digits, and never at the end of a number".', 'B'),
              mc(21, 'What is said about the manuscript near Peshawar?', ['It was written by Brahmagupta.', 'It was dated much earlier than had been thought.', 'It contains rules for division.', 'It was written in Latin.'], 'B', 'Paragraph C: "several centuries earlier than had been thought".', 'C'),
              mc(22, 'Why did Florence ban the new numerals in banking?', ['They were difficult to read.', 'They were too expensive.', 'The zero could easily be altered to change figures.', 'They came from abroad.'], 'C', 'Paragraph D: "could easily be altered to change a figure into a larger one".', 'D'),
              mc(23, 'According to paragraph G, Aristotle', ['invented the zero', 'rejected the idea of a void', 'wrote about Indian mathematics', 'used a dot as a symbol'], 'B', 'Paragraph G: "Aristotle, rejected the idea of a void".', 'G'),
            ],
          },
          {
            id: 't17-r2-matchinfo',
            type: 'matching_information',
            instructionHtml: 'Reading Passage 2 has seven paragraphs, A-G. Which paragraph contains the following information? <em>Choose the correct letter, A-G.</em>',
            questions: [
              q(24, 'a description of rules for carrying out arithmetic with zero', 'C', 'Paragraph C: Brahmagupta\'s rules.', 'C'),
              q(25, 'a reference to a city that prohibited the use of the new numerals', 'D', 'Paragraph D: Florence, 1299.', 'D'),
              q(26, 'the importance of zero in computers', 'F', 'Paragraph F: "zero and one".', 'F'),
            ],
          },
        ],
      },
      {
        order: 3,
        title: 'Why play matters',
        subtitle: 'Read the text and answer questions 27-40.',
        paragraphs: paras(
          ['A', `In many schools, the youngest children are spending less of the day playing and more of it sitting at desks. In some countries, kindergartens that once offered sand, water and dressing-up clothes now ask four- and five-year-olds to complete worksheets on letters and numbers, in the belief that an early start will give them an advantage in later life. Parents often support the change, anxious that their children might fall behind. Yet many researchers in child development argue that the trend is a mistake, and that play, far from being a distraction from learning, is one of the most effective ways in which children learn.`],
          ['B', `The idea is not new. The Russian psychologist Lev Vygotsky argued in the 1930s that pretend play creates what he called a zone in which children behave as if they were older than they are. A child who pretends to be a doctor or a shopkeeper, he observed, follows rules, uses language in new ways and plans ahead, and so stretches abilities that she will not normally show. Play, in his view, was not simply enjoyment but an activity that leads development. Later researchers have built on his work, showing that rich pretend play is linked with better language skills and greater creativity.`],
          ['C', `One of the most striking findings concerns self-control. Researchers studied a programme, known as Tools of the Mind, in which young children spent part of each day planning and acting out elaborate make-believe scenarios with their classmates. Compared with children in conventional classes, they showed better self-regulation: they were better able to pay attention, to wait their turn and to control impulses. Since self-control in childhood is a strong predictor of success in later life, the results have attracted a great deal of attention from educators. Follow-up studies, however, have produced mixed findings, and some researchers warn that the benefits depend heavily on how well teachers are trained to run the programme, which suggests that the method is no magic formula.`],
          ['D', `The kind of space in which children play also matters. The first adventure playground was created in Copenhagen in 1943, after a landscape architect noticed that children preferred to play on building sites and in rubble rather than in the neat playgrounds designed for them. The children, he noticed, were absorbed for hours, inventing games and building things, while the expensive swings and slides that had been provided for them stood almost empty. His solution was a site filled with old planks, bricks, tyres and ropes, which children could use to build their own structures, supervised by an adult. Studies since then have found that playgrounds containing such loose parts encourage more imaginative play, and more cooperation between children, than those with fixed equipment.`],
          ['E', `The example often cited by supporters of play-based education is Finland. Children there do not start formal schooling until they are seven, and even in the early grades, lessons are short, with a fifteen-minute break after every forty-five minutes of teaching. Homework is limited, and teachers have considerable freedom to decide how to teach. Finnish pupils have performed very well in international comparisons, which is sometimes taken to show that less pressure produces better results. Researchers caution that a country's results depend on many things, including the quality and status of its teachers, and that it is hard to isolate the effect of any one feature.`],
          ['F', `Play is not a substitute for teaching, and the best evidence suggests that the most effective approach combines the two. In one study, young children were taught about shapes in three ways: by direct instruction, by free play with no adult involvement and by guided play, in which an adult set a goal and then let the children explore for themselves, asking occasional questions. Those in the guided play group learned the most about the properties of shapes, and enjoyed the process more. The lesson is that play works best when it has some structure, and that adults have a role in supporting it, without taking control. Teachers who are skilled at this, researchers say, know when to join in, when to ask a question and when to stand back, and such skills can be learned, though they are rarely included in training courses.`]
        ),
        questionGroups: [
          {
            id: 't17-r3-endings',
            type: 'matching_sentence_endings',
            instructionHtml: 'Complete each sentence with the correct ending, A-H, below.',
            bank: [
              { key: 'A', text: 'encouraged children to go beyond what they could do normally.' },
              { key: 'B', text: 'showed better self-control than those in conventional classes.' },
              { key: 'C', text: 'were first created in Denmark in 1943.' },
              { key: 'D', text: 'led to more cooperation between children.' },
              { key: 'E', text: 'give children a short break after each lesson.' },
              { key: 'F', text: 'should replace all formal teaching.' },
              { key: 'G', text: 'cost less than traditional playgrounds.' },
              { key: 'H', text: 'were banned in the 1950s.' },
            ],
            questions: [
              q(27, 'Vygotsky argued that pretend play', 'A', 'Paragraph B: children "stretch abilities that she will not normally show".', 'B'),
              q(28, 'Children in the make-believe programme', 'B', 'Paragraph C: they "showed better self-regulation".', 'C'),
              q(29, 'Adventure playgrounds', 'C', 'Paragraph D: "created in Copenhagen in 1943".', 'D'),
              q(30, 'Playgrounds with loose parts', 'D', 'Paragraph D: "more cooperation between children".', 'D'),
              q(31, 'Finnish schools', 'E', 'Paragraph E: "a fifteen-minute break after every forty-five minutes".', 'E'),
            ],
          },
          {
            id: 't17-r3-summary',
            type: 'summary_completion_bank',
            instructionHtml: 'Complete the summary of paragraph F using the list of words, A-H, below.',
            bankReusable: false,
            bank: bank(['guided', 'explore', 'shapes', 'free', 'structure', 'rewards', 'reading', 'tests']),
            stemHtml: '<p>In a study of children learning about {{q32}}, the most effective method was {{q33}} play, in which an adult set a goal and let the children {{q34}} for themselves. It was more effective than {{q35}} play with no adult involved. The lesson is that play works best when it has some {{q36}}.</p>',
            questions: [
              q(32, null, 'C', 'Paragraph F: "taught about shapes".', 'F'),
              q(33, null, 'A', 'Paragraph F: "guided play".', 'F'),
              q(34, null, 'B', 'Paragraph F: "let the children explore".', 'F'),
              q(35, null, 'D', 'Paragraph F: "free play with no adult involvement".', 'F'),
              q(36, null, 'E', 'Paragraph F: "some structure".', 'F'),
            ],
          },
          {
            id: 't17-r3-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              q(37, 'Some kindergartens now ask young children to complete worksheets.', 'TRUE', 'Paragraph A: "now ask four- and five-year-olds to complete worksheets".', 'A'),
              q(38, 'Finnish children start formal schooling at the age of seven.', 'TRUE', 'Paragraph E: "do not start formal schooling until they are seven".', 'E'),
              q(39, 'Finnish pupils achieve the best results in the world in every subject.', 'NOT GIVEN', 'Paragraph E says only that they have "performed very well".', 'E'),
              q(40, 'Adventure playgrounds are safer than conventional playgrounds.', 'NOT GIVEN', 'Safety is not discussed.', 'D'),
            ],
          },
        ],
      },
    ],
  },

  listening: {
    durationSec: 1800,
    checkTimeSec: 120,
    parts: [
      {
        order: 1,
        contextText: 'You will hear a man phoning an agency to rent a holiday apartment.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Seaview Holiday Lets, good morning." },
          { speaker: 'B', voice: 'david', text: "Good morning. I'm looking for a self-catering apartment for a family holiday in August." },
          { speaker: 'A', voice: 'zira', text: "Certainly. How many of you will there be?" },
          { speaker: 'B', voice: 'david', text: "Five: two adults and three children, aged nine, seven and three." },
          { speaker: 'A', voice: 'zira', text: "And which part of the coast are you interested in?" },
          { speaker: 'B', voice: 'david', text: "Somewhere close to a sandy beach, in Cornwall if possible." },
          { speaker: 'A', voice: 'zira', text: "We have an apartment in Polperro, with three bedrooms, about two minutes from the harbour and ten from the beach. It's available from the ninth to the sixteenth of August." },
          { speaker: 'B', voice: 'david', text: "That sounds possible. What does it cost?" },
          { speaker: 'A', voice: 'zira', text: "Seven hundred and twenty pounds for the week, including bed linen and towels. There's a refundable deposit of a hundred and fifty pounds, payable when you book." },
          { speaker: 'B', voice: 'david', text: "And what's in the kitchen?" },
          { speaker: 'A', voice: 'zira', text: "Everything you need: a cooker, a fridge-freezer, a microwave and a dishwasher. There's also a washing machine, and Wi-Fi is free." },
          { speaker: 'B', voice: 'david', text: "Good. We'll bring our car. Is there parking?" },
          { speaker: 'A', voice: 'zira', text: "There's a space in a small car park a hundred metres away, which is included in the price. The apartment is on the second floor, and unfortunately there's no lift." },
          { speaker: 'B', voice: 'david', text: "That shouldn't be a problem. Are pets allowed? We'd like to bring our dog." },
          { speaker: 'A', voice: 'zira', text: "Yes, one small dog is allowed, but there's an extra charge of thirty pounds for cleaning." },
          { speaker: 'B', voice: 'david', text: "That's fine. Shall I book now?" },
          { speaker: 'A', voice: 'zira', text: "Yes, please. Can I take your name?" },
          { speaker: 'B', voice: 'david', text: "Stephen Redfern. R-E-D-F-E-R-N." },
          { speaker: 'A', voice: 'zira', text: "And your email address?" },
          { speaker: 'B', voice: 'david', text: "It's s dot redfern at clearmail dot com." },
        ],
        questionGroups: [
          {
            id: 't17-l1-form',
            type: 'form_completion',
            instructionHtml: 'Complete the form below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Seaview Holiday Lets: Enquiry', ''],
              [
                ['Number of people', '{{q1}}'],
                ['Youngest child\'s age', '{{q2}}'],
                ['Location', '{{q3}}'],
                ['Apartment in', '{{q4}}'],
                ['Dates', '{{q5}} to 16 August'],
                ['Price per week', '£{{q6}}'],
                ['Deposit', '£{{q7}}'],
                ['Kitchen includes', 'cooker, fridge-freezer, microwave and {{q8}}'],
                ['Extra charge for dog', '£{{q9}}'],
                ['Customer\'s surname', '{{q10}}'],
              ]
            ),
            questions: [
              q(1, null, ['5', 'five'], '"Five: two adults and three children".'),
              q(2, null, ['3', 'three'], '"aged nine, seven and three".'),
              q(3, null, ['cornwall'], '"in Cornwall if possible".'),
              q(4, null, ['polperro'], '"an apartment in Polperro".'),
              q(5, null, ['9', 'ninth', '9th'], '"from the ninth to the sixteenth of August".'),
              q(6, null, ['720', 'seven hundred and twenty'], '"Seven hundred and twenty pounds".'),
              q(7, null, ['150', 'a hundred and fifty', 'one hundred and fifty'], '"a hundred and fifty pounds".'),
              q(8, null, ['dishwasher'], '"a microwave and a dishwasher".'),
              q(9, null, ['30', 'thirty'], '"thirty pounds for cleaning".'),
              q(10, null, ['redfern'], 'Spelled out: R-E-D-F-E-R-N.'),
            ],
          },
        ],
      },
      {
        order: 2,
        contextText: 'You will hear a guide describing a night walk at a wildlife park.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Good evening, everyone, and welcome to the night walk at Tarn Wildlife Park. I'm Fiona, and I'll be your guide for the next two hours." },
          { speaker: 'A', voice: 'zira', text: "Before we start, some safety rules. Please stay together, follow the path and do not use torches, except the red lights we'll give you. White light would dazzle the animals and spoil your own night vision, which takes about twenty minutes to adjust fully." },
          { speaker: 'A', voice: 'zira', text: "The walk covers about three kilometres on a flat, gravel path, which is suitable for wheelchairs. We'll stop at five viewing points, and I'll tell you about the animals at each." },
          { speaker: 'A', voice: 'zira', text: "Our first stop is the badger sett, at the edge of the wood. Badgers are nocturnal, and sleep through the day in underground burrows. We'll wait quietly, and with luck, we'll see a family emerging at dusk. They have poor eyesight, but an excellent sense of smell, so it helps if you keep still and avoid strong perfume." },
          { speaker: 'A', voice: 'zira', text: "The second stop is the lake, where we'll listen for frogs and look for bats, which hunt for insects above the water. We have a bat detector, which converts their high-pitched calls into sounds we can hear." },
          { speaker: 'A', voice: 'zira', text: "Next, we'll walk through the meadow, where owls hunt for mice and voles. We have a pair of barn owls, which nest in the old barn, and you may see them flying silently over the grass. Their feathers have soft edges that muffle the sound of their wings." },
          { speaker: 'A', voice: 'zira', text: "At the fourth stop, we'll look at the stars. The park is far from any town, so the sky is exceptionally dark, and on a clear night, you can see thousands of stars and often the Milky Way. A member of the local astronomy club will be there to point out the constellations." },
          { speaker: 'A', voice: 'zira', text: "We end at the visitor centre, where hot chocolate and biscuits are served. It's included in the price of twelve pounds for adults and eight for children." },
          { speaker: 'A', voice: 'zira', text: "If it rains heavily, the walk may be cancelled, and we'll offer a refund or an alternative date. Now, if everyone's ready, let's begin, and please switch off your phones." },
        ],
        questionGroups: [
          {
            id: 't17-l2-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(11, 'Why are visitors asked not to use white torches?', ['They would dazzle the animals and spoil night vision.', 'They are too heavy.', 'They frighten children.'], 'A', '"White light would dazzle the animals and spoil your own night vision".'),
              mc(12, 'How long is the walk?', ['two kilometres', 'three kilometres', 'five kilometres'], 'B', '"about three kilometres".'),
              mc(13, 'What is said about the path?', ['It is steep.', 'It is suitable for wheelchairs.', 'It is muddy.'], 'B', '"suitable for wheelchairs".'),
              mc(14, 'Badgers have', ['poor eyesight and an excellent sense of smell', 'excellent eyesight', 'poor hearing'], 'A', '"poor eyesight, but an excellent sense of smell".'),
              mc(15, 'What does the bat detector do?', ['It counts the bats.', 'It converts high-pitched calls into audible sounds.', 'It attracts the bats.'], 'B', '"converts their high-pitched calls into sounds we can hear".'),
            ],
          },
          {
            id: 't17-l2-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Night walk: stops</strong></p><p>• Stop 1: badger {{q16}} at the edge of the wood<br/>• Stop 2: the {{q17}}, for frogs and bats<br/>• Stop 3: the meadow, where {{q18}} owls hunt; their feathers muffle the sound of their wings<br/>• Stop 4: look at the {{q19}}, helped by a member of the astronomy club<br/>• final stop: visitor centre; price £{{q20}} for adults</p>',
            questions: [
              q(16, null, ['sett'], '"the badger sett".'),
              q(17, null, ['lake'], '"the lake, where we\'ll listen for frogs and look for bats".'),
              q(18, null, ['barn'], '"a pair of barn owls".'),
              q(19, null, ['stars'], '"we\'ll look at the stars".'),
              q(20, null, ['12', 'twelve'], '"twelve pounds for adults".'),
            ],
          },
        ],
      },
      {
        order: 3,
        contextText: 'You will hear two environmental science students, Kayla and Ravi, discussing a research project on recycling with their tutor.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david2', text: "Right, Kayla, Ravi, how is your project on recycling behaviour going?" },
          { speaker: 'B', voice: 'zira', text: "We've finished the questionnaire, Dr Nolan, and we've tested it on ten friends to check that the questions are clear." },
          { speaker: 'A', voice: 'david2', text: "Good. Did they raise any problems?" },
          { speaker: 'C', voice: 'david', text: "A couple of questions were confusing. For example, 'How often do you recycle?' means different things to different people, so we've changed it to 'How many times last week did you put items in the recycling bin?'" },
          { speaker: 'A', voice: 'david2', text: "That's much better. A question about a specific period is easier to answer accurately." },
          { speaker: 'B', voice: 'zira', text: "We also wondered whether to include questions about income, but some people might find them intrusive." },
          { speaker: 'A', voice: 'david2', text: "I'd leave them out. Ask about the type of housing instead, because that affects how easy it is to recycle, and it's less sensitive." },
          { speaker: 'C', voice: 'david', text: "Good idea. We'd also like to compare two neighbourhoods: one where residents have a collection from the door, and another where they have to take items to recycling points." },
          { speaker: 'A', voice: 'david2', text: "Excellent. That comparison is what makes the project interesting. How many responses will you aim for?" },
          { speaker: 'B', voice: 'zira', text: "A hundred in each area, so two hundred in total." },
          { speaker: 'A', voice: 'david2', text: "That's ambitious. How will you get them?" },
          { speaker: 'C', voice: 'david', text: "We'll knock on doors on Saturday mornings, when most people are at home. And we'll offer a prize draw for a shopping voucher, to encourage participation." },
          { speaker: 'A', voice: 'david2', text: "Make sure that you carry identification, and that the voucher doesn't cost more than your budget allows." },
          { speaker: 'B', voice: 'zira', text: "It's only twenty pounds. What about analysing the results?" },
          { speaker: 'A', voice: 'david2', text: "Use a spreadsheet to calculate the averages for each area, and then test whether the difference between them is statistically significant. I can show you how, if you come to my office hours on Wednesday afternoon." },
          { speaker: 'C', voice: 'david', text: "That would be very helpful. We're planning to finish the survey by the end of March." },
          { speaker: 'A', voice: 'david2', text: "Good. One last point: be prepared for the possibility that you'll find no difference. That's still a result, and you can discuss why." },
        ],
        questionGroups: [
          {
            id: 't17-l3-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(21, 'How did the students test their questionnaire?', ['on ten friends', 'on their tutor', 'on a class'], 'A', '"tested it on ten friends".'),
              mc(22, 'Why did they change the question about how often people recycle?', ['It was too long.', 'It meant different things to different people.', 'It was too personal.'], 'B', '"means different things to different people".'),
              mc(23, 'Instead of income, the tutor advises asking about', ['age', 'the type of housing', 'education'], 'B', '"Ask about the type of housing instead".'),
              mc(24, 'What will the students compare?', ['two age groups', 'two neighbourhoods with different recycling arrangements', 'two types of bin'], 'B', '"two neighbourhoods: one where residents have a collection from the door".'),
              mc(25, 'What is the prize in the draw?', ['a shopping voucher', 'a bicycle', 'a cash prize'], 'A', '"a prize draw for a shopping voucher".'),
            ],
          },
          {
            id: 't17-l3-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Project plan</strong></p><p>• target: {{q26}} responses in each area<br/>• door-to-door survey on {{q27}} mornings<br/>• prize draw voucher worth £{{q28}}<br/>• analysis: use a {{q29}} to calculate averages<br/>• survey to be finished by the end of {{q30}}</p>',
            questions: [
              q(26, null, ['100', 'a hundred', 'one hundred'], '"A hundred in each area".'),
              q(27, null, ['saturday'], '"on Saturday mornings".'),
              q(28, null, ['20', 'twenty'], '"It\'s only twenty pounds."'),
              q(29, null, ['spreadsheet'], '"Use a spreadsheet".'),
              q(30, null, ['march'], '"by the end of March".'),
            ],
          },
        ],
      },
      {
        order: 4,
        contextText: 'You will hear part of a lecture about the origins of the alphabet.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Nearly every book, sign and screen you see is written with an alphabet, a small set of symbols that stand for sounds. Yet this invention is surprisingly recent, and it was made only once, as far as we know. Today I'll trace the story." },
          { speaker: 'A', voice: 'david', text: "The earliest writing systems, in Mesopotamia and Egypt around five thousand years ago, used hundreds of symbols, each representing a word or a syllable. They were difficult to learn, and the ability to read and write was confined to a small group of trained scribes." },
          { speaker: 'A', voice: 'david', text: "The breakthrough seems to have come around nineteen hundred BC, among Semitic-speaking workers in the Sinai desert, who were employed in Egyptian turquoise mines. They borrowed a small number of Egyptian hieroglyphs, but used them in a new way: each symbol stood not for a whole word but for the first sound of the word it depicted. The sign for a house, for example, came to represent the sound B, from the word for house." },
          { speaker: 'A', voice: 'david', text: "The result was a system of only about thirty symbols, easy enough to learn in weeks rather than years. It spread along the trade routes, and by about a thousand BC, the Phoenicians, merchants from the eastern Mediterranean, had developed a standard version of twenty-two letters, written from right to left." },
          { speaker: 'A', voice: 'david', text: "One important feature of the Phoenician alphabet is that it had only consonants. Readers had to supply the vowels themselves, which works well in Semitic languages but less so in other tongues. The Greeks, who adopted the alphabet in about eight hundred BC, solved the problem by using some of the letters for which they had no consonants to represent vowels. This is the first true alphabet, with symbols for both vowels and consonants." },
          { speaker: 'A', voice: 'david', text: "From the Greeks, the alphabet passed to the Etruscans in Italy, and from them to the Romans, who shaped the letters that we use today. The Romans had a practical approach: they cut their letters with a chisel into stone, which is why capital letters have straight lines and serifs, the little finishing strokes." },
          { speaker: 'A', voice: 'david', text: "Elsewhere, the Greek alphabet gave rise to the Cyrillic alphabet, used in Russia and many neighbouring countries, which was created in the ninth century by missionaries to spread Christianity among Slavic peoples. The alphabets of Hebrew and Arabic also descend from the original Semitic system." },
          { speaker: 'A', voice: 'david', text: "Not all writing systems are alphabets. Chinese, for example, still uses characters that represent words or parts of words, and it developed separately. But the alphabet's simplicity has made it the most widely used system in the world, and it is an example of how one good idea can change history." },
        ],
        questionGroups: [
          {
            id: 't17-l4-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>The alphabet</strong></p><p><em>Early writing</em><br/>• Mesopotamia and Egypt: hundreds of symbols for words or {{q31}}<br/>• reading and writing confined to trained {{q32}}</p><p><em>The breakthrough</em><br/>• about {{q33}} BC, workers in the Sinai desert<br/>• each symbol stood for the {{q34}} of the word it depicted<br/>• only about {{q35}} symbols in the system</p><p><em>Development</em><br/>• Phoenicians: standard version of 22 letters, written from {{q36}} to left; consonants only<br/>• Greeks used some letters to represent {{q37}}<br/>• Romans cut letters into stone with a {{q38}}; serifs are finishing strokes<br/>• Cyrillic alphabet created in the ninth century by {{q39}}<br/>• Chinese still uses {{q40}}</p>',
            questions: [
              q(31, null, ['syllables'], '"each representing a word or a syllable".'),
              q(32, null, ['scribes'], '"a small group of trained scribes".'),
              q(33, null, ['1900', 'nineteen hundred'], '"around nineteen hundred BC".'),
              q(34, null, ['first sound', 'first letter'], '"the first sound of the word it depicted".'),
              q(35, null, ['30', 'thirty'], '"only about thirty symbols".'),
              q(36, null, ['right'], '"written from right to left".'),
              q(37, null, ['vowels'], '"to represent vowels".'),
              q(38, null, ['chisel'], '"cut their letters with a chisel".'),
              q(39, null, ['missionaries'], '"created in the ninth century by missionaries".'),
              q(40, null, ['characters'], '"uses characters that represent words".'),
            ],
          },
        ],
      },
    ],
  },

  writing: {
    durationSec: 3600,
    task1: {
      order: 1,
      minWords: 150,
      recommendedMin: 20,
      promptHtml:
        '<p>The graph below shows the number of visitors to three historic sites in a European country between 2005 and 2025.</p><p>Summarise the information by selecting and reporting the main features, and make comparisons where relevant.</p>',
      chart: {
        chartType: 'line',
        title: 'Visitors to three historic sites (thousands)',
        unit: 'thousands',
        categories: ['2005', '2010', '2015', '2020', '2025'],
        xAxisLabel: 'Year',
        yAxisLabel: 'Visitors (thousands)',
        series: [
          { name: 'Castle', data: [310, 340, 420, 150, 390] },
          { name: 'Abbey', data: [220, 210, 260, 90, 300] },
          { name: 'Museum', data: [150, 200, 330, 120, 410] },
        ],
      },
    },
    task2: {
      order: 2,
      minWords: 250,
      recommendedMin: 40,
      promptHtml:
        '<p>Some people think that children should start formal education at the age of four or five. Others believe that they should not begin until they are seven or older.</p><p>Discuss both views and give your own opinion.</p>',
    },
  },
};
