// Original IELTS-style practice content (NOT copied from any real Cambridge/IELTS
// book — see TZ-vocably-v2.md old-TZ BUG-021). See practice-test-2.mjs for the
// shared format notes (transcriptLines -> TTS, chart -> rendered image later).

export default {
  slug: 'vocably-practice-test-1',
  title: 'Vocably Practice Test 1',
  difficulty: 'medium',

  reading: {
    durationSec: 3600,
    passages: [
      {
        order: 1,
        title: 'The History of Public Libraries',
        subtitle: 'Read the text and answer questions 1-13.',
        paragraphs: [
          { label: 'A', html: '<p>The earliest libraries were nothing like the buildings we associate with the word today. The Library of Alexandria, founded in Egypt in the third century BC, held perhaps the greatest collection of scrolls in the ancient world, yet it existed to serve a narrow circle of scholars and royal officials rather than the general population. Access to written knowledge, for most of human history, remained the privilege of a small, educated elite.</p>' },
          { label: 'B', html: '<p>This began to change in the nineteenth century. In Britain, the Public Libraries Act of 1850 gave local authorities the legal power to fund libraries out of local taxes for the first time, though many towns were slow to act. Progress accelerated considerably once wealthy philanthropists became involved: the industrialist Andrew Carnegie alone funded the construction of more than two thousand library buildings across the English-speaking world, believing that access to books was one of the surest routes out of poverty.</p>' },
          { label: 'C', html: '<p>As free public libraries spread through industrial towns and cities, they came to be described as "the people\'s university". For working-class readers who had left formal schooling at a young age, the library offered a rare opportunity for self-directed education, and many notable scientists, writers and politicians of the era later credited their local library with having shaped their early intellectual development.</p>' },
          { label: 'D', html: '<p>Over the course of the twentieth century, the role of the public library expanded well beyond simply lending books. Reference departments grew to support serious research, children\'s sections were introduced to encourage reading from an early age, and libraries increasingly became venues for talks, exhibitions and community meetings, functioning as a genuine civic gathering space rather than a purely literary institution.</p>' },
          { label: 'E', html: '<p>The rise of the internet led many commentators to predict, from the 1990s onward, that physical libraries would soon become obsolete. In practice, this decline never fully materialised. Libraries have instead adapted, offering free internet access, e-book lending and digital literacy courses alongside their traditional collections, and for many communities they remain one of the few remaining public spaces that anyone can enter without being expected to spend money.</p>' },
        ],
        questionGroups: [
          {
            id: 't1-p1-headings',
            type: 'matching_headings',
            instructionHtml: 'Reading Passage 1 has five paragraphs, A-E. Choose the correct heading for each paragraph from the list of headings below.',
            bank: [
              { key: 'i', text: 'A place that offers more than books' },
              { key: 'ii', text: 'Ancient collections restricted to the few' },
              { key: 'iii', text: 'A prediction that never fully came true' },
              { key: 'iv', text: 'Wealthy individuals fund a new kind of building' },
              { key: 'v', text: 'Opening the door to working-class readers' },
              { key: 'vi', text: 'International cooperation between library networks' },
              { key: 'vii', text: 'New technology changes how books are printed' },
            ],
            questions: [
              { number: 1, promptHtml: 'Paragraph A', answer: { accepted: ['ii'] }, explanationHtml: 'Paragraph A describes the Library of Alexandria serving only "scholars and royal officials".', locatorParagraph: 'A' },
              { number: 2, promptHtml: 'Paragraph B', answer: { accepted: ['iv'] }, explanationHtml: 'Paragraph B describes Carnegie funding library buildings.', locatorParagraph: 'B' },
              { number: 3, promptHtml: 'Paragraph C', answer: { accepted: ['v'] }, explanationHtml: 'Paragraph C describes libraries opening education to working-class readers.', locatorParagraph: 'C' },
              { number: 4, promptHtml: 'Paragraph D', answer: { accepted: ['i'] }, explanationHtml: 'Paragraph D describes libraries becoming venues for talks and meetings, "more than books".', locatorParagraph: 'D' },
              { number: 5, promptHtml: 'Paragraph E', answer: { accepted: ['iii'] }, explanationHtml: 'Paragraph E: the predicted decline "never fully materialised".', locatorParagraph: 'E' },
            ],
          },
          {
            id: 't1-p1-tfng',
            type: 'true_false_notgiven',
            instructionHtml:
              'Do the following statements agree with the information given in the passage?<br/><strong>TRUE</strong> if the statement agrees with the information<br/><strong>FALSE</strong> if the statement contradicts the information<br/><strong>NOT GIVEN</strong> if there is no information on this',
            questions: [
              { number: 6, promptHtml: 'The Library of Alexandria was open to the general public.', answer: { accepted: ['FALSE'] }, explanationHtml: 'Paragraph A: it served "a narrow circle of scholars and royal officials".', locatorParagraph: 'A' },
              { number: 7, promptHtml: 'The Public Libraries Act allowed local authorities to fund libraries using public money.', answer: { accepted: ['TRUE'] }, explanationHtml: 'Paragraph B: it "gave local authorities the legal power to fund libraries out of local taxes".', locatorParagraph: 'B' },
              { number: 8, promptHtml: 'Andrew Carnegie personally worked as a librarian.', answer: { accepted: ['NOT GIVEN'] }, explanationHtml: 'The passage says he funded buildings but never mentions him working as a librarian.' },
              { number: 9, promptHtml: 'Digital services have completely replaced the need for physical library buildings.', answer: { accepted: ['FALSE'] }, explanationHtml: 'Paragraph E: the predicted decline "never fully materialised".', locatorParagraph: 'E' },
            ],
          },
          {
            id: 't1-p1-sentence',
            type: 'sentence_completion',
            instructionHtml: 'Complete the sentences below. Write <strong>ONE WORD ONLY</strong> from the passage for each answer.',
            wordLimit: { maxWords: 1, label: 'ONE WORD ONLY' },
            questions: [
              { number: 10, promptHtml: 'In ancient times, libraries such as the one at Alexandria were used mainly by {{q10}}.', answer: { accepted: ['scholars'] }, explanationHtml: 'Paragraph A mentions "scholars and royal officials".', locatorParagraph: 'A' },
              { number: 11, promptHtml: 'Nineteenth-century libraries benefited greatly from donations by wealthy {{q11}}.', answer: { accepted: ['philanthropists'] }, explanationHtml: 'Paragraph B: "wealthy philanthropists became involved".', locatorParagraph: 'B' },
              { number: 12, promptHtml: 'Public libraries came to be known as "the people\'s {{q12}}" because of the education they offered.', answer: { accepted: ['university'] }, explanationHtml: 'Paragraph C: "the people\'s university".', locatorParagraph: 'C' },
              { number: 13, promptHtml: 'Despite predictions of decline, libraries remain a valued community {{q13}}.', answer: { accepted: ['space'] }, explanationHtml: 'Paragraph E: "one of the few remaining public spaces".', locatorParagraph: 'E' },
            ],
          },
        ],
      },
      {
        order: 2,
        title: 'Urban Bee-keeping',
        subtitle: 'Read the text and answer questions 14-26.',
        paragraphs: [
          { label: 'A', html: '<p>Over the past two decades, a growing number of hobbyists have begun keeping honeybee colonies not on rural farms but on the rooftops of city buildings. This trend has been driven partly by widely reported declines in rural bee populations, caused by intensive farming practices and heavy pesticide use, which have led some conservationists and gardeners to look for alternative places where bee colonies might thrive.</p>' },
          { label: 'B', html: '<p>Somewhat counter-intuitively, urban environments can offer real advantages to bees. City parks, gardens and even roadside verges often contain a wider variety of flowering plants across a longer season than a typical rural landscape dominated by a single crop, giving urban bees access to a more varied diet. In turn, these bees pollinate garden plants and street trees, contributing to the biodiversity of green spaces throughout the city.</p>' },
          { label: 'C', html: "<p>Keeping bees in a city is not without its challenges, however. Local authorities in many places require beekeepers to register their hives and to follow rules limiting how close a hive may be placed to a neighbour's property, largely to address understandable public anxiety about stings. Interestingly, several studies have found that urban bees may actually face lower overall pesticide exposure than their rural counterparts, since city gardens are less likely to be treated with the industrial-strength chemicals used on large farms.</p>" },
          { label: 'D', html: '<p>A number of hotels and office buildings have begun hosting beehives on their rooftops, sometimes as part of a wider sustainability programme, and several cities now run community apiaries that offer beekeeping courses to complete beginners. These courses typically cover hive maintenance, safety equipment and the basic biology of the honeybee colony, allowing newcomers to start their own small-scale hive with proper guidance.</p>' },
          { label: 'E', html: "<p>Recent research comparing colony health in cities and the countryside has produced a surprising pattern: in several studies, urban colonies were found to be healthier, on average, than rural colonies, likely due to the greater diversity of available plants and somewhat lower pesticide exposure described above. These findings have encouraged some conservationists to view cities not as a poor substitute for rural habitats but as a genuinely valuable part of long-term bee conservation strategy.</p>" },
        ],
        questionGroups: [
          {
            id: 't1-p2-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, A, B, C or D.',
            questions: [
              {
                number: 14,
                promptHtml: 'Why have some people started keeping bees in cities?',
                options: [
                  { key: 'A', text: 'Because city councils require it' },
                  { key: 'B', text: 'Because rural bee populations have been declining' },
                  { key: 'C', text: 'Because urban honey sells for a higher price' },
                  { key: 'D', text: 'Because rural land has become too expensive' },
                ],
                answer: { accepted: ['B'] },
                explanationHtml: 'Paragraph A: driven by "widely reported declines in rural bee populations".',
                locatorParagraph: 'A',
              },
              {
                number: 15,
                promptHtml: 'What direct benefit do bees provide to a city, according to paragraph B?',
                options: [
                  { key: 'A', text: 'They reduce traffic noise' },
                  { key: 'B', text: 'They pollinate gardens and street trees' },
                  { key: 'C', text: 'They attract more tourists' },
                  { key: 'D', text: 'They lower local temperatures' },
                ],
                answer: { accepted: ['B'] },
                explanationHtml: 'Paragraph B: bees "pollinate garden plants and street trees".',
                locatorParagraph: 'B',
              },
              {
                number: 16,
                promptHtml: 'What surprising finding does paragraph C mention about pesticide exposure?',
                options: [
                  { key: 'A', text: 'Urban bees may face lower pesticide exposure than rural bees' },
                  { key: 'B', text: 'Pesticides have no effect on any bee population' },
                  { key: 'C', text: 'Rural bees are never exposed to pesticides' },
                  { key: 'D', text: 'Urban pesticide use has recently increased sharply' },
                ],
                answer: { accepted: ['A'] },
                explanationHtml: 'Paragraph C: "urban bees may actually face lower overall pesticide exposure than their rural counterparts".',
                locatorParagraph: 'C',
              },
              {
                number: 17,
                promptHtml: 'What does paragraph D say some hotels have started doing?',
                options: [
                  { key: 'A', text: 'Selling honey exclusively to guests' },
                  { key: 'B', text: 'Hosting beehives on their rooftops' },
                  { key: 'C', text: 'Banning beekeeping near their premises' },
                  { key: 'D', text: 'Training staff as professional beekeepers' },
                ],
                answer: { accepted: ['B'] },
                explanationHtml: 'Paragraph D: hotels "begun hosting beehives on their rooftops".',
                locatorParagraph: 'D',
              },
            ],
          },
          {
            id: 't1-p2-short',
            type: 'short_answer',
            instructionHtml: 'Answer the questions below. Write <strong>NO MORE THAN THREE WORDS</strong> for each answer.',
            wordLimit: { maxWords: 3, label: 'NO MORE THAN THREE WORDS' },
            questions: [
              { number: 18, promptHtml: 'Where are urban beehives often physically placed?', answer: { accepted: ['rooftops', 'on rooftops'] }, explanationHtml: 'Paragraph A: colonies kept "on the rooftops of city buildings".', locatorParagraph: 'A' },
              { number: 19, promptHtml: 'What do community apiaries offer to complete beginners?', answer: { accepted: ['beekeeping courses', 'courses'] }, explanationHtml: 'Paragraph D: "beekeeping courses to complete beginners".', locatorParagraph: 'D' },
              { number: 20, promptHtml: "What do city gardens offer bees that a typical rural landscape may not?", answer: { accepted: ['a wider variety', 'greater diversity', 'variety of flowering plants'] }, explanationHtml: 'Paragraph B: "a wider variety of flowering plants".', locatorParagraph: 'B' },
              { number: 21, promptHtml: 'What did recent research find about the health of urban bee colonies compared with rural ones?', answer: { accepted: ['healthier', 'they were healthier'] }, explanationHtml: 'Paragraph E: "urban colonies were found to be healthier, on average".', locatorParagraph: 'E' },
            ],
          },
          {
            id: 't1-p2-tfng',
            type: 'true_false_notgiven',
            instructionHtml:
              'Do the following statements agree with the information given in the passage?<br/><strong>TRUE</strong> if the statement agrees with the information<br/><strong>FALSE</strong> if the statement contradicts the information<br/><strong>NOT GIVEN</strong> if there is no information on this',
            questions: [
              { number: 22, promptHtml: 'Rural bee populations have increased significantly in recent decades.', answer: { accepted: ['FALSE'] }, explanationHtml: 'Paragraph A describes "declines in rural bee populations".', locatorParagraph: 'A' },
              { number: 23, promptHtml: 'Urban beekeeping is entirely unregulated in most cities.', answer: { accepted: ['FALSE'] }, explanationHtml: 'Paragraph C: authorities "require beekeepers to register their hives".', locatorParagraph: 'C' },
              { number: 24, promptHtml: 'Some hotels have begun hosting beehives as part of sustainability programmes.', answer: { accepted: ['TRUE'] }, explanationHtml: 'Paragraph D confirms this directly.', locatorParagraph: 'D' },
              { number: 25, promptHtml: 'Community apiary courses are only open to experienced beekeepers.', answer: { accepted: ['FALSE'] }, explanationHtml: 'Paragraph D: courses are for "complete beginners".', locatorParagraph: 'D' },
              { number: 26, promptHtml: 'All conservationists agree that cities are a poor substitute for rural bee habitats.', answer: { accepted: ['FALSE'] }, explanationHtml: 'Paragraph E: some conservationists now see cities as "a genuinely valuable part" of conservation.', locatorParagraph: 'E' },
            ],
          },
        ],
      },
      {
        order: 3,
        title: 'The Psychology of Decision-Making',
        subtitle: 'Read the text and answer questions 27-40.',
        paragraphs: [
          { label: 'A', html: '<p>Psychologists studying how people make decisions frequently draw on dual process theory, which distinguishes between two broad modes of thought. System 1 is fast, automatic and intuitive, operating with little conscious effort; System 2 is slow, deliberate and effortful, engaged when a problem demands careful analysis. Most everyday decisions, from choosing what to eat to reacting to a sudden noise, are handled by System 1, with System 2 stepping in only when something unusual or particularly important arises.</p>' },
          { label: 'B', html: '<p>Because System 1 operates quickly, it relies on mental shortcuts, or heuristics, rather than exhaustive analysis. The availability heuristic is a well-studied example: people judge how common or likely an event is based on how easily relevant examples come to mind, rather than on actual statistical frequency. This is why vivid but statistically rare events, such as plane crashes, are often judged to be more common than far more frequent but less memorable risks.</p>' },
          { label: 'C', html: '<p>Framing effects offer further evidence that decisions are shaped by presentation rather than by content alone. In one frequently cited illustration, patients respond very differently to a medical treatment described as having a "ninety per cent survival rate" compared with the logically identical description of a "ten per cent mortality rate", even though the underlying odds are exactly the same in both cases.</p>' },
          { label: 'D', html: '<p>It might seem intuitive that offering consumers more choice would always improve satisfaction, yet research on choice overload suggests the opposite can occur. When faced with an excessive number of options, people frequently report feeling overwhelmed, take longer to decide, and are sometimes less satisfied with whatever they eventually choose; in extreme cases, some consumers avoid making a decision at all rather than face the burden of comparing every alternative.</p>' },
          { label: 'E', html: '<p>Emotional state also exerts a powerful influence on decision-making, often outside conscious awareness. Decisions made under stress, time pressure or strong emotion tend to rely more heavily on System 1 processing, since System 2\'s slower, more deliberate analysis becomes harder to sustain under such conditions. This helps to explain why people frequently regret choices made in the heat of the moment.</p>' },
          { label: 'F', html: '<p>Findings from this field have informed practical policy design. Governments in several countries have introduced "default" options into retirement savings schemes, automatically enrolling employees into a pension plan unless they actively choose to opt out. Because most people simply accept whatever the default option happens to be, this single design choice has measurably increased retirement savings rates without restricting anyone\'s freedom to choose differently.</p>' },
        ],
        questionGroups: [
          {
            id: 't1-p3-sentence',
            type: 'sentence_completion',
            instructionHtml: 'Complete the sentences below. Write <strong>ONE WORD ONLY</strong> from the passage for each answer.',
            wordLimit: { maxWords: 1, label: 'ONE WORD ONLY' },
            questions: [
              { number: 27, promptHtml: 'According to dual process theory, System 1 thinking is fast and {{q27}}.', answer: { accepted: ['intuitive'] }, explanationHtml: 'Paragraph A: "fast, automatic and intuitive".', locatorParagraph: 'A' },
              { number: 28, promptHtml: 'The availability heuristic judges frequency by how easily examples come to {{q28}}.', answer: { accepted: ['mind'] }, explanationHtml: 'Paragraph B: "how easily relevant examples come to mind".', locatorParagraph: 'B' },
              { number: 29, promptHtml: 'Framing effects show that identical information can lead to different {{q29}}.', answer: { accepted: ['decisions'] }, explanationHtml: 'Paragraph C illustrates decisions changing with framing.', locatorParagraph: 'C' },
              { number: 30, promptHtml: 'Research suggests that too many options can lead to decision {{q30}} in extreme cases.', answer: { accepted: ['paralysis'] }, explanationHtml: 'Paragraph D: some consumers "avoid making a decision at all".', locatorParagraph: 'D' },
            ],
          },
          {
            id: 't1-p3-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, A, B, C or D.',
            questions: [
              {
                number: 31,
                promptHtml: 'What is the main difference between System 1 and System 2 thinking?',
                options: [
                  { key: 'A', text: 'System 1 is slow and deliberate; System 2 is fast and automatic' },
                  { key: 'B', text: 'System 1 is fast and intuitive; System 2 is slow and deliberate' },
                  { key: 'C', text: 'Both systems operate at exactly the same speed' },
                  { key: 'D', text: 'System 2 is used for every everyday decision' },
                ],
                answer: { accepted: ['B'] },
                explanationHtml: 'Paragraph A defines the two systems directly.',
                locatorParagraph: 'A',
              },
              {
                number: 32,
                promptHtml: 'What does the medical framing example in paragraph C illustrate?',
                options: [
                  { key: 'A', text: 'Patients always prefer more detailed statistics' },
                  { key: 'B', text: 'People respond differently to logically identical information depending on wording' },
                  { key: 'C', text: 'Survival rates are always more accurate than mortality rates' },
                  { key: 'D', text: 'Doctors rarely explain treatment outcomes to patients' },
                ],
                answer: { accepted: ['B'] },
                explanationHtml: 'Paragraph C: "the underlying odds are exactly the same in both cases".',
                locatorParagraph: 'C',
              },
              {
                number: 33,
                promptHtml: 'According to paragraph D, what can happen when consumers face too many choices?',
                options: [
                  { key: 'A', text: 'They always choose the cheapest option' },
                  { key: 'B', text: 'They may feel overwhelmed and less satisfied' },
                  { key: 'C', text: 'They make decisions more quickly than usual' },
                  { key: 'D', text: 'They ask a shop assistant for help in every case' },
                ],
                answer: { accepted: ['B'] },
                explanationHtml: 'Paragraph D: people "report feeling overwhelmed... less satisfied".',
                locatorParagraph: 'D',
              },
              {
                number: 34,
                promptHtml: 'What practical application is described in paragraph F?',
                options: [
                  { key: 'A', text: 'Banning retirement savings schemes' },
                  { key: 'B', text: 'Using default enrolment to increase pension savings' },
                  { key: 'C', text: 'Forcing all employees to save the same amount' },
                  { key: 'D', text: 'Removing choice from retirement planning entirely' },
                ],
                answer: { accepted: ['B'] },
                explanationHtml: 'Paragraph F describes automatic enrolment with an opt-out.',
                locatorParagraph: 'F',
              },
            ],
          },
          {
            id: 't1-p3-short',
            type: 'short_answer',
            instructionHtml: 'Answer the questions below. Write <strong>NO MORE THAN THREE WORDS</strong> for each answer.',
            wordLimit: { maxWords: 3, label: 'NO MORE THAN THREE WORDS' },
            questions: [
              { number: 35, promptHtml: 'What term describes the fast, intuitive mode of thinking?', answer: { accepted: ['system 1', 'system one'] }, explanationHtml: 'Paragraph A names it "System 1".', locatorParagraph: 'A' },
              { number: 36, promptHtml: 'What term describes the slow, deliberate mode of thinking?', answer: { accepted: ['system 2', 'system two'] }, explanationHtml: 'Paragraph A names it "System 2".', locatorParagraph: 'A' },
              { number: 37, promptHtml: 'What general term is used for the mental shortcuts described in paragraph B?', answer: { accepted: ['heuristics'] }, explanationHtml: 'Paragraph B: "mental shortcuts, or heuristics".', locatorParagraph: 'B' },
              { number: 38, promptHtml: 'What term describes how presentation, rather than content, can change a decision?', answer: { accepted: ['framing effects', 'framing effect'] }, explanationHtml: 'Paragraph C discusses "framing effects".', locatorParagraph: 'C' },
              { number: 39, promptHtml: 'What is the name given to the difficulty caused by too many available options?', answer: { accepted: ['choice overload'] }, explanationHtml: 'Paragraph D: "research on choice overload".', locatorParagraph: 'D' },
              { number: 40, promptHtml: 'What design feature is used to encourage retirement saving, according to paragraph F?', answer: { accepted: ['default option', 'default enrolment', 'default enrollment'] }, explanationHtml: 'Paragraph F describes automatic default enrolment.', locatorParagraph: 'F' },
            ],
          },
        ],
      },
    ],
  },

  listening: {
    durationSec: 1800,
    checkTimeSec: 120,
    parts: [
      {
        order: 1,
        contextText: 'You will hear a conversation between a man booking a court at a community sports centre and a receptionist.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Greenfield Sports Centre, good morning." },
          { speaker: 'B', voice: 'david', text: "Morning. I'd like to book a badminton court for this Saturday, if possible." },
          { speaker: 'A', voice: 'zira', text: "Sure, I can help with that. Can I take your name, please?" },
          { speaker: 'B', voice: 'david', text: "Yes, it's Daniel Harrow." },
          { speaker: 'A', voice: 'zira', text: "Thanks, Daniel. What time were you hoping to play?" },
          { speaker: 'B', voice: 'david', text: "Ideally around eleven in the morning." },
          { speaker: 'A', voice: 'zira', text: "That slot is free. And how long would you like the court for — we book in half-hour blocks?" },
          { speaker: 'B', voice: 'david', text: "An hour, please, so two blocks." },
          { speaker: 'A', voice: 'zira', text: "No problem. How many players will there be in total?" },
          { speaker: 'B', voice: 'david', text: "Four of us altogether." },
          { speaker: 'A', voice: 'zira', text: "Great, that's court three, which is our largest. Are you already a centre member, or is this your first visit?" },
          { speaker: 'B', voice: 'david', text: "First visit, actually." },
          { speaker: 'A', voice: 'zira', text: "In that case the court fee is eighteen pounds for the hour. Would you also like to hire racquets?" },
          { speaker: 'B', voice: 'david', text: "Yes please, we'll need four." },
          { speaker: 'A', voice: 'zira', text: "That's an extra two pounds fifty per racquet. Could I take a contact email in case we need to reach you?" },
          { speaker: 'B', voice: 'david', text: "It's d dot harrow, all one word, at mailbox dot com." },
          { speaker: 'A', voice: 'zira', text: "Got it. Please arrive at reception ten minutes before your slot to collect your racquets and court key." },
          { speaker: 'B', voice: 'david', text: "Will do, thanks very much." },
        ],
        questionGroups: [
          {
            id: 't1-l1-form',
            type: 'form_completion',
            instructionHtml: 'Complete the form below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml:
              '<p><strong>Greenfield Sports Centre — Court Booking</strong></p><p>Name: {{q1}}<br/>Activity: Badminton<br/>Day: Saturday<br/>Time: {{q2}} am<br/>Duration: {{q3}} hour<br/>Court number: {{q4}}<br/>Number of players: {{q5}}<br/>Membership status: {{q6}}<br/>Court fee: £{{q7}}<br/>Racquets to hire: {{q8}}<br/>Contact email: {{q9}}<br/>Arrive {{q10}} minutes before the slot</p>',
            questions: [
              { number: 1, answer: { accepted: ['daniel harrow'] }, explanationHtml: 'The caller gives his name as "Daniel Harrow".' },
              { number: 2, answer: { accepted: ['11', 'eleven'] }, explanationHtml: '"around eleven in the morning".' },
              { number: 3, answer: { accepted: ['1', 'one'] }, explanationHtml: '"An hour, please".' },
              { number: 4, answer: { accepted: ['3', 'three'] }, explanationHtml: "\"that's court three\"." },
              { number: 5, answer: { accepted: ['4', 'four'] }, explanationHtml: '"Four of us altogether."' },
              { number: 6, answer: { accepted: ['first visit', 'new'] }, explanationHtml: '"First visit, actually."' },
              { number: 7, answer: { accepted: ['18', 'eighteen'] }, explanationHtml: '"the court fee is eighteen pounds".' },
              { number: 8, answer: { accepted: ['4', 'four'] }, explanationHtml: '"we\'ll need four".' },
              { number: 9, answer: { accepted: ['d.harrow@mailbox.com'] }, explanationHtml: 'The caller spells out his email address.' },
              { number: 10, answer: { accepted: ['10', 'ten'] }, explanationHtml: '"arrive at reception ten minutes before".' },
            ],
          },
        ],
      },
      {
        order: 2,
        contextText: 'You will hear a guide giving a talk to visitors at the start of a tour of Riverside City Museum.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Welcome to Riverside City Museum, and thank you for joining today's tour." },
          { speaker: 'A', voice: 'zira', text: "The museum is open every day except Monday, from nine in the morning until five in the afternoon." },
          { speaker: 'A', voice: 'zira', text: "We're organised across three floors: the ground floor covers the city's early history, the first floor is dedicated to the industrial period, and the second floor houses our contemporary art collection." },
          { speaker: 'A', voice: 'zira', text: "This month, our special temporary exhibition focuses on local textile manufacturing, and it's located on the first floor alongside the permanent industrial collection." },
          { speaker: 'A', voice: 'zira', text: "Photography without flash is permitted throughout the museum, except within the temporary exhibition, where no photography at all is allowed, to protect some of the more fragile items on loan." },
          { speaker: 'A', voice: 'zira', text: "If you'd like a break, our café is on the ground floor, just past the main entrance, and it serves light lunches until four o'clock." },
          { speaker: 'A', voice: 'zira', text: "For anyone interested in a guided tour of the industrial floor specifically, we run a free thirty-minute talk at half past two every afternoon." },
          { speaker: 'A', voice: 'zira', text: "The museum shop, which sells books and replicas connected to our exhibits, is located near the main entrance and closes fifteen minutes before the museum itself." },
          { speaker: 'A', voice: 'zira', text: "Finally, free wifi is available throughout the building, and the network name is displayed at the front desk." },
          { speaker: 'A', voice: 'zira', text: "If you have any questions during your visit, please ask any member of staff wearing a blue badge. Enjoy your visit." },
        ],
        questionGroups: [
          {
            id: 't1-l2-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, A, B or C.',
            questions: [
              { number: 11, promptHtml: 'On which day is the museum closed?', options: [{ key: 'A', text: 'Sunday' }, { key: 'B', text: 'Monday' }, { key: 'C', text: 'Friday' }], answer: { accepted: ['B'] }, explanationHtml: '"open every day except Monday".' },
              { number: 12, promptHtml: 'What does the ground floor cover?', options: [{ key: 'A', text: "The city's early history" }, { key: 'B', text: 'Contemporary art' }, { key: 'C', text: 'The industrial period' }], answer: { accepted: ['A'] }, explanationHtml: '"the ground floor covers the city\'s early history".' },
              { number: 13, promptHtml: 'Where is the special temporary exhibition located?', options: [{ key: 'A', text: 'Ground floor' }, { key: 'B', text: 'First floor' }, { key: 'C', text: 'Second floor' }], answer: { accepted: ['B'] }, explanationHtml: "\"it's located on the first floor\"." },
              { number: 14, promptHtml: 'What is the topic of this month\'s temporary exhibition?', options: [{ key: 'A', text: 'Contemporary art' }, { key: 'B', text: 'Local textile manufacturing' }, { key: 'C', text: "The city's early history" }], answer: { accepted: ['B'] }, explanationHtml: '"focuses on local textile manufacturing".' },
              { number: 15, promptHtml: 'Where exactly is photography not permitted at all?', options: [{ key: 'A', text: 'The whole museum' }, { key: 'B', text: 'The café' }, { key: 'C', text: 'The temporary exhibition' }], answer: { accepted: ['C'] }, explanationHtml: '"no photography at all is allowed" in the temporary exhibition.' },
              { number: 16, promptHtml: 'Until what time does the café serve light lunches?', options: [{ key: 'A', text: 'Two o\'clock' }, { key: 'B', text: 'Four o\'clock' }, { key: 'C', text: 'Five o\'clock' }], answer: { accepted: ['B'] }, explanationHtml: '"serves light lunches until four o\'clock".' },
              { number: 17, promptHtml: 'What time does the free industrial-floor talk begin each afternoon?', options: [{ key: 'A', text: 'Half past two' }, { key: 'B', text: 'Half past three' }, { key: 'C', text: 'Half past four' }], answer: { accepted: ['A'] }, explanationHtml: '"a free thirty-minute talk at half past two".' },
              { number: 18, promptHtml: 'When does the museum shop close?', options: [{ key: 'A', text: 'At the same time as the museum' }, { key: 'B', text: 'Fifteen minutes before the museum closes' }, { key: 'C', text: 'One hour before the museum closes' }], answer: { accepted: ['B'] }, explanationHtml: '"closes fifteen minutes before the museum itself".' },
              { number: 19, promptHtml: 'Where can visitors find the wifi network name?', options: [{ key: 'A', text: 'In the museum shop' }, { key: 'B', text: 'At the front desk' }, { key: 'C', text: 'In the café' }], answer: { accepted: ['B'] }, explanationHtml: '"displayed at the front desk".' },
              { number: 20, promptHtml: 'How can visitors identify staff they can ask for help?', options: [{ key: 'A', text: 'They wear a blue badge' }, { key: 'B', text: 'They stand near the entrance' }, { key: 'C', text: 'They carry a clipboard' }], answer: { accepted: ['A'] }, explanationHtml: '"any member of staff wearing a blue badge".' },
            ],
          },
        ],
      },
      {
        order: 3,
        contextText: 'You will hear two students, Anna and Ben, discussing a research project with their tutor, Dr Silva.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'C', voice: 'zira', text: "Come in, Anna, Ben — let's go through where the project stands." },
          { speaker: 'A', voice: 'zira', text: "Thanks, Dr Silva. I've finished drafting the literature review section." },
          { speaker: 'B', voice: 'david', text: "And I've been working on the survey questions, though I haven't sent them out yet." },
          { speaker: 'C', voice: 'zira', text: "Good progress. Anna, who's going to handle recruiting participants for the survey?" },
          { speaker: 'A', voice: 'zira', text: "That'll be me — I'll contact the student union about circulating it." },
          { speaker: 'C', voice: 'zira', text: "And the data analysis once responses come in?" },
          { speaker: 'B', voice: 'david', text: "I'll take that on, since I've used the statistics software before." },
          { speaker: 'C', voice: 'zira', text: "Perfect. Who's writing the final discussion section?" },
          { speaker: 'A', voice: 'zira', text: "We're planning to write that one together." },
          { speaker: 'C', voice: 'zira', text: "Good idea, given it needs both perspectives. And the presentation slides for the final seminar?" },
          { speaker: 'B', voice: 'david', text: "I can put those together once the analysis is done." },
          { speaker: 'C', voice: 'zira', text: "And formatting the final written report according to the department's style guide?" },
          { speaker: 'A', voice: 'zira', text: "I'll handle the formatting, since I did it for my last project." },
        ],
        questionGroups: [
          {
            id: 't1-l3-features',
            type: 'matching_features',
            instructionHtml: 'Who is responsible for each task? <em>Write the correct letter, A, B or C.</em>',
            bank: [
              { key: 'A', text: 'Anna' },
              { key: 'B', text: 'Ben' },
              { key: 'C', text: 'Both Anna and Ben' },
            ],
            bankReusable: true,
            questions: [
              { number: 21, promptHtml: 'the literature review', answer: { accepted: ['A'] }, explanationHtml: "Anna says she's \"finished drafting the literature review section\"." },
              { number: 22, promptHtml: 'the survey questions', answer: { accepted: ['B'] }, explanationHtml: "Ben says he's \"been working on the survey questions\"." },
              { number: 23, promptHtml: 'recruiting participants', answer: { accepted: ['A'] }, explanationHtml: '"That\'ll be me" — Anna will contact the student union.' },
              { number: 24, promptHtml: 'the data analysis', answer: { accepted: ['B'] }, explanationHtml: "Ben says \"I'll take that on\"." },
              { number: 25, promptHtml: 'the discussion section', answer: { accepted: ['C'] }, explanationHtml: '"We\'re planning to write that one together."' },
              { number: 26, promptHtml: 'the presentation slides', answer: { accepted: ['B'] }, explanationHtml: 'Ben says he can "put those together".' },
              { number: 27, promptHtml: 'formatting the final report', answer: { accepted: ['A'] }, explanationHtml: "Anna says \"I'll handle the formatting\"." },
            ],
          },
          {
            id: 't1-l3-short',
            type: 'short_answer',
            instructionHtml: 'Answer the questions below. Write <strong>NO MORE THAN THREE WORDS</strong> for each answer.',
            wordLimit: { maxWords: 3, label: 'NO MORE THAN THREE WORDS' },
            questions: [
              { number: 28, promptHtml: 'What has Ben not yet done with the survey questions?', answer: { accepted: ['sent them out', 'send them out'] }, explanationHtml: '"though I haven\'t sent them out yet".' },
              { number: 29, promptHtml: 'Who will Anna contact to help circulate the survey?', answer: { accepted: ['the student union', 'student union'] }, explanationHtml: '"contact the student union".' },
              { number: 30, promptHtml: 'Why will Ben handle the data analysis?', answer: { accepted: ["used the software before", "he's used it before", 'used statistics software before'] }, explanationHtml: '"since I\'ve used the statistics software before".' },
            ],
          },
        ],
      },
      {
        order: 4,
        contextText: 'You will hear a lecture on renewable energy.',
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "This morning I want to give you an overview of renewable energy, meaning energy collected from sources that are naturally replenished." },
          { speaker: 'A', voice: 'david', text: "The most widely used renewable source worldwide is hydropower, which uses the movement of water, usually through a dam, to turn turbines and generate electricity. It has the advantage of being highly predictable compared with other renewable sources." },
          { speaker: 'A', voice: 'david', text: "Solar power has grown enormously in the last decade, largely because the cost of photovoltaic panels, which convert sunlight directly into electricity, has fallen by more than eighty per cent since 2010." },
          { speaker: 'A', voice: 'david', text: "Wind power, generated by turbines that convert the kinetic energy of moving air into electricity, is now competitive in cost with fossil fuels in many regions, particularly where large offshore wind farms have been built." },
          { speaker: 'A', voice: 'david', text: "One ongoing challenge for all renewable sources is storage: solar and wind power are intermittent, meaning they are not always available exactly when demand is highest, so improving battery storage technology remains a major research priority." },
          { speaker: 'A', voice: 'david', text: "Finally, many governments have introduced subsidies to encourage households to install rooftop solar panels, since faster household adoption helps reduce overall dependence on fossil fuel power stations." },
        ],
        questionGroups: [
          {
            id: 't1-l4-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>ONE WORD ONLY</strong> for each answer.',
            wordLimit: { maxWords: 1, label: 'ONE WORD ONLY' },
            stemHtml:
              '<p><strong>Renewable Energy — Lecture Notes</strong></p><p>Definition: energy from sources that are naturally {{q31}}</p><p>Most widely used source worldwide: {{q32}} power (uses a dam and turbines)<br/>Advantage: highly {{q33}}</p><p>Solar power: cost of {{q34}} panels has fallen by over 80% since 2010</p><p>Wind power: turbines convert {{q35}} energy of moving air; competitive cost, especially {{q36}} wind farms</p><p>Main challenge: {{q37}} — solar and wind are {{q38}}, not always available when demand is high</p><p>Priority: improving battery {{q39}} technology</p><p>Government support: {{q40}} for household rooftop solar panels</p>',
            questions: [
              { number: 31, answer: { accepted: ['replenished'] }, explanationHtml: '"naturally replenished".' },
              { number: 32, answer: { accepted: ['hydropower', 'hydro'] }, explanationHtml: '"the most widely used renewable source worldwide is hydropower".' },
              { number: 33, answer: { accepted: ['predictable'] }, explanationHtml: '"highly predictable compared with other renewable sources".' },
              { number: 34, answer: { accepted: ['photovoltaic'] }, explanationHtml: '"photovoltaic panels".' },
              { number: 35, answer: { accepted: ['kinetic'] }, explanationHtml: '"convert the kinetic energy of moving air".' },
              { number: 36, answer: { accepted: ['offshore'] }, explanationHtml: '"large offshore wind farms".' },
              { number: 37, answer: { accepted: ['storage'] }, explanationHtml: '"an ongoing challenge for all renewable sources is storage".' },
              { number: 38, answer: { accepted: ['intermittent'] }, explanationHtml: '"solar and wind power are intermittent".' },
              { number: 39, answer: { accepted: ['storage'] }, explanationHtml: '"improving battery storage technology".' },
              { number: 40, answer: { accepted: ['subsidies'] }, explanationHtml: '"governments have introduced subsidies".' },
            ],
          },
        ],
      },
    ],
  },

  writing: {
    durationSec: 3600,
    task1: {
      order: 1,
      minWords: 150,
      recommendedMin: 20,
      promptHtml:
        '<p>The chart below shows the percentage of people in different age groups who used the internet daily in 2010 and in 2023.</p><p>Summarise the information by selecting and reporting the main features, and make comparisons where relevant.</p>',
      chart: {
        chartType: 'bar',
        title: 'Daily internet use by age group, 2010 vs 2023',
        unit: '%',
        categories: ['18-29', '30-44', '45-59', '60+'],
        series: [
          { name: '2010', data: [58, 41, 22, 8] },
          { name: '2023', data: [96, 91, 78, 52] },
        ],
      },
    },
    task2: {
      order: 2,
      minWords: 250,
      recommendedMin: 40,
      promptHtml:
        '<p>Technology now plays a central role in how students learn, both inside and outside the classroom.</p><p>Do the advantages of this development outweigh the disadvantages?</p>',
    },
  },
};
