// Original IELTS-style practice content (NOT copied or paraphrased from any real
// Cambridge/IELTS book). Only the exam STRUCTURE follows a standard Academic test
// layout; every topic, passage, transcript, question and answer is written from scratch.
import { table, TFNG_INSTRUCTION, q, paras, mc, bank } from './_html.mjs';

export default {
  slug: 'vocably-practice-test-12',
  title: 'Vocably Practice Test 12',
  difficulty: 'medium',

  reading: {
    durationSec: 3600,
    passages: [
      {
        order: 1,
        title: 'Building for the shake',
        subtitle: 'Read the text and answer questions 1-13.',
        paragraphs: paras(
          ['A', `People in Japan feel about fifteen hundred earthquakes in an average year. Most are barely noticeable, but every so often one is powerful enough to destroy whole districts. In 1923, an earthquake near Tokyo and Yokohama, followed by fires that raced through districts of wooden houses, killed more than a hundred thousand people. The disaster prompted the government to introduce the country's first building regulations for earthquake resistance, and since then the rules have been tightened after each major event, most significantly in 1981 and again after the Kobe earthquake of 1995. Today, Japan's engineers are widely regarded as the world's leaders in the science of surviving the shake. Their methods have been exported to dozens of countries, and their research laboratories contain full-size shaking tables on which whole buildings can be tested against recordings of real earthquakes.`],
          ['B', `The central lesson they have learnt is that a building should bend rather than resist. A rigid structure that is very strong but brittle may withstand a small tremor, but in a large one, it is likely to crack and fail suddenly. A flexible structure, by contrast, can sway and absorb some of the energy. Modern Japanese buildings therefore tend to be made of steel frames that can bend without breaking, with joints designed to allow movement. A further step is base isolation, a technique first tested in Japan in the 1980s, in which a building stands on a layer of bearings made of alternating sheets of rubber and steel. When the ground moves, the bearings deform, and the building above moves far less than it would otherwise. Many hospitals, government offices and apartment blocks are now built in this way.`],
          ['C', `Tall buildings face a particular problem, since they sway for some time after a shock, and the movement may build up until damage results. To limit it, engineers fit dampers, devices that work like the shock absorbers of a car. One of the most striking versions is the tuned mass damper: a huge weight, hung near the top of the building, which swings in the opposite direction to the sway. One skyscraper in Taipei contains a steel sphere of some six hundred tonnes that is visible to visitors, and has become a tourist attraction in its own right. In a typhoon or earthquake, it moves by up to a metre, reducing the swaying of the building by a considerable amount.`],
          ['D', `Not all of the solutions are new. Japan has wooden pagodas that have stood for more than a thousand years, and remarkably few have been destroyed by earthquakes. One reason seems to be a central pillar, which runs from the top of the building to the ground, but is not rigidly fixed to the floors. During an earthquake, the storeys of the pagoda move in different directions, like the segments of a snake, while the central column stays relatively still and stabilises the whole. Engineers studied this design carefully when they built the country's tallest tower in Tokyo, which has a similar concrete column at its centre, connected to the outer frame by dampers.`],
          ['E', `Preparation also depends on warning. Japan has a network of thousands of sensors that detect the first, weaker tremor of an earthquake, which travels faster than the stronger shaking that follows. Computers calculate the size and location of the quake within seconds and send an alert to television and mobile phones, which can arrive several seconds before the main shaking. That may seem a trivial amount of time, but it is enough for high-speed trains to be slowed, for gas supplies to be shut off and for surgeons to pause an operation. Schoolchildren are taught to take cover under their desks, and regular drills mean that most people know what to do.`],
          ['F', `Yet the country's record is not perfect. The 2011 earthquake off the north-east coast caused a tsunami that overwhelmed coastal defences and killed nearly twenty thousand people, reminding engineers that buildings designed for one kind of danger may be vulnerable to another. Older buildings, constructed before modern standards, remain a serious problem. Strengthening them, known as retrofitting, is expensive and slow, and owners are often reluctant to pay. Other earthquake-prone countries, including Chile and New Zealand, have adopted similar principles, and have seen a fall in casualties, but many poorer countries cannot afford the same standards, and it is there that the greatest loss of life still occurs.`]
        ),
        questionGroups: [
          {
            id: 't12-r1-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              q(1, 'People in Japan feel about fifteen hundred earthquakes in a typical year.', 'TRUE', 'Paragraph A: "about fifteen hundred earthquakes in an average year".', 'A'),
              q(2, 'Japan\'s first building regulations for earthquake resistance followed the disaster of 1923.', 'TRUE', 'Paragraph A: the disaster "prompted the government to introduce the country\'s first building regulations".', 'A'),
              q(3, 'Rigid buildings are safer than flexible ones in a large earthquake.', 'FALSE', 'Paragraph B: a rigid structure "is likely to crack and fail suddenly".', 'B'),
              q(4, 'Base isolation was first tested in Japan in the 1990s.', 'FALSE', 'Paragraph B: "first tested in Japan in the 1980s".', 'B'),
              q(5, 'The central pillar of a traditional pagoda is made of steel.', 'NOT GIVEN', 'The material of the pillar is not stated.', 'D'),
              q(6, 'Early warning systems give people several minutes to reach safety.', 'FALSE', 'Paragraph E: "several seconds", not minutes.', 'E'),
            ],
          },
          {
            id: 't12-r1-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B, C or D</strong>.',
            questions: [
              mc(7, 'What is the purpose of base isolation?', ['to make a building heavier', 'to separate a building from the movement of the ground', 'to make a building taller', 'to warn people of an earthquake'], 'B', 'Paragraph B: "the building above moves far less than it would otherwise".', 'B'),
              mc(8, 'How does a tuned mass damper work?', ['It holds the building rigidly still.', 'A heavy weight swings in the opposite direction to the building\'s sway.', 'It transfers the shaking to the ground.', 'It warns the occupants of a storm.'], 'B', 'Paragraph C: "swings in the opposite direction to the sway".', 'C'),
              mc(9, 'What does the writer say about retrofitting older buildings?', ['It is cheap and quick.', 'It is unnecessary.', 'It is expensive and slow, and owners are reluctant to pay.', 'It has been completed in Japan.'], 'C', 'Paragraph F: "expensive and slow, and owners are often reluctant to pay".', 'F'),
            ],
          },
          {
            id: 't12-r1-summary',
            type: 'summary_completion_bank',
            instructionHtml: 'Complete the summary of paragraph E using the list of words, A-H, below.',
            bankReusable: false,
            bank: bank(['tremor', 'shaking', 'slowed', 'shut off', 'evacuated', 'cables', 'tsunamis', 'repaired']),
            stemHtml: '<p>Sensors detect the first, weaker {{q10}} of an earthquake. An alert can reach people before the stronger {{q11}} begins. In those few seconds, high-speed trains are {{q12}} and gas supplies are {{q13}}.</p>',
            questions: [
              q(10, null, 'A', 'Paragraph E: "the first, weaker tremor".', 'E'),
              q(11, null, 'B', 'Paragraph E: "the stronger shaking that follows".', 'E'),
              q(12, null, 'C', 'Paragraph E: "trains to be slowed".', 'E'),
              q(13, null, 'D', 'Paragraph E: "gas supplies to be shut off".', 'E'),
            ],
          },
        ],
      },
      {
        order: 2,
        title: 'The psychology of giving',
        subtitle: 'Read the text and answer questions 14-26.',
        paragraphs: paras(
          ['A', `Why do people give money to strangers? To an economist who believes that individuals act mainly to benefit themselves, the question is a puzzle. A donor receives nothing tangible in return, and yet in many countries, charitable giving is a significant part of the economy. In the United States, for example, the average household gives about two per cent of its income to charity each year, and in some countries, the figure is higher. Psychologists and neuroscientists have spent decades trying to understand what motivates this behaviour, and their answers have surprised many people. The findings matter not only to charities, which depend on donations, but also to governments that wish to encourage volunteering, blood donation and other forms of public-spirited behaviour.`],
          ['B', `One explanation, known as the warm glow, is that giving makes the donor feel good. Brain scans have shown that when volunteers decide to donate money to a charity, regions associated with reward and pleasure become active, and these are the same regions that respond when people receive money themselves. In one study, volunteers who were given a sum of money were asked either to keep it or to give it away; those who gave it away, and those who had it taken away as a tax, showed different patterns of brain activity, with the voluntary donors experiencing the stronger response. The results suggest that generosity is, in part, its own reward.`],
          ['C', `But the warm glow is not triggered equally by every appeal. Experiments have repeatedly shown that people give more to help one named child than to help a group of a thousand. This is known as the identifiable victim effect. In one study, participants who were shown a photograph and the name of a single hungry girl donated more than twice as much as those who were told about millions of hungry people in the same region. Researchers describe the tendency for large numbers to fail to move us as psychic numbing: a number is an abstraction, but a face is someone we can imagine meeting.`],
          ['D', `Other people's behaviour also has a strong influence. People are more likely to give when they are told that others have done so, and they tend to give more when their contribution will be seen. In workplaces, charity campaigns that publish the names of donors usually collect more than those that do not, and colleagues who are asked in person by someone they know are hard to refuse. Some critics regard this as a sign that giving is motivated less by compassion than by a desire to be seen as generous, but, as one researcher put it, a donation that helps is useful whatever its motive.`],
          ['E', `A movement known as effective altruism has argued that these emotional responses may lead us astray. Charities vary enormously in how much good they do with each pound they receive: a treatment for a tropical disease may save a life for a few hundred pounds, while another programme with a more appealing story may achieve far less. If donors respond to stories rather than evidence, the movement says, much money is wasted. Its supporters urge people to consult independent evaluations before they give, and to think of donations as a chance to do as much good as possible, rather than as an expression of feeling.`],
          ['F', `Fundraisers have learnt from all of this. Simple changes in the way a request is made can have large effects: suggesting a default amount on a donation form, for example, increases the average gift, and offering to match a donor's contribution, so that each pound is doubled, increases both the number of donors and the sum raised. Telling the story of one individual, then showing how the same help could be given to many, can combine the power of the identifiable victim with the force of the facts.`],
          ['G', `The study of giving shows that generosity is neither purely selfish nor purely selfless. People are moved by feelings, by their neighbours and by the way a request is made, and these influences are neither good nor bad in themselves. The challenge for charities, and for donors, is to make use of the emotions that bring people to give while ensuring that the money reaches where it is most needed.`]
        ),
        questionGroups: [
          {
            id: 't12-r2-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B, C or D</strong>.',
            questions: [
              mc(14, 'What puzzles some economists about charitable giving?', ['that it is so rare', 'that donors receive nothing tangible in return', 'that it is decreasing', 'that it is taxed'], 'B', 'Paragraph A: "A donor receives nothing tangible in return".', 'A'),
              mc(15, 'In the brain-scan studies, donating money', ['made volunteers anxious', 'activated regions that also respond to receiving money', 'was less pleasant than paying tax', 'made no difference to brain activity'], 'B', 'Paragraph B: "the same regions that respond when people receive money themselves".', 'B'),
              mc(16, 'The identifiable victim effect is the tendency for people to', ['give more to a single named person than to a large group', 'refuse to give to individuals', 'prefer large charities', 'ignore photographs'], 'A', 'Paragraph C: people "give more to help one named child than to help a group of a thousand".', 'C'),
              mc(17, 'What is the view of the effective altruism movement?', ['Emotional giving is always the best kind.', 'Giving should be based on evidence of how much good is done.', 'People should give less.', 'Charities should not advertise.'], 'B', 'Paragraph E: donors should "consult independent evaluations".', 'E'),
            ],
          },
          {
            id: 't12-r2-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              q(18, 'The average American household gives about ten per cent of its income to charity.', 'FALSE', 'Paragraph A: "about two per cent".', 'A'),
              q(19, 'People are more likely to give when they are told that others have done so.', 'TRUE', 'Paragraph D: "more likely to give when they are told that others have done so".', 'D'),
              q(20, 'Offers to match a donor\'s contribution reduce the total amount raised.', 'FALSE', 'Paragraph F: matching "increases both the number of donors and the sum raised".', 'F'),
              q(21, 'Large charities are generally more effective than small ones.', 'NOT GIVEN', 'The size of charities is not discussed.'),
            ],
          },
          {
            id: 't12-r2-matchinfo',
            type: 'matching_information',
            instructionHtml: 'Reading Passage 2 has seven paragraphs, A-G. Which paragraph contains the following information? <em>Choose the correct letter, A-G.</em>',
            questions: [
              q(22, 'a description of the failure of large numbers to move people', 'C', 'Paragraph C: "psychic numbing".', 'C'),
              q(23, 'evidence from studies of the brain', 'B', 'Paragraph B: brain scans.', 'B'),
              q(24, 'advice that donors should consult independent evaluations', 'E', 'Paragraph E: "consult independent evaluations before they give".', 'E'),
              q(25, 'an example of how small changes in a request can affect the amount given', 'F', 'Paragraph F: suggesting a default amount on a form.', 'F'),
              q(26, 'the influence of colleagues on giving at work', 'D', 'Paragraph D: "In workplaces, charity campaigns ...".', 'D'),
            ],
          },
        ],
      },
      {
        order: 3,
        title: 'The evolution of money',
        subtitle: 'Read the text and answer questions 27-40.',
        paragraphs: paras(
          ['A', `Imagine a world without money. If you were a farmer who wanted a pair of shoes, you would have to find a shoemaker who wanted your vegetables. This system of direct exchange, known as barter, is hard to operate because it requires a double coincidence of wants: each person must happen to have what the other one needs. Money solves the problem by serving as a medium of exchange that everyone will accept. It also acts as a store of value, allowing wealth to be kept for the future, and as a unit of account, making it easy to compare the worth of very different goods. How these functions have been performed has changed enormously over time.`],
          ['B', `The earliest forms of money were ordinary goods that people valued. Cowrie shells, which are small, durable and hard to forge, were used across large parts of Africa and Asia for thousands of years. Salt, which was essential for preserving food, was so valuable that, according to a widely repeated belief, the word salary comes from the Latin word for it. In the ancient city of Mesopotamia, payments were made in measured quantities of grain, and were recorded on clay tablets. Commodity money of this sort had obvious weaknesses: it could be bulky, it could spoil, and the quality of one sack of grain differed from another.`],
          ['C', `A great step forward came with metal coins. The first were made in Lydia, in what is now western Turkey, around 600 BC, from a natural mixture of gold and silver. Each coin was stamped by the ruler, who thereby guaranteed its weight and purity, so that traders no longer needed to weigh and test the metal every time. The idea spread rapidly across the Mediterranean and the Middle East, and in China, where coins of bronze had been in use for centuries, it took a different form, with holes in the middle so that they could be strung together. Coins, however, gave rulers an opportunity to cheat. By mixing cheaper metals into the coins, a government could produce more of them from the same quantity of gold, a practice known as debasement, which gradually reduced what the money could buy.`],
          ['D', `Paper money began in China, where merchants found that carrying heavy strings of coins over long distances was inconvenient, and began to deposit them with trusted agents in exchange for paper receipts. By the eleventh century, the government had taken over the system and was issuing notes of its own. The idea reached Europe much later; the first European bank notes were issued in Sweden in 1661. For a long time, paper notes could be exchanged for a fixed amount of gold or silver held by the issuer, but during the twentieth century, governments abandoned this link, and modern notes are valuable only because people trust the state that issues them.`],
          ['E', `Today, most money exists only as numbers in bank computers. The spread of cards in the second half of the twentieth century, followed by online banking, meant that millions of people can go through a working week without handling a coin. In some countries, mobile phones have gone further: a service launched in Kenya in 2007 allowed people to send money by text message, and within a few years, it was used by a large share of the adult population, including millions who had never had a bank account.`],
          ['F', `The most recent development is the cryptocurrency. The first, introduced in 2009, used a shared digital ledger that could not be altered, removing the need for a central authority. Thousands of others have followed. Their values, however, swing wildly, which makes them unsuitable for everyday purchases, and the computers that create some of them consume vast amounts of electricity. Several central banks are now exploring digital versions of their own national currencies, which would combine the convenience of digital payments with the stability of official money. Critics worry that such currencies could give governments unprecedented insight into how individuals spend their money, and the question of how to protect privacy is still unresolved.`],
          ['G', `Each of these forms has rested on trust: trust that a shell would be accepted by the next person, that a ruler's stamp meant what it said, that a government would honour its notes, that a bank would keep the records straight. The technology of money has changed from shells to computers, but the underlying principle remains the same, and money will probably continue to evolve as long as people find new ways of trusting each other.`]
        ),
        questionGroups: [
          {
            id: 't12-r3-sentences',
            type: 'sentence_completion',
            instructionHtml: 'Complete the sentences below. Choose <strong>NO MORE THAN TWO WORDS</strong> from the passage for each answer.',
            wordLimit: { maxWords: 2, label: 'NO MORE THAN TWO WORDS' },
            questions: [
              q(27, 'Barter requires a double {{q27}} of wants.', ['coincidence'], 'Paragraph A: "a double coincidence of wants".', 'A'),
              q(28, 'Money acts as a medium of exchange, a store of value and a unit of {{q28}}.', ['account'], 'Paragraph A: "a unit of account".', 'A'),
              q(29, 'The word salary is thought to come from the Latin word for {{q29}}.', ['salt'], 'Paragraph B: "the word salary comes from the Latin word for it [salt]".', 'B'),
              q(30, 'Payments in grain in Mesopotamia were recorded on clay {{q30}}.', ['tablets'], 'Paragraph B: "recorded on clay tablets".', 'B'),
              q(31, 'The first coins were made in {{q31}} around 600 BC.', ['lydia'], 'Paragraph C: "made in Lydia".', 'C'),
              q(32, 'Mixing cheaper metals into coins is known as {{q32}}.', ['debasement'], 'Paragraph C: "a practice known as debasement".', 'C'),
            ],
          },
          {
            id: 't12-r3-classify',
            type: 'matching_features',
            instructionHtml: 'Look at the following statements (Questions 33-40) and the list of types of money below. Match each statement with the correct type, <strong>A, B, C or D</strong>.<br/>You may use any letter more than once.',
            bankReusable: true,
            bank: [
              { key: 'A', text: 'commodity money' },
              { key: 'B', text: 'metal coins' },
              { key: 'C', text: 'paper money' },
              { key: 'D', text: 'digital money' },
            ],
            questions: [
              q(33, 'was first issued in Europe in Sweden in 1661', 'C', 'Paragraph D: "the first European bank notes were issued in Sweden in 1661".', 'D'),
              q(34, 'could spoil or vary in quality', 'A', 'Paragraph B: "it could spoil, and the quality of one sack of grain differed from another".', 'B'),
              q(35, 'carried the ruler\'s guarantee of weight and purity', 'B', 'Paragraph C: "guaranteed its weight and purity".', 'C'),
              q(36, 'mostly exists only as numbers in bank computers', 'D', 'Paragraph E: "most money exists only as numbers in bank computers".', 'E'),
              q(37, 'included measured quantities of grain', 'A', 'Paragraph B: "payments were made in measured quantities of grain".', 'B'),
              q(38, 'allowed people in Kenya without bank accounts to send money', 'D', 'Paragraph E: "millions who had never had a bank account".', 'E'),
              q(39, 'was first used in China by merchants who wanted to avoid carrying heavy loads', 'C', 'Paragraph D: paper receipts replaced strings of coins.', 'D'),
              q(40, 'gave governments a way to produce more money from the same amount of gold', 'B', 'Paragraph C: debasement.', 'C'),
            ],
          },
        ],
      },
    ],
  },

  listening: {
    durationSec: 1800,
    checkTimeSec: 120,
    parts: [
      {
        order: 1,
        contextText: 'You will hear a man reporting a lost suitcase to an airport baggage office.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Baggage services, good afternoon. How can I help?" },
          { speaker: 'B', voice: 'david', text: "Hello. I've just arrived on a flight from Lisbon, and my suitcase hasn't appeared on the carousel." },
          { speaker: 'A', voice: 'zira', text: "I'm sorry to hear that. I'll take some details. What's your name?" },
          { speaker: 'B', voice: 'david', text: "Daniel Okonkwo. O-K-O-N-K-W-O." },
          { speaker: 'A', voice: 'zira', text: "And your flight number?" },
          { speaker: 'B', voice: 'david', text: "It was TP four-one-seven, arriving at two-fifteen this afternoon." },
          { speaker: 'A', voice: 'zira', text: "Thank you. Could you describe the suitcase?" },
          { speaker: 'B', voice: 'david', text: "It's a large one, dark green, with wheels and a combination lock. There's a yellow ribbon on the handle, so it's easy to spot." },
          { speaker: 'A', voice: 'zira', text: "Good. And what was inside?" },
          { speaker: 'B', voice: 'david', text: "Mainly clothes, a pair of hiking boots, and a laptop bag, which I hope is safe. Oh, and some presents for my family." },
          { speaker: 'A', voice: 'zira', text: "I understand. Did you check the bag in at Lisbon, or did you change planes?" },
          { speaker: 'B', voice: 'david', text: "I changed at Madrid. I had about an hour between flights, so perhaps it didn't make the connection." },
          { speaker: 'A', voice: 'zira', text: "That's quite common. I'll contact Madrid straight away. If it's there, it will probably arrive on the evening flight, at seven-thirty." },
          { speaker: 'B', voice: 'david', text: "And what happens then?" },
          { speaker: 'A', voice: 'zira', text: "We'll deliver it to your address free of charge. Where are you staying?" },
          { speaker: 'B', voice: 'david', text: "At the Riverside Hotel, on Mill Lane, for the first week. Then I'll be at my sister's in Oxford." },
          { speaker: 'A', voice: 'zira', text: "I'll put the hotel down. And a contact number?" },
          { speaker: 'B', voice: 'david', text: "My mobile is oh-seven-seven-oh-oh, nine-oh-oh, five-five-two." },
          { speaker: 'A', voice: 'zira', text: "Thank you, Mr Okonkwo. In the meantime, you can claim up to fifty pounds for essential items, such as toiletries, if you keep your receipts." },
        ],
        questionGroups: [
          {
            id: 't12-l1-form',
            type: 'form_completion',
            instructionHtml: 'Complete the form below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Baggage services: Report of missing luggage', ''],
              [
                ['Surname', '{{q1}}'],
                ['Arriving from', '{{q2}}'],
                ['Flight number', 'TP {{q3}}'],
                ['Colour of suitcase', '{{q4}}'],
                ['Distinguishing feature', 'yellow {{q5}} on the handle'],
                ['Contents', 'clothes, hiking boots, {{q6}} bag and presents'],
                ['Connection at', '{{q7}}'],
                ['Probable arrival', 'evening flight at {{q8}}'],
                ['Delivery address', 'Riverside Hotel, {{q9}} Lane'],
                ['Amount for essential items', 'up to £{{q10}}'],
              ]
            ),
            questions: [
              q(1, null, ['okonkwo'], 'Spelled out: O-K-O-N-K-W-O.'),
              q(2, null, ['lisbon'], '"a flight from Lisbon".'),
              q(3, null, ['417', 'four one seven', 'four-one-seven'], '"TP four-one-seven".'),
              q(4, null, ['dark green', 'green'], '"dark green, with wheels".'),
              q(5, null, ['ribbon'], '"a yellow ribbon on the handle".'),
              q(6, null, ['laptop'], '"a laptop bag".'),
              q(7, null, ['madrid'], '"I changed at Madrid."'),
              q(8, null, ['7.30', '7:30', 'seven-thirty', 'seven thirty', 'half past seven', '19:30'], '"at seven-thirty".'),
              q(9, null, ['mill'], '"on Mill Lane".'),
              q(10, null, ['50', 'fifty'], '"up to fifty pounds".'),
            ],
          },
        ],
      },
      {
        order: 2,
        contextText: 'You will hear a guide explaining how cheese is made during a visit to a dairy.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Welcome to Hillcrest Dairy. I'm Peter, and I'll take you through the cheese-making process. We've been making cheese here for four generations, and we still use many traditional methods." },
          { speaker: 'A', voice: 'david', text: "First, a little about the farm. We have a herd of a hundred and twenty cows, which graze in the fields you passed on the way in. They're milked twice a day, and the milk comes straight to the dairy, usually within two hours of milking." },
          { speaker: 'A', voice: 'david', text: "Our tour follows the route of the milk. In the first room, the milk is gently heated to sixty-five degrees, which kills harmful bacteria but keeps the flavour. This is known as pasteurisation." },
          { speaker: 'A', voice: 'david', text: "It is then cooled, and a starter culture is added. This is a mixture of friendly bacteria, which turn the sugar in milk into lactic acid, and this gives the cheese its tangy taste. After about an hour, we add rennet, a substance which makes the milk set like a jelly." },
          { speaker: 'A', voice: 'david', text: "The jelly is then cut into small cubes with wire knives. This is called cutting the curd, and it releases the watery part of the milk, the whey. The smaller the pieces, the drier and harder the final cheese." },
          { speaker: 'A', voice: 'david', text: "Next, the curds and whey are warmed slowly, and stirred for about forty minutes. You'll see the curds sink to the bottom of the vat. The whey is then drained off, and, incidentally, it isn't wasted; it goes to a neighbour, who feeds it to his pigs." },
          { speaker: 'A', voice: 'david', text: "The curds are then cut into slabs, stacked and turned, and then milled into small pieces, and salt is added. The salt improves the flavour and helps to preserve the cheese." },
          { speaker: 'A', voice: 'david', text: "After that, the curds are packed into moulds and pressed overnight, to squeeze out the last of the whey and to give the cheese its shape." },
          { speaker: 'A', voice: 'david', text: "Finally, the cheeses are moved to the storeroom, which you'll see at the end of the tour, where they mature for between three months and two years, depending on the type. They're turned regularly, so that the moisture is evenly spread." },
          { speaker: 'A', voice: 'david', text: "There's a shop at the end of the tour, where you can taste our cheeses, and if you've any questions, just ask. Now, please follow me to the first room." },
        ],
        questionGroups: [
          {
            id: 't12-l2-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(11, 'How long has the dairy been making cheese?', ['two generations', 'three generations', 'four generations'], 'C', '"for four generations".'),
              mc(12, 'How many cows are there in the herd?', ['100', '120', '220'], 'B', '"a hundred and twenty cows".'),
              mc(13, 'How soon does the milk reach the dairy?', ['within two hours of milking', 'the next morning', 'within a week'], 'A', '"usually within two hours of milking".'),
              mc(14, 'What happens to the whey?', ['It is thrown away.', 'It is fed to pigs by a neighbour.', 'It is made into butter.'], 'B', '"it goes to a neighbour, who feeds it to his pigs".'),
            ],
          },
          {
            id: 't12-l2-flow',
            type: 'flowchart_completion',
            instructionHtml: 'Complete the flow-chart below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Making cheese</strong></p><p>1. Milk is heated to {{q15}} degrees (pasteurisation).</p><p>2. A {{q16}} culture is added.</p><p>3. {{q17}} is added to make the milk set.</p><p>4. The jelly is cut into small cubes with {{q18}}.</p><p>5. The curds are stirred for about {{q19}} minutes, and the whey is drained off.</p><p>6. The curds are cut, stacked and milled, then {{q20}} is added.</p>',
            questions: [
              q(15, null, ['65', 'sixty-five', 'sixty five'], '"gently heated to sixty-five degrees".'),
              q(16, null, ['starter'], '"a starter culture is added".'),
              q(17, null, ['rennet'], '"we add rennet".'),
              q(18, null, ['wire knives', 'knives'], '"cut into small cubes with wire knives".'),
              q(19, null, ['40', 'forty'], '"stirred for about forty minutes".'),
              q(20, null, ['salt'], '"salt is added".'),
            ],
          },
        ],
      },
      {
        order: 3,
        contextText: 'You will hear a student, Isaac, discussing his dissertation on urban noise with his supervisor.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david2', text: "Good morning, Isaac. How's the dissertation on urban noise coming along?" },
          { speaker: 'B', voice: 'david', text: "Slowly, I'm afraid. I've done a lot of reading, but I'm finding it hard to narrow down my research question." },
          { speaker: 'A', voice: 'david2', text: "That's very common at this stage. What aspect interests you most?" },
          { speaker: 'B', voice: 'david', text: "Originally I wanted to study the effect of traffic noise on sleep, but I've realised that would need medical equipment which I don't have access to." },
          { speaker: 'A', voice: 'david2', text: "Quite. Have you thought about something you can measure yourself, such as how noise levels vary across different parts of the city?" },
          { speaker: 'B', voice: 'david', text: "I have. I could compare a busy shopping street, a park and a residential area, taking readings with a sound meter at different times of day." },
          { speaker: 'A', voice: 'david2', text: "That's a manageable project, and the department has a meter you can borrow. You'd need a sound level of readings from at least five locations in each area to make the results reliable." },
          { speaker: 'B', voice: 'david', text: "Five is fine. Should I also ask people how they feel about the noise?" },
          { speaker: 'A', voice: 'david2', text: "That would add an interesting dimension, because people's perceptions don't always match the measurements. A short questionnaire of no more than ten questions would be enough. But you'd need ethical approval first." },
          { speaker: 'B', voice: 'david', text: "How long does that take?" },
          { speaker: 'A', voice: 'david2', text: "About three weeks, so submit the form as soon as possible. Do you have a provisional timetable?" },
          { speaker: 'B', voice: 'david', text: "I thought I'd do the fieldwork in February, and analyse the data in March, and write up in April." },
          { speaker: 'A', voice: 'david2', text: "That seems tight, given that the dissertation is due at the end of April. I'd suggest starting the fieldwork in January, and writing your introduction and method sections while you wait for the results." },
          { speaker: 'B', voice: 'david', text: "That makes sense. And for the literature review, should I include studies from other countries?" },
          { speaker: 'A', voice: 'david2', text: "Yes, but concentrate on those from cities similar to yours. A study from a tiny village on the other side of the world won't tell you much." },
          { speaker: 'B', voice: 'david', text: "Right. I'll redraft my proposal and send it to you by the end of the week." },
          { speaker: 'A', voice: 'david2', text: "Good. And remember, it doesn't need to be perfect. A small, well-designed study is better than an ambitious one that you can't finish." },
        ],
        questionGroups: [
          {
            id: 't12-l3-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(21, 'What is Isaac\'s main difficulty?', ['narrowing down his research question', 'finding enough books', 'understanding the theory'], 'A', '"I\'m finding it hard to narrow down my research question".'),
              mc(22, 'Why has Isaac given up his original idea?', ['It needs medical equipment.', 'It has been done before.', 'It is too expensive.'], 'A', '"that would need medical equipment which I don\'t have access to".'),
              mc(23, 'How many locations will he measure in each area?', ['at least three', 'at least five', 'at least ten'], 'B', '"at least five locations in each area".'),
              mc(24, 'The supervisor warns that Isaac will need', ['a bigger budget', 'ethical approval', 'a research assistant'], 'B', '"you\'d need ethical approval first".'),
              mc(25, 'What does the supervisor say about Isaac\'s timetable?', ['It is too tight.', 'It is perfect.', 'It is too relaxed.'], 'A', '"That seems tight".'),
            ],
          },
          {
            id: 't12-l3-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS</strong> for each answer.',
            wordLimit: { maxWords: 2, label: 'NO MORE THAN TWO WORDS' },
            stemHtml: '<p><strong>Dissertation plan</strong></p><p>• compare a shopping street, a park and a {{q26}} area<br/>• borrow a {{q27}} from the department<br/>• short {{q28}} of no more than ten questions<br/>• start fieldwork in {{q29}}<br/>• literature review: focus on studies from {{q30}} similar to his own</p>',
            questions: [
              q(26, null, ['residential'], '"a busy shopping street, a park and a residential area".'),
              q(27, null, ['sound meter', 'meter'], '"the department has a meter you can borrow".'),
              q(28, null, ['questionnaire'], '"A short questionnaire of no more than ten questions".'),
              q(29, null, ['january'], '"starting the fieldwork in January".'),
              q(30, null, ['cities'], '"those from cities similar to yours".'),
            ],
          },
        ],
      },
      {
        order: 4,
        contextText: 'You will hear part of a lecture about the science of sourdough bread.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Sourdough is the oldest form of leavened bread, and in recent years it has become very fashionable. Today I'll look at the science behind it, and in particular at the microorganisms that make it work." },
          { speaker: 'A', voice: 'zira', text: "A sourdough starter is simply a mixture of flour and water that has been left for several days so that wild microorganisms from the flour and the air can grow. It contains two main groups: wild yeasts, and bacteria known as lactic acid bacteria." },
          { speaker: 'A', voice: 'zira', text: "The yeasts do the same job as those in commercial bread: they feed on sugars in the flour and produce carbon dioxide gas, which makes the dough rise. But wild yeasts work much more slowly, which is why sourdough takes many hours to rise, rather than one or two." },
          { speaker: 'A', voice: 'zira', text: "The bacteria produce lactic and acetic acids. These give the bread its distinctive sour taste. They also make the dough more acidic, which affects the texture and helps to stop other microorganisms from growing. The acidity is the reason why sourdough stays fresh for longer than ordinary bread, and is less likely to go mouldy." },
          { speaker: 'A', voice: 'zira', text: "Interestingly, yeasts and bacteria live in harmony. The bacteria break down complex sugars that the yeasts cannot use, and the yeasts tolerate the acidity. Researchers have found that starters from different parts of the world contain different species, but every starter has a stable community that persists for years, provided it's fed regularly." },
          { speaker: 'A', voice: 'zira', text: "Some starters have been kept alive for well over a hundred years, and are passed from one baker to the next. A bakery in San Francisco is famous for a starter said to date back to the middle of the nineteenth century." },
          { speaker: 'A', voice: 'zira', text: "There have also been claims about health. Some studies suggest that the long fermentation breaks down substances in the flour that can interfere with the absorption of minerals, and that sourdough may cause a smaller rise in blood sugar than ordinary bread. The evidence is limited, however, and sourdough is not suitable for people with coeliac disease, because it still contains gluten." },
          { speaker: 'A', voice: 'zira', text: "Finally, a practical point. Bakers say that the flavour depends on the temperature. A warm kitchen favours the yeasts and produces a milder loaf, while a cool one favours the bacteria and produces a more sour taste. So if you want to experiment, try making the same recipe at different temperatures." },
        ],
        questionGroups: [
          {
            id: 't12-l4-table',
            type: 'table_completion',
            instructionHtml: 'Complete the table below. Write <strong>NO MORE THAN TWO WORDS</strong> for each answer.',
            wordLimit: { maxWords: 2, label: 'NO MORE THAN TWO WORDS' },
            stemHtml: table(
              ['Topic', 'Notes'],
              [
                ['Starter', 'mixture of flour and {{q31}}, left for several days'],
                ['Main groups of microorganisms', 'wild yeasts and {{q32}} bacteria'],
                ['Role of yeasts', 'produce {{q33}} gas, which makes the dough rise'],
                ['Speed', 'wild yeasts work slowly, so the dough takes many {{q34}} to rise'],
                ['Role of bacteria', 'produce lactic and {{q35}} acids, giving a sour taste'],
                ['Effect of acidity', 'sourdough stays {{q36}} for longer and is less likely to go mouldy'],
                ['Relationship', 'bacteria break down complex {{q37}} that yeasts cannot use'],
                ['Age of starters', 'some kept alive for over a {{q38}} years'],
                ['Health', 'unsuitable for people with {{q39}} disease because it contains gluten'],
                ['Flavour', 'a {{q40}} kitchen produces a more sour taste'],
              ]
            ),
            questions: [
              q(31, null, ['water'], '"a mixture of flour and water".'),
              q(32, null, ['lactic acid'], '"lactic acid bacteria".'),
              q(33, null, ['carbon dioxide'], '"produce carbon dioxide gas".'),
              q(34, null, ['hours'], '"many hours to rise".'),
              q(35, null, ['acetic'], '"lactic and acetic acids".'),
              q(36, null, ['fresh'], '"stays fresh for longer".'),
              q(37, null, ['sugars'], '"break down complex sugars".'),
              q(38, null, ['hundred', '100'], '"well over a hundred years".'),
              q(39, null, ['coeliac', 'celiac'], '"not suitable for people with coeliac disease".'),
              q(40, null, ['cool', 'cooler'], '"a cool one favours the bacteria and produces a more sour taste".'),
            ],
          },
        ],
      },
    ],
  },

  writing: {
    durationSec: 3600,
    task1: {
      order: 1,
      minWords: 150,
      recommendedMin: 20,
      promptHtml:
        '<p>The pie chart below shows the main reasons why people visited a national museum in 2023.</p><p>Summarise the information by selecting and reporting the main features, and make comparisons where relevant.</p>',
      chart: {
        chartType: 'pie',
        title: 'Main reason for visiting a national museum, 2023 (%)',
        unit: '%',
        categories: ['Special exhibition', 'Family outing', 'School trip', 'Research', 'Tourism', 'Other'],
        series: [{ name: 'Share of visitors', data: [29, 24, 17, 6, 18, 6] }],
      },
    },
    task2: {
      order: 2,
      minWords: 250,
      recommendedMin: 40,
      promptHtml:
        '<p>Some people think that cash will soon disappear and that everyone will pay digitally.</p><p>Do you think this would be a positive or negative development?</p>',
    },
  },
};
