// Original IELTS-style practice content (NOT copied or paraphrased from any real
// Cambridge/IELTS book). Only the exam STRUCTURE follows a standard Academic test
// layout; every topic, passage, transcript, question and answer is written from scratch.
import { table, TFNG_INSTRUCTION, YNNG_INSTRUCTION, q, paras, mc, bank } from './_html.mjs';

export default {
  slug: 'vocably-practice-test-19',
  title: 'Vocably Practice Test 19',
  difficulty: 'medium',

  reading: {
    durationSec: 3600,
    passages: [
      {
        order: 1,
        title: 'What really happened to the Great Library?',
        subtitle: 'Read the text and answer questions 1-13.',
        paragraphs: paras(
          ['A', `Around 290 BC, in the Egyptian port of Alexandria, a Greek ruler set out to create the most ambitious library the world had ever seen. The aim was to collect the writings of every known people in a single place, and to employ scholars to study them. The king provided housing, food and a salary to researchers who were invited from all over the Mediterranean, and the institution that housed them, known as the Museum, became the first great centre of organised scholarship. Its members included the mathematician Euclid, whose geometry is still taught today, and Eratosthenes, who calculated the circumference of the Earth with remarkable accuracy by comparing the lengths of shadows in two Egyptian towns.`],
          ['B', `The library's founders were determined to build the collection quickly, and they were not always scrupulous about how. According to a later writer, ships arriving in the harbour were searched for books, which were seized and taken to the library, where they were copied. The copies, rather than the originals, were then returned to the owners. Kings also wrote to other rulers asking to borrow precious manuscripts, and on at least one occasion, a large sum paid as a guarantee was forfeited because the borrower preferred to keep the originals. Nobody knows how many scrolls the library held. Ancient sources give figures ranging from forty thousand to seven hundred thousand, and modern scholars think that the true number was probably in the tens of thousands.`],
          ['C', `Popular accounts often blame a single catastrophic fire for the loss of the library, and several culprits have been proposed. One story says that when Julius Caesar's troops were besieged in Alexandria in 48 BC, he ordered his ships in the harbour to be set on fire and that the flames spread to the library. Another, told by later writers, says that when Arab armies captured the city in the seventh century, their commander ordered the books to be burnt as heating for the public baths. Historians have cast doubt on both. The fire of 48 BC seems to have destroyed warehouses near the docks, in which scrolls were stored, but not the main library, and the story about the Arab commander was first told nearly six centuries after the event, and appears to have no foundation.`],
          ['D', `The evidence suggests that the library did not disappear in a single day but declined slowly over several centuries. Its fortunes depended on the support of the rulers, and when the later kings of the dynasty grew weak and quarrelsome, the money dried up. In 145 BC, a king who had taken the throne after a violent struggle expelled many of the foreign scholars, who scattered to other cities, and the Museum never fully recovered. When Egypt came under Roman control, the emperors in distant Rome showed little interest in the library, and its funding was reduced. There was also a practical problem: scrolls written on papyrus decay in damp air, and each one had to be copied every few decades if it was to survive. When the money to pay the copyists ran out, the contents quietly rotted away.`],
          ['E', `The library's real legacy lies in the work done there. Scholars collected and compared different versions of the great poems of Homer, and produced the editions on which later texts were based. A poet named Callimachus compiled the first known catalogue, which listed the works by author and subject and ran to 120 scrolls, an invention that still underlies the way libraries are organised. Another scholar, Aristarchus of Samos, proposed that the Earth moves around the Sun, nearly two thousand years before Copernicus, although few took the idea seriously. Whatever the fate of the building, the methods of scholarship developed in Alexandria shaped the way knowledge was collected and classified for centuries.`],
          ['F', `In 2002, a new library opened on the waterfront of modern Alexandria, close to the site of the ancient one. Designed as a huge circular building, tilted like a rising sun, with walls carved with letters from many alphabets, it houses millions of books, along with museums, a planetarium and a centre for the study of manuscripts. It is a fitting memorial, although its founders insist that it is more than that: an attempt to restore to Alexandria something of its ancient role as a meeting place for the world's scholars.`]
        ),
        questionGroups: [
          {
            id: 't19-r1-matchinfo',
            type: 'matching_information',
            instructionHtml: 'Reading Passage 1 has six paragraphs, A-F. Which paragraph contains the following information? <em>Choose the correct letter, A-F.</em>',
            questions: [
              q(1, 'a reference to a scholar who calculated the size of the Earth', 'A', 'Paragraph A: Eratosthenes "calculated the circumference of the Earth".', 'A'),
              q(2, 'a description of how books were obtained from visitors', 'B', 'Paragraph B: ships "were searched for books".', 'B'),
              q(3, 'an example of a story that historians have rejected', 'C', 'Paragraph C: the story about the Arab commander "appears to have no foundation".', 'C'),
              q(4, 'an explanation of how political changes affected the library\'s funding', 'D', 'Paragraph D: when Egypt came under Roman control, "its funding was reduced".', 'D'),
              q(5, 'mention of the first library catalogue', 'E', 'Paragraph E: "the first known catalogue".', 'E'),
              q(6, 'a reference to a modern library near the ancient site', 'F', 'Paragraph F: "In 2002, a new library opened".', 'F'),
            ],
          },
          {
            id: 't19-r1-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              q(7, 'The library was founded around 290 BC.', 'TRUE', 'Paragraph A: "Around 290 BC".', 'A'),
              q(8, 'Eratosthenes was one of the scholars who worked at the Museum.', 'TRUE', 'Paragraph A: "Its members included ... Eratosthenes".', 'A'),
              q(9, 'The original books taken from ships were returned to their owners.', 'FALSE', 'Paragraph B: "The copies, rather than the originals, were then returned".', 'B'),
              q(10, 'The library held exactly four hundred thousand scrolls.', 'FALSE', 'Paragraph B: "Nobody knows how many scrolls the library held."', 'B'),
              q(11, 'Caesar\'s fire of 48 BC destroyed the whole of the library.', 'FALSE', 'Paragraph C: it "seems to have destroyed warehouses near the docks ... but not the main library".', 'C'),
              q(12, 'Many scholars were expelled from Alexandria in 145 BC.', 'TRUE', 'Paragraph D: "In 145 BC, a king ... expelled many of the foreign scholars".', 'D'),
              q(13, 'The modern library holds more books than the ancient one.', 'NOT GIVEN', 'Paragraph F says it houses millions of books, but the ancient total is not known.', 'F'),
            ],
          },
        ],
      },
      {
        order: 2,
        title: 'Flowers on a plane',
        subtitle: 'Read the text and answer questions 14-26.',
        paragraphs: paras(
          ['A', `Every February, in the days before Valentine's Day, tens of millions of roses are cut on farms near the equator and flown to shops in Europe and North America. Kenya is one of the most important suppliers. Its cut-flower exports earn the country around a billion dollars a year, making it, along with tea and tourism, one of its biggest sources of foreign currency, and the industry directly employs around a hundred thousand people, most of them in a few districts around a single lake. The flower trade is a striking example of how a perishable luxury good can be produced in one continent and sold in another, and it raises questions about who benefits from it.`],
          ['B', `Why Kenya? The answer is partly a matter of geography. The farms are concentrated around Lake Naivasha, in the highlands at an altitude of about two thousand metres. Because the lake lies on the equator, the days are sunny and of equal length all year, which is ideal for growing flowers, while the altitude keeps the nights cool, so that the plants grow slowly and develop large, long-stemmed blooms. The flowers are cut in the morning, graded, packed and placed in cold stores within hours, and then trucked to the airport, from where they are flown to Europe overnight. The whole journey, which is kept cold from the farm to the shop by an arrangement known as the cold chain, takes less than forty-eight hours.`],
          ['C', `The people who work in the industry are mostly women, many of whom have come from rural areas in search of a regular income. Wages are modest, and the work, which involves long hours of standing and exposure to chemicals, is demanding, but workers often say that it is a better option than the alternatives, such as subsistence farming, and the money allows them to send children to school. Conditions vary greatly from farm to farm. Some farms provide housing, nurseries and medical care, while others have been accused of long working hours and failure to protect employees from pesticides. Independent certification schemes, which inspect farms and give a label to those that meet standards, have improved conditions on many, but not all.`],
          ['D', `The environmental questions are less simple than they appear. The industry draws large amounts of water from the lake, and its level has fallen several times in drought years, which has been blamed partly on the farms. Chemicals from the farms have run into the water, harming fish and wildlife. On the other hand, a study in 2007 that compared roses grown in Kenya with those grown in heated greenhouses in the Netherlands found that the Kenyan flowers produced much less carbon dioxide per stem, even after the flight to Europe was taken into account, because the Dutch growers burn large quantities of gas to keep their greenhouses warm. The finding surprised many people and led to a long debate about how to measure the environmental cost of goods that travel long distances.`],
          ['E', `The industry has responded to criticism. Many farms have replaced sprays and sprinklers with drip irrigation, which delivers water directly to the roots of the plants and uses far less of it. Others recycle their water, treat waste, and have planted trees around the lake to reduce erosion. A number of farms now generate part of their electricity from solar panels, and some have replaced chemical pesticides with insects that prey on the pests. The changes are driven not only by regulation but also by the demands of supermarkets in Europe, which require growers to show that they meet ethical and environmental standards.`],
          ['F', `The industry's future is uncertain. Kenya faces growing competition from Ethiopia, which has built its own flower farms with government support and which is closer to Europe. Climate change threatens to disrupt the pattern of rainfall and temperature on which the farms depend. The pandemic of 2020, when airlines grounded their aircraft and shops closed, showed how fragile the trade can be: tonnes of unsold flowers were thrown away, and thousands of workers lost their jobs. Growers are now trying to reduce their dependence on a few distant markets by selling more flowers within Africa and by diversifying into other crops, but for the time being, the health of the industry depends on the wishes of shoppers thousands of kilometres away.`]
        ),
        questionGroups: [
          {
            id: 't19-r2-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B, C or D</strong>.',
            questions: [
              mc(14, 'What does paragraph A say about cut flowers?', ['They are mostly sold in Africa.', 'They are a major source of income and jobs for Kenya.', 'They are grown in many different regions of Kenya.', 'They are more valuable than tea.'], 'B', 'Paragraph A: "around a billion dollars a year" and "employs around a hundred thousand people".', 'A'),
              mc(15, 'Why are the farms concentrated around Lake Naivasha?', ['Labour is cheap there.', 'The days are sunny all year and the nights are cool.', 'It is close to Europe.', 'The soil is unusually rich.'], 'B', 'Paragraph B: "sunny ... all year" and "the altitude keeps the nights cool".', 'B'),
              mc(16, 'The "cold chain" is', ['a chain of farms', 'an arrangement that keeps flowers cold from farm to shop', 'a type of aircraft', 'a method of packing'], 'B', 'Paragraph B: "kept cold from the farm to the shop by an arrangement known as the cold chain".', 'B'),
              mc(17, 'What does paragraph C suggest about flower workers?', ['They earn high wages.', 'They are mostly men.', 'They often regard the work as better than the alternatives.', 'They are protected on all farms.'], 'C', 'Paragraph C: "workers often say that it is a better option than the alternatives".', 'C'),
              mc(18, 'The 2007 study found that Kenyan roses', ['had a larger carbon footprint than Dutch ones', 'produced much less carbon dioxide per stem than roses from heated Dutch greenhouses', 'used no water', 'were cheaper than Dutch roses'], 'B', 'Paragraph D: "much less carbon dioxide per stem".', 'D'),
            ],
          },
          {
            id: 't19-r2-sentences',
            type: 'sentence_completion',
            instructionHtml: 'Complete the sentences below. Choose <strong>ONE WORD ONLY</strong> from the passage for each answer.',
            wordLimit: { maxWords: 1, label: 'ONE WORD ONLY' },
            questions: [
              q(19, 'The flowers are cut in the {{q19}}.', ['morning'], 'Paragraph B: "cut in the morning".', 'B'),
              q(20, 'They are flown to Europe {{q20}}.', ['overnight'], 'Paragraph B: "flown to Europe overnight".', 'B'),
              q(21, 'Many farms have installed {{q21}} irrigation to use less water.', ['drip'], 'Paragraph E: "drip irrigation".', 'E'),
              q(22, 'Some farms generate part of their electricity from {{q22}} panels.', ['solar'], 'Paragraph E: "solar panels".', 'E'),
            ],
          },
          {
            id: 't19-r2-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              q(23, 'Kenya is the largest exporter of cut flowers in the world.', 'NOT GIVEN', 'Paragraph A says Kenya is "one of the most important suppliers", not the largest.', 'A'),
              q(24, 'Most of the people who work on the flower farms are women.', 'TRUE', 'Paragraph C: "mostly women".', 'C'),
              q(25, 'All of the farms have stopped using chemical pesticides.', 'FALSE', 'Paragraph E: "some have replaced chemical pesticides".', 'E'),
              q(26, 'Ethiopia has set up flower farms that compete with Kenya\'s.', 'TRUE', 'Paragraph F: "Ethiopia, which has built its own flower farms".', 'F'),
            ],
          },
        ],
      },
      {
        order: 3,
        title: 'Giving time: the benefits of volunteering',
        subtitle: 'Read the text and answer questions 27-40.',
        paragraphs: paras(
          ['A', `Millions of people around the world give their time without payment: they coach children's football teams, deliver meals to elderly neighbours, clear rubbish from beaches, answer telephones on help lines and staff charity shops. In many countries, volunteers provide services that would cost governments billions to replace. It has long been assumed that volunteering benefits the people who receive help, but a growing body of research suggests that it also benefits the people who give it, and that the effects may be considerable. The findings have interested doctors and policy-makers, and they raise some intriguing questions about why helping others should be good for us.`],
          ['B', `The evidence on health is perhaps the most striking. In a number of large studies, which followed thousands of people over many years, those who volunteered were less likely to die during the period than those who did not, even after the researchers took account of differences in age, health, income and lifestyle. Volunteers have also been found to have lower rates of depression, particularly in later life, and some studies suggest that they are less likely to suffer from heart disease. The effects are not enormous, and research of this kind cannot prove cause and effect, since healthy and sociable people may be more likely to volunteer in the first place, but the results have been reproduced often enough to be taken seriously.`],
          ['C', `How might volunteering improve health? Researchers have suggested several explanations. One is that it provides a sense of purpose, which is associated with lower stress and a greater feeling of wellbeing, particularly for people who have retired or lost a partner and who might otherwise feel that they have no role. A second is that it creates social ties: volunteers meet new people, build friendships and are less likely to be lonely, which is a recognised risk to health. A third is physical activity, since many voluntary tasks involve walking, lifting or gardening. There is also evidence, from brain scans and from the reports of volunteers themselves, of a feeling of pleasure after helping, which some call the helper's high.`],
          ['D', `However, volunteering is not a cure-all, and the benefits depend on the circumstances. Studies indicate that people gain most when they choose to volunteer freely and for reasons that matter to them. Those who are pressured, or whose participation is compulsory, such as students obliged to complete hours of community service, seem to gain much less, and may come to resent the work. Volunteers who take on too many tasks can become exhausted, and those whose efforts are not valued may feel discouraged and leave. Organisations that give their volunteers training, clear roles and recognition are therefore more likely to keep them, and to produce benefits for everyone concerned.`],
          ['E', `The advantages differ between groups. Older adults, who face the greatest risk of isolation, seem to benefit the most, and some health services have begun to encourage their patients to take up volunteering as part of their recovery. For young people, the gains are of a different kind: volunteering provides experience, skills and contacts, and employers often regard it as evidence of initiative and reliability. In a number of countries, unemployed people are encouraged to volunteer as a way of keeping in touch with working life, although critics warn that it should never be used as a substitute for paid work.`],
          ['F', `The pattern of volunteering is also changing. The traditional volunteer, who gave a few hours every week to one organisation for many years, is becoming rarer. Increasingly, people prefer to help for short periods, on a single project or at a single event, and to do so in ways that fit their other commitments. Some organisations have adapted by breaking up tasks into short, flexible assignments, and by using websites to match volunteers with opportunities. Others have found it hard to cope with the change, since they depend on the regular commitment of a core of reliable helpers and cannot easily plan for a constantly changing group.`],
          ['G', `What conclusions should we draw? In my view, the research gives society a reason to make volunteering easier and more attractive, for example by providing time off work and by reducing the bureaucracy that discourages would-be helpers. It would be a mistake, however, to treat it as a cheap alternative to public services, or to force people into it. If volunteering were a medicine, it would be one with few side effects and many advantages; but like any medicine, it works best when it is taken willingly, and in the right dose.`]
        ),
        questionGroups: [
          {
            id: 't19-r3-headings',
            type: 'matching_headings',
            instructionHtml: 'Reading Passage 3 has seven paragraphs, A-G. Choose the correct heading for paragraphs B-G from the list of headings below.<br/><em>Example: Paragraph A — viii</em>',
            bank: [
              { key: 'i', text: 'Different benefits for different age groups' },
              { key: 'ii', text: 'Evidence of effects on health' },
              { key: 'iii', text: 'A call for practical support, with a warning' },
              { key: 'iv', text: 'Why helping others may be good for the helper' },
              { key: 'v', text: 'Conditions under which the benefits are greatest' },
              { key: 'vi', text: 'The history of charities' },
              { key: 'vii', text: 'Changing habits among volunteers' },
              { key: 'viii', text: 'A growing interest in an old practice' },
              { key: 'ix', text: 'The cost of training volunteers' },
            ],
            questions: [
              q(27, 'Paragraph B', 'ii', 'Paragraph B: volunteers less likely to die, less depression.', 'B'),
              q(28, 'Paragraph C', 'iv', 'Paragraph C: possible explanations such as purpose, social ties and activity.', 'C'),
              q(29, 'Paragraph D', 'v', 'Paragraph D: people gain most when they choose to volunteer freely.', 'D'),
              q(30, 'Paragraph E', 'i', 'Paragraph E: older adults and young people benefit in different ways.', 'E'),
              q(31, 'Paragraph F', 'vii', 'Paragraph F: people prefer short, flexible assignments.', 'F'),
              q(32, 'Paragraph G', 'iii', 'Paragraph G: make volunteering easier, but "a mistake ... to force people into it".', 'G'),
            ],
          },
          {
            id: 't19-r3-ynng',
            type: 'yes_no_notgiven',
            instructionHtml: YNNG_INSTRUCTION,
            questions: [
              q(33, 'People who volunteer may live longer than those who do not.', 'YES', 'Paragraph B: volunteers "were less likely to die during the period".', 'B'),
              q(34, 'Volunteering is more beneficial to health than regular exercise.', 'NOT GIVEN', 'The two are not compared.', 'C'),
              q(35, 'Compulsory volunteering schemes are as effective as voluntary ones.', 'NO', 'Paragraph D: those whose participation is compulsory "seem to gain much less".', 'D'),
              q(36, 'Governments should pay volunteers for their work.', 'NOT GIVEN', 'Payment is not discussed.', 'G'),
            ],
          },
          {
            id: 't19-r3-summary',
            type: 'summary_completion',
            instructionHtml: 'Complete the summary of paragraph D below. Choose <strong>ONE WORD ONLY</strong> from the passage for each answer.',
            wordLimit: { maxWords: 1, label: 'ONE WORD ONLY' },
            stemHtml: '<p>People gain most from volunteering when they choose to do so {{q37}}. Those whose participation is {{q38}} seem to gain much less. Volunteers who take on too many tasks can become {{q39}}, and those whose efforts are not valued may feel {{q40}}.</p>',
            questions: [
              q(37, null, ['freely'], 'Paragraph D: "choose to volunteer freely".', 'D'),
              q(38, null, ['compulsory'], 'Paragraph D: "compulsory".', 'D'),
              q(39, null, ['exhausted'], 'Paragraph D: "can become exhausted".', 'D'),
              q(40, null, ['discouraged'], 'Paragraph D: "may feel discouraged".', 'D'),
            ],
          },
        ],
      },
    ],
  },

  listening: {
    durationSec: 1800,
    checkTimeSec: 120,
    parts: [
      {
        order: 1,
        contextText: 'You will hear a woman phoning a leisure centre to enquire about a yoga course.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Westgate Leisure Centre, how can I help?" },
          { speaker: 'B', voice: 'zira', text: "Hello. I'm interested in joining a yoga course, and I saw your advertisement in the library." },
          { speaker: 'A', voice: 'david', text: "Certainly. Have you done yoga before?" },
          { speaker: 'B', voice: 'zira', text: "No, I'm a complete beginner. I have a bad back, and my doctor suggested yoga might help." },
          { speaker: 'A', voice: 'david', text: "Then I'd recommend our gentle yoga course. It runs for eight weeks, and it's designed for people with back problems. The instructor is Ms Kapoor, who is a qualified physiotherapist." },
          { speaker: 'B', voice: 'zira', text: "That sounds ideal. When does it take place?" },
          { speaker: 'A', voice: 'david', text: "On Thursday evenings, from half past six until half past seven, in the studio on the first floor. The next course starts on the fifth of February." },
          { speaker: 'B', voice: 'zira', text: "And how much does it cost?" },
          { speaker: 'A', voice: 'david', text: "It's ninety-six pounds for the eight weeks, which is twelve pounds a session. If you're a member of the leisure centre, there's a discount of twenty-five per cent." },
          { speaker: 'B', voice: 'zira', text: "I'm not a member. Is it worth joining?" },
          { speaker: 'A', voice: 'david', text: "Membership is thirty pounds a month, and it includes the swimming pool and gym. It's worth it if you'll use them." },
          { speaker: 'B', voice: 'zira', text: "I'll think about it. Do I need to bring anything?" },
          { speaker: 'A', voice: 'david', text: "A yoga mat, which you can buy here for fifteen pounds or borrow for free. Wear loose, comfortable clothes, and please don't eat a large meal within two hours before the class." },
          { speaker: 'B', voice: 'zira', text: "Is there a limit on numbers?" },
          { speaker: 'A', voice: 'david', text: "Yes, there are twelve places, and at the moment, four are still available, so I'd advise booking quickly." },
          { speaker: 'B', voice: 'zira', text: "I'd like to book one, please." },
          { speaker: 'A', voice: 'david', text: "Of course. Your name?" },
          { speaker: 'B', voice: 'zira', text: "Sandra Whitehouse. W-H-I-T-E-H-O-U-S-E." },
          { speaker: 'A', voice: 'david', text: "And a contact number?" },
          { speaker: 'B', voice: 'zira', text: "It's oh-seven-seven-oh-oh, nine-oh-oh, two-one-four." },
        ],
        questionGroups: [
          {
            id: 't19-l1-form',
            type: 'form_completion',
            instructionHtml: 'Complete the form below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Westgate Leisure Centre: Course booking', ''],
              [
                ['Heard about the course in the', '{{q1}}'],
                ['Reason for joining', 'bad {{q2}}'],
                ['Course', '{{q3}} yoga'],
                ['Length', '{{q4}} weeks'],
                ['Instructor', 'Ms {{q5}}'],
                ['Day and time', 'Thursday, from {{q6}} p.m. to 7.30 p.m.'],
                ['Start date', '{{q7}} February'],
                ['Cost', '£{{q8}}'],
                ['Yoga mat', 'can be bought for £{{q9}}'],
                ['Surname', '{{q10}}'],
              ]
            ),
            questions: [
              q(1, null, ['library'], '"your advertisement in the library".'),
              q(2, null, ['back'], '"I have a bad back".'),
              q(3, null, ['gentle'], '"our gentle yoga course".'),
              q(4, null, ['8', 'eight'], '"It runs for eight weeks".'),
              q(5, null, ['kapoor'], '"Ms Kapoor".'),
              q(6, null, ['6.30', '6:30', 'half past six', 'six thirty', '18:30'], '"from half past six".'),
              q(7, null, ['5', 'fifth', '5th'], '"the fifth of February".'),
              q(8, null, ['96', 'ninety-six', 'ninety six'], '"ninety-six pounds".'),
              q(9, null, ['15', 'fifteen'], '"buy here for fifteen pounds".'),
              q(10, null, ['whitehouse'], 'Spelled out: W-H-I-T-E-H-O-U-S-E.'),
            ],
          },
        ],
      },
      {
        order: 2,
        contextText: 'You will hear a radio presenter talking about a forthcoming food festival in a town called Marlow.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Now, if you enjoy food, here's something to put in your diary. The Marlow Food Festival returns next month, and it promises to be bigger than ever. I've been talking to the organiser, Anita Shah." },
          { speaker: 'A', voice: 'david', text: "The festival takes place over the first weekend of September, on the town's riverside meadow. It began eleven years ago as a small market with just twelve stalls, and this year, there will be over a hundred." },
          { speaker: 'A', voice: 'david', text: "Admission is free, although there's a charge of four pounds for the cookery demonstrations, which take place in a large tent. The demonstrations are given by well-known chefs, who will cook dishes from the region, and they are very popular, so it's wise to book in advance." },
          { speaker: 'A', voice: 'david', text: "New this year is a competition for amateur cooks, which will take place on Sunday afternoon. Each competitor has one hour to prepare a main course from a box of local ingredients, and a panel of judges will award a prize of two hundred pounds. Entry is ten pounds, and applications must be made by the twentieth of August." },
          { speaker: 'A', voice: 'david', text: "There will also be a children's area, where youngsters can make their own pizza, which costs two pounds, and plant herbs to take home. A craft beer marquee will be open throughout the weekend, and a stage will host music by local bands." },
          { speaker: 'A', voice: 'david', text: "Anita told me that about thirty per cent of the stallholders come from within twenty miles of the town, and she's particularly proud of this. The organisers insist that all the food must be produced locally, or be made with locally grown ingredients, to support nearby farmers." },
          { speaker: 'A', voice: 'david', text: "Environmental concerns have shaped the festival. All the plates and cutlery are compostable, and visitors are encouraged to bring their own water bottles, which can be filled at free points around the site. There are no plastic bags." },
          { speaker: 'A', voice: 'david', text: "If you're travelling to the festival, avoid driving if you can, because parking in the town is very limited. A free shuttle bus will run every fifteen minutes from the railway station, and there will be secure bicycle parking near the entrance." },
          { speaker: 'A', voice: 'david', text: "The festival is open from ten in the morning until six in the evening on both days. For more information, visit the festival website, or follow it on social media. And now, let's have some music." },
        ],
        questionGroups: [
          {
            id: 't19-l2-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(11, 'How many stalls were there at the first festival?', ['12', '50', '100'], 'A', '"just twelve stalls".'),
              mc(12, 'Admission to the festival is', ['free', '£4', '£10'], 'A', '"Admission is free".'),
              mc(13, 'Why should people book for the cookery demonstrations?', ['They are very popular.', 'Places are very expensive.', 'They are held indoors.'], 'A', '"they are very popular, so it\'s wise to book in advance".'),
              mc(14, 'The cooking competition will take place on', ['Saturday morning', 'Sunday afternoon', 'Friday evening'], 'B', '"on Sunday afternoon".'),
              mc(15, 'The organiser is proud that about thirty per cent of the stallholders', ['sell craft beer', 'come from within twenty miles', 'are under 25'], 'B', '"come from within twenty miles of the town".'),
            ],
          },
          {
            id: 't19-l2-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Marlow Food Festival</strong></p><p>• held on the riverside {{q16}}<br/>• competition: prize £{{q17}}; entry £10; apply by {{q18}} August<br/>• children can make {{q19}} and plant herbs<br/>• plates and cutlery are {{q20}}</p>',
            questions: [
              q(16, null, ['meadow'], '"the town\'s riverside meadow".'),
              q(17, null, ['200', 'two hundred'], '"a prize of two hundred pounds".'),
              q(18, null, ['20th', 'twentieth', '20'], '"by the twentieth of August".'),
              q(19, null, ['pizza', 'their own pizza'], '"make their own pizza".'),
              q(20, null, ['compostable'], '"All the plates and cutlery are compostable".'),
            ],
          },
        ],
      },
      {
        order: 3,
        contextText: 'You will hear two nursing students, Gabi and Ahmed, discussing their hospital placements with a tutor.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david2', text: "Welcome back, Gabi, Ahmed. You've both finished your first placement. How did it go?" },
          { speaker: 'B', voice: 'zira', text: "I enjoyed it, although it was more tiring than I expected. I was on a surgical ward, and we often had to start at seven in the morning." },
          { speaker: 'C', voice: 'david', text: "I was in a children's ward. What surprised me most was how much time we spent on talking to parents. They were often more anxious than the children." },
          { speaker: 'A', voice: 'david2', text: "That's a useful observation. Was there anything you found difficult?" },
          { speaker: 'B', voice: 'zira', text: "The paperwork. Every action has to be recorded, and I was slow at first. My supervisor said that accuracy matters more than speed, but I still felt under pressure." },
          { speaker: 'C', voice: 'david', text: "For me, it was handling medicines. I was terrified of making a mistake, so I checked everything twice, which took a long time." },
          { speaker: 'A', voice: 'david2', text: "Double-checking is exactly right. It's a sign of a careful professional. You'll get faster with practice." },
          { speaker: 'B', voice: 'zira', text: "What are we supposed to write in the reflective report?" },
          { speaker: 'A', voice: 'david2', text: "Choose one incident from your placement and analyse it: what happened, what you did, how you felt, and what you would do differently. It should be about fifteen hundred words." },
          { speaker: 'C', voice: 'david', text: "Can we choose an incident where something went wrong?" },
          { speaker: 'A', voice: 'david2', text: "Yes, and I'd encourage it. Students often pick only successes, but you learn more from difficulties, provided you're honest. You must not include any patient's name or details that might identify them, because of confidentiality." },
          { speaker: 'B', voice: 'zira', text: "I'd like to write about a time when a patient refused treatment." },
          { speaker: 'A', voice: 'david2', text: "That's a rich topic, with ethical dimensions. Link it to a theory from your course, such as the principle of patient autonomy." },
          { speaker: 'C', voice: 'david', text: "I'll write about a frightened child who wouldn't let me take his temperature." },
          { speaker: 'A', voice: 'david2', text: "Good. Think about how communication skills, such as tone of voice and play, helped, or could have helped. The report is due on the ninth of June, and I'll be available for tutorials on Tuesdays." },
          { speaker: 'B', voice: 'zira', text: "Thank you. That's very helpful." },
        ],
        questionGroups: [
          {
            id: 't19-l3-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(21, 'Gabi says her placement was', ['more tiring than she expected', 'easier than she expected', 'boring'], 'A', '"more tiring than I expected".'),
              mc(22, 'What surprised Ahmed about the children\'s ward?', ['the amount of time spent talking to parents', 'the noise', 'the paperwork'], 'A', '"how much time we spent on talking to parents".'),
              mc(23, 'What did Gabi find difficult at first?', ['paperwork', 'medicines', 'night shifts'], 'A', '"The paperwork."'),
              mc(24, 'Ahmed checked everything twice because he was', ['slow', 'afraid of making mistakes', 'told to do so by patients'], 'B', '"I was terrified of making a mistake, so I checked everything twice".'),
              mc(25, 'The tutor encourages students to write about', ['only successful incidents', 'incidents where something went wrong', 'their favourite patient'], 'B', '"I\'d encourage it" (an incident where something went wrong).'),
            ],
          },
          {
            id: 't19-l3-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Reflective report</strong></p><p>• analyse one {{q26}} from the placement<br/>• length: about {{q27}} words<br/>• must not include patient names because of {{q28}}<br/>• link to a theory, such as patient {{q29}}<br/>• deadline: {{q30}} June</p>',
            questions: [
              q(26, null, ['incident'], '"Choose one incident from your placement".'),
              q(27, null, ['1500', '1,500', 'fifteen hundred'], '"about fifteen hundred words".'),
              q(28, null, ['confidentiality'], '"because of confidentiality".'),
              q(29, null, ['autonomy'], '"the principle of patient autonomy".'),
              q(30, null, ['9th', 'ninth', '9'], '"the ninth of June".'),
            ],
          },
        ],
      },
      {
        order: 4,
        contextText: 'You will hear part of a lecture about the history of vaccination.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Vaccination has saved more lives than almost any other medical advance. Today I want to trace its history, from its beginnings to the present." },
          { speaker: 'A', voice: 'zira', text: "Long before the science was understood, people had noticed that those who survived certain diseases were protected from catching them again. In China and India, there was a practice known as variolation, in which material from the sores of a person with mild smallpox was scratched into the skin of a healthy person, who then developed a mild case and was usually immune for life. It was risky, and about two or three people in a hundred died, but the risk was far smaller than that of natural smallpox." },
          { speaker: 'A', voice: 'zira', text: "The next step came in seventeen ninety-six, when an English country doctor, Edward Jenner, noticed that milkmaids who had caught cowpox, a mild disease of cattle, seemed never to get smallpox. He tested his idea by inoculating an eight-year-old boy with material from a milkmaid's cowpox sore, and then exposing him to smallpox. The boy did not become ill. The word vaccine comes from the Latin for cow." },
          { speaker: 'A', voice: 'zira', text: "Jenner's method spread quickly across Europe and beyond, and governments began to make vaccination compulsory. But it was not until the nineteenth century that Louis Pasteur put the approach on a scientific footing. He developed vaccines against chicken cholera and rabies by weakening the germs that cause them, and showed that the same principle could be used for many diseases." },
          { speaker: 'A', voice: 'zira', text: "In the twentieth century, vaccines were developed against diphtheria, tetanus, polio, measles and many others. The polio vaccine, introduced in the nineteen-fifties, was particularly dramatic. Before it, polio paralysed thousands of children every year, and parents lived in fear each summer. Within a few years, cases had fallen by ninety per cent." },
          { speaker: 'A', voice: 'zira', text: "The greatest triumph was the eradication of smallpox. A worldwide campaign, led by the World Health Organization, used a strategy in which teams identified every outbreak and vaccinated everyone around it. The last natural case occurred in nineteen seventy-seven, and in nineteen eighty, the disease was officially declared to have been eradicated. It remains the only human disease to have been eliminated in this way." },
          { speaker: 'A', voice: 'zira', text: "Not everything has gone smoothly. Some people distrust vaccines, in part because of a now-discredited study in the nineteen-nineties that falsely linked a vaccine to autism. Vaccination rates fell in some countries, and outbreaks of measles followed. Public health experts stress that the vast majority of side effects are mild, and that the risks of the diseases are far greater." },
          { speaker: 'A', voice: 'zira', text: "Today, new technology, such as messenger RNA, allows vaccines to be developed in months rather than years. The success of these methods against a recent pandemic has opened up prospects for vaccines against other diseases, including some cancers." },
        ],
        questionGroups: [
          {
            id: 't19-l4-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>History of vaccination</strong></p><p><em>Early methods</em><br/>• China and India: variolation, in which material from a {{q31}} sore was scratched into the skin<br/>• about two or three in a {{q32}} died</p><p><em>Jenner</em><br/>• in {{q33}}, noticed that milkmaids who had caught {{q34}} did not get smallpox<br/>• tested his idea on an {{q35}}-year-old boy</p><p><em>Pasteur</em><br/>• vaccines against chicken cholera and {{q36}}, made by weakening the germs</p><p><em>Twentieth century</em><br/>• polio vaccine introduced in the {{q37}}; cases fell by 90%<br/>• smallpox eradicated; last natural case in {{q38}}</p><p><em>Modern issues</em><br/>• a discredited study linked a vaccine to {{q39}}<br/>• new technology, messenger RNA, allows vaccines to be developed in {{q40}}</p>',
            questions: [
              q(31, null, ['smallpox'], '"from the sores of a person with mild smallpox".'),
              q(32, null, ['hundred', '100'], '"two or three people in a hundred died".'),
              q(33, null, ['1796'], '"in seventeen ninety-six".'),
              q(34, null, ['cowpox'], '"had caught cowpox".'),
              q(35, null, ['8', 'eight'], '"an eight-year-old boy".'),
              q(36, null, ['rabies'], '"chicken cholera and rabies".'),
              q(37, null, ['1950s', 'nineteen-fifties', 'nineteen fifties', 'fifties'], '"introduced in the nineteen-fifties".'),
              q(38, null, ['1977'], '"The last natural case occurred in nineteen seventy-seven".'),
              q(39, null, ['autism'], '"falsely linked a vaccine to autism".'),
              q(40, null, ['months'], '"in months rather than years".'),
            ],
          },
        ],
      },
    ],
  },

  writing: {
    durationSec: 3600,
    task1: {
      order: 1,
      minWords: 150,
      recommendedMin: 20,
      promptHtml:
        '<p>The pie chart below shows how adults in a European country spent their free time on an average weekend day in 2022.</p><p>Summarise the information by selecting and reporting the main features, and make comparisons where relevant.</p>',
      chart: {
        chartType: 'pie',
        title: 'How adults spend free time on a weekend day, 2022 (%)',
        unit: '%',
        categories: ['Television and streaming', 'Socialising', 'Sport and exercise', 'Reading', 'Hobbies', 'Volunteering'],
        series: [{ name: 'Share of free time', data: [34, 24, 14, 9, 14, 5] }],
      },
    },
    task2: {
      order: 2,
      minWords: 250,
      recommendedMin: 40,
      promptHtml:
        '<p>Some people believe that everyone should be required to spend a period of time doing voluntary work in the community, for example after leaving school.</p><p>To what extent do you agree or disagree?</p>',
    },
  },
};
