// Original IELTS-style practice content (NOT copied or paraphrased from any real
// Cambridge/IELTS book). Only the exam STRUCTURE follows a standard Academic test
// layout; every topic, passage, transcript, question and answer is written from scratch.
import { table, TFNG_INSTRUCTION, YNNG_INSTRUCTION, q, paras, mc, bank } from './_html.mjs';

export default {
  slug: 'vocably-practice-test-18',
  title: 'Vocably Practice Test 18',
  difficulty: 'medium',

  reading: {
    durationSec: 3600,
    passages: [
      {
        order: 1,
        title: 'Living on a volcano',
        subtitle: 'Read the text and answer questions 1-13.',
        paragraphs: paras(
          ['A', `Iceland sits astride the boundary between two tectonic plates, which are slowly pulling apart, and the country has more than thirty active volcanic systems. For most of its history, this was a cause of hardship, since eruptions destroyed farms and poisoned the air. Today, however, the same geological activity provides the country with nearly all of its electricity and most of its heating. About seventy per cent of the country's electricity comes from hydropower, and about thirty per cent from geothermal plants, which use heat from deep underground, so that almost every unit of power is generated from renewable sources. No other industrialised nation comes close.`],
          ['B', `The use of geothermal heat began in a modest way. In 1930, a pipe was laid from a hot spring to a school in Reykjavik, and its success led to the construction of a network that now warms nearly nine out of ten homes in the country. Hot water is pumped from wells and sent through insulated pipes, sometimes for distances of tens of kilometres, losing only a few degrees on the way. The water is so cheap that some towns use it to keep pavements and car parks free of ice. Geothermal energy has been part of everyday life for so long that most Icelanders scarcely give it a thought.`],
          ['C', `Cheap, clean power has attracted industry. Several aluminium smelters, which consume huge amounts of electricity, have been built in Iceland, and the country has become a centre for data storage, since computer servers need power and cooling, which the cold climate provides. Icelanders have also found ingenious ways of using the heat. Greenhouses warmed by hot water grow tomatoes, cucumbers and even bananas, which would otherwise be impossible so far north, although the short winter days mean that artificial lighting is necessary. A famous lagoon, whose milky blue water is heated by a nearby power station, was created by accident in the 1970s when waste water from the plant collected in a hollow in the lava, and it is now one of the country's biggest tourist attractions.`],
          ['D', `Geothermal power is not entirely free of pollution, since the steam contains carbon dioxide and other gases. Iceland has been a pioneer in dealing with this. At one power plant, the gas is dissolved in water and pumped deep underground, where it reacts with the basalt rock and turns into solid minerals within two years, a process called carbon mineralisation. A project that began as an experiment now removes thousands of tonnes every year, and a newer plant nearby uses fans to draw carbon dioxide directly from the air and inject it into the same rock. Scientists are interested because basalt is common in many parts of the world.`],
          ['E', `Living on a volcano carries risks, of course. In 2023, after weeks of earthquakes, the ground near the town of Grindavik opened up and lava began to flow, and the entire population of the town, nearly four thousand people, was evacuated. Barriers of earth and rock were built to protect a nearby power station, and they succeeded in holding back the lava for the time being. Eruptions in recent decades have also damaged roads and interrupted flights. Icelanders have learned to watch the signs, to keep evacuation plans ready and to accept that their land is alive.`],
          ['F', `The engineers also face a more subtle problem. A geothermal field can be depleted if hot water is taken from it faster than nature replaces it, and some early wells declined after a few decades. The solution is to manage the fields carefully, and to pump the used water back into the ground so that it can be heated again. Ambitious proposals include laying an undersea cable to sell Icelandic electricity to Britain, although the cost is considerable, and some Icelanders fear that the plan would push up domestic prices. Drilling experiments have also reached extremely hot fluids close to magma, which could produce many times more energy per well, though the technical difficulties are formidable.`],
          ['G', `Can other countries learn from Iceland? Partly. Some regions of the world, such as parts of Kenya, Indonesia and the western United States, have similar geology and are already building geothermal plants. But most countries do not sit on the boundary between two tectonic plates, and their heat lies far deeper. New drilling techniques borrowed from the oil industry may eventually make it possible to tap heat almost anywhere, but for now, Iceland's good fortune remains a rare combination of geology, engineering and habit.`]
        ),
        questionGroups: [
          {
            id: 't18-r1-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B, C or D</strong>.',
            questions: [
              mc(1, 'What does paragraph A say about how Iceland obtains its electricity?', ['It imports most of it.', 'Almost all of it comes from renewable sources.', 'Most of it comes from geothermal plants.', 'It comes mainly from burning oil.'], 'B', 'Paragraph A: "almost every unit of power is generated from renewable sources".', 'A'),
              mc(2, 'When did the use of geothermal heat in Reykjavik begin?', ['in 1830', 'in 1930', 'in 1970', 'in 2000'], 'B', 'Paragraph B: "In 1930, a pipe was laid from a hot spring".', 'B'),
              mc(3, 'How was the famous lagoon created?', ['It was built deliberately as a tourist attraction.', 'It formed naturally from a hot spring.', 'Waste water from a power station collected in a hollow.', 'It was dug by miners.'], 'C', 'Paragraph C: "created by accident ... waste water from the plant collected in a hollow".', 'C'),
              mc(4, 'What happens to carbon dioxide in the mineralisation process?', ['It is burnt.', 'It turns into solid minerals in basalt rock.', 'It is released into the sea.', 'It is sold to industry.'], 'B', 'Paragraph D: "turns into solid minerals".', 'D'),
              mc(5, 'Why do aluminium smelters locate in Iceland?', ['Labour is cheap.', 'The climate is cold.', 'Electricity is cheap and clean.', 'Raw materials are local.'], 'C', 'Paragraph C: "Cheap, clean power has attracted industry".', 'C'),
              mc(6, 'What does paragraph F suggest about drilling close to magma?', ['It has already been adopted everywhere.', 'It could produce much more energy per well but is technically difficult.', 'It is too dangerous to be considered.', 'It has failed.'], 'B', 'Paragraph F: "many times more energy per well, though the technical difficulties are formidable".', 'F'),
            ],
          },
          {
            id: 't18-r1-summary',
            type: 'summary_completion',
            instructionHtml: 'Complete the summary of paragraphs E to G below. Choose <strong>NO MORE THAN TWO WORDS</strong> from the passage for each answer.',
            wordLimit: { maxWords: 2, label: 'NO MORE THAN TWO WORDS' },
            stemHtml: '<p>Iceland\'s energy sources carry risks. {{q7}} can damage roads and power stations, and in 2023 a town was {{q8}}. A geothermal field can be {{q9}} if hot water is removed faster than it is replaced, so used water is {{q10}} into the ground. Plans have been discussed to sell electricity through an undersea {{q11}} to Britain. Because Iceland lies on the boundary between two {{q12}}, its experience cannot easily be copied, although some countries are growing {{q13}} plants of their own.</p>',
            questions: [
              q(7, null, ['eruptions'], 'Paragraph E: "Eruptions ... have also damaged roads".', 'E'),
              q(8, null, ['evacuated'], 'Paragraph E: "was evacuated".', 'E'),
              q(9, null, ['depleted'], 'Paragraph F: "can be depleted".', 'F'),
              q(10, null, ['pumped back'], 'Paragraph F: "pump the used water back into the ground".', 'F'),
              q(11, null, ['cable'], 'Paragraph F: "an undersea cable".', 'F'),
              q(12, null, ['tectonic plates'], 'Paragraph G: "the boundary between two tectonic plates".', 'G'),
              q(13, null, ['geothermal'], 'Paragraph G: "already building geothermal plants".', 'G'),
            ],
          },
        ],
      },
      {
        order: 2,
        title: 'Rethinking the traffic jam',
        subtitle: 'Read the text and answer questions 14-26.',
        paragraphs: paras(
          ['A', `Drivers in some of the world's largest cities spend the equivalent of a full working week each year sitting in traffic. The waste is enormous: hours of lost time, extra fuel burnt for no purpose, air polluted by engines that are running but not moving, and the frustration of millions of people who are late for work. Engineers have been trying to solve the problem for nearly a century, and in most cities, they have failed. It is worth asking why, because the reasons suggest what might work.`],
          ['B', `The obvious solution is to build more roads, and it is the one that politicians and voters most often demand. Unfortunately, experience shows that new roads fill up quickly. Researchers who studied American cities over several decades found that the total distance driven rises almost exactly in proportion to the amount of road space, so that a city that adds ten per cent to its roads will, within a few years, find that traffic has risen by about ten per cent. This is known as induced demand. New capacity makes driving more attractive, so that people who once took the bus now drive, businesses relocate to the new road and families move further from work, and the extra space is soon absorbed.`],
          ['C', `If supply cannot be increased, demand must be managed, and the most powerful tool is price. Singapore introduced the world's first congestion charge in 1975, requiring drivers to buy a licence to enter the city centre, and later replaced it with an electronic system in which the charge varies with the time of day and the level of traffic. London adopted a similar scheme in 2003, and traffic in the charging zone fell by about a third in the first year, with the average speed of vehicles rising. The approach is not popular, however, and critics complain that it is unfair to lower-income drivers, who may have no alternative but to drive. Some cities respond by using the revenue to improve buses and subsidise fares.`],
          ['D', `Better alternatives to the private car are the natural partner of any charging scheme. A full metro train can carry as many people as forty buses or several hundred cars, and dedicated lanes allow buses to move freely past queues of cars. Ride-sharing has been promoted as another answer, since a car carrying four passengers takes up a quarter of the road space per person. Ride-hailing apps, which were expected to reduce traffic, have in some cities had the opposite effect, because passengers who would have walked, cycled or taken a train now travel in a car, and because drivers circle the streets waiting for their next fare.`],
          ['E', `Technology offers smaller but real gains. Traditional traffic signals run on fixed timings, which are a poor match for traffic that changes by the minute. Adaptive signals, which use sensors and cameras to count vehicles and adjust the timing of the lights accordingly, can keep traffic flowing more smoothly. Trials in several cities have reported reductions in travel time of ten to twenty per cent on the routes concerned. Such systems are cheaper than new roads, and they can be installed quickly, but their effect is limited to the roads on which they are fitted, and they cannot create space where none exists.`],
          ['F', `The pattern of the working day also matters. Most of the congestion in a city occurs in two short periods, in the morning and the evening, when nearly everyone is travelling at once. The pandemic showed what happens when that pattern is changed: as millions of people began working from home, traffic fell sharply, and in many places, the peak all but disappeared. Since then, some employers have introduced staggered working hours, or allowed staff to work at home for part of the week, and even a modest change, affecting one worker in ten, is enough to ease the pressure noticeably.`],
          ['G', `No single measure will end traffic jams. The most successful cities combine several: they charge for road use, provide good public transport, use technology to manage the flow and encourage flexible working. The aim is not to eliminate congestion entirely, which may be impossible, but to keep it at a level that people can tolerate. It is a question of managing demand and making the best use of the space that exists, rather than trying to build one's way out of the problem.`]
        ),
        questionGroups: [
          {
            id: 't18-r2-headings',
            type: 'matching_headings',
            instructionHtml: 'Reading Passage 2 has seven paragraphs, A-G. Choose the correct heading for paragraphs B-G from the list of headings below.<br/><em>Example: Paragraph A — ix</em>',
            bank: [
              { key: 'i', text: 'Technology that responds to conditions' },
              { key: 'ii', text: 'Why more road space may not help' },
              { key: 'iii', text: 'The history of the motor car' },
              { key: 'iv', text: 'No single answer' },
              { key: 'v', text: 'Alternatives to the private car' },
              { key: 'vi', text: 'Making drivers pay' },
              { key: 'vii', text: 'Accidents and road safety' },
              { key: 'viii', text: 'Changing when and where people work' },
              { key: 'ix', text: 'A costly everyday problem' },
              { key: 'x', text: 'The rise of the electric vehicle' },
            ],
            questions: [
              q(14, 'Paragraph B', 'ii', 'Paragraph B: "new roads fill up quickly" (induced demand).', 'B'),
              q(15, 'Paragraph C', 'vi', 'Paragraph C: congestion charges in Singapore and London.', 'C'),
              q(16, 'Paragraph D', 'v', 'Paragraph D: metro, buses and ride-sharing.', 'D'),
              q(17, 'Paragraph E', 'i', 'Paragraph E: adaptive signals that adjust to traffic.', 'E'),
              q(18, 'Paragraph F', 'viii', 'Paragraph F: working from home and staggered hours.', 'F'),
              q(19, 'Paragraph G', 'iv', 'Paragraph G: "No single measure will end traffic jams."', 'G'),
            ],
          },
          {
            id: 't18-r2-classify',
            type: 'matching_features',
            instructionHtml: 'Look at the following statements (Questions 20-26) and the list of measures below. Match each statement with the correct measure, <strong>A, B or C</strong>.<br/>You may use any letter more than once.',
            bankReusable: true,
            bank: [
              { key: 'A', text: 'road pricing' },
              { key: 'B', text: 'building more roads' },
              { key: 'C', text: 'adaptive traffic signals' },
            ],
            questions: [
              q(20, 'reduced traffic in a central zone by about a third in its first year', 'A', 'Paragraph C: London, "traffic ... fell by about a third".', 'C'),
              q(21, 'tends to attract extra vehicles that fill the new space', 'B', 'Paragraph B: induced demand.', 'B'),
              q(22, 'can change the timing of lights according to the number of vehicles', 'C', 'Paragraph E: "adjust the timing of the lights accordingly".', 'E'),
              q(23, 'is criticised as unfair to drivers with low incomes', 'A', 'Paragraph C: "unfair to lower-income drivers".', 'C'),
              q(24, 'was first introduced in Singapore in 1975', 'A', 'Paragraph C: "Singapore introduced the world\'s first congestion charge in 1975".', 'C'),
              q(25, 'has been reported to cut travel times by ten to twenty per cent on the routes concerned', 'C', 'Paragraph E: "reductions in travel time of ten to twenty per cent".', 'E'),
              q(26, 'is the solution that politicians and voters most often demand', 'B', 'Paragraph B: "the one that politicians and voters most often demand".', 'B'),
            ],
          },
        ],
      },
      {
        order: 3,
        title: 'Reading our genes',
        subtitle: 'Read the text and answer questions 27-40.',
        paragraphs: paras(
          ['A', `When the Human Genome Project announced in 2003 that it had read the complete genetic code of a human being, the work had taken thirteen years and cost about three billion dollars. Today, a person's genome can be read in a day for under a thousand dollars, and millions of people have bought home testing kits that promise to reveal their ancestry and their health risks. The procedure is simple: customers provide a sample of saliva in a small tube, post it to a laboratory, where the DNA is extracted and scanned for thousands of genetic markers, and receive a report by email a few weeks later. The fall in cost is one of the most dramatic in the history of technology, and it has raised questions that society is only beginning to answer.`],
          ['B', `The medical benefits are real. Tests can identify people who carry variants of genes that greatly increase the risk of certain cancers, allowing them to have more frequent screening or preventive treatment. Couples can find out whether they both carry the gene for a serious inherited condition such as cystic fibrosis before deciding to have children, and every newborn baby in many countries is tested for a range of rare disorders, so that treatment can begin before symptoms appear. Some drugs work better or more safely depending on a patient's genes, and doctors have begun to tailor prescriptions accordingly, an approach known as personalised medicine.`],
          ['C', `Privacy is the first concern. A person's genetic data is uniquely personal, yet it is stored on computers that may be hacked or sold. In 2018, American police identified a suspect in a series of murders committed decades earlier by searching a public genealogy website for relatives of the man whose DNA had been found at the crime scenes. The case was celebrated, but it alarmed privacy campaigners, since the relatives had not agreed to be used in this way. There is also the matter of discrimination. A law passed in the United States in 2008 prevents health insurers and employers from using genetic information, but it does not cover life insurance, and many countries have no such protection.`],
          ['D', `Another problem is that genetic information is often less clear than it looks. A handful of rare diseases are caused by a change in a single gene, but most common conditions, such as heart disease and diabetes, are influenced by hundreds of genes and by diet, exercise and luck. Results for these conditions are presented as risk scores, which give probabilities rather than certainties, and many people find it difficult to interpret them. A person who is told that their risk of a disease is twenty per cent higher than average may worry unnecessarily, and one who is told that it is lower may feel entitled to ignore healthy habits. Research suggests that many doctors, too, are not well prepared to explain the results.`],
          ['E', `A person's genes are shared with relatives, which makes genetic testing a family matter. A woman who learns that she carries a variant linked to breast cancer has learned something about her sisters, her mother and her daughters, who may not wish to know. Doctors disagree about whether they have a duty to warn relatives if the patient refuses, and the law in most countries is silent. The same problem arises with home tests, where customers who discover an unexpected family connection, such as a half-brother or a different father, may find the discovery painful.`],
          ['F', `The most controversial application concerns embryos. Couples undergoing fertility treatment can have their embryos tested for serious inherited diseases before choosing which to implant, a practice that most people accept. Some companies now claim to use risk scores to rank embryos by the likelihood of conditions such as diabetes, or even by characteristics such as height, which critics say is a step towards designing babies. Scientists point out that such scores are weak predictors, and that the technology is still far from being able to deliver what is promised, but the prospect has raised fears of a society in which wealth buys genetic advantage.`],
          ['G', `In my view, the answer is neither to ban testing nor to allow it to proceed without restraint. Companies should be required to state plainly what their tests can and cannot show, and to obtain consent before sharing or selling anyone's data. People who receive results should have access to trained counselling, to help them understand what the numbers mean. And legislation should close the gaps in protection against discrimination. Genetic information can do great good, but only if its use is governed by the same standards of consent, honesty and fairness that we expect in other parts of medicine.`]
        ),
        questionGroups: [
          {
            id: 't18-r3-ynng',
            type: 'yes_no_notgiven',
            instructionHtml: YNNG_INSTRUCTION,
            questions: [
              q(27, 'The fall in the cost of reading a genome has been remarkable.', 'YES', 'Paragraph A: "one of the most dramatic in the history of technology".', 'A'),
              q(28, 'Genetic testing has no medical value for people who are healthy.', 'NO', 'Paragraph B lists medical benefits, such as identifying people at risk of cancers.', 'B'),
              q(29, 'The police use of genealogy websites raises concerns about privacy.', 'YES', 'Paragraph C: the case "alarmed privacy campaigners".', 'C'),
              q(30, 'Current US law fully protects people from discrimination by insurers.', 'NO', 'Paragraph C: the law "does not cover life insurance".', 'C'),
              q(31, 'Most common diseases are caused by a change in a single gene.', 'NO', 'Paragraph D: "most common conditions ... are influenced by hundreds of genes".', 'D'),
              q(32, 'Parents should be banned from testing embryos for inherited diseases.', 'NOT GIVEN', 'Paragraph F says most people accept this practice; no ban is proposed by the writer.', 'F'),
            ],
          },
          {
            id: 't18-r3-flow',
            type: 'flowchart_completion',
            instructionHtml: 'Complete the flow-chart below. Choose <strong>NO MORE THAN TWO WORDS</strong> from paragraph A for each answer.',
            wordLimit: { maxWords: 2, label: 'NO MORE THAN TWO WORDS' },
            stemHtml: '<p><strong>How a home genetic test works</strong></p><p>1. The customer provides a sample of {{q33}} in a small tube.</p><p>2. The tube is posted to a {{q34}}.</p><p>3. The DNA is extracted and scanned for thousands of {{q35}}.</p><p>4. A report is sent to the customer by {{q36}}.</p>',
            questions: [
              q(33, null, ['saliva'], 'Paragraph A: "a sample of saliva".', 'A'),
              q(34, null, ['laboratory'], 'Paragraph A: "post it to a laboratory".', 'A'),
              q(35, null, ['genetic markers'], 'Paragraph A: "thousands of genetic markers".', 'A'),
              q(36, null, ['email'], 'Paragraph A: "a report by email".', 'A'),
            ],
          },
          {
            id: 't18-r3-short',
            type: 'short_answer',
            instructionHtml: 'Answer the questions below. Choose <strong>NO MORE THAN THREE WORDS AND/OR A NUMBER</strong> from the passage for each answer.',
            wordLimit: { maxWords: 3, maxNumbers: 1, label: 'NO MORE THAN THREE WORDS AND/OR A NUMBER' },
            questions: [
              q(37, 'What project read the complete genetic code of a human being in 2003?', ['the human genome project', 'human genome project'], 'Paragraph A: "the Human Genome Project".', 'A'),
              q(38, 'In what year was the US law on genetic information passed?', ['2008'], 'Paragraph C: "A law passed in the United States in 2008".', 'C'),
              q(39, 'What do risk scores give, rather than certainties?', ['probabilities'], 'Paragraph D: "give probabilities rather than certainties".', 'D'),
              q(40, 'What does the writer think people receiving results should have access to?', ['trained counselling', 'counselling'], 'Paragraph G: "access to trained counselling".', 'G'),
            ],
          },
        ],
      },
    ],
  },

  listening: {
    durationSec: 1800,
    checkTimeSec: 120,
    parts: [
      {
        order: 1,
        contextText: 'You will hear a woman phoning a veterinary clinic to make an appointment for her cat.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Elm Tree Veterinary Clinic, good morning." },
          { speaker: 'B', voice: 'zira', text: "Hello. I'd like to make an appointment for my cat, please. He's not been eating for two days." },
          { speaker: 'A', voice: 'david', text: "I'm sorry to hear that. Could I have your name first?" },
          { speaker: 'B', voice: 'zira', text: "Helen Marchant. M-A-R-C-H-A-N-T." },
          { speaker: 'A', voice: 'david', text: "And the cat's name?" },
          { speaker: 'B', voice: 'zira', text: "Biscuit. He's a ginger tom, eleven years old." },
          { speaker: 'A', voice: 'david', text: "Has he been to us before?" },
          { speaker: 'B', voice: 'zira', text: "No, I've just moved here. His last vet was in Bristol. He had his vaccinations in September, and he's microchipped." },
          { speaker: 'A', voice: 'david', text: "Good. Has he shown any other symptoms besides not eating?" },
          { speaker: 'B', voice: 'zira', text: "He's been drinking a lot more than usual, and he seems rather sleepy." },
          { speaker: 'A', voice: 'david', text: "I'd like the vet to see him today, then. We have an emergency slot at half past two, with Dr Okafor." },
          { speaker: 'B', voice: 'zira', text: "That's fine. How much will it cost?" },
          { speaker: 'A', voice: 'david', text: "The consultation is forty-five pounds. If the vet recommends blood tests, they would be an extra seventy. We take cards or cash." },
          { speaker: 'B', voice: 'zira', text: "Do I need to bring anything?" },
          { speaker: 'A', voice: 'david', text: "Yes, please bring him in a carrier, and any medication he's taking. Also, if you can, take a sample from his litter tray in a clean container." },
          { speaker: 'B', voice: 'zira', text: "I'll do that. Where exactly are you?" },
          { speaker: 'A', voice: 'david', text: "We're at fifty-two Chapel Street, opposite the library. There's free parking at the back." },
          { speaker: 'B', voice: 'zira', text: "Thank you. I'll be there at twenty-five past two." },
        ],
        questionGroups: [
          {
            id: 't18-l1-form',
            type: 'form_completion',
            instructionHtml: 'Complete the form below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Elm Tree Veterinary Clinic: Appointment', ''],
              [
                ['Owner\'s surname', '{{q1}}'],
                ['Pet\'s name', '{{q2}}'],
                ['Type and colour', '{{q3}} tom'],
                ['Age', '{{q4}}'],
                ['Previous vet in', '{{q5}}'],
                ['Symptoms', 'not eating; drinking a lot; {{q6}}'],
                ['Appointment time', '{{q7}} p.m.'],
                ['Vet', 'Dr {{q8}}'],
                ['Cost of consultation', '£{{q9}}'],
                ['Clinic address', '{{q10}} Chapel Street'],
              ]
            ),
            questions: [
              q(1, null, ['marchant'], 'Spelled out: M-A-R-C-H-A-N-T.'),
              q(2, null, ['biscuit'], '"Biscuit."'),
              q(3, null, ['ginger'], '"a ginger tom".'),
              q(4, null, ['11', 'eleven'], '"eleven years old".'),
              q(5, null, ['bristol'], '"His last vet was in Bristol."'),
              q(6, null, ['sleepy'], '"he seems rather sleepy".'),
              q(7, null, ['2.30', '2:30', 'half past two', 'two thirty', '14:30'], '"half past two".'),
              q(8, null, ['okafor'], '"Dr Okafor".'),
              q(9, null, ['45', 'forty-five', 'forty five'], '"The consultation is forty-five pounds."'),
              q(10, null, ['52', 'fifty-two', 'fifty two'], '"fifty-two Chapel Street".'),
            ],
          },
        ],
      },
      {
        order: 2,
        contextText: 'You will hear a museum guide introducing the archaeology galleries to a group of visitors.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Good afternoon, and welcome to the Riverside Museum of Archaeology. I'm Olivia, and I'm going to take you through our galleries, which tell the story of this region from the earliest times." },
          { speaker: 'A', voice: 'zira', text: "The museum was established in nineteen twelve, after workmen digging a canal uncovered a Roman villa. The mosaic floor from that villa is one of our most popular exhibits, and you'll see it in the second gallery." },
          { speaker: 'A', voice: 'zira', text: "The museum has four galleries. In the first, on the ground floor, we cover the Stone Age, from about ten thousand years ago, when the first hunters settled along the river. You can see flint tools, and a reconstruction of a hut." },
          { speaker: 'A', voice: 'zira', text: "The second gallery, also on the ground floor, is devoted to the Roman period. As well as the mosaic, there are coins, pottery and a model of the fort that once stood on the hill above the town." },
          { speaker: 'A', voice: 'zira', text: "Upstairs, the third gallery covers the early medieval period, and its main treasure is a hoard of silver coins and jewellery, found by a farmer in a field three years ago. It's the largest find of its kind in the region, and it's on display for the first time." },
          { speaker: 'A', voice: 'zira', text: "The fourth gallery, at the end of the upper floor, is for the later Middle Ages, with armour, books and a fascinating collection of toys that belonged to medieval children." },
          { speaker: 'A', voice: 'zira', text: "Now for some practical points. The museum is open from ten until five, Tuesday to Sunday. Admission is free, but donations are welcome. There's a café on the ground floor, and a shop near the exit that sells books and replicas of objects in the collection." },
          { speaker: 'A', voice: 'zira', text: "We run activities for families at weekends. On Saturdays, children can dress up as Roman soldiers, and on Sundays, there's a workshop in which they make their own pottery, which costs three pounds per child." },
          { speaker: 'A', voice: 'zira', text: "Photography is permitted throughout, without flash. The lift is beside the main staircase. If you have any questions, the staff in blue shirts will be happy to help." },
        ],
        questionGroups: [
          {
            id: 't18-l2-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(11, 'The museum was established after', ['a farmer found a hoard', 'workmen found a Roman villa', 'a fort was excavated'], 'B', '"after workmen digging a canal uncovered a Roman villa".'),
              mc(12, 'When did the museum open?', ['1912', '1921', '1952'], 'A', '"established in nineteen twelve".'),
              mc(13, 'The hoard of silver coins was found', ['in a canal', 'by a farmer three years ago', 'by the museum\'s staff'], 'B', '"found by a farmer in a field three years ago".'),
              mc(14, 'Admission to the museum is', ['free', '£3', '£5'], 'A', '"Admission is free".'),
              mc(15, 'On Sundays, children can', ['dress up as soldiers', 'make their own pottery', 'see a film'], 'B', '"on Sundays, there\'s a workshop in which they make their own pottery".'),
            ],
          },
          {
            id: 't18-l2-match',
            type: 'matching_features',
            instructionHtml: 'What can visitors see in each gallery? Choose the correct answer and write the correct letter, <strong>A-G</strong>, next to Questions 16-20.',
            bank: [
              { key: 'A', text: 'a mosaic floor' },
              { key: 'B', text: 'flint tools' },
              { key: 'C', text: 'a hoard of silver' },
              { key: 'D', text: 'medieval toys' },
              { key: 'E', text: 'a reconstruction of a hut' },
              { key: 'F', text: 'a model of a fort' },
              { key: 'G', text: 'a collection of swords' },
            ],
            questions: [
              q(16, 'Gallery 1: Stone Age (flint tools and …)', 'E', '"flint tools, and a reconstruction of a hut".'),
              q(17, 'Gallery 2: Roman period (main exhibit)', 'A', '"The mosaic floor from that villa".'),
              q(18, 'Gallery 2: Roman period (also)', 'F', '"a model of the fort".'),
              q(19, 'Gallery 3: early medieval period', 'C', '"a hoard of silver coins and jewellery".'),
              q(20, 'Gallery 4: later Middle Ages', 'D', '"a fascinating collection of toys".'),
            ],
          },
        ],
      },
      {
        order: 3,
        contextText: 'You will hear two biology students, Jon and Mei, discussing a plant-growth experiment with their tutor.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david2', text: "Good morning, Jon, Mei. I've read your report on the experiment with bean seedlings, and I'd like to go through some points." },
          { speaker: 'B', voice: 'david', text: "We weren't sure about the method section. We thought it was clear, but maybe it was too detailed." },
          { speaker: 'A', voice: 'david2', text: "It wasn't too detailed, but it was out of order. You described the results before explaining how you measured them. Always follow the sequence in which things happened." },
          { speaker: 'C', voice: 'zira', text: "Right. We'll reorganise it." },
          { speaker: 'A', voice: 'david2', text: "Now, your aim was to see whether the colour of light affects growth. Why did you choose red, blue and green?" },
          { speaker: 'C', voice: 'zira', text: "Because plants absorb red and blue light for photosynthesis, but reflect green, so we predicted that seedlings under green light would grow least." },
          { speaker: 'A', voice: 'david2', text: "And what did you find?" },
          { speaker: 'B', voice: 'david', text: "The seedlings under blue light were shorter but had thicker stems, those under red light were the tallest, and the green group grew more slowly, as predicted." },
          { speaker: 'A', voice: 'david2', text: "That's interesting. But you only used five seedlings in each group. With such a small sample, you can't be confident the differences are real." },
          { speaker: 'C', voice: 'zira', text: "We only had one growth cabinet, so we couldn't grow more at once." },
          { speaker: 'A', voice: 'david2', text: "Then say so in the discussion, and suggest repeating the experiment with more plants. Acknowledging limitations strengthens a report." },
          { speaker: 'B', voice: 'david', text: "We also noticed that the plants nearest the door grew more slowly, perhaps because it was cooler there." },
          { speaker: 'A', voice: 'david2', text: "That's a good observation, and it's exactly the sort of thing to mention. It's called an uncontrolled variable. In future, rotate the positions of the pots each day." },
          { speaker: 'C', voice: 'zira', text: "Should we include the photographs?" },
          { speaker: 'A', voice: 'david2', text: "Yes, but with labels and a scale. And your graph needs a title and axis labels. At present, the vertical axis has no units." },
          { speaker: 'B', voice: 'david', text: "We'll add centimetres. When's the deadline for the final version?" },
          { speaker: 'A', voice: 'david2', text: "Friday the twenty-first, at noon. Submit it online, and keep a copy." },
        ],
        questionGroups: [
          {
            id: 't18-l3-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(21, 'What is wrong with the students\' method section?', ['It is too short.', 'It is out of order.', 'It is missing.'], 'B', '"it was out of order".'),
              mc(22, 'Why did the students expect the green group to grow least?', ['Plants reflect green light.', 'Green light is too bright.', 'Green light is too dim.'], 'A', '"plants absorb red and blue light ... but reflect green".'),
              mc(23, 'Which seedlings grew tallest?', ['those under blue light', 'those under red light', 'those under green light'], 'B', '"those under red light were the tallest".'),
              mc(24, 'The tutor is concerned that', ['the sample was small', 'the seedlings died', 'the light was too bright'], 'A', '"you only used five seedlings in each group".'),
              mc(25, 'What does the tutor suggest to deal with the effect of the position of the pots?', ['use a larger cabinet', 'rotate the positions each day', 'use different plants'], 'B', '"rotate the positions of the pots each day".'),
            ],
          },
          {
            id: 't18-l3-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Report: improvements</strong></p><p>• reorganise the method section in {{q26}}<br/>• seedlings under {{q27}} light had shorter but thicker stems<br/>• mention in the discussion that only {{q28}} seedlings were used in each group<br/>• photographs need labels and a {{q29}}<br/>• vertical axis of the graph needs {{q30}}</p>',
            questions: [
              q(26, null, ['sequence', 'order'], '"Always follow the sequence in which things happened."'),
              q(27, null, ['blue'], '"The seedlings under blue light were shorter but had thicker stems".'),
              q(28, null, ['5', 'five'], '"only used five seedlings in each group".'),
              q(29, null, ['scale'], '"with labels and a scale".'),
              q(30, null, ['units'], '"the vertical axis has no units".'),
            ],
          },
        ],
      },
      {
        order: 4,
        contextText: 'You will hear part of a lecture about how penguins survive the Antarctic winter.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "The emperor penguin is the only animal that breeds during the Antarctic winter, when temperatures can fall below minus fifty degrees and winds reach a hundred and fifty kilometres an hour. Today I'll describe how it survives." },
          { speaker: 'A', voice: 'david', text: "The first adaptation is the body. Emperor penguins are the largest of all penguins, standing about one metre tall and weighing up to forty kilograms. A large body loses heat more slowly in proportion to its size. They also have a thick layer of fat, and dense, waterproof feathers, which overlap like the tiles of a roof and trap a layer of air close to the skin." },
          { speaker: 'A', voice: 'david', text: "Their beaks and flippers are small, to reduce heat loss, and the blood vessels in their legs are arranged so that warm blood going out to the feet passes close to the cold blood returning, and gives up its heat. As a result, the feet stay near freezing point, which saves energy." },
          { speaker: 'A', voice: 'david', text: "But the most remarkable adaptation is behavioural. In the depth of winter, thousands of males huddle together in a tight group, shuffling slowly so that every bird takes a turn in the warm centre. The temperature in the middle of a huddle may be as high as thirty-seven degrees, which is about seventy degrees warmer than the surrounding air." },
          { speaker: 'A', voice: 'david', text: "Why are the males doing this? Because they are caring for the eggs. After the female lays a single egg, she transfers it to the male with great care, and then walks up to eighty kilometres to the sea, to feed. The male balances the egg on his feet, covering it with a fold of skin called the brood pouch, for about two months. During this time, he eats nothing, and may lose up to forty per cent of his body weight." },
          { speaker: 'A', voice: 'david', text: "The females return about the time the chicks hatch, bringing food in their stomachs, which they regurgitate to feed the young. The males, who are by now starving, then head to the sea to feed, and the parents share the task of raising the chick, taking turns." },
          { speaker: 'A', voice: 'david', text: "Penguins are sensitive to changes in the sea ice on which they breed. If the ice melts too early, the chicks, which are not yet waterproof, may drown, and scientists have linked declines in some colonies to warming. Some models predict that most colonies could be lost by the end of the century, unless warming is limited." },
        ],
        questionGroups: [
          {
            id: 't18-l4-table',
            type: 'table_completion',
            instructionHtml: 'Complete the table below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Adaptation', 'Details'],
              [
                ['Conditions in winter', 'temperatures below minus {{q31}} degrees; winds of 150 km/h'],
                ['Body size', 'about one metre tall; weighs up to {{q32}} kg'],
                ['Insulation', 'layer of fat; dense feathers that overlap like {{q33}}'],
                ['Extremities', 'small beaks and {{q34}}; warm blood passes close to returning cold blood in the legs'],
                ['Huddling', 'temperature in the middle can reach {{q35}} degrees'],
                ['Egg', 'female passes it to the male; male keeps it on his feet under the {{q36}} for about {{q37}} months'],
                ['Male\'s weight', 'may lose up to {{q38}} per cent'],
                ['Return of females', 'bring food in their {{q39}} to feed the chick'],
                ['Threat', 'if the sea ice melts too early, chicks may {{q40}}'],
              ]
            ),
            questions: [
              q(31, null, ['50', 'fifty'], '"below minus fifty degrees".'),
              q(32, null, ['40', 'forty'], '"weighing up to forty kilograms".'),
              q(33, null, ['tiles', 'roof tiles', 'the tiles of a roof'], '"overlap like the tiles of a roof".'),
              q(34, null, ['flippers'], '"beaks and flippers are small".'),
              q(35, null, ['37', 'thirty-seven', 'thirty seven'], '"as high as thirty-seven degrees".'),
              q(36, null, ['brood pouch'], '"a fold of skin called the brood pouch".'),
              q(37, null, ['2', 'two'], '"for about two months".'),
              q(38, null, ['40', 'forty'], '"up to forty per cent of his body weight".'),
              q(39, null, ['stomachs', 'stomach'], '"bringing food in their stomachs".'),
              q(40, null, ['drown'], '"the chicks ... may drown".'),
            ],
          },
        ],
      },
    ],
  },

  writing: {
    durationSec: 3600,
    task1: {
      order: 1,
      minWords: 150,
      recommendedMin: 20,
      promptHtml:
        '<p>The charts below show the proportion of energy used for heating in homes in four countries in 2000 and in 2020, by fuel type.</p><p>Summarise the information by selecting and reporting the main features, and make comparisons where relevant.</p>',
      chart: {
        chartType: 'bar',
        title: 'Share of home heating from renewable sources (%)',
        unit: '%',
        categories: ['Iceland', 'Sweden', 'Germany', 'Poland'],
        xAxisLabel: 'Country',
        yAxisLabel: 'Percentage of home heating',
        series: [
          { name: '2000', data: [88, 41, 6, 9] },
          { name: '2020', data: [91, 66, 17, 18] },
        ],
      },
    },
    task2: {
      order: 2,
      minWords: 250,
      recommendedMin: 40,
      promptHtml:
        '<p>Traffic congestion is a growing problem in many large cities.</p><p>What are the causes of this problem, and what measures could be taken to reduce it?</p>',
    },
  },
};
