// Original IELTS-style practice content (NOT copied or paraphrased from any real
// Cambridge/IELTS book). Only the exam STRUCTURE follows a standard Academic test
// layout; every topic, passage, transcript, question and answer is written from scratch.
import { table, TFNG_INSTRUCTION, q, paras, mc, bank } from './_html.mjs';

export default {
  slug: 'vocably-practice-test-23',
  title: 'Vocably Practice Test 23',
  difficulty: 'medium',

  reading: {
    durationSec: 3600,
    passages: [
      {
        order: 1,
        title: 'Mining the deep',
        subtitle: 'Read the text and answer questions 1-13.',
        paragraphs: paras(
          ['A', `Four thousand metres below the surface of the Pacific Ocean, in permanent darkness and near-freezing water, the sea floor is covered with what look like dark, lumpy potatoes. They are known as polymetallic nodules, and they have been lying there, growing by a few millimetres every million years, since long before the first humans appeared. To a mining engineer, they are a treasure: each contains a concentrated mixture of manganese, nickel, cobalt and copper, the metals that are essential for the batteries of electric vehicles and for renewable energy systems. As the world moves away from fossil fuels, demand for these metals is growing fast, and a few companies and governments have concluded that the ocean floor may be the best place to find them.`],
          ['B', `The richest deposits lie in a huge area of the Pacific between Hawaii and Mexico, known as the Clarion-Clipperton Zone, which is about as large as the continental United States. Estimates suggest that the nodules there contain more nickel, cobalt and manganese than all the known reserves on land combined. The nodules lie loose on the muddy sea bed, and need not be dug out of solid rock. The planned method is to send a large vehicle across the bottom to collect them, in the way a giant vacuum cleaner might, and to pump them through a long pipe to a ship at the surface, where the water and sediment are separated from the nodules and, in most designs, returned to the sea.`],
          ['C', `Supporters make several arguments. They point out that mining on land has serious costs of its own: forests are cleared, rivers polluted and communities displaced, and some of the largest deposits of cobalt are in a country where mining is associated with child labour and dangerous working conditions. Nodules, by contrast, involve no digging of open pits, produce little waste rock and would not require anyone to be relocated. Some calculations also suggest that the carbon emissions from producing a tonne of metal from nodules would be lower than those from ore on land, although the estimates vary widely and have been challenged.`],
          ['D', `Environmental scientists are deeply worried. The deep sea floor, once thought a lifeless desert, is now known to contain an extraordinary variety of animals, most of them unknown to science, many living on the nodules themselves. The ecosystems are fragile and slow to recover. In a famous experiment carried out in 1989, scientists ploughed a strip of the sea bed in the Pacific to imitate the effect of mining. When researchers returned twenty-six years later, the tracks were still clearly visible, and the number of animals in the disturbed areas had still not returned to normal. Another concern is the plume of fine mud that the collector would stir up, and the discharge of waste water from the ship, which could drift for hundreds of kilometres and smother animals that filter their food from the water.`],
          ['E', `Regulation is unsettled. The sea bed beyond national waters is regarded as the common heritage of humankind, and mining in it is governed by an international body based in Jamaica, which issues exploration licences and is supposed to draw up rules for commercial mining. Dozens of licences have been granted, but the rules have not been completed, and although test collections have been made, no company has yet begun large-scale commercial mining. A group of countries has called for a pause until the environmental risks are better understood, and a number of major technology companies have announced that they will not use metals from the deep sea in their products.`],
          ['F', `Alternatives exist. Recycling of batteries, which at present is done on a small scale, could supply a growing share of the metals in future, and researchers are developing batteries that use less cobalt, or none at all. Better design could also reduce the amount of metal needed for each vehicle. The question is whether these measures can meet demand quickly enough. Supporters of mining say that they cannot, and that the nodules offer the quickest route to a clean energy future. Opponents reply that it would be unwise to destroy an ecosystem that we barely understand in order to solve a problem that might be dealt with in other ways.`]
        ),
        questionGroups: [
          {
            id: 't23-r1-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              q(1, 'Polymetallic nodules grow very quickly.', 'FALSE', 'Paragraph A: "growing by a few millimetres every million years".', 'A'),
              q(2, 'The nodules contain metals that are used in batteries.', 'TRUE', 'Paragraph A: "essential for the batteries of electric vehicles".', 'A'),
              q(3, 'Most of the richest deposits lie in the Atlantic Ocean.', 'FALSE', 'Paragraph B: the richest deposits lie "in a huge area of the Pacific".', 'B'),
              q(4, 'Companies have begun large-scale commercial mining of nodules.', 'FALSE', 'Paragraph E: "no company has yet begun large-scale commercial mining".', 'E'),
              q(5, 'Plumes of mud from mining could harm animals far from the site.', 'TRUE', 'Paragraph D: "could drift for hundreds of kilometres and smother animals".', 'D'),
              q(6, 'Battery makers will stop using cobalt by 2030.', 'NOT GIVEN', 'Paragraph F mentions research into batteries with less cobalt, not a date.', 'F'),
              q(7, 'A group of countries has called for a pause in deep-sea mining.', 'TRUE', 'Paragraph E: "A group of countries has called for a pause".', 'E'),
            ],
          },
          {
            id: 't23-r1-table',
            type: 'table_completion',
            instructionHtml: 'Complete the table below. Choose <strong>ONE WORD AND/OR A NUMBER</strong> from the passage for each answer.',
            wordLimit: { maxWords: 1, maxNumbers: 1, label: 'ONE WORD AND/OR A NUMBER' },
            stemHtml: table(
              ['Topic', 'Details'],
              [
                ['Depth', 'nodules lie at a depth of about {{q8}} metres'],
                ['Appearance', 'lumpy, like dark {{q9}}'],
                ['Metals', 'nickel, cobalt, copper and {{q10}}'],
                ['Method', 'a {{q11}} vehicle travels across the sea bed'],
                ['Regulator', 'the international body is based in {{q12}}'],
                ['1989 experiment', 'tracks still visible after {{q13}} years'],
              ]
            ),
            questions: [
              q(8, null, ['4000', '4,000', 'four thousand'], 'Paragraph A: "Four thousand metres below the surface".', 'A'),
              q(9, null, ['potatoes', 'potato'], 'Paragraph A: "dark, lumpy potatoes".', 'A'),
              q(10, null, ['manganese'], 'Paragraph A: "manganese, nickel, cobalt and copper".', 'A'),
              q(11, null, ['collector', 'collecting'], 'Paragraph B: "a large vehicle ... to collect them"; Paragraph D: "the collector".', 'B'),
              q(12, null, ['jamaica'], 'Paragraph E: "based in Jamaica".', 'E'),
              q(13, null, ['26', 'twenty-six', 'twenty six'], 'Paragraph D: "twenty-six years later".', 'D'),
            ],
          },
        ],
      },
      {
        order: 2,
        title: 'Do animals have culture?',
        subtitle: 'Read the text and answer questions 14-26.',
        paragraphs: paras(
          ['A', `For a long time, it was taken for granted that culture was something that belonged to human beings alone. Culture, in the sense used by scientists, means behaviour that is learnt from others in a group, rather than inherited or worked out individually, and that is passed from one generation to the next. Songs, cooking methods, styles of dress and ways of greeting one another are cultural in this sense; so, arguably, is language itself. Over the past half-century, however, researchers who have watched animals in the wild have found that several species appear to have traditions of their own, and the claim that humans are the only cultural animals has become hard to defend.`],
          ['B', `The strongest evidence comes from chimpanzees. Different communities in Africa have very different habits, which cannot be explained by differences in their environment. Chimpanzees in the forests of West Africa crack nuts by placing them on a flat rock and pounding them with a stone, a skill that young animals take several years to learn by watching their mothers. Those in East Africa do not crack nuts, even where nuts are plentiful, but they do catch termites, by poking long sticks into a termite mound and pulling them out covered in insects, which they then eat. Some communities use leaves as sponges to soak up water, while others use them to wipe themselves. Each group, it seems, has its own set of customs.`],
          ['C', `Nor are apes the only animals concerned. In the 1950s, on a small island off Japan, a young macaque was seen to wash a sweet potato in the sea before eating it, removing the sand and, perhaps, adding a pleasant taste of salt. The habit spread gradually to other members of her group, and within a few decades, it had become general. Humpback whales sing complex songs, which are shared by the males of a given population and change slowly from year to year; a new song that originates in one part of the Pacific may spread across the ocean within a few years. Even small birds have shown a capacity for tradition: in the 1920s, tits in England learnt to peck through the foil tops of milk bottles left on doorsteps in order to reach the cream, and the habit spread quickly across the country.`],
          ['D', `Among the most striking examples are killer whales, or orcas, which live in stable family groups led by older females. Groups in the same waters differ in what they eat, in how they hunt and even in the calls they make, which are so distinctive that researchers can identify a pod from its dialect. Some hunt seals by sliding onto the beach; others eat only fish. The calves learn these techniques from their mothers and grandmothers, and scientists have found that the presence of an elderly female improves the survival of her grandchildren, which suggests that she is a store of useful knowledge.`],
          ['E', `How can scientists be sure that a behaviour is cultural, and not simply a response to local conditions? One approach is to introduce an innovation and see whether it spreads. In a well-known experiment, researchers taught one chimpanzee in each of two groups to solve a puzzle box, using two different methods, and then observed what happened. Over the following weeks, most members of each group adopted the method of their own group's trained member, even though the other technique would have worked just as well. The result showed that chimpanzees do not simply discover solutions for themselves, but copy their neighbours, and that the practices can become characteristic of a group.`],
          ['F', `Not everyone is convinced that animal traditions deserve the same name as human culture. The critics point out that human culture is cumulative: each generation builds on the discoveries of the last, so that over centuries, tools, languages and institutions become more complex, an effect sometimes called the ratchet. Animal traditions, by contrast, seem to remain simple, and there is little evidence that any species improves on inherited methods in this way. Others reply that the difference is one of degree, and that there is no reason to regard the human form as the only legitimate one.`],
          ['G', `The discovery has implications for conservation. If animals learn much of their behaviour from others, then the loss of individuals may mean the loss of knowledge that cannot be recovered, in the way that the death of the last speaker of a language takes a language with it. Some biologists have therefore proposed that conservation should aim to protect not only species but also the distinct groups within them and the traditions that they carry. Whether or not animals have culture in the human sense, it is clear that they have more of it than we once supposed, and that it is worth preserving.`]
        ),
        questionGroups: [
          {
            id: 't23-r2-matchinfo',
            type: 'matching_information',
            instructionHtml: 'Reading Passage 2 has seven paragraphs, A-G. Which paragraph contains the following information? <em>Choose the correct letter, A-G.</em>',
            questions: [
              q(14, 'a definition of the term "culture"', 'A', 'Paragraph A: "Culture ... means behaviour that is learnt from others in a group".', 'A'),
              q(15, 'an example of a tool used to obtain insects', 'B', 'Paragraph B: "long sticks into a termite mound".', 'B'),
              q(16, 'an experiment in which a new behaviour spread through a group', 'E', 'Paragraph E: puzzle box experiment.', 'E'),
              q(17, 'an example of a song that changes and spreads across an ocean', 'C', 'Paragraph C: humpback whale songs.', 'C'),
              q(18, 'a reason for doubting that animal traditions are equivalent to human culture', 'F', 'Paragraph F: human culture is cumulative.', 'F'),
              q(19, 'a suggestion that groups as well as species should be protected', 'G', 'Paragraph G: "protect not only species but also the distinct groups".', 'G'),
              q(20, 'a reference to elderly females as a store of knowledge', 'D', 'Paragraph D: "an elderly female ... a store of useful knowledge".', 'D'),
            ],
          },
          {
            id: 't23-r2-summary',
            type: 'summary_completion_bank',
            instructionHtml: 'Complete the summary of paragraphs B and C using the list of words, A-I, below.',
            bankReusable: false,
            bank: bank(['stones', 'sticks', 'wash', 'change', 'bottles', 'quickly', 'leaves', 'slowly', 'cook']),
            stemHtml: '<p>Chimpanzees in West Africa crack nuts with {{q21}}, while those in East Africa catch termites using {{q22}}. Macaques on a Japanese island learnt to {{q23}} sweet potatoes in the sea. The songs of humpback whales {{q24}} from year to year. In England, small birds learnt to open milk {{q25}}, and the habit spread {{q26}} across the country.</p>',
            questions: [
              q(21, null, 'A', 'Paragraph B: "pounding them with a stone".', 'B'),
              q(22, null, 'B', 'Paragraph B: "poking long sticks into a termite mound".', 'B'),
              q(23, null, 'C', 'Paragraph C: "wash a sweet potato".', 'C'),
              q(24, null, 'D', 'Paragraph C: songs "change slowly from year to year".', 'C'),
              q(25, null, 'E', 'Paragraph C: "milk bottles left on doorsteps".', 'C'),
              q(26, null, 'F', 'Paragraph C: "the habit spread quickly across the country".', 'C'),
            ],
          },
        ],
      },
      {
        order: 3,
        title: 'Free trade: who gains?',
        subtitle: 'Read the text and answer questions 27-40.',
        paragraphs: paras(
          ['A', `The argument for free trade is one of the oldest and most influential in economics. In 1817, the English economist David Ricardo set out a principle that still underpins the arguments of those who favour open markets. Even if one country can produce everything more cheaply than another, he argued, both will be better off if each specialises in what it does relatively best and trades for the rest. In his example, England and Portugal both gained when England concentrated on cloth and Portugal on wine, although Portugal was more efficient at producing both. The idea, known as comparative advantage, has been tested by two centuries of experience and remains the starting point for any discussion of trade.`],
          ['B', `The benefits for consumers are easy to see. Imports of foods, clothes, electronics and other goods from low-cost countries have lowered prices and widened the choice of goods in shops everywhere. Economists estimate that trade has made an average household in rich countries richer by the equivalent of several thousand dollars a year, and that the poorest families, who spend the largest share of their incomes on goods such as clothes and food, have gained the most in proportion. Trade also spreads technology and ideas, and it forces companies to compete, which encourages them to improve quality and to cut waste.`],
          ['C', `But the gains are spread unevenly, and some people lose a great deal. When cheap imports arrive, workers in the industries affected may find themselves out of work, and because industries tend to be concentrated in particular towns, whole communities can be hit. A widely cited study of the United States found that the rapid growth of imports from China between 1999 and 2011 was linked with the loss of around a million manufacturing jobs, with effects that lasted for years, since many of those who lost them did not find comparable employment. Economists who once assumed that workers would quickly move to new jobs have had to acknowledge that, in practice, the adjustment is slow and painful.`],
          ['D', `For poorer countries, trade has been both an opportunity and a trap. Several East Asian economies, notably South Korea and Taiwan, grew rapidly from the 1960s by exporting manufactured goods, and in doing so lifted millions of people out of poverty. Their governments did not simply open their markets, however: they protected young industries for a time, directed credit to favoured sectors and required firms to meet export targets. In contrast, countries that depend on exports of a single raw material, such as copper or oil, are exposed to swings in world prices, and have found it difficult to diversify. Many economists now accept that trade is not a substitute for a deliberate strategy of development.`],
          ['E', `Opponents of free trade often raise concerns about standards. They fear that companies will move production to countries with weak rules on wages, working conditions or pollution, causing governments to reduce their own standards for fear of losing jobs, a process sometimes described as a race to the bottom. There is some evidence of this, for example in the movement of polluting industries to countries with lax regulation, but studies suggest that the effect has been smaller than critics feared, and that, in many cases, the companies with the highest standards are those that trade most. A more recent worry is that goods produced under lenient rules may undermine countries' efforts to cut their carbon emissions.`],
          ['F', `Trade is governed by a web of agreements and institutions. The World Trade Organization provides rules that member countries are supposed to follow, and a procedure for settling disputes. The system has been under strain: in recent years, several major economies have raised tariffs, the taxes that are charged on imports, in the belief that they would protect domestic jobs, and in some cases, other countries have responded with tariffs of their own. Studies of these trade wars generally find that the costs have fallen mainly on the consumers and on the firms that rely on imported materials, rather than on the countries that were the targets.`],
          ['G', `What conclusion should be drawn? The gains from trade are real but unevenly shared, and the losses are concentrated in particular towns and regions. Governments that open their economies should therefore support the workers who lose their jobs, through retraining and income support paid for by a fraction of the gains, and help the regions affected to attract new industries. In the past, this has too often been neglected, with the result that those who suffered from trade became the most hostile to it. A policy of openness can be sustained only if the benefits are seen to be widely shared.`]
        ),
        questionGroups: [
          {
            id: 't23-r3-headings',
            type: 'matching_headings',
            instructionHtml: 'Reading Passage 3 has seven paragraphs, A-G. Choose the correct heading for paragraphs B-G from the list of headings below.<br/><em>Example: Paragraph A — viii</em>',
            bank: [
              { key: 'i', text: 'Sharing the gains more fairly' },
              { key: 'ii', text: 'Paths to growth for poorer countries' },
              { key: 'iii', text: 'The history of money' },
              { key: 'iv', text: 'Those who lose out' },
              { key: 'v', text: 'Rules and disputes between nations' },
              { key: 'vi', text: 'Lower prices and greater choice' },
              { key: 'vii', text: 'Tax havens and avoidance' },
              { key: 'viii', text: 'An old idea with lasting influence' },
              { key: 'ix', text: 'Fears about standards' },
            ],
            questions: [
              q(27, 'Paragraph B', 'vi', 'Paragraph B: lower prices and wider choice in shops.', 'B'),
              q(28, 'Paragraph C', 'iv', 'Paragraph C: workers in affected industries "find themselves out of work".', 'C'),
              q(29, 'Paragraph D', 'ii', 'Paragraph D: East Asian economies and development strategies.', 'D'),
              q(30, 'Paragraph E', 'ix', 'Paragraph E: concerns about wages, conditions and pollution.', 'E'),
              q(31, 'Paragraph F', 'v', 'Paragraph F: the WTO and trade wars.', 'F'),
              q(32, 'Paragraph G', 'i', 'Paragraph G: support for workers paid for by a fraction of the gains.', 'G'),
            ],
          },
          {
            id: 't23-r3-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              q(33, 'David Ricardo set out the principle of comparative advantage in the nineteenth century.', 'TRUE', 'Paragraph A: "In 1817".', 'A'),
              q(34, 'All workers benefit from free trade.', 'FALSE', 'Paragraph C: some workers lose their jobs.', 'C'),
              q(35, 'South Korea and Taiwan grew rapidly by exporting manufactured goods.', 'TRUE', 'Paragraph D: "grew rapidly from the 1960s by exporting manufactured goods".', 'D'),
              q(36, 'The writer believes that all tariffs should be abolished.', 'NOT GIVEN', 'The writer does not express a view on abolishing tariffs.', 'F'),
            ],
          },
          {
            id: 't23-r3-summary',
            type: 'summary_completion',
            instructionHtml: 'Complete the summary of paragraph G below. Choose <strong>ONE WORD ONLY</strong> from the passage for each answer.',
            wordLimit: { maxWords: 1, label: 'ONE WORD ONLY' },
            stemHtml: '<p>The gains from trade are real but {{q37}} shared. Governments should support workers who lose their jobs, through {{q38}} and income support, paid for by a fraction of the {{q39}}, and should help the {{q40}} affected to attract new industries.</p>',
            questions: [
              q(37, null, ['unevenly'], 'Paragraph G: "unevenly shared".', 'G'),
              q(38, null, ['retraining'], 'Paragraph G: "through retraining".', 'G'),
              q(39, null, ['gains'], 'Paragraph G: "a fraction of the gains".', 'G'),
              q(40, null, ['regions'], 'Paragraph G: "help the regions affected".', 'G'),
            ],
          },
        ],
      },
    ],
  },

  listening: {
    durationSec: 1800,
    checkTimeSec: 120,
    parts: [
      {
        order: 1,
        contextText: 'You will hear a man phoning a driving school to book lessons.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Good morning, Safe Start Driving School." },
          { speaker: 'B', voice: 'david', text: "Good morning. I'd like to start driving lessons. I've never driven before." },
          { speaker: 'A', voice: 'zira', text: "Of course. Could I take your name?" },
          { speaker: 'B', voice: 'david', text: "Yusuf Demir. That's D-E-M-I-R." },
          { speaker: 'A', voice: 'zira', text: "And do you have a provisional licence?" },
          { speaker: 'B', voice: 'david', text: "Yes, I got it last month. The number is on the card; I'll give it to you at the first lesson." },
          { speaker: 'A', voice: 'zira', text: "That's fine. How many lessons do you think you'll need?" },
          { speaker: 'B', voice: 'david', text: "I've no idea. My friend took thirty." },
          { speaker: 'A', voice: 'zira', text: "That's about average. On a standard package, you get ten lessons of two hours each for four hundred and ninety pounds, or you can pay thirty-eight pounds an hour for single lessons." },
          { speaker: 'B', voice: 'david', text: "I think I'll take the package. Which days are available?" },
          { speaker: 'A', voice: 'zira', text: "Our instructor, Mrs Hanley, works Monday, Wednesday and Friday. There's a slot on Wednesdays at half past four." },
          { speaker: 'B', voice: 'david', text: "That suits me, because I finish work at four. Where would the lesson start?" },
          { speaker: 'A', voice: 'zira', text: "She can collect you from your home or from work." },
          { speaker: 'B', voice: 'david', text: "From work, please. That's the Regency Hotel on Castle Street." },
          { speaker: 'A', voice: 'zira', text: "Fine. The first lesson will be on the car park of a local supermarket, where you can practise the controls. Then we move on to quiet roads." },
          { speaker: 'B', voice: 'david', text: "What about the theory test?" },
          { speaker: 'A', voice: 'zira', text: "You should take it after about ten lessons, but you can book it now online. It costs twenty-three pounds. The practical test is ninety-five pounds." },
          { speaker: 'B', voice: 'david', text: "I see. And what should I wear?" },
          { speaker: 'A', voice: 'zira', text: "Comfortable shoes with a thin sole, not heavy boots or sandals. And bring your glasses if you wear them." },
          { speaker: 'B', voice: 'david', text: "Thank you. My mobile is oh-seven-seven-oh-oh, nine-oh-oh, eight-six-three." },
        ],
        questionGroups: [
          {
            id: 't23-l1-form',
            type: 'form_completion',
            instructionHtml: 'Complete the form below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Safe Start Driving School: New pupil', ''],
              [
                ['Surname', '{{q1}}'],
                ['Licence', '{{q2}} licence, obtained last month'],
                ['Package', '{{q3}} lessons of two hours'],
                ['Package price', '£{{q4}}'],
                ['Single lesson price', '£{{q5}} per hour'],
                ['Instructor', 'Mrs {{q6}}'],
                ['Day and time', 'Wednesday at {{q7}}'],
                ['Pick-up place', 'the {{q8}} Hotel, Castle Street'],
                ['Cost of theory test', '£{{q9}}'],
                ['Cost of practical test', '£{{q10}}'],
              ]
            ),
            questions: [
              q(1, null, ['demir'], 'Spelled out: D-E-M-I-R.'),
              q(2, null, ['provisional'], '"a provisional licence".'),
              q(3, null, ['10', 'ten'], '"ten lessons of two hours each".'),
              q(4, null, ['490', 'four hundred and ninety'], '"four hundred and ninety pounds".'),
              q(5, null, ['38', 'thirty-eight', 'thirty eight'], '"thirty-eight pounds an hour".'),
              q(6, null, ['hanley'], '"Mrs Hanley".'),
              q(7, null, ['4.30', '4:30', 'half past four', 'four thirty', '16:30'], '"Wednesdays at half past four".'),
              q(8, null, ['regency'], '"the Regency Hotel on Castle Street".'),
              q(9, null, ['23', 'twenty-three', 'twenty three'], '"twenty-three pounds".'),
              q(10, null, ['95', 'ninety-five', 'ninety five'], '"ninety-five pounds".'),
            ],
          },
        ],
      },
      {
        order: 2,
        contextText: 'You will hear a librarian describing the facilities of a newly opened library.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Welcome, everybody, to the opening of the new Central Library. I'm Gareth Price, the chief librarian, and I'd like to tell you about what you'll find inside." },
          { speaker: 'A', voice: 'david', text: "The building replaces the old library, which was opened in nineteen fifty-eight and had become too small. It took two years to build and cost eleven million pounds, which came from the council and from a grant from a national charity." },
          { speaker: 'A', voice: 'david', text: "The library has three floors. The ground floor contains the main lending library, with over eighty thousand books, together with newspapers and magazines, and a café that's open from nine until five." },
          { speaker: 'A', voice: 'david', text: "The first floor is devoted to children and young people. It has a story-telling room, and a games area with computers, where children can play under supervision. On Saturdays, there's a reading club for children, and a homework club after school on weekdays, which is free." },
          { speaker: 'A', voice: 'david', text: "The second floor is quiet. It contains study spaces, meeting rooms, which can be booked for two pounds an hour, and a local history centre, where you can look at old maps, photographs and newspapers, some of them two hundred years old." },
          { speaker: 'A', voice: 'david', text: "There's also a large hall, which holds up to a hundred and fifty people, where we'll organise talks, performances and exhibitions. The first will be a talk by a local author next Thursday evening, and entry is free." },
          { speaker: 'A', voice: 'david', text: "New services include a recording studio, which members can use to make podcasts and music, and a maker space, with a three-dimensional printer and sewing machines. Both can be booked online, and staff will show you how to use the equipment." },
          { speaker: 'A', voice: 'david', text: "Membership is free for residents, and you'll need proof of address and a form of identification. You can borrow up to fifteen items at a time for three weeks. E-books and audiobooks can be downloaded for free on your phone or tablet." },
          { speaker: 'A', voice: 'david', text: "The library is open from nine until eight on weekdays, and from ten until four on Saturdays and Sundays. There's a car park for ninety cars, and a bicycle store at the entrance. And now, let's cut the ribbon." },
        ],
        questionGroups: [
          {
            id: 't23-l2-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(11, 'The old library was opened in', ['1948', '1958', '1968'], 'B', '"opened in nineteen fifty-eight".'),
              mc(12, 'The new building cost', ['£1 million', '£11 million', '£21 million'], 'B', '"eleven million pounds".'),
              mc(13, 'The homework club is', ['on Saturdays', 'after school on weekdays', 'only in the holidays'], 'B', '"a homework club after school on weekdays, which is free".'),
              mc(14, 'Meeting rooms cost', ['£2 an hour', '£5 an hour', 'nothing'], 'A', '"two pounds an hour".'),
              mc(15, 'Next Thursday evening, there will be', ['a film', 'a talk by a local author', 'a concert'], 'B', '"a talk by a local author next Thursday evening".'),
            ],
          },
          {
            id: 't23-l2-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Central Library</strong></p><p>• more than {{q16}} books in the main lending library<br/>• the second floor has a local {{q17}} centre<br/>• the large hall holds up to {{q18}} people<br/>• new services: a recording studio and a maker space with a {{q19}} printer<br/>• members can borrow {{q20}} items at a time</p>',
            questions: [
              q(16, null, ['80000', '80,000', 'eighty thousand'], '"over eighty thousand books".'),
              q(17, null, ['history'], '"a local history centre".'),
              q(18, null, ['150', 'a hundred and fifty', 'one hundred and fifty'], '"up to a hundred and fifty people".'),
              q(19, null, ['3d', 'three-dimensional', 'three dimensional'], '"a three-dimensional printer".'),
              q(20, null, ['15', 'fifteen'], '"up to fifteen items at a time".'),
            ],
          },
        ],
      },
      {
        order: 3,
        contextText: 'You will hear two economics students, Bella and Kai, discussing an assignment on inflation with their tutor.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david2', text: "Bella, Kai, welcome. I understand you'd like to talk about your essay on inflation." },
          { speaker: 'B', voice: 'zira', text: "Yes, Professor Rees. The question asks us to explain the causes of inflation in one country, but we can't decide which one to choose." },
          { speaker: 'C', voice: 'david', text: "I'd like to write about Argentina, because inflation there has been so high for so long." },
          { speaker: 'B', voice: 'zira', text: "And I'd prefer the United Kingdom, because the data is easier to find, and I understand the institutions better." },
          { speaker: 'A', voice: 'david2', text: "Both are sensible. Kai, the risk with Argentina is that the story is so complicated that you'll struggle to cover it in three thousand words. Bella, the UK might seem less dramatic, but it would allow you to analyse recent events in detail." },
          { speaker: 'C', voice: 'david', text: "That's a good point. I could focus on one period, say the last ten years." },
          { speaker: 'A', voice: 'david2', text: "That would make it manageable. What data will you use?" },
          { speaker: 'B', voice: 'zira', text: "The consumer price index, from the national statistics office, and some figures on wages and energy prices." },
          { speaker: 'A', voice: 'david2', text: "Good. Remember that the index has limitations: it measures an average basket of goods, and your own experience of prices may differ. A short discussion of that would strengthen your essay." },
          { speaker: 'C', voice: 'david', text: "We're also thinking of including a graph of inflation over time." },
          { speaker: 'A', voice: 'david2', text: "Yes, but choose a clear type. A line graph is best for changes over time. Label the axes, and give it a title." },
          { speaker: 'B', voice: 'zira', text: "Should we explain the theories of inflation, such as demand-pull and cost-push?" },
          { speaker: 'A', voice: 'david2', text: "Briefly. Demand-pull inflation arises when spending grows faster than the economy's capacity to produce, and cost-push when the costs of production rise. Use them to structure your analysis, not just to define terms." },
          { speaker: 'C', voice: 'david', text: "And policy responses? Should we discuss interest rates?" },
          { speaker: 'A', voice: 'david2', text: "Yes. Explain how raising interest rates is meant to reduce inflation, and then assess whether it worked in your chosen case." },
          { speaker: 'B', voice: 'zira', text: "When's the deadline?" },
          { speaker: 'A', voice: 'david2', text: "The twenty-ninth of April. Send me an outline by the fifteenth, and I'll give you feedback within a week." },
        ],
        questionGroups: [
          {
            id: 't23-l3-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(21, 'Why does Kai want to write about Argentina?', ['Inflation there has been high for a long time.', 'He has lived there.', 'The data is easy to find.'], 'A', '"inflation there has been so high for so long".'),
              mc(22, 'Why does Bella prefer the United Kingdom?', ['The data is easier to find.', 'It is more dramatic.', 'The essay is shorter.'], 'A', '"the data is easier to find".'),
              mc(23, 'What does the tutor suggest Kai does?', ['focus on one period', 'choose another country', 'use more graphs'], 'A', '"focus on one period, say the last ten years".'),
              mc(24, 'What limitation of the consumer price index does the tutor mention?', ['It measures an average basket of goods.', 'It is published late.', 'It excludes food.'], 'A', '"it measures an average basket of goods".'),
              mc(25, 'The tutor recommends using which type of graph?', ['a pie chart', 'a line graph', 'a bar chart'], 'B', '"A line graph is best for changes over time."'),
            ],
          },
          {
            id: 't23-l3-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Essay plan</strong></p><p>• length: {{q26}} words<br/>• data: consumer price index, plus figures on wages and {{q27}} prices<br/>• theories: demand-pull and {{q28}}, used to structure the analysis<br/>• policy: assess whether raising {{q29}} worked<br/>• send an outline by the {{q30}} of April</p>',
            questions: [
              q(26, null, ['3000', '3,000', 'three thousand'], '"three thousand words".'),
              q(27, null, ['energy'], '"wages and energy prices".'),
              q(28, null, ['cost-push', 'cost push'], '"demand-pull and cost-push".'),
              q(29, null, ['interest rates'], '"raising interest rates".'),
              q(30, null, ['15th', 'fifteenth', '15'], '"by the fifteenth".'),
            ],
          },
        ],
      },
      {
        order: 4,
        contextText: 'You will hear part of a lecture about how glaciers shape the landscape.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Glaciers cover about ten per cent of the Earth's land, but in the past, they were far more extensive. During the last ice age, which ended about eleven thousand years ago, ice sheets several kilometres thick covered much of northern Europe and North America. Today I'll explain how moving ice has shaped the landscapes that we see." },
          { speaker: 'A', voice: 'zira', text: "A glacier forms when snow accumulates year after year, without melting completely. The weight of the upper layers compresses the lower ones into ice, and when the ice is thick enough, it begins to flow slowly downhill under its own weight, typically at a rate of a few centimetres to a few metres a day." },
          { speaker: 'A', voice: 'zira', text: "Moving ice is a powerful agent of erosion, for two main reasons. First, rocks frozen into the base of the glacier act like sandpaper, scratching and polishing the bedrock below. The scratches, called striations, show the direction in which the ice moved. Second, the ice can pull away pieces of rock, a process called plucking, which is especially effective on the downstream side of rocky bumps." },
          { speaker: 'A', voice: 'zira', text: "These processes produce some of the most distinctive landforms. A river valley, which is V-shaped in cross-section, becomes U-shaped after a glacier has passed through it, because the ice widens and deepens it. When the ice melts, the side valleys, which were cut less deeply, are left hanging high above the main valley floor, and streams that flow along them form waterfalls." },
          { speaker: 'A', voice: 'zira', text: "At the head of a glacier, where the ice begins, a bowl-shaped hollow called a cirque is carved in the mountainside. Where two cirques form back to back, the ridge between them is worn to a sharp edge, called an arête, and where three or more meet, they leave a steep, pointed peak known as a horn. The most famous example is in the Alps." },
          { speaker: 'A', voice: 'zira', text: "Glaciers also deposit material. As they melt, they drop the rocks and sand that they've carried, in a mixed, unsorted mass called till. At the furthest advance of a glacier, this builds up into a ridge, known as a terminal moraine. Some of these ridges form dams, behind which lakes collect." },
          { speaker: 'A', voice: 'zira', text: "Large rocks that have been carried far from their origin and left behind are called erratics. Their composition is different from that of the rock on which they lie, which shows that they've been transported by ice, sometimes for hundreds of kilometres." },
          { speaker: 'A', voice: 'zira', text: "Today, most glaciers are retreating because of warming, which affects water supplies for hundreds of millions of people who depend on meltwater, and contributes to the rise in sea levels. Scientists study them not only for the past they reveal, but also for the future they may foretell." },
        ],
        questionGroups: [
          {
            id: 't23-l4-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Glaciers</strong></p><p><em>Formation and movement</em><br/>• snow accumulates and the weight of upper layers compresses the lower ones into {{q31}}<br/>• the glacier flows downhill at a few centimetres to a few {{q32}} a day</p><p><em>Erosion</em><br/>• rocks frozen in the base scratch the bedrock like {{q33}}; the scratches are called striations<br/>• {{q34}}: pieces of rock are pulled away</p><p><em>Landforms</em><br/>• V-shaped river valley becomes {{q35}}-shaped<br/>• side valleys left hanging, with {{q36}}<br/>• cirque: a bowl-shaped hollow; ridge between two cirques is an {{q37}}<br/>• horn: a steep, pointed peak</p><p><em>Deposition</em><br/>• mixed, unsorted material is called {{q38}}<br/>• ridge at the furthest advance is a {{q39}} moraine<br/>• large rocks carried far from their origin are {{q40}}</p>',
            questions: [
              q(31, null, ['ice'], '"compresses the lower ones into ice".'),
              q(32, null, ['metres'], '"a few centimetres to a few metres a day".'),
              q(33, null, ['sandpaper'], '"act like sandpaper".'),
              q(34, null, ['plucking'], '"a process called plucking".'),
              q(35, null, ['u', 'u-shaped'], '"becomes U-shaped".'),
              q(36, null, ['waterfalls'], '"form waterfalls".'),
              q(37, null, ['arete', 'arête'], '"called an arête".'),
              q(38, null, ['till'], '"a mixed, unsorted mass called till".'),
              q(39, null, ['terminal'], '"a terminal moraine".'),
              q(40, null, ['erratics'], '"called erratics".'),
            ],
          },
        ],
      },
    ],
  },

  writing: {
    durationSec: 3600,
    task1: {
      order: 1,
      minWords: 150,
      recommendedMin: 20,
      promptHtml:
        '<p>The chart below shows the value of goods exported by four countries in 2000 and in 2020.</p><p>Summarise the information by selecting and reporting the main features, and make comparisons where relevant.</p>',
      chart: {
        chartType: 'bar',
        title: 'Value of exports (billion US dollars)',
        unit: 'billion US dollars',
        categories: ['Germany', 'Vietnam', 'Mexico', 'Australia'],
        xAxisLabel: 'Country',
        yAxisLabel: 'Billion US dollars',
        series: [
          { name: '2000', data: [550, 14, 166, 64] },
          { name: '2020', data: [1380, 282, 417, 245] },
        ],
      },
    },
    task2: {
      order: 2,
      minWords: 250,
      recommendedMin: 40,
      promptHtml:
        '<p>Some people believe that governments should protect their own industries by placing taxes on imported goods. Others think that international trade should be completely free.</p><p>Discuss both views and give your own opinion.</p>',
    },
  },
};
