// Original IELTS-style practice content (NOT copied or paraphrased from any real
// Cambridge/IELTS book). Only the exam STRUCTURE follows a standard Academic test
// layout; every topic, passage, transcript, question and answer is written from scratch.
import { table, TFNG_INSTRUCTION, YNNG_INSTRUCTION, q, paras, mc, bank } from './_html.mjs';

export default {
  slug: 'vocably-practice-test-5',
  title: 'Vocably Practice Test 5',
  difficulty: 'medium',

  reading: {
    durationSec: 3600,
    passages: [
      {
        order: 1,
        title: 'Bridges that grow',
        subtitle: 'Read the text and answer questions 1-13.',
        paragraphs: paras(
          ['A', `In the hills of north-eastern India, where some villages receive more than eleven metres of rain in a typical year, people cross rivers on bridges that no engineer designed and no factory produced. The bridges are alive. Made from the roots of rubber fig trees, they have been shaped by generations of villagers, and some are thought to be more than five hundred years old. Visitors who reach them after a long walk through the forest often mistake them at first for a natural formation, until they notice the carefully guided roots, the stone steps and the handrails of twisted branches. Researchers who have studied the bridges argue that they offer a lesson in building with, rather than against, the natural environment.`],
          ['B', `The method begins with a young tree planted on the bank of a stream. The rubber fig sends out thick secondary roots from its trunk above the ground, and this habit is what makes the bridges possible. Villagers take the trunk of an areca palm, split it lengthwise and hollow out its centre to make a long channel. The young roots are placed inside the channel and guided across the water, where the channel protects them from drying out and from the current. When the roots reach the far bank, they are allowed to push into the soil, where they take hold and thicken. Only then is the channel removed, and the roots left to grow. Over time, extra roots are woven in and the gaps are filled with stones and earth, so that the walkway becomes firmer.`],
          ['C', `Patience is the defining quality of the craft. A bridge of ten or fifteen metres may take fifteen years before it can carry a person, and twice as long before it can carry several people at once. No one who begins a bridge can be sure of using it, so villagers often start one for their children or grandchildren. Unlike steel or wood, the structure becomes stronger with age, since the roots thicken each year and continue to fuse with one another where they touch. Some of the longest bridges, at more than fifty metres, are said to have taken a lifetime to complete.`],
          ['D', `The reasons for building in this way are practical. During the monsoon, which lasts for several months, the streams swell into torrents within hours and can carry away any bridge fixed to the banks. Wooden bridges decay quickly in the damp and need regular replacing, and timber and metal are difficult to carry along narrow forest paths to villages that have no roads. A root bridge, by contrast, needs no imported materials. Its roots are anchored deep in the soil, and if a flood damages part of it, new roots simply grow to replace what was lost. Because the trees also help to hold the riverbank together, they reduce the erosion that would otherwise undermine the crossing.`],
          ['E', `The bridges are also a social structure. Each is looked after by the families of the village nearest to it, who inspect the roots after storms, clear away fallen branches and guide new growth into place. The work is shared, and knowledge passes from parents to children through practice rather than writing. In some places, a bridge belongs to a single family, who allow others to use it freely. Anthropologists note that looking after the bridges has given the villages a strong sense of shared responsibility, which also shows in the way they manage their forests and water.`],
          ['F', `Today the bridges face an uncertain future. Tourism has brought income, but hundreds of visitors a day place a heavy load on roots that were shaped for a few people at a time, and several popular sites have been damaged by crowds. Young people increasingly move to cities, and fewer are willing to spend their lives tending trees. At the same time, engineers and architects from other countries have begun to study the bridges, hoping to apply the same principles to structures that grow and repair themselves. Local groups have started to plant new bridges and to limit the number of visitors at the most popular sites, in the hope that the craft will survive long enough for the youngest bridges to mature.`]
        ),
        questionGroups: [
          {
            id: 't5-r1-headings',
            type: 'matching_headings',
            instructionHtml: 'Reading Passage 1 has six paragraphs, A-F. Choose the correct heading for paragraphs B-F from the list of headings below.<br/><em>Example: Paragraph A — vii</em>',
            bank: [
              { key: 'i', text: 'An uncertain future' },
              { key: 'ii', text: 'A step-by-step method of guiding roots' },
              { key: 'iii', text: 'A comparison with bridges in other countries' },
              { key: 'iv', text: 'Advantages over other materials' },
              { key: 'v', text: 'A craft that requires patience' },
              { key: 'vi', text: 'The discovery of the trees by foreign scientists' },
              { key: 'vii', text: 'An unusual crossing' },
              { key: 'viii', text: 'A community responsibility' },
            ],
            questions: [
              q(1, 'Paragraph B', 'ii', 'Paragraph B describes the method from planting to removing the channel.', 'B'),
              q(2, 'Paragraph C', 'v', 'Paragraph C: "Patience is the defining quality of the craft."', 'C'),
              q(3, 'Paragraph D', 'iv', 'Paragraph D: root bridges need no imported materials and survive floods, unlike wooden ones.', 'D'),
              q(4, 'Paragraph E', 'viii', 'Paragraph E: families look after each bridge; "a strong sense of shared responsibility".', 'E'),
              q(5, 'Paragraph F', 'i', 'Paragraph F: "Today the bridges face an uncertain future."', 'F'),
            ],
          },
          {
            id: 't5-r1-flow',
            type: 'flowchart_completion',
            instructionHtml: 'Complete the flow-chart below. Choose <strong>NO MORE THAN TWO WORDS</strong> from paragraph B for each answer.',
            wordLimit: { maxWords: 2, label: 'NO MORE THAN TWO WORDS' },
            stemHtml: '<p>1. A young tree is planted on the bank of a stream.</p><p>2. The trunk of an {{q6}} is split and hollowed out to form a long channel.</p><p>3. Young roots are placed in the channel and guided across the {{q7}}.</p><p>4. The roots are allowed to push into the {{q8}} on the far bank, where they thicken.</p><p>5. Once the roots have taken hold, the {{q9}} is removed.</p>',
            questions: [
              q(6, null, ['areca palm'], 'Paragraph B: "the trunk of an areca palm".', 'B'),
              q(7, null, ['water'], 'Paragraph B: "guided across the water".', 'B'),
              q(8, null, ['soil'], 'Paragraph B: "allowed to push into the soil".', 'B'),
              q(9, null, ['channel'], 'Paragraph B: "Only then is the channel removed".', 'B'),
            ],
          },
          {
            id: 't5-r1-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              q(10, 'All of the living root bridges are more than five hundred years old.', 'FALSE', 'Paragraph A: "some are thought to be more than five hundred years old".', 'A'),
              q(11, 'A bridge of ten to fifteen metres may need about fifteen years before a person can cross it.', 'TRUE', 'Paragraph C: "may take fifteen years before it can carry a person".', 'C'),
              q(12, 'Root bridges are cheaper to build than concrete ones.', 'NOT GIVEN', 'Costs compared with concrete are not discussed.'),
              q(13, 'Some families who own a bridge refuse to let other people use it.', 'FALSE', 'Paragraph E: owners "allow others to use it freely".', 'E'),
            ],
          },
        ],
      },
      {
        order: 2,
        title: 'The hidden life of soil',
        subtitle: 'Read the text and answer questions 14-26.',
        paragraphs: paras(
          ['A', `A handful of healthy soil contains more living organisms than there are people on Earth. Most of them are too small to see: bacteria, fungi and microscopic worms, along with larger creatures such as earthworms, beetles and mites. For most of history, soil was treated as little more than a medium for holding plants in place, and scientists paid far more attention to the plants than to what happened beneath them. In the past few decades, however, advances in DNA analysis have allowed researchers to identify the organisms in a sample without having to grow them in a laboratory, and this has revealed a world far more varied than anyone expected. Estimates suggest that fewer than one per cent of the species living in soil have ever been formally described, which means that most of the life beneath our feet still has no name.`],
          ['B', `Bacteria are the most numerous soil organisms; a single gram may contain a billion of them, and their numbers rise in warm, damp weather and fall during drought. They break down dead plant and animal material, releasing nutrients such as nitrogen and phosphorus in forms that roots can absorb. Some bacteria live inside small swellings on the roots of peas and beans, where they convert nitrogen gas from the air into a form the plant can use, in return for sugars. This partnership is the reason farmers have grown beans between cereal crops for centuries, although they did not understand why it worked.`],
          ['C', `Fungi form fine threads, known as hyphae, which spread through the soil in networks that may cover many hectares. Some hyphae are finer than a human hair, yet a single teaspoon of forest soil can contain several kilometres of them. Many attach themselves to plant roots in a relationship called a mycorrhiza. The fungus extends the plant's reach, collecting water and minerals from far beyond the roots, and receives up to a fifth of the plant's sugars in return. Some scientists have suggested that these networks also allow plants to exchange chemical signals, warning their neighbours of attack by insects, although how far this really happens remains a matter of debate.`],
          ['D', `Larger animals rebuild the structure of the soil. Earthworms pull leaves down from the surface and mix them with minerals, and their tunnels allow air and water to reach the deeper layers. In his last book, published in 1881, Charles Darwin calculated that worms in an English field could bring several tonnes of soil to the surface per hectare each year, a figure that later measurements have largely confirmed. Without worms, heavy soils become compacted, and rainwater runs off the surface instead of soaking in.`],
          ['E', `Modern farming can damage this community. Ploughing breaks up fungal networks and exposes organic matter to the air, where it decays quickly. Erosion is a further consequence: bare soil that has lost its cover of plants and its binding fungal threads can be washed away in a single storm, taking decades of accumulated goodness with it. Heavy machinery compresses the soil, and some pesticides kill organisms they were never intended to target. A study of farmland in several countries found that fields that had been intensively cultivated for decades contained far fewer species than neighbouring meadows, and that their soils were less able to hold water.`],
          ['F', `Soil also plays a part in the climate. It holds more carbon than the atmosphere and all the world's plants put together. When soil is disturbed or warmed, microbes release some of this carbon as carbon dioxide. On the other hand, practices that increase the amount of organic matter in the soil could, in theory, store additional carbon for decades. Estimates of how much vary widely, and some researchers warn that the potential has been exaggerated by those who hope that farming alone can offset emissions from other sources.`],
          ['G', `Farmers are already responding. Some have abandoned ploughing in favour of drilling seeds directly into undisturbed ground, and many plant cover crops, such as clover or rye, between harvests to keep the soil covered and to feed the organisms beneath it. Others add compost or fungal products, although the evidence that the latter work is mixed. Researchers argue that the first step is simply to measure soil life routinely, as farmers already measure acidity and nutrients, so that they can see whether their methods are helping or harming.`]
        ),
        questionGroups: [
          {
            id: 't5-r2-matchinfo',
            type: 'matching_information',
            instructionHtml: 'Reading Passage 2 has seven paragraphs, A-G. Which paragraph contains the following information? <em>Choose the correct letter, A-G.</em><br/><strong>NB</strong> You may use any letter more than once.',
            bankReusable: true,
            questions: [
              q(14, 'a historical estimate that has been supported by modern measurement', 'D', 'Paragraph D: Darwin\'s figure "later measurements have largely confirmed".', 'D'),
              q(15, 'a comparison between farmland and uncultivated land', 'E', 'Paragraph E: farmland had "far fewer species than neighbouring meadows".', 'E'),
              q(16, 'how a scientific technique changed what we know about soil life', 'A', 'Paragraph A: DNA analysis "has revealed a world far more varied".', 'A'),
              q(17, 'organisms that turn a gas from the air into a nutrient plants can use', 'B', 'Paragraph B: bacteria "convert nitrogen gas from the air".', 'B'),
              q(18, 'uncertainty about whether plants can send warnings to one another', 'C', 'Paragraph C: "remains a matter of debate".', 'C'),
              q(19, 'a recommendation to monitor soil life on a regular basis', 'G', 'Paragraph G: "measure soil life routinely".', 'G'),
            ],
          },
          {
            id: 't5-r2-sentences',
            type: 'sentence_completion',
            instructionHtml: 'Complete the sentences below. Choose <strong>NO MORE THAN TWO WORDS</strong> from the passage for each answer.',
            wordLimit: { maxWords: 2, label: 'NO MORE THAN TWO WORDS' },
            questions: [
              q(20, 'Researchers can identify soil organisms using {{q20}} analysis, without growing them in a laboratory.', 'DNA', 'Paragraph A: "advances in DNA analysis".', 'A'),
              q(21, 'Bacteria release nutrients such as nitrogen and {{q21}} from dead material.', 'phosphorus', 'Paragraph B: "nitrogen and phosphorus".', 'B'),
              q(22, 'The fine threads formed by fungi are called {{q22}}.', 'hyphae', 'Paragraph C: "known as hyphae".', 'C'),
              q(23, 'A fungus may receive up to {{q23}} of a plant\'s sugars.', ['a fifth', 'one fifth'], 'Paragraph C: "up to a fifth of the plant\'s sugars".', 'C'),
              q(24, 'The tunnels made by earthworms let water and {{q24}} reach deeper layers.', 'air', 'Paragraph D: "allow air and water to reach the deeper layers".', 'D'),
              q(25, 'Some pesticides kill organisms that they were never {{q25}} to target.', 'intended', 'Paragraph E: "never intended to target".', 'E'),
              q(26, 'Clover or rye grown between harvests are known as {{q26}} crops.', 'cover', 'Paragraph G: "cover crops, such as clover or rye".', 'G'),
            ],
          },
        ],
      },
      {
        order: 3,
        title: 'Who should own the past?',
        subtitle: 'Read the text and answer questions 27-40.',
        paragraphs: paras(
          ['A', `Walk through the great museums of London, Paris or Berlin and you will pass cases full of objects that were taken from elsewhere: temple sculptures, royal regalia, ceremonial masks, manuscripts. Some were bought in fair transactions; others were removed during wars, in periods of colonial rule, or by archaeologists who were given permission by authorities that no longer exist. For most of the twentieth century, few visitors asked how the objects came to be there. Today the question is hard to avoid, and demands for the return of such objects have moved from the margins of academic debate into the centre of international politics.`],
          ['B', `Directors of large museums usually defend their collections by pointing to their purpose. A museum that displays objects from many cultures under one roof, they argue, allows ordinary people to make comparisons and discover connections that would be impossible if every object stayed where it was made. They also point to the costs of care: climate-controlled galleries, trained conservators and security staff are expensive, and some argue that fragile objects are safer in well-funded institutions than in countries affected by conflict or theft. These arguments carry weight, but they are weaker than their supporters suggest. Several of the countries that have requested returns have built modern museums for the purpose, and the claim that an object is safer abroad is hard to sustain when it was itself taken by force.`],
          ['C', `For the governments and communities that request returns, the issue is one of identity rather than of display. A ceremonial mask or royal throne is not simply an example of skilled craftsmanship; it may have a role in living traditions, and its absence can feel like a missing part of a community's history. Officials from several countries also note that visitors to foreign museums see the objects detached from their surroundings, often with little explanation of what they meant to the people who made them. Travelling to see them is, for most citizens of the countries concerned, unrealistic, since the cost of a flight and a visa is far beyond an ordinary income.`],
          ['D', `The legal position is far less clear than either side often admits. Most acquisitions took place under laws that have since changed, and the main international agreement on the subject, signed in 1970, applies only to objects that left their countries after that date. Courts have been reluctant to apply modern standards to events of earlier centuries, and museums in many countries are prevented by law from giving away items in their permanent collections. As a result, the most significant settlements have been reached by negotiation rather than litigation, and they take a wide range of forms, from permanent transfers of ownership to loans that circulate between institutions.`],
          ['E', `Recent years have seen a small but growing number of returns. A university in northern Europe handed back a group of ceremonial masks to a national museum in West Africa; a private collector in North America gave a set of ancient tablets to the government of the country where they were found. Such cases are still the exception, and most requests receive no response. Yet each one has made it slightly easier for the next to be discussed, and some museum staff admit privately that the atmosphere has changed faster than anyone predicted a decade ago.`],
          ['F', `Technology has opened up a further option. High-resolution scanning now makes it possible to produce exact three-dimensional copies of almost any object, and some commentators suggest that museums could return originals and keep replicas, or that both sides could display copies. I find this proposal less convincing than it first appears. A replica may be accurate to a fraction of a millimetre, but it cannot carry the significance that comes from being the object itself, and suggesting that it can risks treating those who ask for returns as if they were merely asking for an image. Scanning is valuable for study and education; it is not a substitute for a decision about ownership.`],
          ['G', `It would be easy to conclude from all this that the debate can never be resolved. I believe the opposite. The disagreement is sharpest when it is framed as a single choice between keeping and returning, and it softens once the discussion turns to practical arrangements: shared research, loans with guarantees of return, training for museum staff in the countries concerned, and honest labelling of how each object was acquired. None of these will satisfy everyone, but together they would replace an argument about who is right with a relationship in which both sides have something to gain.`]
        ),
        questionGroups: [
          {
            id: 't5-r3-ynng',
            type: 'yes_no_notgiven',
            instructionHtml: YNNG_INSTRUCTION,
            questions: [
              q(27, 'The arguments made by museum directors about caring for objects have no merit at all.', 'NO', 'Paragraph B: "These arguments carry weight, but they are weaker than their supporters suggest."', 'B'),
              q(28, 'It is difficult to claim that an object is safer abroad if it was taken by force.', 'YES', 'Paragraph B: "hard to sustain when it was itself taken by force".', 'B'),
              q(29, 'Courts ought to judge acquisitions from earlier centuries by modern standards.', 'NOT GIVEN', 'Paragraph D says courts have been reluctant but the writer gives no opinion.', 'D'),
              q(30, 'Both sides in the debate tend to overstate how clear the law is.', 'YES', 'Paragraph D: "far less clear than either side often admits".', 'D'),
              q(31, 'Replicas are an acceptable substitute for original objects.', 'NO', 'Paragraph F: "it is not a substitute for a decision about ownership".', 'F'),
              q(32, 'The debate over returns can never be resolved.', 'NO', 'Paragraph G: "I believe the opposite."', 'G'),
            ],
          },
          {
            id: 't5-r3-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B, C or D</strong>.',
            questions: [
              mc(33, 'According to paragraph A, during most of the twentieth century', ['museums refused to discuss how they obtained objects', 'few visitors questioned how objects came to be in museums', 'most objects were bought in fair transactions', 'archaeologists were forbidden to remove objects'], 'B', 'Paragraph A: "few visitors asked how the objects came to be there".', 'A'),
              mc(34, 'In paragraph C, officials complain that visitors to foreign museums', ['pay too much for admission', 'see objects without their original setting', 'are not allowed to photograph objects', 'rarely show interest in the objects'], 'B', 'Paragraph C: "objects detached from their surroundings".', 'C'),
              mc(35, 'What does paragraph D suggest about settlements?', ['They are usually decided by international courts.', 'They nearly always involve permanent transfers of ownership.', 'They have mostly been reached through negotiation and vary in form.', 'They are prevented by the 1970 agreement.'], 'C', 'Paragraph D: "reached by negotiation rather than litigation ... a wide range of forms".', 'D'),
              mc(36, 'What is the writer\'s main purpose in paragraph G?', ['to criticise museum directors', 'to propose practical arrangements in place of an all-or-nothing argument', 'to predict that most objects will be returned', 'to explain why the law should change'], 'B', 'Paragraph G: the discussion "softens once it turns to practical arrangements".', 'G'),
            ],
          },
          {
            id: 't5-r3-classify',
            type: 'matching_features',
            instructionHtml: 'Look at the following statements (Questions 37-40) and the list of people below. Match each statement with the correct person, <strong>A, B or C</strong>.<br/>You may use any letter more than once.',
            bankReusable: true,
            bank: [
              { key: 'A', text: 'museum directors' },
              { key: 'B', text: 'officials from countries requesting returns' },
              { key: 'C', text: 'the writer' },
            ],
            questions: [
              q(37, 'Fragile objects may be better protected in well-funded institutions.', 'A', 'Paragraph B: "fragile objects are safer in well-funded institutions".', 'B'),
              q(38, 'Objects lose much of their meaning when displayed away from their surroundings.', 'B', 'Paragraph C: "objects detached from their surroundings".', 'C'),
              q(39, 'Each object should be honestly labelled to show how it was acquired.', 'C', 'Paragraph G: "honest labelling of how each object was acquired".', 'G'),
              q(40, 'Collections from many cultures allow people to discover connections.', 'A', 'Paragraph B: "make comparisons and discover connections".', 'B'),
            ],
          },
        ],
      },
    ],
  },

  listening: {
    durationSec: 1800,
    checkTimeSec: 120,
    parts: [
      {
        order: 1,
        contextText: 'You will hear a woman phoning a swimming school to register her son for lessons.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Good afternoon, Harbour Swim School. How can I help you?" },
          { speaker: 'B', voice: 'zira', text: "Hello. I'd like to register my son for swimming lessons, please." },
          { speaker: 'A', voice: 'david', text: "Certainly. Could I take his name first?" },
          { speaker: 'B', voice: 'zira', text: "It's Oliver Brandt. That's B-R-A-N-D-T." },
          { speaker: 'A', voice: 'david', text: "Thank you. And how old is Oliver?" },
          { speaker: 'B', voice: 'zira', text: "He's seven. He'll be eight on the ninth of November." },
          { speaker: 'A', voice: 'david', text: "Has he had any lessons before?" },
          { speaker: 'B', voice: 'zira', text: "Only a few on holiday. He's happy in the water, but he can't swim without armbands yet." },
          { speaker: 'A', voice: 'david', text: "That's fine; we'll put him in the beginners' group. Does he have any medical conditions we should know about?" },
          { speaker: 'B', voice: 'zira', text: "He has asthma, so he'll need to keep his inhaler at the side of the pool." },
          { speaker: 'A', voice: 'david', text: "Of course, we can arrange that. Now, classes for his age group run on Wednesdays at four-thirty and on Saturdays at ten in the morning." },
          { speaker: 'B', voice: 'zira', text: "Wednesday would be difficult, because I don't finish work until five. Saturday would be better." },
          { speaker: 'A', voice: 'david', text: "Saturday at ten, then. The course lasts ten weeks and costs a hundred and eighty pounds, which you can pay at the start, or in two instalments of ninety pounds." },
          { speaker: 'B', voice: 'zira', text: "I'll pay in two instalments, if that's all right. Does he need to bring anything?" },
          { speaker: 'A', voice: 'david', text: "Goggles and a swim cap, please. You can buy both at reception if you don't have them. Towels are provided only in the shower area, so bring his own for afterwards." },
          { speaker: 'B', voice: 'zira', text: "Fine. By the way, I heard about you from my neighbour, who saw a poster in the library." },
          { speaker: 'A', voice: 'david', text: "Oh, good. I'll make a note of that. Finally, I'll need your address." },
          { speaker: 'B', voice: 'zira', text: "It's fourteen Kestrel Road. That's K-E-S-T-R-E-L." },
          { speaker: 'A', voice: 'david', text: "Thank you, Mrs Brandt. We'll send a confirmation by email this afternoon." },
        ],
        questionGroups: [
          {
            id: 't5-l1-form',
            type: 'form_completion',
            instructionHtml: 'Complete the form below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Harbour Swim School: Registration', ''],
              [
                ['Child\'s surname', '{{q1}}'],
                ['Birthday', '{{q2}} November'],
                ['Swimming experience', 'cannot swim without {{q3}}'],
                ['Medical condition', '{{q4}}'],
                ['Preferred day', '{{q5}}'],
                ['Class time', '{{q6}} a.m.'],
                ['Course fee', '£{{q7}}'],
                ['Equipment needed', 'goggles and a {{q8}}'],
                ['Heard about school from neighbour, who saw a poster in the', '{{q9}}'],
                ['Address', '14 {{q10}} Road'],
              ]
            ),
            questions: [
              q(1, null, ['brandt'], 'Spelled out: B-R-A-N-D-T.'),
              q(2, null, ['9', 'ninth', '9th'], '"He\'ll be eight on the ninth of November."'),
              q(3, null, ['armbands'], '"he can\'t swim without armbands yet".'),
              q(4, null, ['asthma'], '"He has asthma".'),
              q(5, null, ['saturday', 'saturdays'], '"Saturday would be better."'),
              q(6, null, ['10', 'ten'], '"Saturday at ten".'),
              q(7, null, ['180', 'one hundred and eighty', 'a hundred and eighty'], '"a hundred and eighty pounds".'),
              q(8, null, ['swim cap'], '"Goggles and a swim cap".'),
              q(9, null, ['library'], '"a poster in the library".'),
              q(10, null, ['kestrel'], 'Spelled out: K-E-S-T-R-E-L.'),
            ],
          },
        ],
      },
      {
        order: 2,
        contextText: 'You will hear a sports officer talking to new students about the university sports centre.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Welcome, everyone. I'm Dana Whitfield, the sports officer here, and I'd like to tell you what's on offer at the sports centre this year." },
          { speaker: 'A', voice: 'zira', text: "The centre is open on weekdays from seven in the morning until ten at night, and at weekends from nine until six. So whatever your timetable, you should be able to fit in some exercise." },
          { speaker: 'A', voice: 'zira', text: "I should mention that the swimming pool is closed at the moment. People often think it's for cleaning, but in fact we're replacing part of the heating system, and it should reopen after the winter break." },
          { speaker: 'A', voice: 'zira', text: "Membership costs fifteen pounds a month for students, which is about a third less than the standard price, and you can cancel at any time. If you join before the end of the month, your first week is free." },
          { speaker: 'A', voice: 'zira', text: "Before using the gym, you must attend an induction session. Please bring your student card, because we can't let you in without it. A medical form is available if you want to fill one in, but it's optional. And please wear trainers, as sandals and bare feet aren't allowed." },
          { speaker: 'A', voice: 'zira', text: "The biggest addition this year is the new climbing wall, which is nine metres high and suitable for beginners. There are also plans for an outdoor running track, but that won't be ready until next year." },
          { speaker: 'A', voice: 'zira', text: "Now, the clubs. All of them welcome beginners. Table tennis meets on Monday evenings. Badminton is on Tuesdays. The karate club trains on Thursdays. The rowing club goes out on the river early on Saturday mornings, so you'll need to be an early riser. And the hockey club plays friendly matches on Sundays." },
          { speaker: 'A', voice: 'zira', text: "You can sign up for any of these at the sports fair in the main hall tomorrow. Thank you for listening." },
        ],
        questionGroups: [
          {
            id: 't5-l2-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(11, 'On weekdays the sports centre opens at', ['6 a.m.', '7 a.m.', '9 a.m.'], 'B', '"open on weekdays from seven in the morning".'),
              mc(12, 'The swimming pool is closed because', ['it is being cleaned', 'the heating system is being replaced', 'the roof is being repaired'], 'B', '"we\'re replacing part of the heating system".'),
              mc(13, 'Student membership costs', ['£12 a month', '£15 a month', '£20 a month'], 'B', '"fifteen pounds a month for students".'),
              mc(14, 'What must students bring to the gym induction?', ['their student card', 'a completed medical form', 'a towel'], 'A', '"Please bring your student card".'),
              mc(15, 'What is new at the sports centre this year?', ['an outdoor running track', 'a climbing wall', 'a cycling studio'], 'B', '"the new climbing wall".'),
            ],
          },
          {
            id: 't5-l2-match',
            type: 'matching_features',
            instructionHtml: 'On which day does each club meet? Choose the correct answer and write the correct letter, <strong>A-G</strong>, next to Questions 16-20.',
            bank: bank(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']),
            questions: [
              q(16, 'Badminton', 'B', '"Badminton is on Tuesdays."'),
              q(17, 'Rowing', 'F', '"The rowing club goes out on the river early on Saturday mornings".'),
              q(18, 'Karate', 'D', '"The karate club trains on Thursdays."'),
              q(19, 'Table tennis', 'A', '"Table tennis meets on Monday evenings."'),
              q(20, 'Hockey', 'G', '"The hockey club plays friendly matches on Sundays."'),
            ],
          },
        ],
      },
      {
        order: 3,
        contextText: 'You will hear two geography students, Ingrid and Felix, discussing a river survey project with their tutor.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david2', text: "Come in, both of you. So, tell me how the river project is going." },
          { speaker: 'B', voice: 'zira', text: "Quite well, Dr Patel. We chose the River Wren because it flows through both farmland and the town, so we can compare the two sections." },
          { speaker: 'A', voice: 'david2', text: "That's a sensible choice. Any problems so far?" },
          { speaker: 'C', voice: 'david', text: "One or two. Three of our sites are on private land, so we need to ask the owners for permission before we can collect anything." },
          { speaker: 'A', voice: 'david2', text: "Yes, write to them this week. Most farmers are happy to help if you explain what you're doing. Now, what will you measure?" },
          { speaker: 'B', voice: 'zira', text: "The temperature of the water, using a digital probe, and the width and depth of the channel. To measure the speed of the flow, we'll drop a bright orange ball into the water and time how long it takes to travel ten metres." },
          { speaker: 'A', voice: 'david2', text: "Good. One suggestion: take all your measurements at the same time of day. Water temperature changes a lot between morning and afternoon, and that could spoil your comparison." },
          { speaker: 'C', voice: 'david', text: "That makes sense. We'd planned to visit the four sites over two days, so we'll need to start early." },
          { speaker: 'A', voice: 'david2', text: "And small animals? Are you sampling them?" },
          { speaker: 'B', voice: 'zira', text: "Yes, using a kick net. We stand in the stream, disturb the bed with our feet, and catch whatever floats into the net. The first site will be near the old stone bridge, which is easy to reach." },
          { speaker: 'A', voice: 'david2', text: "How do you plan to present your results?" },
          { speaker: 'B', voice: 'zira', text: "I'd like to use maps, with the data marked at each site, because I think they show the pattern along the river better than tables." },
          { speaker: 'C', voice: 'david', text: "I'd have preferred graphs, but I can see Ingrid's point. We might include a few of each." },
          { speaker: 'A', voice: 'david2', text: "Fine. What worries you most about the project?" },
          { speaker: 'C', voice: 'david', text: "Probably having enough time to analyse everything. The fieldwork is only part of it." },
          { speaker: 'B', voice: 'zira', text: "I agree. The data will take longer to process than the trips themselves." },
          { speaker: 'A', voice: 'david2', text: "Then plan the analysis now. The final report is due at the end of April, so work backwards from that." },
        ],
        questionGroups: [
          {
            id: 't5-l3-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(21, 'Why did the students choose the River Wren?', ['It is close to the university.', 'It flows through both farmland and a town.', 'It is the longest river in the area.'], 'B', '"it flows through both farmland and the town".'),
              mc(22, 'What problem does Felix mention?', ['Equipment has been booked by other groups.', 'The weather forecast is poor.', 'Some sites are on private land.'], 'C', '"Three of our sites are on private land".'),
              mc(23, 'The tutor advises the students to', ['measure at the same time of day', 'visit each site only once', 'work at different sites separately'], 'A', '"take all your measurements at the same time of day".'),
              mc(24, 'Ingrid would prefer to present the results as', ['graphs', 'tables', 'maps'], 'C', '"I\'d like to use maps".'),
              mc(25, 'The students agree that the biggest challenge will be', ['getting permission', 'finding enough time to analyse the data', 'using the equipment correctly'], 'B', '"having enough time to analyse everything".'),
            ],
          },
          {
            id: 't5-l3-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS</strong> for each answer.',
            wordLimit: { maxWords: 2, label: 'NO MORE THAN TWO WORDS' },
            stemHtml: '<p><strong>River survey: plan</strong></p><p>• water {{q26}} measured with a digital probe<br/>• speed of flow: time an orange {{q27}} over ten metres<br/>• first site: near the old stone {{q28}}<br/>• small animals collected using a kick {{q29}}<br/>• report due at the end of {{q30}}</p>',
            questions: [
              q(26, null, ['temperature'], '"The temperature of the water, using a digital probe".'),
              q(27, null, ['ball'], '"a bright orange ball".'),
              q(28, null, ['bridge'], '"near the old stone bridge".'),
              q(29, null, ['net'], '"using a kick net".'),
              q(30, null, ['april'], '"due at the end of April".'),
            ],
          },
        ],
      },
      {
        order: 4,
        contextText: 'You will hear part of a lecture about the science of snowflakes.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Today I'm going to talk about snowflakes: how they form, why they look the way they do, and what happens to them once they reach the ground." },
          { speaker: 'A', voice: 'david', text: "A snowflake begins when a tiny droplet of water in a cloud freezes around a speck of dust. That speck gives the ice something to cling to, and without it, the droplet would stay liquid even at very low temperatures." },
          { speaker: 'A', voice: 'david', text: "The basic shape of a snowflake is determined by the way water molecules join together as they freeze. They arrange themselves in a pattern with six sides, which is why almost all snowflakes have six arms or six corners." },
          { speaker: 'A', voice: 'david', text: "But the detail depends on the conditions the crystal meets as it falls. At around minus two degrees, thin flat plates tend to form. At around minus fifteen degrees, the crystal grows the delicate, feathery branches known as dendrites, which is the classic star shape we see on greeting cards." },
          { speaker: 'A', voice: 'david', text: "It's often said that no two snowflakes are alike. In practice, this is because each crystal follows its own path through the cloud, meeting slightly different temperatures and humidity along the way, so its growth is never exactly the same as that of its neighbours." },
          { speaker: 'A', voice: 'david', text: "Snowflakes were first photographed in eighteen eighty-five by a farmer from Vermont, Wilson Bentley, who attached a camera to a microscope. Over his lifetime he took images of more than five thousand crystals, and his photographs are still used by scientists today." },
          { speaker: 'A', voice: 'david', text: "Once on the ground, fresh snow is surprisingly light. About ninety per cent of its volume is air, and this trapped air is what makes snow such good insulation. Small animals such as mice and voles survive the winter by living in tunnels beneath the snow, where it is much warmer than on the surface." },
          { speaker: 'A', voice: 'david', text: "The air in snow also absorbs sound, which is why a snowfall seems to make the world quiet." },
          { speaker: 'A', voice: 'david', text: "Finally, forecasting snow is notoriously difficult. A difference of a single degree in the temperature of the air can turn what should be a heavy snowfall into rain, and forecasters often have to revise their predictions at the last minute." },
        ],
        questionGroups: [
          {
            id: 't5-l4-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Snowflakes</strong></p><p><em>Formation</em><br/>• a water droplet freezes around a speck of {{q31}}<br/>• water molecules form a pattern with {{q32}} sides</p><p><em>Shapes</em><br/>• at around minus {{q33}} degrees, feathery {{q34}} grow<br/>• no two crystals are alike because each follows its own {{q35}} through the cloud</p><p><em>Photography</em><br/>• Wilson Bentley attached a camera to a {{q36}}<br/>• he photographed more than {{q37}} crystals</p><p><em>On the ground</em><br/>• fresh snow is about 90% {{q38}}, so it provides good {{q39}} for small animals<br/>• forecasting is difficult: a difference of {{q40}} can turn snow to rain</p>',
            questions: [
              q(31, null, ['dust'], '"freezes around a speck of dust".'),
              q(32, null, ['six', '6'], '"a pattern with six sides".'),
              q(33, null, ['15', 'fifteen'], '"around minus fifteen degrees".'),
              q(34, null, ['dendrites', 'branches'], '"feathery branches known as dendrites".'),
              q(35, null, ['path'], '"its own path through the cloud".'),
              q(36, null, ['microscope'], '"attached a camera to a microscope".'),
              q(37, null, ['5000', '5,000', 'five thousand'], '"more than five thousand crystals".'),
              q(38, null, ['air'], '"About ninety per cent of its volume is air".'),
              q(39, null, ['insulation'], '"makes snow such good insulation".'),
              q(40, null, ['1 degree', 'one degree', 'a single degree', 'single degree'], '"A difference of a single degree".'),
            ],
          },
        ],
      },
    ],
  },

  writing: {
    durationSec: 3600,
    task1: {
      order: 1,
      minWords: 150,
      recommendedMin: 20,
      promptHtml:
        '<p>The chart below shows the average number of hours of homework done per week by students aged 12 and 16 in four countries.</p><p>Summarise the information by selecting and reporting the main features, and make comparisons where relevant.</p>',
      chart: {
        chartType: 'bar',
        title: 'Hours of homework per week, by age and country',
        unit: 'hours',
        categories: ['Finland', 'Japan', 'Spain', 'Canada'],
        xAxisLabel: 'Country',
        yAxisLabel: 'Hours per week',
        series: [
          { name: 'Age 12', data: [2.8, 4.1, 6.5, 4.6] },
          { name: 'Age 16', data: [4.2, 6.4, 7.9, 6.0] },
        ],
      },
    },
    task2: {
      order: 2,
      minWords: 250,
      recommendedMin: 40,
      promptHtml:
        '<p>Some people believe that every child should learn to play a musical instrument at school. Others think that school time should be spent on academic subjects only.</p><p>Discuss both views and give your own opinion.</p>',
    },
  },
};
