// Original IELTS-style practice content (NOT copied or paraphrased from any real
// Cambridge/IELTS book). Only the exam STRUCTURE follows a standard Academic test
// layout; every topic, passage, transcript, question and answer is written from scratch.
import { table, TFNG_INSTRUCTION, YNNG_INSTRUCTION, q, paras, mc, bank } from './_html.mjs';

export default {
  slug: 'vocably-practice-test-11',
  title: 'Vocably Practice Test 11',
  difficulty: 'medium',

  reading: {
    durationSec: 3600,
    passages: [
      {
        order: 1,
        title: 'Wolves at the door',
        subtitle: 'Read the text and answer questions 1-13.',
        paragraphs: paras(
          ['A', `For several centuries, the wolf was the most hated animal in Europe. It was blamed for killing livestock, it appeared as a villain in folk tales, and it was hunted relentlessly with traps, poison and guns. By the middle of the twentieth century, wolves had been wiped out in most of Western Europe, surviving only in a few remote mountain regions. Today, the picture has changed dramatically. Wolf populations have recovered across the continent, and there are now an estimated twenty thousand of them, including some that have settled within a few kilometres of large cities. Their return is one of the most striking conservation stories of recent decades, and one of the most controversial.`],
          ['B', `Several factors explain the recovery. The first is legal protection: an international agreement signed in 1979 obliged many European countries to protect wolves, and hunting was gradually restricted or banned. The second is a change in the countryside. As people moved from villages to cities, farmland in mountain and rural regions was abandoned, and forests grew back, providing shelter for wolves and for the deer and wild boar on which they feed. The third is the animal's own ability to travel. Young wolves leaving their family pack may walk several hundred kilometres to find a territory of their own, and one animal is known to have covered more than a thousand kilometres, crossing motorways and rivers on the way.`],
          ['C', `Ecologists have watched the return with great interest, partly because of what happened in the United States. When wolves were reintroduced to Yellowstone National Park in 1995, after an absence of seventy years, the number of elk fell and their behaviour changed, since they avoided open valleys where wolves could hunt them. Some scientists argued that this allowed willows and other trees along the rivers to recover, which in turn benefited beavers, birds and fish. Other researchers think this account is too simple, and that the effects of the wolves have been exaggerated; scientists still disagree about how much of the change was caused by them. What is agreed is that carcasses left by wolves provide food for scavengers such as ravens, eagles and bears, which do not always find enough in winter.`],
          ['D', `For farmers, the wolf's return is a problem. A pack can kill many sheep in a single night, and the loss of a prized animal is distressing as well as costly. Across Europe, wolves are responsible for thousands of attacks on livestock each year, and in some regions the number is rising. Yet in most countries, wolves account for only a small share of all livestock deaths; disease, accidents and attacks by dogs cause far more. The difficulty is that wolf losses are concentrated in a few places, where the farmers affected may lose a large part of their flock. Governments in many countries pay compensation for animals killed by wolves, but payments are often slow, and farmers complain that they do not cover the time and stress involved.`],
          ['E', `Fortunately, there are ways to protect flocks. One of the most effective is the guard dog, of a breed raised among the sheep from puppyhood so that it regards the flock as its family and defends it against intruders. Electric fences, at least 1.2 metres high and with the lowest wire close to the ground, prevent wolves from crawling underneath. Shepherds who keep their animals in a pen overnight, when most attacks occur, have fewer losses than those who leave them in open fields. Trials in several countries have found that a combination of such methods can reduce attacks substantially, although the equipment is expensive, and in regions with steep, rocky terrain, it may be impractical to fence large areas.`],
          ['F', `Attitudes towards wolves depend strongly on where people live. Surveys show that people in cities, who rarely meet wolves, tend to be more supportive than those in rural areas, where the animals are a daily concern. Some governments and farming organisations have therefore proposed that a limited, controlled cull should be permitted in areas where the damage is greatest, arguing that it would reduce conflict and build local tolerance. Conservationists reply that killing wolves may break up packs, and so increase attacks on livestock, and that it would set back a recovery that has taken decades. The debate is likely to continue, since it reflects a deeper question: whether people are prepared to share their landscape with a large predator.`]
        ),
        questionGroups: [
          {
            id: 't11-r1-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              q(1, 'By the middle of the twentieth century, wolves had been wiped out in most of Western Europe.', 'TRUE', 'Paragraph A: "wiped out in most of Western Europe".', 'A'),
              q(2, 'Young wolves never travel more than fifty kilometres from their birthplace.', 'FALSE', 'Paragraph B: "several hundred kilometres".', 'B'),
              q(3, 'An international agreement protecting wolves was signed in 1979.', 'TRUE', 'Paragraph B: "an international agreement signed in 1979".', 'B'),
              q(4, 'Scientists agree on all the ecological effects of the wolves at Yellowstone.', 'FALSE', 'Paragraph C: "scientists still disagree about how much of the change was caused by them".', 'C'),
              q(5, 'Scavengers such as ravens benefit from animals killed by wolves.', 'TRUE', 'Paragraph C: "carcasses left by wolves provide food for scavengers".', 'C'),
              q(6, 'Wolves are the main cause of livestock deaths in most European countries.', 'FALSE', 'Paragraph D: "wolves account for only a small share".', 'D'),
              q(7, 'Farmers who use guard dogs spend less time looking after their flocks.', 'NOT GIVEN', 'The time farmers spend is not discussed.', 'E'),
            ],
          },
          {
            id: 't11-r1-table',
            type: 'table_completion',
            instructionHtml: 'Complete the table below. Choose <strong>ONE WORD AND/OR A NUMBER</strong> from the passage for each answer.',
            wordLimit: { maxWords: 1, maxNumbers: 1, label: 'ONE WORD AND/OR A NUMBER' },
            stemHtml: table(
              ['Topic', 'Details'],
              [
                ['Guard dogs', 'raised among sheep so that the flock is seen as its {{q8}}'],
                ['Electric fences', 'at least {{q9}} metres high'],
                ['Night protection', 'animals kept in a {{q10}} overnight'],
                ['Compensation', 'paid by governments, but often {{q11}}'],
                ['Attitudes', 'people in {{q12}} areas tend to be more supportive'],
                ['Proposed measure', 'a limited, controlled {{q13}} where damage is greatest'],
              ]
            ),
            questions: [
              q(8, null, ['family'], 'Paragraph E: "regards the flock as its family".', 'E'),
              q(9, null, ['1.2'], 'Paragraph E: "at least 1.2 metres high".', 'E'),
              q(10, null, ['pen'], 'Paragraph E: "in a pen overnight".', 'E'),
              q(11, null, ['slow'], 'Paragraph D: "payments are often slow".', 'D'),
              q(12, null, ['urban', 'city', 'cities'], 'Paragraph F: "people in cities ... more supportive".', 'F'),
              q(13, null, ['cull'], 'Paragraph F: "a limited, controlled cull".', 'F'),
            ],
          },
        ],
      },
      {
        order: 2,
        title: 'The language of colour',
        subtitle: 'Read the text and answer questions 14-26.',
        paragraphs: paras(
          ['A', `In the Greek epic poems composed nearly three thousand years ago, the sea is described as wine-dark, honey is green, and the sky is never called blue. In 1858, the British statesman William Gladstone, who was also a scholar of Homer, noticed this oddity and suggested that the ancient Greeks may not have been able to see the colour blue at all. The idea does not survive scrutiny, since there is no evidence that human eyes have changed in the past few thousand years, but it raised a question that has fascinated scientists ever since: do the words we use affect the way we see colour?`],
          ['B', `In 1969, two researchers at a university in California, Brent Berlin and Paul Kay, put forward a bold claim. After studying the colour words in about twenty languages, they argued that the basic colour terms of the world's languages appear in a fixed order. A language with only two terms will have words for dark and light, roughly black and white. A language with three will add red. The next to appear are green and yellow, then blue, and later, brown, purple, pink, orange and grey. The pattern suggested that colour vocabulary is shaped by universal features of human perception rather than by chance, and the study became one of the most widely discussed in the history of linguistics.`],
          ['C', `Berlin and Kay's work has been criticised on several grounds. Their sample was small, and many of the speakers they consulted were living in California, and therefore familiar with English. Some later researchers argued that the method of asking people to choose the best example of each colour from a chart of carefully prepared samples took it for granted that every language treats colour as a series of separate categories, when in some it may not. Others have pointed out that the real world contains few colours in isolation, and that the words people use depend on what they are describing: a language may have one word for the colour of ripe fruit and another for the colour of dry grass. Most researchers today accept that culture plays a part in how colour categories are formed, although few doubt that biology sets limits.`],
          ['D', `Some of the most interesting evidence comes from the Himba, a people of north-western Namibia. Their language groups green and blue under a single term, but has several different words for shades of green that English speakers would not distinguish. In one experiment, Himba participants were shown a ring of twelve squares, eleven of which were the same shade of green and one slightly different. They found the odd one out more quickly than English speakers did, but they were slower to find a square of blue among the greens. Having a word for a distinction, it seems, makes the distinction easier to notice.`],
          ['E', `A similar effect has been found among speakers of Russian, which has two basic words for blue: a light blue and a dark blue, which Russians treat as different colours, just as English speakers treat pink and red. In tests, Russian speakers were faster than English speakers at telling apart two shades of blue that fell on opposite sides of the boundary between the two words. Significantly, the advantage disappeared when the participants were asked to repeat a string of numbers while they performed the task, which occupied the part of the brain that handles language. This suggests that the words were being used in the act of perception, even though the subjects were not aware of it.`],
          ['F', `Why do languages add colour terms at all? One explanation links the growth of colour vocabulary to technology. In societies that do not make dyes and pigments, there is little need to name a colour separately from the thing it describes; the question "what colour is it?" becomes important only when objects differ in nothing else. The ancient Egyptians, who were the first to produce a blue pigment, were also the first known culture to have a word for blue, a coincidence that supports this view. As societies become more industrial and trade more in manufactured goods, the number of colour words tends to grow.`],
          ['G', `The current consensus, therefore, is somewhere between two extremes. Language does not determine what we can see: speakers of every language can distinguish an enormous number of colours, and can learn new words for them with little difficulty. But it does seem to influence how quickly we sort colours into groups and how easily we remember them. The Greek sea may not have been wine-dark because the Greeks could not see blue, but because their vocabulary offered them a different way of describing what they saw.`]
        ),
        questionGroups: [
          {
            id: 't11-r2-matchinfo',
            type: 'matching_information',
            instructionHtml: 'Reading Passage 2 has seven paragraphs, A-G. Which paragraph contains the following information? <em>Choose the correct letter, A-G.</em><br/><strong>NB</strong> You may use any letter more than once.',
            bankReusable: true,
            questions: [
              q(14, 'a reference to an unusual description of the sea in ancient literature', 'A', 'Paragraph A: "the sea is described as wine-dark".', 'A'),
              q(15, 'a claim about the order in which colour words appear in languages', 'B', 'Paragraph B: "appear in a fixed order".', 'B'),
              q(16, 'a criticism of the people who took part in an early study', 'C', 'Paragraph C: "many of the speakers they consulted were living in California".', 'C'),
              q(17, 'a people whose language groups two colours together but which can distinguish shades of another', 'D', 'Paragraph D: the Himba group green and blue but distinguish shades of green.', 'D'),
              q(18, 'an experiment in which a spoken task removed an advantage', 'E', 'Paragraph E: "the advantage disappeared when the participants were asked to repeat a string of numbers".', 'E'),
              q(19, 'an explanation for why one colour was named early in an ancient culture', 'F', 'Paragraph F: Egyptians produced blue pigment and were first to name blue.', 'F'),
            ],
          },
          {
            id: 't11-r2-ynng',
            type: 'yes_no_notgiven',
            instructionHtml: YNNG_INSTRUCTION,
            questions: [
              q(20, 'Gladstone\'s idea that the ancient Greeks could not see blue is now widely accepted.', 'NO', 'Paragraph A: "The idea does not survive scrutiny".', 'A'),
              q(21, 'Berlin and Kay\'s findings have been confirmed in every later study.', 'NO', 'Paragraph C lists several criticisms.', 'C'),
              q(22, 'Culture can influence how colour categories are formed.', 'YES', 'Paragraph C: "culture plays a part in how colour categories are formed".', 'C'),
              q(23, 'Himba speakers are unable to tell the difference between blue and green.', 'NO', 'Paragraph D: they were slower at finding blue among greens, not unable.', 'D'),
              q(24, 'The Russian speakers\' advantage in distinguishing blues disappeared when they carried out a verbal task at the same time.', 'YES', 'Paragraph E: "the advantage disappeared".', 'E'),
              q(25, 'All languages will eventually have the same number of colour terms.', 'NOT GIVEN', 'The writer makes no such prediction.'),
              q(26, 'Language has no effect at all on how people sort colours.', 'NO', 'Paragraph G: "it does seem to influence how quickly we sort colours into groups".', 'G'),
            ],
          },
        ],
      },
      {
        order: 3,
        title: 'Inventing the weekend',
        subtitle: 'Read the text and answer questions 27-40.',
        paragraphs: paras(
          ['A', `For most of human history, there was no such thing as the weekend. Farmers worked when the weather and the seasons demanded, resting on religious festivals and, in Christian countries, on Sundays. The idea that an entire population should have a regular two-day break from work is barely a century old, and its arrival is a story of religion, business and politics, in which the people who benefited most were often not the ones who first proposed it.`],
          ['B', `The Industrial Revolution made regular working hours necessary. Factory owners needed their machines to run for as long as possible, and in the early nineteenth century, many employees in British mills worked twelve hours a day, six days a week. Workers, however, had their own customs. In many towns, skilled craftsmen made a habit of taking Monday off, to recover from the excesses of the weekend, a practice known as Saint Monday. Employers disliked it, but it was so widespread that for decades they could not stamp it out.`],
          ['C', `A compromise emerged in the middle of the century. Some mill owners came to believe that workers who had Saturday afternoon free would be healthier and work harder on other days, and that they would be less likely to take the whole of Monday off. The Saturday half-holiday spread from the north of England to other industries, and was quickly taken up by football and cricket clubs, which found that they now had crowds of spectators on a day when they had previously had none. The half-holiday, in other words, created a new leisure industry.`],
          ['D', `Religion complicated matters. In the United States, many immigrant communities observed a day of rest on Saturday rather than Sunday, and employers who wished to keep these workers had to accommodate them. According to most historians, the first factory to adopt a five-day week, in a New England cotton mill in 1908, did so to give Jewish employees a day off on their sabbath without losing the Sunday holiday observed by everyone else. The result was a two-day break, and the idea began to attract attention.`],
          ['E', `It was a motor manufacturer, Henry Ford, who made the five-day week famous. In 1926, he announced that his factories would close on Saturdays as well as Sundays, reducing the working week to forty hours without cutting wages. Ford was not acting out of generosity. He believed that if workers had more free time, they would want to spend money on leisure, including, he hoped, driving cars, and that an economy in which ordinary people had both money and time would be a better market for his products. Output, he claimed, did not fall, because workers were more alert.`],
          ['F', `The Great Depression of the 1930s gave the idea political support. With millions unemployed, governments and unions argued that shorter hours would spread the available work among more people. In 1938, the United States passed a law that set a maximum standard week, and by 1940, it had fallen to forty hours, with extra pay for anyone working more. Other industrial countries followed in the decades after the Second World War, and the two-day weekend became normal across much of the world.`],
          ['G', `Not all experiments were successful. In 1929, the Soviet Union introduced a continuous week, in which workers had a day off in rotation, so that factories never stopped. It was intended to increase production and discourage religious observance, but it broke up families, since relatives often had different days off, and damaged machinery that was never given a rest. It was abandoned after about a decade. France took a different path in 2000, when it reduced the legal working week to thirty-five hours, in the hope of creating more jobs. The results were mixed, and later governments relaxed the rules.`],
          ['H', `Today, a new experiment is under way. Dozens of companies in several countries have tested a four-day week, in which staff are paid the same for fewer hours. Researchers who monitored the trials reported that productivity generally did not fall and that employees reported less stress and better health; most of the companies chose to continue. Critics point out that the trials were voluntary, so that the firms that took part may have been those most likely to succeed, and that not every kind of job, from nursing to manufacturing, can be compressed into fewer days. The shape of the working week, it seems, is still being invented.`]
        ),
        questionGroups: [
          {
            id: 't11-r3-headings',
            type: 'matching_headings',
            instructionHtml: 'Reading Passage 3 has eight paragraphs, A-H. Choose the correct heading for paragraphs B-H from the list of headings below.<br/><em>Example: Paragraph A — ix</em>',
            bank: [
              { key: 'i', text: 'A religious reason for a two-day break' },
              { key: 'ii', text: 'An employer who linked free time to spending' },
              { key: 'iii', text: 'Informal habits that employers could not remove' },
              { key: 'iv', text: 'Hopes that shorter hours would create jobs' },
              { key: 'v', text: 'Sport and a new pattern of leisure' },
              { key: 'vi', text: 'Two attempts by governments that did not last' },
              { key: 'vii', text: 'Trials of a further reduction in hours' },
              { key: 'viii', text: 'The decline of religious observance' },
              { key: 'ix', text: 'A recent idea with a complicated history' },
              { key: 'x', text: 'The effect of unemployment on working time' },
            ],
            questions: [
              q(27, 'Paragraph B', 'iii', 'Paragraph B: Saint Monday, which "they could not stamp out".', 'B'),
              q(28, 'Paragraph C', 'v', 'Paragraph C: half-holiday and football and cricket clubs.', 'C'),
              q(29, 'Paragraph D', 'i', 'Paragraph D: a New England mill gave Jewish employees a day off.', 'D'),
              q(30, 'Paragraph E', 'ii', 'Paragraph E: Ford hoped workers with free time would spend money.', 'E'),
              q(31, 'Paragraph F', 'x', 'Paragraph F: "With millions unemployed ... shorter hours would spread the available work".', 'F'),
              q(32, 'Paragraph G', 'vi', 'Paragraph G: the Soviet continuous week and the French 35-hour week.', 'G'),
              q(33, 'Paragraph H', 'vii', 'Paragraph H: trials of a four-day week.', 'H'),
            ],
          },
          {
            id: 't11-r3-classify',
            type: 'matching_features',
            instructionHtml: 'Look at the following statements (Questions 34-40) and the list of people and organisations below. Match each statement with the correct one, <strong>A-E</strong>.<br/>You may use any letter more than once.',
            bankReusable: true,
            bank: [
              { key: 'A', text: 'mill owners in Britain' },
              { key: 'B', text: 'Henry Ford' },
              { key: 'C', text: 'the Soviet government' },
              { key: 'D', text: 'the French government' },
              { key: 'E', text: 'researchers monitoring four-day-week trials' },
            ],
            questions: [
              q(34, 'argued that workers with free time would buy more products', 'B', 'Paragraph E: workers "would want to spend money on leisure".', 'E'),
              q(35, 'introduced a week in which workers had their days off in rotation', 'C', 'Paragraph G: "a continuous week, in which workers had a day off in rotation".', 'G'),
              q(36, 'reduced the legal working week to thirty-five hours', 'D', 'Paragraph G: "reduced the legal working week to thirty-five hours".', 'G'),
              q(37, 'reported that productivity generally did not fall', 'E', 'Paragraph H: "productivity generally did not fall".', 'H'),
              q(38, 'believed that a free Saturday afternoon would make employees healthier', 'A', 'Paragraph C: "workers who had Saturday afternoon free would be healthier".', 'C'),
              q(39, 'reduced the working week to forty hours without cutting wages', 'B', 'Paragraph E: "forty hours without cutting wages".', 'E'),
              q(40, 'abandoned an experiment after about ten years', 'C', 'Paragraph G: "abandoned after about a decade".', 'G'),
            ],
          },
        ],
      },
    ],
  },

  listening: {
    durationSec: 1800,
    checkTimeSec: 120,
    parts: [
      {
        order: 1,
        contextText: 'You will hear a student phoning a university accommodation office to ask about a room.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "University Accommodation Office, good morning." },
          { speaker: 'B', voice: 'david', text: "Good morning. I'm starting a master's course in September, and I'm looking for a room in a hall of residence." },
          { speaker: 'A', voice: 'zira', text: "Of course. Could I take your name?" },
          { speaker: 'B', voice: 'david', text: "It's Tomas Reyes. Tomas is spelled without an accent, T-O-M-A-S, and Reyes is R-E-Y-E-S." },
          { speaker: 'A', voice: 'zira', text: "And which course are you taking?" },
          { speaker: 'B', voice: 'david', text: "Environmental engineering, and I'll be here for one year." },
          { speaker: 'A', voice: 'zira', text: "Right. We have three halls. Linden Court is a twenty-minute walk from the campus and has single rooms with shared bathrooms, at a hundred and twenty pounds a week. Kingsley House is closer, about five minutes away, but more expensive, at a hundred and fifty, and every room has its own bathroom." },
          { speaker: 'B', voice: 'david', text: "And the third?" },
          { speaker: 'A', voice: 'zira', text: "Bramwell Hall, which is for postgraduates only. It's the quietest and has a large kitchen, but it's a bus ride from campus. The price is a hundred and thirty-five pounds a week." },
          { speaker: 'B', voice: 'david', text: "I'd like a quiet place, since I'll be studying a lot, but I don't want a long journey. Kingsley House sounds best, even though it's the most expensive." },
          { speaker: 'A', voice: 'zira', text: "It has some advantages. Internet is included in the rent, and there's a laundry room in the basement. Meals are not provided, but each floor has a shared kitchen." },
          { speaker: 'B', voice: 'david', text: "That's fine. Can I get a room from the first of September?" },
          { speaker: 'A', voice: 'zira', text: "The contract starts on the twenty-eighth of August, and lasts for fifty-one weeks. We need a deposit of two hundred pounds, which is returned at the end if there's no damage." },
          { speaker: 'B', voice: 'david', text: "I see. Is there a bike store?" },
          { speaker: 'A', voice: 'zira', text: "Yes, it's locked, and you'll need your student card to get in. Now, I'll need an address to send the contract to." },
          { speaker: 'B', voice: 'david', text: "It's sixty-three Mill Road, Leeds." },
          { speaker: 'A', voice: 'zira', text: "Thank you. You should receive it within a week. Please sign it and return it within fourteen days, or the room will be offered to someone else." },
        ],
        questionGroups: [
          {
            id: 't11-l1-form',
            type: 'form_completion',
            instructionHtml: 'Complete the form below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['University Accommodation: Enquiry', ''],
              [
                ['Surname', '{{q1}}'],
                ['Course', '{{q2}} engineering'],
                ['Length of stay', '{{q3}} year'],
                ['Hall chosen', '{{q4}} House'],
                ['Rent per week', '£{{q5}}'],
                ['Included in rent', '{{q6}}'],
                ['Contract starts on', '{{q7}} August'],
                ['Deposit', '£{{q8}}'],
                ['Access to bike store needs', 'student {{q9}}'],
                ['Contract must be returned within', '{{q10}} days'],
              ]
            ),
            questions: [
              q(1, null, ['reyes'], 'Spelled out: R-E-Y-E-S.'),
              q(2, null, ['environmental'], '"Environmental engineering".'),
              q(3, null, ['1', 'one'], '"I\'ll be here for one year."'),
              q(4, null, ['kingsley'], '"Kingsley House sounds best".'),
              q(5, null, ['150', 'a hundred and fifty', 'one hundred and fifty'], '"a hundred and fifty".'),
              q(6, null, ['internet', 'the internet'], '"Internet is included in the rent".'),
              q(7, null, ['28', 'twenty-eighth', '28th', 'twenty eighth'], '"The contract starts on the twenty-eighth of August".'),
              q(8, null, ['200', 'two hundred'], '"a deposit of two hundred pounds".'),
              q(9, null, ['card', 'card.'], '"you\'ll need your student card".'),
              q(10, null, ['14', 'fourteen'], '"within fourteen days".'),
            ],
          },
        ],
      },
      {
        order: 2,
        contextText: 'You will hear a radio presenter talking about a new walking festival.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Now for some news that should please anyone who enjoys the outdoors. Next month, the town of Halstead is holding its first walking festival, and I've been speaking to the organiser, Julie Brennan, to find out what's planned." },
          { speaker: 'A', voice: 'zira', text: "The festival runs for nine days, starting on the second of June. The idea came from a group of local walkers who noticed how many visitors came to the area for the hills, but then left without spending anything in the town. The festival is designed to change that." },
          { speaker: 'A', voice: 'zira', text: "There will be over forty guided walks, led by volunteers who know the area. They vary from gentle strolls of three or four kilometres, suitable for families, to demanding hill walks of more than twenty. Each one is graded from easy to hard, so you can choose one to suit your fitness." },
          { speaker: 'A', voice: 'zira', text: "Some walks have special themes. One looks at the wildlife of the river valley, with an expert on birds. Another follows the route of an old railway that once carried stone from the quarries, and a third is a night walk, for looking at the stars, using a telescope provided by the local astronomy club." },
          { speaker: 'A', voice: 'zira', text: "Booking is essential for all the walks, as numbers are limited to twenty people per guide. Tickets cost five pounds each, apart from the family walks, which are free. The night walk is more expensive, at eight pounds, because of the equipment." },
          { speaker: 'A', voice: 'zira', text: "You can book online, or in person at the tourist information office in the market square. Julie told me that more than half of the tickets have already been sold, so it's worth acting quickly." },
          { speaker: 'A', voice: 'zira', text: "As well as walks, there'll be a programme of evening events: talks by authors of walking guides, an exhibition of photographs of the hills by a local photographer, and a concert on the final night in the church, with music by a choir from the town." },
          { speaker: 'A', voice: 'zira', text: "Local businesses have been very supportive. Cafés and pubs are offering special menus for walkers, and several hotels have cut their prices for festival week. There's even a shuttle bus which will take walkers to the start of the longer routes, so you don't need a car." },
          { speaker: 'A', voice: 'zira', text: "If the festival is a success, it will become an annual event, and Julie hopes that in future years, there will be walks in other languages to attract visitors from abroad. So, if you fancy stretching your legs, now's your chance." },
        ],
        questionGroups: [
          {
            id: 't11-l2-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(11, 'Why was the festival created?', ['to attract more visitors to spend money in the town', 'to raise money for a charity', 'to celebrate the town\'s history'], 'A', '"visitors ... left without spending anything in the town. The festival is designed to change that."'),
              mc(12, 'The festival starts on', ['2 June', '9 June', '12 June'], 'A', '"starting on the second of June".'),
              mc(13, 'The walks are', ['all the same length', 'graded from easy to hard', 'led by professional guides'], 'B', '"graded from easy to hard".'),
              mc(14, 'How many people can join each walk?', ['ten', 'twenty', 'forty'], 'B', '"twenty people per guide".'),
              mc(15, 'What has happened to tickets?', ['Only a few have been sold.', 'More than half have been sold.', 'All have been sold.'], 'B', '"more than half of the tickets have already been sold".'),
            ],
          },
          {
            id: 't11-l2-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Halstead Walking Festival</strong></p><p>• over {{q16}} guided walks led by volunteers<br/>• themed walks: river valley {{q17}}, an old {{q18}} route and a night walk with a telescope<br/>• ticket price: £5; the night walk costs £{{q19}}<br/>• tickets available online or at the tourist information office in the {{q20}}</p>',
            questions: [
              q(16, null, ['40', 'forty'], '"over forty guided walks".'),
              q(17, null, ['wildlife'], '"the wildlife of the river valley".'),
              q(18, null, ['railway'], '"the route of an old railway".'),
              q(19, null, ['8', 'eight'], '"at eight pounds".'),
              q(20, null, ['market square'], '"in the market square".'),
            ],
          },
        ],
      },
      {
        order: 3,
        contextText: 'You will hear two marine biology students, Jess and Ali, rehearsing a presentation with their tutor.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david2', text: "Thanks for showing me your presentation on deep-sea exploration. Overall, it was very good, but I have some suggestions. Jess, your opening slide was excellent, with the photograph of the submarine." },
          { speaker: 'B', voice: 'zira', text: "Thank you. We wanted to start with something striking." },
          { speaker: 'A', voice: 'david2', text: "It worked. But the second slide, which shows the history of exploration, has far too much text. Audiences can't read and listen at the same time. I'd suggest a simple timeline instead." },
          { speaker: 'C', voice: 'david', text: "That's fair. I'll redo it with dates and pictures only." },
          { speaker: 'A', voice: 'david2', text: "Good. Ali, you spoke for about four minutes on the pressure problem. I found it clear, but you read from your notes too often, so you lost contact with the audience." },
          { speaker: 'C', voice: 'david', text: "I get nervous, so I hold on to them." },
          { speaker: 'A', voice: 'david2', text: "Then try keeping only a few key words on small cards. The more you look up, the more confident you'll seem." },
          { speaker: 'B', voice: 'zira', text: "What about the video of the anglerfish? I wasn't sure whether to include it." },
          { speaker: 'A', voice: 'david2', text: "Keep it, but shorten it. Thirty seconds is plenty. It's fascinating, but if it's too long, people start to lose interest in what you're saying." },
          { speaker: 'B', voice: 'zira', text: "OK. And our conclusion?" },
          { speaker: 'A', voice: 'david2', text: "That was the weakest part. You simply repeated your earlier points. A conclusion should answer the question you posed at the start, and leave the audience with something to think about." },
          { speaker: 'C', voice: 'david', text: "Perhaps we could finish by asking whether it's right to spend money on exploring the deep sea when there are problems on land?" },
          { speaker: 'A', voice: 'david2', text: "That would be much better. It invites discussion, and you can move on to the questions." },
          { speaker: 'B', voice: 'zira', text: "How long do we have?" },
          { speaker: 'A', voice: 'david2', text: "Fifteen minutes in total, with five for questions. At the moment, you're running to about eighteen, so you'll need to cut. I'd suggest removing the section on the submarine's design, which isn't central to your argument." },
          { speaker: 'C', voice: 'david', text: "We'll do that. Thank you very much." },
        ],
        questionGroups: [
          {
            id: 't11-l3-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(21, 'What did the tutor like about the first slide?', ['the photograph', 'the amount of text', 'the title'], 'A', '"your opening slide was excellent, with the photograph of the submarine".'),
              mc(22, 'The tutor suggests replacing the history slide with', ['a timeline', 'a map', 'a video'], 'A', '"I\'d suggest a simple timeline instead".'),
              mc(23, 'What is Ali\'s problem during the presentation?', ['He speaks too quietly.', 'He reads from his notes too often.', 'He speaks too fast.'], 'B', '"you read from your notes too often".'),
              mc(24, 'The tutor advises Ali to', ['use small cards with key words', 'learn the talk by heart', 'use fewer slides'], 'A', '"keeping only a few key words on small cards".'),
              mc(25, 'How long should the anglerfish video be?', ['thirty seconds', 'one minute', 'two minutes'], 'A', '"Thirty seconds is plenty."'),
            ],
          },
          {
            id: 't11-l3-match',
            type: 'matching_features',
            instructionHtml: 'What does the tutor say about each part of the presentation? Choose <strong>FIVE</strong> answers from the box and write the correct letter, A-G, next to Questions 26-30.',
            bank: [
              { key: 'A', text: 'It is excellent.' },
              { key: 'B', text: 'It contains too much text.' },
              { key: 'C', text: 'It is too long.' },
              { key: 'D', text: 'It should be shortened.' },
              { key: 'E', text: 'It needs a different ending.' },
              { key: 'F', text: 'It should be removed.' },
              { key: 'G', text: 'It is too complicated.' },
            ],
            questions: [
              q(26, 'opening slide', 'A', '"Your opening slide was excellent".'),
              q(27, 'history slide', 'B', '"far too much text".'),
              q(28, 'anglerfish video', 'D', '"Keep it, but shorten it."'),
              q(29, 'conclusion', 'E', '"The weakest part ... You simply repeated your earlier points."'),
              q(30, 'section on the submarine\'s design', 'F', '"I\'d suggest removing the section on the submarine\'s design".'),
            ],
          },
        ],
      },
      {
        order: 4,
        contextText: 'You will hear part of a lecture about spider silk.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Spiders are among the most skilful builders in nature, and their silk is among the most remarkable materials ever studied. Today I want to look at how it is made, and why engineers are so interested in it." },
          { speaker: 'A', voice: 'david', text: "Spider silk is a protein, produced in glands in the spider's abdomen. The liquid silk is stored in the gland in a form that is dissolved in water, and as it passes through a narrow duct towards the spinnerets, the protein molecules line up and the silk hardens into a solid thread. Spiders do this without heat or toxic chemicals, and all of it happens at normal temperature." },
          { speaker: 'A', voice: 'david', text: "An individual spider can make up to seven types of silk, each with its own purpose. One type, used for the frame and the spokes of a web and for the lifeline that a spider trails behind it, is exceptionally strong. Another, used for the spiral that catches the prey, is very stretchy and coated with glue. A third is used to wrap prey, and a fourth to make the protective case for eggs." },
          { speaker: 'A', voice: 'david', text: "The strongest silks are, weight for weight, stronger than steel, and they can stretch to several times their original length before breaking. This combination of strength and elasticity makes them extremely tough. A web made of threads as thick as a pencil could, in theory, stop a passenger aircraft in flight." },
          { speaker: 'A', voice: 'david', text: "Naturally, scientists would like to use silk in products. Possible uses include surgical stitches that are absorbed by the body, artificial tendons and ligaments, bulletproof vests and lightweight ropes. The difficulty is production. Spiders cannot be farmed like silkworms, because they are territorial and they eat each other." },
          { speaker: 'A', voice: 'david', text: "Researchers have therefore turned to genetic engineering. Genes for spider silk have been transferred to bacteria, yeast, plants and even goats, which produce the protein in their milk. The silk protein can then be purified and spun into thread. The results so far have been weaker than natural silk, because it is hard to reproduce the precise way in which spiders form it, but they are steadily improving." },
          { speaker: 'A', voice: 'david', text: "Some companies have already launched products, including a limited range of clothing made from silk-like fibre produced by fermentation. They remain expensive, but prices are expected to fall as production increases." },
          { speaker: 'A', voice: 'david', text: "In summary, spider silk shows how nature can achieve remarkable results with simple ingredients and gentle conditions, and it remains a major inspiration for the design of new materials." },
        ],
        questionGroups: [
          {
            id: 't11-l4-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS</strong> for each answer.',
            wordLimit: { maxWords: 2, label: 'NO MORE THAN TWO WORDS' },
            stemHtml: '<p><strong>Spider silk</strong></p><p><em>How it is made</em><br/>• a protein, produced in glands in the {{q31}}<br/>• stored dissolved in {{q32}}<br/>• as it passes through a narrow {{q33}}, the protein molecules line up and the silk hardens<br/>• no heat or {{q34}} chemicals needed</p><p><em>Types</em><br/>• up to {{q35}} types per spider<br/>• strong silk for frames, spokes and the {{q36}}<br/>• stretchy silk coated with {{q37}} catches prey</p><p><em>Uses and problems</em><br/>• possible uses: surgical stitches, artificial tendons, bulletproof {{q38}}<br/>• spiders cannot be farmed because they are {{q39}}<br/>• genes have been transferred to bacteria, plants and {{q40}}</p>',
            questions: [
              q(31, null, ['abdomen'], '"glands in the spider\'s abdomen".'),
              q(32, null, ['water'], '"dissolved in water".'),
              q(33, null, ['duct'], '"a narrow duct".'),
              q(34, null, ['toxic'], '"without heat or toxic chemicals".'),
              q(35, null, ['seven', '7'], '"up to seven types".'),
              q(36, null, ['lifeline'], '"the lifeline that a spider trails behind it".'),
              q(37, null, ['glue'], '"coated with glue".'),
              q(38, null, ['vests'], '"bulletproof vests".'),
              q(39, null, ['territorial'], '"they are territorial".'),
              q(40, null, ['goats'], '"even goats".'),
            ],
          },
        ],
      },
    ],
  },

  writing: {
    durationSec: 3600,
    task1: {
      order: 1,
      minWords: 150,
      recommendedMin: 20,
      promptHtml:
        '<p>The graph below shows the percentage of the population aged 65 and over in three countries between 1960 and 2020, with a projection for 2040.</p><p>Summarise the information by selecting and reporting the main features, and make comparisons where relevant.</p>',
      chart: {
        chartType: 'line',
        title: 'Population aged 65 and over (% of total)',
        unit: '%',
        categories: ['1960', '1980', '2000', '2020', '2040'],
        xAxisLabel: 'Year',
        yAxisLabel: 'Percentage of population',
        series: [
          { name: 'Japan', data: [5.7, 9.1, 17.4, 28.4, 35.3] },
          { name: 'Italy', data: [9.0, 13.1, 18.3, 23.3, 32.0] },
          { name: 'Mexico', data: [3.5, 4.0, 5.0, 7.6, 14.5] },
        ],
      },
    },
    task2: {
      order: 2,
      minWords: 250,
      recommendedMin: 40,
      promptHtml:
        '<p>Some people believe that the best way to reduce crime is to give longer prison sentences. Others think there are better ways to reduce crime.</p><p>Discuss both views and give your own opinion.</p>',
    },
  },
};
