// Original IELTS-style practice content (NOT copied or paraphrased from any real
// Cambridge/IELTS book). Only the exam STRUCTURE follows a standard Academic test
// layout; every topic, passage, transcript, question and answer is written from scratch.
import { table, TFNG_INSTRUCTION, q, paras, mc, bank } from './_html.mjs';

export default {
  slug: 'vocably-practice-test-10',
  title: 'Vocably Practice Test 10',
  difficulty: 'medium',

  reading: {
    durationSec: 3600,
    passages: [
      {
        order: 1,
        title: 'Seeing clearly: the story of spectacles',
        subtitle: 'Read the text and answer questions 1-13.',
        paragraphs: paras(
          ['A', `Most of us take spectacles for granted. We reach for them in the morning, push them up our noses without thinking and replace them every few years when our prescription changes. Roughly half of the adults in wealthy countries wear some form of corrective lens, and in many societies, a child who cannot see the blackboard is identified and helped within months. It is easy to forget how recently this became possible. For most of human history, anyone whose eyesight began to fail in middle age had no remedy at all, and a skilled scribe, engraver or weaver who could no longer see fine detail simply had to give up his craft, often at the height of his experience.`],
          ['B', `The first aid to reading was not the spectacle but the reading stone. In medieval monasteries, where monks spent their lives copying manuscripts, a polished lump of clear quartz or glass, rounded on one side, was placed directly on the page, where it magnified the letters beneath. The reading stone helped, but it was awkward to use, and it covered part of the text. Then, around 1286, in northern Italy, an unknown craftsman had the idea of mounting two lenses in frames, joined at the top by a rivet, which could be balanced on the nose. We do not know his name, but a preacher in Florence mentioned in a sermon in 1306 that spectacles had been invented less than twenty years before, and that he had met the man who made the first pair.`],
          ['C', `The earliest lenses were convex, thicker in the middle than at the edges, and were useful only for people who were long-sighted, which is to say, mainly those whose eyes had aged. Lenses for the short-sighted, which are concave, did not appear until the fifteenth century, and it was the invention of printing that encouraged them. As books became cheaper and more people learned to read, demand for spectacles rose sharply, and workshops in Venice, famous for their glassmaking, began to produce lenses in large numbers. Spectacles were sold by street pedlars, and customers chose them by trying on pair after pair until one seemed to work, a method which, for many people, remained the only one for several hundred years.`],
          ['D', `The design improved slowly. For centuries, spectacles were either held in front of the face or pinched onto the nose, and they fell off easily. In the 1720s, a London optician named Edward Scarlett developed rigid arms that extended over the ears, which made it possible to wear them all day. In the 1780s, the American statesman Benjamin Franklin, who was tired of constantly swapping between one pair for distance and another for reading, had the two lenses cut in half and combined in a single frame, producing the first bifocals. In the nineteenth century, doctors began to measure eyesight scientifically, using charts of letters of decreasing size, and prescriptions became far more precise.`],
          ['E', `In the twentieth century came contact lenses and, in the 1990s, laser surgery, which can reshape the front of the eye. Plastic has largely replaced glass in lenses, making them lighter and safer. Yet spectacles have not been displaced. They remain cheaper, carry no risk of infection, and can be changed as easily as a hat, and for many people, they have become a fashion accessory as much as a medical device.`],
          ['F', `The story is far from complete, however. The World Health Organization estimates that more than a billion people who need glasses do not have them, most of them in low-income countries where there are few eye specialists and where even a simple pair can cost more than a month's wages. The effect on children's schooling and adults' earnings is considerable: studies in several countries have found that workers given glasses become markedly more productive. Some organisations are now developing adjustable spectacles, in which the wearer changes the power of the lenses by adjusting a small syringe of fluid, and training local volunteers to carry out basic eye tests, in the hope that a technology that began in a medieval workshop may at last reach everyone who needs it.`]
        ),
        questionGroups: [
          {
            id: 't10-r1-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B, C or D</strong>.',
            questions: [
              mc(1, 'According to paragraph A, before spectacles were invented', ['children could not go to school', 'workers whose sight failed often had to give up skilled work', 'most people had excellent eyesight', 'doctors could treat poor sight with surgery'], 'B', 'Paragraph A: a scribe or weaver "simply had to give up his craft".', 'A'),
              mc(2, 'Reading stones were', ['lenses fixed in a frame', 'polished pieces of quartz or glass placed on the page', 'made only by unknown craftsmen', 'used by the short-sighted'], 'B', 'Paragraph B: "a polished lump of clear quartz or glass ... placed directly on the page".', 'B'),
              mc(3, 'The sermon of 1306 is mentioned as evidence that', ['spectacles were a very recent invention', 'spectacles were invented in Florence', 'the inventor was a priest', 'reading stones were still popular'], 'A', 'Paragraph B: spectacles "had been invented less than twenty years before".', 'B'),
              mc(4, 'Why did demand for spectacles grow in the fifteenth century?', ['Glassmakers reduced their prices.', 'Printing made books cheaper and more people learned to read.', 'Doctors began to prescribe them.', 'Short-sighted people needed them for work.'], 'B', 'Paragraph C: "As books became cheaper and more people learned to read, demand ... rose sharply".', 'C'),
              mc(5, 'What problem did Benjamin Franklin want to solve?', ['Spectacles fell off too easily.', 'Glass lenses were too heavy.', 'He had to keep changing between two pairs.', 'His prescription kept changing.'], 'C', 'Paragraph D: "tired of constantly swapping between one pair for distance and another for reading".', 'D'),
            ],
          },
          {
            id: 't10-r1-summary',
            type: 'summary_completion',
            instructionHtml: 'Complete the summary of paragraphs B and C below. Choose <strong>NO MORE THAN TWO WORDS</strong> from the passage for each answer.',
            wordLimit: { maxWords: 2, label: 'NO MORE THAN TWO WORDS' },
            stemHtml: '<p>Before spectacles, monks used {{q6}} made from clear {{q7}} or glass, which magnified the text. Around {{q8}}, a craftsman in northern Italy joined two {{q9}} with a {{q10}}, so that they could be balanced on the nose. The earliest lenses were {{q11}}, and helped people who were {{q12}}. Lenses for the short-sighted did not appear until the {{q13}} century.</p>',
            questions: [
              q(6, null, ['reading stones', 'reading stone'], 'Paragraph B: "the reading stone".', 'B'),
              q(7, null, ['quartz'], 'Paragraph B: "clear quartz or glass".', 'B'),
              q(8, null, ['1286'], 'Paragraph B: "around 1286".', 'B'),
              q(9, null, ['lenses'], 'Paragraph B: "mounting two lenses in frames".', 'B'),
              q(10, null, ['rivet'], 'Paragraph B: "joined at the top by a rivet".', 'B'),
              q(11, null, ['convex'], 'Paragraph C: "The earliest lenses were convex".', 'C'),
              q(12, null, ['long-sighted', 'long sighted'], 'Paragraph C: "useful only for people who were long-sighted".', 'C'),
              q(13, null, ['fifteenth', '15th'], 'Paragraph C: "did not appear until the fifteenth century".', 'C'),
            ],
          },
        ],
      },
      {
        order: 2,
        title: 'What elephants remember',
        subtitle: 'Read the text and answer questions 14-26.',
        paragraphs: paras(
          ['A', `Elephants have the largest brains of any land animal, weighing around five kilograms, about four times as much as a human's. Their brains also contain regions linked to memory and emotion that are strikingly similar to our own, and the behaviour of elephants in the wild has led many researchers to conclude that the popular saying, that an elephant never forgets, is not far from the truth. Field studies carried out over several decades, in which individual animals have been followed from birth to death, have provided the most convincing evidence. Because elephants live for sixty years or more, and because family members stay together throughout their lives, they offer researchers a rare chance to observe how knowledge is gathered, stored and shared over several generations.`],
          ['B', `Elephant herds are led by the oldest female, the matriarch, and the knowledge she carries can decide whether a herd lives or dies. In a study of a severe drought in Tanzania in the early 1990s, herds led by older matriarchs, who had lived through an earlier drought decades before, travelled to distant sources of water that younger leaders did not know about, and lost far fewer calves. The researchers concluded that the older females had stored a detailed map of the landscape, including places that had not been used for many years, and that this knowledge had been passed on to the rest of the family simply by being followed. The finding helped to explain why herds in which the older females are present tend to be larger and healthier, even when food is plentiful.`],
          ['C', `Researchers in Kenya have tested how well elephants recognise one another by playing recorded calls from hidden loudspeakers. Older matriarchs were able to identify the voices of around a hundred other elephants, and they reacted differently to the calls of strangers than to those of familiar animals. When a stranger's call was played, the herd bunched together and moved away defensively, led by the matriarch, whereas the call of a familiar neighbour produced no such response. Herds led by older matriarchs, who had the largest catalogue of voices, were the quickest to respond correctly.`],
          ['D', `Elephants communicate with rumbles so low that they fall below the range of human hearing. These sounds, known as infrasound, can travel several kilometres through the air, allowing members of a family scattered across a wide landscape to keep in touch. Some scientists also believe that elephants can detect vibrations through the soles of their feet and the tips of their trunks, and that this gives them warning of distant storms or approaching herds, although the idea has not yet been proved.`],
          ['E', `Elephants also seem to have a strong response to death. Herds have been seen standing quietly around a dead companion, touching the body gently with their trunks, and returning to the bones of dead relatives years later, handling them carefully. Whether this should be interpreted as grief in the human sense is a matter of debate among scientists, some of whom warn against attributing human emotions to other species. But few observers doubt that elephants notice and remember their dead. Such behaviour, recorded again and again in different parts of Africa and Asia, is one of the reasons why many people find the treatment of elephants in captivity so troubling.`],
          ['F', `Other tests have shown that elephants are capable of ingenious behaviour. They have been seen using branches to swat flies, and in experiments, they have stacked boxes to reach food that was out of their reach. In one well-known test at a zoo in New York, an Asian elephant touched a mark on her own head that she could only see in a mirror, which suggests a sense of self of the kind that only a few other species, including apes and dolphins, have shown.`],
          ['G', `These abilities make the loss of older elephants especially serious. Poachers hunt for ivory, and the largest tusks belong to the oldest animals. When a matriarch dies, her herd loses not only a leader but also a store of knowledge about water, routes and dangers, and studies suggest that young females in such herds breed less successfully. Conservationists therefore argue that protecting the oldest individuals is essential, and that the survival of the species depends on preserving not just their numbers, but also the social structures in which they live.`]
        ),
        questionGroups: [
          {
            id: 't10-r2-short',
            type: 'short_answer',
            instructionHtml: 'Answer the questions below. Choose <strong>NO MORE THAN THREE WORDS</strong> from the passage for each answer.',
            wordLimit: { maxWords: 3, label: 'NO MORE THAN THREE WORDS' },
            questions: [
              q(14, 'About how heavy is an elephant\'s brain?', ['five kilograms', '5 kilograms', '5 kg', 'around five kilograms'], 'Paragraph A: "around five kilograms".', 'A'),
              q(15, 'Who leads an elephant herd?', ['the oldest female', 'oldest female', 'the matriarch', 'matriarch'], 'Paragraph B: "led by the oldest female, the matriarch".', 'B'),
              q(16, 'In which country did the study of a severe drought take place?', ['tanzania'], 'Paragraph B: "a severe drought in Tanzania".', 'B'),
              q(17, 'What name is given to rumbles that are too low for humans to hear?', ['infrasound'], 'Paragraph D: "known as infrasound".', 'D'),
            ],
          },
          {
            id: 't10-r2-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B, C or D</strong>.',
            questions: [
              mc(18, 'In the Kenyan experiment, how did herds react to the call of a stranger?', ['They ignored it.', 'They bunched together and moved away defensively.', 'They called back loudly.', 'They scattered in all directions.'], 'B', 'Paragraph C: "the herd bunched together and moved away defensively".', 'C'),
              mc(19, 'What do scientists think about elephants detecting vibrations through their feet?', ['It has been proved.', 'It has been disproved.', 'Some believe it happens, but it is not yet proved.', 'It is the main way elephants communicate.'], 'C', 'Paragraph D: "the idea has not yet been proved".', 'D'),
              mc(20, 'In the mirror test at a zoo, the elephant', ['attacked her reflection', 'touched a mark on her own head', 'refused to look', 'used a branch to reach the mirror'], 'B', 'Paragraph F: "touched a mark on her own head".', 'F'),
            ],
          },
          {
            id: 't10-r2-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              q(21, 'An elephant\'s brain weighs about four times as much as a human\'s.', 'TRUE', 'Paragraph A: "about four times as much as a human\'s".', 'A'),
              q(22, 'Older matriarchs in Kenya could recognise the voices of about a hundred other elephants.', 'TRUE', 'Paragraph C: "around a hundred other elephants".', 'C'),
              q(23, 'In the Tanzanian drought, herds with younger leaders lost fewer calves.', 'FALSE', 'Paragraph B: herds led by older matriarchs "lost far fewer calves".', 'B'),
              q(24, 'Elephants have been seen touching the body of a dead companion.', 'TRUE', 'Paragraph E: "touching the body gently with their trunks".', 'E'),
              q(25, 'Researchers have taught elephants to use tools.', 'NOT GIVEN', 'Paragraph F describes tool use but not training.', 'F'),
              q(26, 'Young females in herds without a matriarch breed less successfully.', 'TRUE', 'Paragraph G: "young females in such herds breed less successfully".', 'G'),
            ],
          },
        ],
      },
      {
        order: 3,
        title: 'The invisible tide',
        subtitle: 'Read the text and answer questions 27-40.',
        paragraphs: paras(
          ['A', `The plastic bottle on the beach is easy to see. The plastic that does most to worry scientists is not. Microplastics, defined as fragments smaller than five millimetres across, have been found in the deepest ocean trenches, in Arctic ice, in the snow of remote mountains, in the air of cities and in the stomachs of animals from plankton to whales. More recently, researchers have reported them in human blood, lungs and placentas. Because plastic does not decay in the way that wood or paper does, but simply breaks into smaller and smaller pieces, almost all of the plastic that has ever been made is still in existence in some form, and the quantity of microplastic in the environment is increasing every year. Since production of plastic has doubled in the past two decades and is expected to double again, the problem is likely to grow before it begins to shrink.`],
          ['B', `Microplastics come from two main kinds of source. Some are made small on purpose: the tiny beads that were once added to cosmetics and toothpaste, and the pellets, known as nurdles, that are the raw material for plastic factories and are sometimes spilt in transit. Most, however, are created when larger items break down. Tyres, which shed fine particles with every kilometre driven, are thought to be among the largest single sources, and synthetic clothes release fibres every time they are washed. A single load of laundry can shed hundreds of thousands of fibres, though studies give very different figures, depending on the fabric and the machine.`],
          ['C', `The particles reach the environment by several routes. Water from washing machines and drains flows into sewage works, which remove most microplastics but not all, and since the volumes of waste water are enormous, the quantity that escapes is large. The solid sludge that remains is often spread on farmland as fertiliser, which transfers the plastic to the soil. Particles are also carried by the wind, washed from roads by rain and dropped directly into the sea from ships and fishing gear. Once in the ocean, they are moved around the world by currents, and they accumulate in regions where the water circulates slowly.`],
          ['D', `The effects on wildlife are better understood than those on people. Small animals mistake plastic fragments for food, and in laboratory studies, this has been shown to reduce feeding and growth, because the animals feel full when they are not. Plastic surfaces also attract chemical pollutants from the water around them, so that the particles may act as carriers for toxic substances. However, many of the laboratory experiments have used concentrations much higher than those found in nature, and some scientists argue that the harm to populations in the wild has yet to be demonstrated.`],
          ['E', `People take in microplastics in food, drinking water and the air they breathe, and researchers have detected them in bottled water, sea salt, honey and shellfish. What this means for health is unknown. Some studies suggest that the particles can trigger inflammation in cells, but there is no proof that they cause disease in humans, and the methods used to count them vary so much between laboratories that comparisons are difficult. Most experts say that the right response is neither alarm nor complacency, but more research, using standard methods that allow results to be compared. A large international project to agree such methods is now under way, and its first results are expected within a few years.`],
          ['F', `Policy has begun to respond. A number of countries have banned microbeads from cosmetics, and some have required filters to be fitted to new washing machines to catch fibres. Researchers are developing tyres that shed less rubber and fabrics that release fewer fibres, and several cities are experimenting with systems that trap particles in drains before they reach rivers. Such measures deal with individual sources, and their effects will take years to appear, because the plastic already in the environment will remain for centuries.`],
          ['G', `The most sensible approach, in my opinion, is to concentrate on prevention. Cleaning up microplastics once they have spread through the oceans, soil and air is practically impossible; the particles are too small and too widely dispersed. But the flow of new plastic into the environment can be reduced, by redesigning products, by using less plastic where alternatives exist and by improving the way waste is collected and treated. The challenge is to act on the evidence we have, while continuing to ask the questions that science has not yet answered.`]
        ),
        questionGroups: [
          {
            id: 't10-r3-headings',
            type: 'matching_headings',
            instructionHtml: 'Reading Passage 3 has seven paragraphs, A-G. Choose the correct heading for paragraphs B-G from the list of headings below.<br/><em>Example: Paragraph A — viii</em>',
            bank: [
              { key: 'i', text: 'Ways in which particles travel' },
              { key: 'ii', text: 'Why prevention is better than cleaning up' },
              { key: 'iii', text: 'Dangers to animals and gaps in the evidence' },
              { key: 'iv', text: 'Where the particles come from' },
              { key: 'v', text: 'Attempts to tackle individual sources' },
              { key: 'vi', text: 'The recycling of plastic bottles' },
              { key: 'vii', text: 'What is known, and not known, about human health' },
              { key: 'viii', text: 'A problem that cannot be seen' },
              { key: 'ix', text: 'The cost of banning plastic' },
            ],
            questions: [
              q(27, 'Paragraph B', 'iv', 'Paragraph B: two kinds of source: particles made small on purpose, and pieces from larger items.', 'B'),
              q(28, 'Paragraph C', 'i', 'Paragraph C: routes by drains, sludge, wind, rain and ocean currents.', 'C'),
              q(29, 'Paragraph D', 'iii', 'Paragraph D: effects on animals, but harm in the wild "has yet to be demonstrated".', 'D'),
              q(30, 'Paragraph E', 'vii', 'Paragraph E: "What this means for health is unknown."', 'E'),
              q(31, 'Paragraph F', 'v', 'Paragraph F: bans, filters, new tyres and drain traps each deal with "individual sources".', 'F'),
              q(32, 'Paragraph G', 'ii', 'Paragraph G: "concentrate on prevention. Cleaning up ... is practically impossible".', 'G'),
            ],
          },
          {
            id: 't10-r3-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              q(33, 'Microplastics are defined as fragments smaller than five millimetres across.', 'TRUE', 'Paragraph A: "smaller than five millimetres across".', 'A'),
              q(34, 'Sewage works remove all microplastics from waste water.', 'FALSE', 'Paragraph C: "remove most microplastics but not all".', 'C'),
              q(35, 'Laboratory studies have proved that microplastics cause disease in humans.', 'FALSE', 'Paragraph E: "there is no proof that they cause disease in humans".', 'E'),
              q(36, 'Charges for plastic bags have reduced the amount of microplastic in the sea.', 'NOT GIVEN', 'Plastic bag charges are not mentioned.'),
            ],
          },
          {
            id: 't10-r3-summary',
            type: 'summary_completion_bank',
            instructionHtml: 'Complete the summary using the list of words, A-H, below.',
            bankReusable: false,
            bank: bank(['microbeads', 'tyres', 'waste water', 'farmland', 'glaciers', 'fishing nets', 'rainfall', 'detergents']),
            stemHtml: '<p><strong>Sources and routes</strong></p><p>Some microplastics are made small on purpose, like the {{q37}} once added to cosmetics. Others come from larger items; {{q38}} are thought to be among the largest single sources. Much of the plastic reaches rivers through {{q39}}, and the sludge left at sewage works is often spread on {{q40}}.</p>',
            questions: [
              q(37, null, 'A', 'Paragraph B: "the tiny beads that were once added to cosmetics".', 'B'),
              q(38, null, 'B', 'Paragraph B: "Tyres ... among the largest single sources".', 'B'),
              q(39, null, 'C', 'Paragraph C: "Water from washing machines and drains flows into sewage works".', 'C'),
              q(40, null, 'D', 'Paragraph C: "spread on farmland as fertiliser".', 'C'),
            ],
          },
        ],
      },
    ],
  },

  listening: {
    durationSec: 1800,
    checkTimeSec: 120,
    parts: [
      {
        order: 1,
        contextText: 'You will hear a woman phoning a music school to ask about lessons for her daughter.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Hello, Westbrook School of Music." },
          { speaker: 'B', voice: 'zira', text: "Hello. I'm interested in violin lessons for my daughter. Could you tell me about them?" },
          { speaker: 'A', voice: 'david', text: "Certainly. How old is she?" },
          { speaker: 'B', voice: 'zira', text: "She's nine. Her name's Sophie Lindqvist, and that's spelled L-I-N-D-Q-V-I-S-T." },
          { speaker: 'A', voice: 'david', text: "Thank you. Has she played an instrument before?" },
          { speaker: 'B', voice: 'zira', text: "She's had a year of piano lessons at school, but she'd like to try something different." },
          { speaker: 'A', voice: 'david', text: "That's a good foundation, because she'll already be able to read music. We offer individual lessons, which last thirty minutes, and cost twenty-four pounds each, or group lessons with up to five children, at twelve pounds." },
          { speaker: 'B', voice: 'zira', text: "I think individual lessons would be better to start with. What days are available?" },
          { speaker: 'A', voice: 'david', text: "Our violin teacher, Mr Okafor, works on Tuesdays and Thursdays. There's a space at four fifteen on Thursdays." },
          { speaker: 'B', voice: 'zira', text: "That should be possible. Do we need to buy a violin?" },
          { speaker: 'A', voice: 'david', text: "Not at first. We rent out small violins for seven pounds a month, and you can exchange them for a bigger size as she grows. The price includes a case and a bow." },
          { speaker: 'B', voice: 'zira', text: "That sounds sensible. Are there any concerts?" },
          { speaker: 'A', voice: 'david', text: "Yes, pupils perform twice a year, in the summer and at Christmas, but it's entirely optional." },
          { speaker: 'B', voice: 'zira', text: "And when can she start?" },
          { speaker: 'A', voice: 'david', text: "The new term begins on the ninth of January. There's a registration fee of fifteen pounds, which covers the music books for the first term." },
          { speaker: 'B', voice: 'zira', text: "Fine. Could I give you my address? It's twelve Ashgrove Close, in Brentford." },
          { speaker: 'A', voice: 'david', text: "Thank you, and a telephone number?" },
          { speaker: 'B', voice: 'zira', text: "It's oh-seven-nine-oh-oh, eight-one-eight, four-four-six." },
          { speaker: 'A', voice: 'david', text: "Lovely. I'll send you a registration form this afternoon." },
        ],
        questionGroups: [
          {
            id: 't10-l1-form',
            type: 'form_completion',
            instructionHtml: 'Complete the form below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Westbrook School of Music: Enquiry', ''],
              [
                ['Pupil\'s surname', '{{q1}}'],
                ['Age', '{{q2}}'],
                ['Instrument', '{{q3}}'],
                ['Previous experience', 'one year of {{q4}} lessons at school'],
                ['Type of lesson', 'individual, {{q5}} minutes'],
                ['Cost of individual lesson', '£{{q6}}'],
                ['Day and time', 'Thursday at {{q7}}'],
                ['Violin rental', '£{{q8}} per month'],
                ['Term starts on', '{{q9}} January'],
                ['Registration fee', '£{{q10}}'],
              ]
            ),
            questions: [
              q(1, null, ['lindqvist'], 'Spelled out: L-I-N-D-Q-V-I-S-T.'),
              q(2, null, ['9', 'nine'], '"She\'s nine."'),
              q(3, null, ['violin'], '"violin lessons for my daughter".'),
              q(4, null, ['piano'], '"a year of piano lessons at school".'),
              q(5, null, ['30', 'thirty'], '"individual lessons, which last thirty minutes".'),
              q(6, null, ['24', 'twenty-four', 'twenty four'], '"twenty-four pounds each".'),
              q(7, null, ['4.15', '4:15', 'four fifteen', 'quarter past four', '16:15'], '"a space at four fifteen on Thursdays".'),
              q(8, null, ['7', 'seven'], '"seven pounds a month".'),
              q(9, null, ['9', 'ninth', '9th'], '"The new term begins on the ninth of January."'),
              q(10, null, ['15', 'fifteen'], '"a registration fee of fifteen pounds".'),
            ],
          },
        ],
      },
      {
        order: 2,
        contextText: 'You will hear a council officer explaining a new household recycling scheme at a public meeting.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Good evening, everyone. I'm Mark Dawson from the waste department of the council, and I'm here to explain the new recycling scheme that begins next month." },
          { speaker: 'A', voice: 'david', text: "At present, the council collects only two kinds of waste: general rubbish and a mixed recycling bin. This has worked reasonably well, but about one fifth of what people put in the recycling bin can't be recycled, because it's dirty or of the wrong type, and this contaminates the rest." },
          { speaker: 'A', voice: 'david', text: "So from the first of March, every household will receive four containers. The green bin is for glass bottles and jars. Please rinse them, but there's no need to remove the labels. The blue bin is for paper and cardboard. It must be dry, so please don't put in greasy pizza boxes." },
          { speaker: 'A', voice: 'david', text: "The brown bin is for food waste and garden waste. It will be collected every week, because food waste can smell in warm weather, and we'll provide a small container for your kitchen, together with a supply of biodegradable bags. And the grey bin is for general rubbish that can't be recycled, such as nappies, broken crockery and dirty plastic film. The grey bin will be collected only every three weeks, which should encourage everyone to recycle more." },
          { speaker: 'A', voice: 'david', text: "Plastic bottles, tins and cartons will go in a separate red bag, which will be left out on the same day as the blue bin. Please squash them flat to save space." },
          { speaker: 'A', voice: 'david', text: "I know some of you are concerned about having so many containers. We're aware that flats and houses with small gardens have limited space, so we've designed the new bins to be narrower than the old ones, and residents in flats can use shared bins in the courtyard instead." },
          { speaker: 'A', voice: 'david', text: "A leaflet explaining everything will be delivered to every home in the next ten days. There's also a telephone helpline, open from eight until six on weekdays, and an app that tells you the date of your next collection." },
          { speaker: 'A', voice: 'david', text: "If you have large items, such as furniture or a fridge, don't put them out with your normal waste. You can book a special collection by phone or online; the first three items each year are free." },
          { speaker: 'A', voice: 'david', text: "Finally, from the second year of the scheme, households that still put the wrong items in the wrong bins may receive a warning letter, and repeated offences could result in a fine. But our aim is to help, not to punish. Now, are there any questions?" },
        ],
        questionGroups: [
          {
            id: 't10-l2-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(11, 'What is the problem with the current recycling bin?', ['It is collected too rarely.', 'About one fifth of its contents cannot be recycled.', 'It is too small.'], 'B', '"about one fifth of what people put in the recycling bin can\'t be recycled".'),
              mc(12, 'The new scheme starts on', ['1 February', '1 March', '1 April'], 'B', '"from the first of March".'),
              mc(13, 'How often will the grey bin be collected?', ['every week', 'every two weeks', 'every three weeks'], 'C', '"collected only every three weeks".'),
              mc(14, 'Flats with limited space can', ['use shared bins in the courtyard', 'refuse the new bins', 'use smaller bags'], 'A', '"residents in flats can use shared bins in the courtyard".'),
              mc(15, 'How many items can be collected free of charge each year as special collections?', ['one', 'three', 'five'], 'B', '"the first three items each year are free".'),
            ],
          },
          {
            id: 't10-l2-match',
            type: 'matching_features',
            instructionHtml: 'Which container should be used for each type of waste? Choose the correct answer and write the correct letter, <strong>A-E</strong>, next to Questions 16-20.',
            bank: [
              { key: 'A', text: 'green bin' },
              { key: 'B', text: 'blue bin' },
              { key: 'C', text: 'brown bin' },
              { key: 'D', text: 'grey bin' },
              { key: 'E', text: 'red bag' },
            ],
            bankReusable: false,
            questions: [
              q(16, 'glass jars', 'A', '"The green bin is for glass bottles and jars."'),
              q(17, 'dry cardboard', 'B', '"The blue bin is for paper and cardboard."'),
              q(18, 'kitchen food waste', 'C', '"The brown bin is for food waste and garden waste."'),
              q(19, 'broken crockery', 'D', '"the grey bin is for general rubbish ... such as ... broken crockery".'),
              q(20, 'plastic bottles', 'E', '"Plastic bottles, tins and cartons will go in a separate red bag".'),
            ],
          },
        ],
      },
      {
        order: 3,
        contextText: 'You will hear two literature students, Dina and Patrick, discussing an essay on a novel with their tutor.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david2', text: "Right, Dina, Patrick, let's talk about your essays on the novel. Dina, you go first." },
          { speaker: 'B', voice: 'zira', text: "I'm writing about how the author uses the weather to reflect the characters' feelings, but I'm worried that my argument is a bit obvious." },
          { speaker: 'A', voice: 'david2', text: "It's a familiar idea, yes. To make it more interesting, try asking where it doesn't work. Are there scenes where the weather contrasts with the mood?" },
          { speaker: 'B', voice: 'zira', text: "There's the wedding scene, where the sun shines but the atmosphere is tense." },
          { speaker: 'A', voice: 'david2', text: "Exactly. That's the sort of thing that will lift your essay. Patrick?" },
          { speaker: 'C', voice: 'david', text: "I've chosen to write about the narrator, and whether we can trust what he tells us. I've found seven places where his account contradicts the other characters'." },
          { speaker: 'A', voice: 'david2', text: "Seven is plenty. Don't try to discuss them all; pick three or four and analyse them in depth." },
          { speaker: 'C', voice: 'david', text: "Right. Should I include critics' opinions?" },
          { speaker: 'A', voice: 'david2', text: "Yes, but use them to support your own argument rather than replacing it. Quote a critic only if you can say why you agree or disagree." },
          { speaker: 'B', voice: 'zira', text: "How many sources should we have?" },
          { speaker: 'A', voice: 'david2', text: "At least six, with at least two from the past five years. The essay is two and a half thousand words, due on the second of May." },
          { speaker: 'C', voice: 'david', text: "What's the best way to plan it?" },
          { speaker: 'A', voice: 'david2', text: "I suggest you start by writing your main argument in a single sentence. If you can't do that, you aren't ready to write. Next, make a list of the evidence, then arrange it in order of importance. Write the introduction last, so that it matches what you've actually written." },
          { speaker: 'B', voice: 'zira', text: "That's the opposite of what I usually do." },
          { speaker: 'A', voice: 'david2', text: "Many students do. But introductions written first tend to promise things the essay doesn't deliver. After that, leave the draft for a few days, then read it aloud to catch awkward sentences, and finally check the references." },
        ],
        questionGroups: [
          {
            id: 't10-l3-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(21, 'What is Dina worried about?', ['Her argument may be too obvious.', 'She has too little time.', 'She has not read the novel.'], 'A', '"I\'m worried that my argument is a bit obvious."'),
              mc(22, 'The tutor advises Dina to', ['change her topic', 'look for scenes where the weather does not reflect the mood', 'add more quotations'], 'B', '"try asking where it doesn\'t work".'),
              mc(23, 'Patrick has found', ['three contradictions', 'seven contradictions', 'ten contradictions'], 'B', '"I\'ve found seven places".'),
              mc(24, 'What does the tutor say about critics\' opinions?', ['They should replace the student\'s argument.', 'They should be avoided.', 'They should support the student\'s own argument.'], 'C', '"use them to support your own argument rather than replacing it".'),
              mc(25, 'The essay is due on', ['2 May', '12 May', '22 May'], 'A', '"due on the second of May".'),
            ],
          },
          {
            id: 't10-l3-flow',
            type: 'flowchart_completion',
            instructionHtml: 'Complete the flow-chart below. Write <strong>NO MORE THAN TWO WORDS</strong> for each answer.',
            wordLimit: { maxWords: 2, label: 'NO MORE THAN TWO WORDS' },
            stemHtml: '<p><strong>Planning the essay</strong></p><p>1. Write the main argument in a single {{q26}}.</p><p>2. Make a list of the {{q27}}.</p><p>3. Arrange the points in order of {{q28}}.</p><p>4. Write the {{q29}} last.</p><p>5. Leave the draft for a few days, then read it {{q30}} to find awkward sentences.</p>',
            questions: [
              q(26, null, ['sentence'], '"your main argument in a single sentence".'),
              q(27, null, ['evidence'], '"make a list of the evidence".'),
              q(28, null, ['importance'], '"arrange it in order of importance".'),
              q(29, null, ['introduction'], '"Write the introduction last".'),
              q(30, null, ['aloud', 'out loud'], '"read it aloud".'),
            ],
          },
        ],
      },
      {
        order: 4,
        contextText: 'You will hear part of a lecture about why leaves change colour in autumn.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Every autumn, in temperate parts of the world, forests turn red, orange and gold. Today I'm going to explain what causes this change, and why some years are more spectacular than others." },
          { speaker: 'A', voice: 'david', text: "The green of a leaf comes from chlorophyll, the pigment that absorbs sunlight and uses it to make sugars. Chlorophyll is unstable, and the tree has to renew it constantly during the summer, which it can do easily when days are long and warm." },
          { speaker: 'A', voice: 'david', text: "As autumn approaches, the days become shorter. This is the trigger: trees detect the length of the night, and begin preparing for winter. They stop producing chlorophyll, and the green fades." },
          { speaker: 'A', voice: 'david', text: "What is revealed is the yellow and orange of other pigments called carotenoids, which were present in the leaf all along but hidden by the green. The same pigments give carrots and egg yolks their colour." },
          { speaker: 'A', voice: 'david', text: "The reds and purples are different. They come from anthocyanins, which are not present in the leaf during the summer, but are made in autumn, from sugars trapped in the leaf. Why trees should do this is still a puzzle. One idea is that anthocyanins act like a sunscreen, protecting the leaf while the tree recovers valuable nutrients from it. Another suggests that bright colours warn insects that the tree is healthy and well defended, so that they should not lay their eggs on it." },
          { speaker: 'A', voice: 'david', text: "The best displays occur after a warm, sunny autumn with cool nights, but no frost. Sunny days allow the leaves to produce plenty of sugar, and cool nights prevent the sugar from leaving the leaf. A sudden hard frost, on the other hand, kills the leaves and they fall while still dull and brown. Drought in summer can also weaken the colours." },
          { speaker: 'A', voice: 'david', text: "Not all trees behave the same way. In North America, maples and sumacs produce brilliant reds, whereas in Europe, autumn colours are mostly yellow and brown, which some scientists link to differences in the past climate and in the insects that feed on the trees." },
          { speaker: 'A', voice: 'david', text: "Eventually, a layer of cells forms at the base of each leaf stalk, sealing the wound, and the leaf drops. The tree is then ready for winter. The fallen leaves rot on the ground, releasing their nutrients back to the soil, and the cycle begins again in spring." },
        ],
        questionGroups: [
          {
            id: 't10-l4-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(31, 'What causes trees to stop producing chlorophyll?', ['cold temperatures', 'shorter days', 'lack of water'], 'B', '"This is the trigger: trees detect the length of the night".'),
              mc(32, 'The yellow and orange colours are caused by', ['carotenoids', 'anthocyanins', 'chlorophyll'], 'A', '"the yellow and orange of other pigments called carotenoids".'),
              mc(33, 'Anthocyanins are', ['present in the leaf all year', 'made in autumn', 'found only in fruit'], 'B', '"are made in autumn, from sugars trapped in the leaf".'),
              mc(34, 'The best autumn colours follow', ['a wet summer', 'a warm, sunny autumn with cool nights', 'an early frost'], 'B', '"a warm, sunny autumn with cool nights, but no frost".'),
              mc(35, 'In Europe, autumn colours are mostly', ['red', 'purple', 'yellow and brown'], 'C', '"mostly yellow and brown".'),
            ],
          },
          {
            id: 't10-l4-sentences',
            type: 'sentence_completion',
            instructionHtml: 'Complete the sentences below. Write <strong>NO MORE THAN TWO WORDS</strong> for each answer.',
            wordLimit: { maxWords: 2, label: 'NO MORE THAN TWO WORDS' },
            questions: [
              q(36, 'Chlorophyll absorbs {{q36}} and uses it to make sugars.', ['sunlight'], '"absorbs sunlight and uses it to make sugars".'),
              q(37, 'Carotenoids also give {{q37}} and egg yolks their colour.', ['carrots'], '"carrots and egg yolks".'),
              q(38, 'One idea is that anthocyanins act like a {{q38}}, protecting the leaf.', ['sunscreen'], '"act like a sunscreen".'),
              q(39, 'A hard frost kills the leaves, which fall while still {{q39}}.', ['dull and brown', 'dull', 'brown'], '"fall while still dull and brown".'),
              q(40, 'A layer of cells at the base of the leaf stalk seals the {{q40}}.', ['wound'], '"sealing the wound".'),
            ],
          },
        ],
      },
    ],
  },

  writing: {
    durationSec: 3600,
    task1: {
      order: 1,
      minWords: 150,
      recommendedMin: 20,
      promptHtml:
        '<p>The chart below shows the percentage of households in four countries that owned different types of device in 2021.</p><p>Summarise the information by selecting and reporting the main features, and make comparisons where relevant.</p>',
      chart: {
        chartType: 'bar',
        title: 'Households owning devices, 2021 (%)',
        unit: '%',
        categories: ['Smartphone', 'Laptop', 'Tablet', 'Games console'],
        xAxisLabel: 'Device',
        yAxisLabel: 'Percentage of households',
        series: [
          { name: 'Norway', data: [97, 88, 74, 41] },
          { name: 'Brazil', data: [90, 52, 38, 22] },
          { name: 'India', data: [72, 24, 15, 8] },
        ],
      },
    },
    task2: {
      order: 2,
      minWords: 250,
      recommendedMin: 40,
      promptHtml:
        '<p>Some people believe that animals should not be kept in zoos. Others think zoos are necessary for the protection of animals.</p><p>Discuss both views and give your own opinion.</p>',
    },
  },
};
