// Original IELTS-style practice content (NOT copied or paraphrased from any real
// Cambridge/IELTS book). Only the exam STRUCTURE follows a standard Academic test
// layout; every topic, passage, transcript, question and answer is written from scratch.
import { table, TFNG_INSTRUCTION, YNNG_INSTRUCTION, q, paras, mc, bank } from './_html.mjs';

export default {
  slug: 'vocably-practice-test-20',
  title: 'Vocably Practice Test 20',
  difficulty: 'medium',

  reading: {
    durationSec: 3600,
    passages: [
      {
        order: 1,
        title: 'Birds that never land',
        subtitle: 'Read the text and answer questions 1-13.',
        paragraphs: paras(
          ['A', `On a summer evening in Europe, flocks of dark, crescent-shaped birds scream across the sky at rooftop height, wheeling and diving after insects. They are swifts, and they are among the most extraordinary flyers in the world. A young swift that leaves its nest in late summer may not touch a solid surface again for two years, flying continuously while it migrates, feeds, drinks, and even sleeps. It lands only when it is ready to breed and must build a nest. No other bird is so completely at home in the air, and researchers who study them say that the more they find out, the more surprising the picture becomes.`],
          ['B', `The swift's body is exquisitely designed for flight. Its scientific name, Apus, means footless in Greek, because early naturalists who examined specimens noticed that the legs were so short and weak that they seemed to be missing altogether. In fact, the bird does have feet, which end in sharp claws that allow it to cling to vertical walls, but it cannot perch like a sparrow, nor walk. Its long, scythe-shaped wings, which span about forty centimetres, are the main reason why it cannot take off from flat ground: a swift that finds itself on a pavement is in trouble, since there is not enough room to lift its wings, and it must be picked up and thrown gently into the air.`],
          ['C', `Swifts feed entirely in flight. Their food is the cloud of tiny insects and spiders that drift in the air, sometimes called aerial plankton, carried upwards by warm air currents. A swift catches them by flying with its mouth open, a wide gape like a net, and in the breeding season, it gathers hundreds of insects at a time, holding them in a ball in its throat, to be carried back to the nest and fed to the chicks. Swifts also drink on the wing, skimming the surface of a pond or river and dipping their bills. In bad weather, when insects are scarce, the parents may fly several hundred kilometres to find better conditions, leaving the chicks to survive on their own by lowering their body temperature and going into a kind of torpor.`],
          ['D', `Sleep has long puzzled scientists. Swifts were once thought to roost in trees or on cliffs, but observers noticed that at dusk, some birds climb high into the sky, sometimes to two thousand metres, and do not return. Experiments with tiny recorders attached to the birds have shown that they glide slowly downwards with only occasional flaps, apparently in a state of rest, and climb again at intervals. Some scientists have suggested that swifts sleep one half of their brain at a time, as some dolphins do, but this has not been shown. It is possible that they take very short naps, and that the long period of flight is less tiring than it seems, since the birds make use of air currents to stay aloft.`],
          ['E', `The birds that breed in Europe spend the winter in Africa, and their journeys are now beginning to be understood. The information comes from miniature devices, known as geolocators, which record the light level, from which the position can be calculated. A study published in 2016 fitted them to a group of swifts and found that one bird remained in the air for ten months, from the end of summer until the following spring, without touching down once. It flew a total distance of roughly two hundred thousand kilometres in a year, and its journey took it across the Sahara and the Congo basin and back. Such results show how much remained to be discovered about even the commonest birds.`],
          ['F', `Yet swifts are in trouble. Numbers in several European countries have fallen by more than half over recent decades, and one of the causes is the loss of nest sites. Swifts in towns nest in small gaps under the roof tiles and in the walls of old buildings, and modern buildings are sealed so tightly that they offer no openings. The number of insects has also fallen, which makes it harder for the birds to find enough food. Conservationists have responded by fitting nest boxes to buildings, playing recorded calls to attract the birds to them, and asking builders to leave small holes in new walls. Volunteers also count the birds each summer, and the information helps them to see where protection is most needed.`]
        ),
        questionGroups: [
          {
            id: 't20-r1-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B, C or D</strong>.',
            questions: [
              mc(1, 'What does the name Apus suggest about the swift?', ['that it cannot fly', 'that it seems to have no feet', 'that it lives in trees', 'that it is very small'], 'B', 'Paragraph B: "Apus, means footless in Greek".', 'B'),
              mc(2, 'Why can a swift not take off from flat ground?', ['It is too heavy.', 'Its long wings need room to lift.', 'It has no claws.', 'It is too tired.'], 'B', 'Paragraph B: "there is not enough room to lift its wings".', 'B'),
              mc(3, 'What is meant by "aerial plankton"?', ['tiny insects and spiders drifting in the air', 'small seeds', 'clouds of dust', 'the birds\' flocks'], 'A', 'Paragraph C: "tiny insects and spiders that drift in the air".', 'C'),
              mc(4, 'How do swifts drink?', ['They land beside water.', 'They skim the surface of water in flight.', 'They collect rain in their feathers.', 'They do not drink.'], 'B', 'Paragraph C: "skimming the surface of a pond or river".', 'C'),
              mc(5, 'What does the writer say about the idea that swifts sleep one half of the brain at a time?', ['It has been proved.', 'It has been disproved.', 'It has been suggested but not shown.', 'It is the only explanation.'], 'C', 'Paragraph D: "this has not been shown".', 'D'),
            ],
          },
          {
            id: 't20-r1-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              q(6, 'A young swift may stay in the air for two years without landing.', 'TRUE', 'Paragraph A: "may not touch a solid surface again for two years".', 'A'),
              q(7, 'Swifts build their nests from mud.', 'NOT GIVEN', 'The material of the nests is not mentioned.'),
              q(8, 'European swifts spend the winter in Africa.', 'TRUE', 'Paragraph E: "spend the winter in Africa".', 'E'),
              q(9, 'The swifts in the 2016 study were tracked by satellite transmitters.', 'FALSE', 'Paragraph E: "geolocators, which record the light level".', 'E'),
            ],
          },
          {
            id: 't20-r1-sentences',
            type: 'sentence_completion',
            instructionHtml: 'Complete the sentences below. Choose <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> from the passage for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            questions: [
              q(10, 'Swifts have long, {{q10}}-shaped wings.', ['scythe'], 'Paragraph B: "scythe-shaped wings".', 'B'),
              q(11, 'Swifts carry insects to their chicks in a {{q11}} in the throat.', ['ball'], 'Paragraph C: "holding them in a ball in its throat".', 'C'),
              q(12, 'At dusk, some swifts climb to about {{q12}} metres.', ['2000', '2,000', 'two thousand'], 'Paragraph D: "two thousand metres".', 'D'),
              q(13, 'Modern buildings are sealed so tightly that they offer no {{q13}} for nests.', ['gaps', 'openings'], 'Paragraph F: "no openings" and "small gaps".', 'F'),
            ],
          },
        ],
      },
      {
        order: 2,
        title: 'The press and the scientific revolution',
        subtitle: 'Read the text and answer questions 14-26.',
        paragraphs: paras(
          ['A', `For most of history, books were copied by hand. A monk or professional scribe might take months to produce a single copy of a large work, and every copy contained slips, which were passed on, and multiplied, when the copy was itself copied. Around 1450, in the German city of Mainz, a goldsmith named Johannes Gutenberg developed a method of printing with movable metal type, and within a few decades, presses had spread across Europe. By 1500, an estimated twenty million volumes had been printed, more than the total of all the manuscripts produced in the previous thousand years. The invention is usually described as a turning point in the history of communication, but its effects on the growth of science deserve a special mention.`],
          ['B', `The first benefit was accuracy. Because every copy of a printed book was identical, scholars in different countries could be sure that they were reading the same text, and could refer to the same page. Astronomers were among the first to see the possibilities: in the fifteenth century, a German astronomer set up his own press in order to publish tables of the positions of the stars and planets, free of the errors that crept into hand-copied versions. Illustrations also benefited. The anatomist Andreas Vesalius, whose 1543 book on the structure of the human body included superb woodcut illustrations based on his own dissections, was able to reproduce his drawings faithfully in hundreds of copies, which would have been impossible by hand.`],
          ['C', `The second benefit was speed. A discovery could be made known to readers across Europe within months. The Polish astronomer Copernicus published his proposal that the Earth moves around the Sun in the same year as Vesalius's book, and Galileo's account of the moons of Jupiter, printed in 1610, was read by educated people all over the continent within weeks of its appearance. Scholars who would once have worked alone could read, criticise and build on one another's work, even when they lived hundreds of kilometres apart.`],
          ['D', `Printing also changed the way scientists communicated. In 1665, two journals appeared, one in Paris and one in London, which published short reports of experiments and observations. The London journal, issued by the Royal Society, became the model for scientific publication. Journals had a particular advantage: they provided a public and dated record of who had discovered what, which helped to settle disputes about priority, and so encouraged scientists to publish their results rather than keep them secret. In time, editors began to ask other experts to read submissions before they were accepted, the origin of the process of peer review that remains at the centre of science today.`],
          ['E', `Less obvious, but equally important, was the standardisation of the language of science. Printers needed fixed spellings, consistent diagrams and agreed symbols, and these gradually became the common property of scholars. The equals sign, for example, was introduced by a Welsh mathematician in 1557, who explained that he had chosen two parallel lines because nothing could be more equal, and it was soon adopted by others. Similar conventions for chemical and mathematical notation made it possible for a researcher in one country to read the work of a researcher in another without translation.`],
          ['F', `The effects were not all beneficial. Printing spread errors as easily as truths, and the same presses that produced Vesalius's anatomy also produced pamphlets on astrology and magic, which were often far more popular. The authorities, alarmed by the speed with which new ideas circulated, introduced censorship: in 1559, the Catholic Church issued a list of banned books, and Galileo's defence of the Copernican system, published in 1632, led to his trial and to the prohibition of his writings. Yet censorship failed to stop the spread of ideas; banned books were printed in Protestant countries and smuggled across borders, and the work of the forbidden authors was read more eagerly than before.`],
          ['G', `It is tempting to compare the printing press with the internet. Both have lowered the cost of spreading information, and both have been accused of spreading falsehood as well as truth. The internet, however, has gone further, since anyone can publish without a printer's permission, and every scientific paper can be read almost instantly by a researcher anywhere in the world. Whether it will have effects as great as those of the press remains to be seen. But the history of printing suggests that the value of a new means of communication depends less on the technology itself than on the habits and institutions that grow up around it.`]
        ),
        questionGroups: [
          {
            id: 't20-r2-matchinfo',
            type: 'matching_information',
            instructionHtml: 'Reading Passage 2 has seven paragraphs, A-G. Which paragraph contains the following information? <em>Choose the correct letter, A-G.</em>',
            questions: [
              q(14, 'a reference to the number of books printed by 1500', 'A', 'Paragraph A: "an estimated twenty million volumes".', 'A'),
              q(15, 'an example of illustrations in a scientific book', 'B', 'Paragraph B: Vesalius and his woodcut illustrations.', 'B'),
              q(16, 'a description of a new way of publishing short reports of experiments', 'D', 'Paragraph D: "journals ... published short reports".', 'D'),
              q(17, 'an example of a symbol that became standard', 'E', 'Paragraph E: the equals sign.', 'E'),
              q(18, 'a reference to the banning of books', 'F', 'Paragraph F: "a list of banned books".', 'F'),
              q(19, 'a comparison with a modern technology', 'G', 'Paragraph G: the internet.', 'G'),
            ],
          },
          {
            id: 't20-r2-ynng',
            type: 'yes_no_notgiven',
            instructionHtml: YNNG_INSTRUCTION,
            questions: [
              q(20, 'Copying books by hand often introduced mistakes that were then passed on.', 'YES', 'Paragraph A: "every copy contained slips, which were passed on".', 'A'),
              q(21, 'Gutenberg understood from the start how important his invention would be for science.', 'NOT GIVEN', 'Gutenberg\'s intentions are not discussed.', 'A'),
              q(22, 'Accurate illustrations were of little importance to science.', 'NO', 'Paragraph B stresses the value of faithfully reproduced illustrations.', 'B'),
              q(23, 'Journals made it easier to settle disputes about who had made a discovery first.', 'YES', 'Paragraph D: "helped to settle disputes about priority".', 'D'),
              q(24, 'The presses spread only accurate information.', 'NO', 'Paragraph F: "Printing spread errors as easily as truths".', 'F'),
              q(25, 'Censorship succeeded in stopping new ideas from spreading.', 'NO', 'Paragraph F: "censorship failed to stop the spread of ideas".', 'F'),
              q(26, 'The internet will have exactly the same effects on science as printing did.', 'NOT GIVEN', 'Paragraph G: "remains to be seen".', 'G'),
            ],
          },
        ],
      },
      {
        order: 3,
        title: 'The rise of esports',
        subtitle: 'Read the text and answer questions 27-40.',
        paragraphs: paras(
          ['A', `In a packed arena in Asia, tens of thousands of spectators watch two teams of five players sit in front of computer screens, while a giant display shows the action. The tournament is one of the biggest in the world of competitive video gaming, or esports, and the prize fund, pooled partly from the sale of in-game items to fans, runs to more than thirty million dollars, which is more than the winners of most traditional sporting events receive. Tens of millions more watch online. Only a decade ago, most people had never heard of such contests; now, esports is a multi-billion-dollar industry, with professional leagues, corporate sponsors and stars who are recognised in the street.`],
          ['B', `The games themselves fall into a few broad categories. One of the most popular is the multiplayer online battle arena, in which two teams of five players, each controlling a single character, compete to destroy the other team's base. Matches last about forty minutes, and the games require intense cooperation and planning. A second category is the first-person shooter, in which players see the action through the eyes of their character. They are usually played in short rounds, in which teams try to complete an objective, such as planting a bomb, or eliminate the opposing side. The third category consists of sports simulations, based on real competitions such as football and basketball, in which players control the athletes in a virtual match.`],
          ['C', `Professional players lead lives that are more disciplined than outsiders might expect. Top teams live together in houses and train for up to ten hours a day, practising tactics, reviewing recordings of their matches and studying their opponents. They are supported by coaches, analysts and, increasingly, psychologists and fitness trainers. The pressure is intense, and careers are short: reaction speed declines from the mid-twenties, and most professional players retire by the age of thirty. The most skilled can perform more than three hundred actions a minute, about five a second, with extraordinary precision.`],
          ['D', `The money comes from several sources. Sponsors, including makers of computers, drinks and banks, pay teams and leagues to display their names, and broadcasters pay for the right to show matches. Fans watch on streaming websites, where the most popular players have audiences larger than those of many television programmes, and they buy merchandise and in-game items. Some events sell out stadiums, and ticket sales add to the revenue. Teams have salaries comparable to those in traditional sports for their best players, while the majority earn only modest amounts. Games publishers, who own the rights to the games, also play a central part, since they organise the leagues, set the rules and decide how the money is shared, which gives them considerable power over the players and the teams.`],
          ['E', `Is esports a sport? The question divides opinion. Supporters point to the skill, training and teamwork involved, and argue that the ability to make split-second decisions under pressure is no less an athletic quality than speed or strength. Critics reply that sport by definition involves physical exertion, which gaming does not. The Olympic authorities have considered including esports, but have so far held back, and a major regional games in Asia has included them as a medal event. Meanwhile, medical studies have found that professional players are prone to injuries of the wrist and back, from many hours of repetitive movement, and to sleep problems, caused by long hours and late-night matches.`],
          ['F', `The industry has other challenges. Women make up only a small fraction of professional players, and those who compete often report being subjected to online abuse, which has led some organisers to set up leagues of their own and to introduce codes of conduct. Some governments have supported the industry: in South Korea, where it has been a national pastime for two decades, there are television channels devoted to it, and special training academies. Universities in several countries now offer scholarships to talented players and courses in the management of esports, which reflects the belief that the industry will be a source of careers for years to come. Not everyone welcomes this development, however: some educators worry that scholarships for gaming send the wrong message to teenagers who already spend many hours a day at a screen, and ask whether the money would be better spent on more traditional activities.`]
        ),
        questionGroups: [
          {
            id: 't20-r3-classify',
            type: 'matching_features',
            instructionHtml: 'Look at the following statements (Questions 27-30) and the list of game types below. Match each statement with the correct type, <strong>A, B or C</strong>.<br/>You may use any letter more than once.',
            bankReusable: true,
            bank: [
              { key: 'A', text: 'multiplayer online battle arena' },
              { key: 'B', text: 'first-person shooter' },
              { key: 'C', text: 'sports simulation' },
            ],
            questions: [
              q(27, 'Two teams of five players try to destroy each other\'s base.', 'A', 'Paragraph B: "two teams of five players ... to destroy the other team\'s base".', 'B'),
              q(28, 'It is played in short rounds in which teams complete an objective.', 'B', 'Paragraph B: "played in short rounds".', 'B'),
              q(29, 'It is based on real competitions.', 'C', 'Paragraph B: "based on real competitions such as football and basketball".', 'B'),
              q(30, 'Matches last about forty minutes and require intense cooperation.', 'A', 'Paragraph B: "Matches last about forty minutes".', 'B'),
            ],
          },
          {
            id: 't20-r3-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              q(31, 'Top teams may train for up to ten hours a day.', 'TRUE', 'Paragraph C: "train for up to ten hours a day".', 'C'),
              q(32, 'Most professional players continue to compete into their forties.', 'FALSE', 'Paragraph C: "most professional players retire by the age of thirty".', 'C'),
              q(33, 'Some esports events sell out stadiums.', 'TRUE', 'Paragraph D: "Some events sell out stadiums".', 'D'),
              q(34, 'The Olympic authorities have decided to include esports in the Games.', 'FALSE', 'Paragraph E: "have so far held back".', 'E'),
              q(35, 'Some universities offer scholarships to talented esports players.', 'TRUE', 'Paragraph F: "offer scholarships to talented players".', 'F'),
            ],
          },
          {
            id: 't20-r3-summary',
            type: 'summary_completion_bank',
            instructionHtml: 'Complete the summary of paragraphs E and F using the list of words, A-H, below.',
            bankReusable: false,
            bank: bank(['teamwork', 'wrist', 'sleep', 'Korea', 'women', 'hearing', 'Japan', 'strength']),
            stemHtml: '<p>Supporters argue that esports require skill and {{q36}}. Medical studies have found that professional players are prone to {{q37}} injuries and to {{q38}} problems. In {{q39}}, the industry has received government support, while {{q40}} make up only a small fraction of professional players.</p>',
            questions: [
              q(36, null, 'A', 'Paragraph E: "the skill, training and teamwork involved".', 'E'),
              q(37, null, 'B', 'Paragraph E: "injuries of the wrist and back".', 'E'),
              q(38, null, 'C', 'Paragraph E: "sleep problems".', 'E'),
              q(39, null, 'D', 'Paragraph F: "in South Korea".', 'F'),
              q(40, null, 'E', 'Paragraph F: "Women make up only a small fraction of professional players".', 'F'),
            ],
          },
        ],
      },
    ],
  },

  listening: {
    durationSec: 1800,
    checkTimeSec: 120,
    parts: [
      {
        order: 1,
        contextText: 'You will hear a student enquiring about an English course at a language school.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Lakeside Language School, good afternoon." },
          { speaker: 'B', voice: 'david', text: "Good afternoon. I'm from Brazil, and I'm planning to study English in Britain for a few months. Could I ask about your courses?" },
          { speaker: 'A', voice: 'zira', text: "Certainly. Could I take your name?" },
          { speaker: 'B', voice: 'david', text: "Rafael Domingues. That's R-A-F-A-E-L, and Domingues is D-O-M-I-N-G-U-E-S." },
          { speaker: 'A', voice: 'zira', text: "Thank you. And how long would you like to study?" },
          { speaker: 'B', voice: 'david', text: "Twelve weeks, starting in January, if possible." },
          { speaker: 'A', voice: 'zira', text: "We have an intensive course that runs for twelve weeks, starting on the eighth of January. There are twenty-five hours of lessons a week, from nine until two, Monday to Friday." },
          { speaker: 'B', voice: 'david', text: "What level would I need?" },
          { speaker: 'A', voice: 'zira', text: "We test everybody on the first day. Your level will decide your class. Most classes have twelve students, from many different countries." },
          { speaker: 'B', voice: 'david', text: "I'd like to improve my speaking and also prepare for an exam, because I want to study engineering at a British university." },
          { speaker: 'A', voice: 'zira', text: "In that case, the course includes an hour of exam preparation every day, for the academic English test. The fee is three thousand two hundred pounds for the twelve weeks, including books." },
          { speaker: 'B', voice: 'david', text: "And accommodation?" },
          { speaker: 'A', voice: 'zira', text: "We can arrange a room with a host family, at a hundred and ten pounds a week, including breakfast and dinner. Most families live within half an hour of the school by bus." },
          { speaker: 'B', voice: 'david', text: "That sounds good. Do I need a visa?" },
          { speaker: 'A', voice: 'zira', text: "For a course of more than six months, yes, but for twelve weeks, you'll need only a short-stay student visa. We can send you a letter of acceptance to support your application." },
          { speaker: 'B', voice: 'david', text: "Excellent. What are the social activities like?" },
          { speaker: 'A', voice: 'zira', text: "There's a programme every week, with trips to places like Oxford and the coast, and in the evenings, there's a film night and a conversation club. Some activities are free, and others cost a few pounds." },
          { speaker: 'B', voice: 'david', text: "Thank you. Could you email me the application form?" },
          { speaker: 'A', voice: 'zira', text: "Of course. What's your email address?" },
          { speaker: 'B', voice: 'david', text: "It's r dot domingues at brmail dot com." },
        ],
        questionGroups: [
          {
            id: 't20-l1-form',
            type: 'form_completion',
            instructionHtml: 'Complete the form below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Lakeside Language School: Enquiry', ''],
              [
                ['Student\'s surname', '{{q1}}'],
                ['Country', '{{q2}}'],
                ['Course', '{{q3}} course'],
                ['Length', '{{q4}} weeks'],
                ['Start date', '{{q5}} January'],
                ['Lessons per week', '{{q6}} hours'],
                ['Class size', 'up to {{q7}} students'],
                ['Course fee', '£{{q8}}'],
                ['Host family cost per week', '£{{q9}}'],
                ['Needs', 'short-stay student {{q10}}'],
              ]
            ),
            questions: [
              q(1, null, ['domingues'], 'Spelled out: D-O-M-I-N-G-U-E-S.'),
              q(2, null, ['brazil'], '"I\'m from Brazil".'),
              q(3, null, ['intensive'], '"an intensive course".'),
              q(4, null, ['12', 'twelve'], '"twelve weeks".'),
              q(5, null, ['8', 'eighth', '8th'], '"the eighth of January".'),
              q(6, null, ['25', 'twenty-five', 'twenty five'], '"twenty-five hours of lessons a week".'),
              q(7, null, ['12', 'twelve'], '"Most classes have twelve students".'),
              q(8, null, ['3200', '3,200', 'three thousand two hundred'], '"three thousand two hundred pounds".'),
              q(9, null, ['110', 'a hundred and ten', 'one hundred and ten'], '"a hundred and ten pounds a week".'),
              q(10, null, ['visa'], '"a short-stay student visa".'),
            ],
          },
        ],
      },
      {
        order: 2,
        contextText: 'You will hear a guide talking to visitors at the start of a tour of a botanical garden.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Good morning, everyone, and welcome to Kingsbridge Botanical Garden. I'm Patrick, and I'll be taking you around the main sections this morning." },
          { speaker: 'A', voice: 'zira', text: "The garden was founded in eighteen forty-six on land donated by a local landowner, who wanted to grow plants brought back from expeditions overseas. Today, it covers forty hectares and contains more than eight thousand different plants, from every continent except Antarctica." },
          { speaker: 'A', voice: 'zira', text: "We're starting in the Temperate House, which is the large glass building in front of you. It was built in eighteen seventy and restored ten years ago, and it contains plants from Mediterranean climates, such as olives and citrus trees. The oldest plant here is a palm that was planted in eighteen fifty-two." },
          { speaker: 'A', voice: 'zira', text: "Next, we'll walk through the Rose Garden, which is at its best in June and July, and on to the Herb Garden, where you can touch and smell many plants used in cooking and medicine. The plants are labelled with their uses, and you're welcome to taste the mint, but please don't pick anything else." },
          { speaker: 'A', voice: 'zira', text: "We'll then reach the Tropical House. It's kept at twenty-eight degrees, with high humidity, so you may want to take off your coat. It contains orchids, bananas and a giant water lily, whose leaves grow to two metres across and can support the weight of a small child." },
          { speaker: 'A', voice: 'zira', text: "After that, we'll pass the lake, where you can see herons and ducks, and cross the footbridge to the Woodland Walk. The trees here include some of the oldest in the country, such as a cedar that's over three hundred years old." },
          { speaker: 'A', voice: 'zira', text: "The garden isn't only a place to look at plants. It's also a scientific institution, and researchers here study rare species and work to conserve those in danger. In our seed bank, we store seeds from over two thousand species, to protect them from extinction. The seed bank isn't open to the public, but there's a small exhibition about its work in the visitor centre." },
          { speaker: 'A', voice: 'zira', text: "The tour lasts about ninety minutes, and ends at the café, where you can stay for lunch. The garden is open until six in summer, and until four in winter. Please keep to the paths, and remember that the plants are living things, so don't climb on the trees or pick the flowers." },
        ],
        questionGroups: [
          {
            id: 't20-l2-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(11, 'The garden was founded in', ['1816', '1846', '1876'], 'B', '"founded in eighteen forty-six".'),
              mc(12, 'The Temperate House contains', ['tropical orchids', 'plants from Mediterranean climates', 'desert plants'], 'B', '"plants from Mediterranean climates".'),
              mc(13, 'In the Herb Garden, visitors may taste', ['the mint', 'the roses', 'any plant'], 'A', '"you\'re welcome to taste the mint".'),
              mc(14, 'The giant water lily leaves can', ['support the weight of a small child', 'grow up to five metres', 'be picked by visitors'], 'A', '"can support the weight of a small child".'),
              mc(15, 'The seed bank', ['is open to the public', 'stores seeds of over two thousand species', 'is in the Tropical House'], 'B', '"we store seeds from over two thousand species".'),
            ],
          },
          {
            id: 't20-l2-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Kingsbridge Botanical Garden</strong></p><p>• area: {{q16}} hectares<br/>• Temperate House built in {{q17}}<br/>• Tropical House kept at {{q18}} degrees<br/>• Woodland Walk includes a {{q19}} more than three hundred years old<br/>• open until {{q20}} p.m. in summer</p>',
            questions: [
              q(16, null, ['40', 'forty'], '"forty hectares".'),
              q(17, null, ['1870'], '"built in eighteen seventy".'),
              q(18, null, ['28', 'twenty-eight', 'twenty eight'], '"twenty-eight degrees".'),
              q(19, null, ['cedar'], '"a cedar that\'s over three hundred years old".'),
              q(20, null, ['6', 'six'], '"open until six in summer".'),
            ],
          },
        ],
      },
      {
        order: 3,
        contextText: 'You will hear two environmental science students, Hana and Tariq, planning a field trip to a wetland with their tutor.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david2', text: "Let's plan the field trip to Fenwick Marsh. Hana, you've checked the transport?" },
          { speaker: 'B', voice: 'zira', text: "Yes. A minibus will collect us from the university at seven-thirty, and it takes about an hour and a half to reach the marsh. It costs nine pounds each, which I'll collect on Thursday." },
          { speaker: 'A', voice: 'david2', text: "Good. And the weather forecast?" },
          { speaker: 'C', voice: 'david', text: "Cold but dry. We should all wear waterproof boots, because the ground will be muddy, and layers of clothing, as it's very exposed." },
          { speaker: 'A', voice: 'david2', text: "Right. Now, what will you be doing? Tariq?" },
          { speaker: 'C', voice: 'david', text: "We're going to survey the plant species along three lines, called transects, running from the edge of the marsh into the centre. At every five metres, we'll record which plants are present inside a one-metre square frame." },
          { speaker: 'A', voice: 'david2', text: "That's called a quadrat. And Hana, you'll be measuring the water?" },
          { speaker: 'B', voice: 'zira', text: "Yes. I'll measure how salty it is, and its acidity, at each point, and I'll also record its depth, using a measuring stick." },
          { speaker: 'A', voice: 'david2', text: "Excellent. What do you expect to find?" },
          { speaker: 'B', voice: 'zira', text: "We expect that plants that tolerate salt will grow near the sea, and that a different group will dominate where the water is fresher." },
          { speaker: 'A', voice: 'david2', text: "Good. You should also record the birds you see, because the marsh is famous for its waders. There's a bird hide at the north end, where you can rest, and there are binoculars in the department store." },
          { speaker: 'C', voice: 'david', text: "Is it safe? I've heard that the tide comes in very fast." },
          { speaker: 'A', voice: 'david2', text: "That's true. High tide is at two-fifteen, so you must be back on the path by one o'clock. Keep in pairs, carry a whistle, and make sure that someone has a mobile phone, although the signal is poor." },
          { speaker: 'B', voice: 'zira', text: "What should we do with the results?" },
          { speaker: 'A', voice: 'david2', text: "Enter them into a spreadsheet the same evening, while you remember the details, and then write a report of two thousand words. It's due three weeks after the trip." },
          { speaker: 'C', voice: 'david', text: "What about photographs?" },
          { speaker: 'A', voice: 'david2', text: "Take plenty, especially of each quadrat, but don't pick any plants, since the marsh is a protected site." },
        ],
        questionGroups: [
          {
            id: 't20-l3-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(21, 'The minibus will collect the students at', ['7.00', '7.30', '8.30'], 'B', '"at seven-thirty".'),
              mc(22, 'How much does the transport cost each?', ['£5', '£9', '£19'], 'B', '"nine pounds each".'),
              mc(23, 'The students should wear', ['sandals', 'waterproof boots', 'shorts'], 'B', '"waterproof boots".'),
              mc(24, 'How often will Tariq record plants along the transects?', ['every metre', 'every five metres', 'every ten metres'], 'B', '"At every five metres".'),
              mc(25, 'What will Hana measure?', ['the salt and acidity of the water', 'the temperature of the air', 'the speed of the wind'], 'A', '"how salty it is, and its acidity".'),
            ],
          },
          {
            id: 't20-l3-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Safety and follow-up</strong></p><p>• high tide at {{q26}}; be back on the path by 1 o\'clock<br/>• keep in pairs and carry a {{q27}}<br/>• mobile phone signal is {{q28}}<br/>• enter results into a spreadsheet the {{q29}}<br/>• report of {{q30}} words due three weeks after the trip</p>',
            questions: [
              q(26, null, ['2.15', '2:15', 'two-fifteen', 'two fifteen', 'quarter past two', '14:15'], '"High tide is at two-fifteen".'),
              q(27, null, ['whistle'], '"carry a whistle".'),
              q(28, null, ['poor'], '"the signal is poor".'),
              q(29, null, ['same evening'], '"the same evening".'),
              q(30, null, ['2000', '2,000', 'two thousand'], '"a report of two thousand words".'),
            ],
          },
        ],
      },
      {
        order: 4,
        contextText: 'You will hear part of a lecture about the global coffee trade.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Coffee is one of the most widely traded commodities in the world, second only to oil in some measures, and it's drunk in every country. Yet the people who grow it are among the poorest in the food chain. Today I'll look at how the industry works." },
          { speaker: 'A', voice: 'david', text: "Coffee is grown in a belt around the equator, known as the coffee belt, in countries such as Brazil, Vietnam, Colombia and Ethiopia. Brazil alone produces about a third of the world's coffee. There are two main species. Arabica, which makes up about sixty per cent of production, is considered to have a better flavour, but it is delicate and grows best at high altitudes. Robusta is hardier and higher in caffeine, and is often used in instant coffee." },
          { speaker: 'A', voice: 'david', text: "About twenty-five million farmers grow coffee, and most of them have small farms of less than two hectares. They sell their beans, often to a local trader, who sells them to an exporter, and from there, the beans pass through roasters, distributors and retailers. At each stage, someone takes a share of the price." },
          { speaker: 'A', voice: 'david', text: "The price of coffee is set on commodity exchanges in New York and London, and it fluctuates widely, depending on the weather in Brazil, the state of the economy and the actions of speculators. When prices fall, farmers may receive less than it costs them to grow the crop. Typically, farmers receive only about ten per cent of the price paid by the consumer for a cup of coffee." },
          { speaker: 'A', voice: 'david', text: "Various schemes aim to improve the position of growers. Fair trade guarantees a minimum price and an additional premium to be spent on community projects, such as schools and clinics. Another approach is direct trade, in which roasters buy from farms directly and pay a higher price for quality. Critics of fair trade say that the benefits are small, because only a fraction of certified coffee is sold at the premium price." },
          { speaker: 'A', voice: 'david', text: "Climate change is an increasing threat. Coffee plants are sensitive to temperature, and as the world warms, the areas suitable for Arabica may shrink by up to half by the middle of the century. Some growers have moved their plantations to higher ground, while others are planting shade trees, which keep the plants cooler and improve the soil." },
          { speaker: 'A', voice: 'david', text: "Consumers also have a part to play. The rise of specialty coffee shops has encouraged interest in where beans come from, and more people are prepared to pay extra for ethically produced coffee. In future, transparency, for example through labels that show the farm and the price paid, may allow buyers to see exactly where their money goes." },
        ],
        questionGroups: [
          {
            id: 't20-l4-table',
            type: 'table_completion',
            instructionHtml: 'Complete the table below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Topic', 'Notes'],
              [
                ['Where coffee is grown', 'the coffee {{q31}} around the equator; Brazil produces about a third of the world\'s coffee'],
                ['Arabica', 'about {{q32}} per cent of production; better flavour but delicate; grows at high {{q33}}'],
                ['Robusta', 'hardier and higher in {{q34}}; often used in instant coffee'],
                ['Farmers', 'about 25 million; most have farms of less than {{q35}} hectares'],
                ['Supply chain', 'local trader, exporter, {{q36}}, distributors and retailers'],
                ['Price', 'set on commodity exchanges in New York and {{q37}}; farmers get about {{q38}} per cent of the price of a cup'],
                ['Fair trade', 'guarantees a minimum price and a {{q39}} for community projects'],
                ['Climate change', 'areas suitable for Arabica may shrink by up to {{q40}} by mid-century'],
              ]
            ),
            questions: [
              q(31, null, ['belt'], '"known as the coffee belt".'),
              q(32, null, ['60', 'sixty'], '"about sixty per cent of production".'),
              q(33, null, ['altitudes', 'altitude'], '"grows best at high altitudes".'),
              q(34, null, ['caffeine'], '"higher in caffeine".'),
              q(35, null, ['2', 'two'], '"less than two hectares".'),
              q(36, null, ['roasters'], '"through roasters, distributors and retailers".'),
              q(37, null, ['london'], '"in New York and London".'),
              q(38, null, ['10', 'ten'], '"only about ten per cent".'),
              q(39, null, ['premium'], '"an additional premium".'),
              q(40, null, ['half', 'a half', 'one half'], '"shrink by up to half".'),
            ],
          },
        ],
      },
    ],
  },

  writing: {
    durationSec: 3600,
    task1: {
      order: 1,
      minWords: 150,
      recommendedMin: 20,
      promptHtml:
        '<p>The graph below shows the number of people taking part in competitive video gaming tournaments in four regions between 2015 and 2025.</p><p>Summarise the information by selecting and reporting the main features, and make comparisons where relevant.</p>',
      chart: {
        chartType: 'line',
        title: 'Participants in gaming tournaments (thousands)',
        unit: 'thousands',
        categories: ['2015', '2017', '2019', '2021', '2023', '2025'],
        xAxisLabel: 'Year',
        yAxisLabel: 'Participants (thousands)',
        series: [
          { name: 'Asia', data: [120, 210, 340, 460, 590, 720] },
          { name: 'Europe', data: [80, 130, 190, 240, 300, 350] },
          { name: 'North America', data: [70, 120, 200, 210, 260, 290] },
          { name: 'South America', data: [15, 30, 60, 95, 140, 200] },
        ],
      },
    },
    task2: {
      order: 2,
      minWords: 250,
      recommendedMin: 40,
      promptHtml:
        '<p>Some people regard competitive video gaming as a real sport, while others think it should not be treated as one.</p><p>Discuss both views and give your own opinion.</p>',
    },
  },
};
