// Original IELTS-style practice content (NOT copied or paraphrased from any real
// Cambridge/IELTS book). Only the exam STRUCTURE — section order, question types,
// question counts and word limits — follows a standard Academic test layout; every
// topic, passage, transcript, question and answer is written from scratch. See
// practice-test-2.mjs for the shared format notes.
import { table, TFNG_INSTRUCTION } from './_html.mjs';

export default {
  slug: 'vocably-practice-test-26',
  title: 'Vocably Practice Test 26',
  difficulty: 'medium',

  reading: {
    durationSec: 3600,
    passages: [
      {
        order: 1,
        title: 'Letting rivers run free',
        subtitle: 'Read the text and answer questions 1-13.',
        paragraphs: [
          { label: 'A', html: "<p>For most of the twentieth century, building a dam was seen as a sign of progress. Dams provided electricity, stored water for farms and cities, and protected towns from floods. Across Europe and North America, tens of thousands were built, from enormous concrete walls hundreds of metres high to small weirs across streams. In recent decades, however, a growing number of dams have been deliberately removed, and river restoration has become one of the most active areas of environmental work. What was once celebrated as the taming of nature is now often described as a mistake to be corrected, and engineers who spent their careers building dams are sometimes asked to advise on how best to dismantle them. This shift reflects a broader change in the way societies think about rivers: not simply as sources of water and power, but as living systems whose health matters in its own right.</p>" },
          { label: 'B', html: "<p>The reasons are partly practical. Many dams were built for purposes that no longer exist, such as powering water mills or supplying factories that have long since closed. Others are old and in poor condition, and the cost of repairing them is often greater than the cost of taking them down. In Europe alone, it has been estimated that there are more than a million barriers on rivers, many of them small, forgotten structures that serve no purpose at all. Some are so overgrown with vegetation that local people are unaware they exist, and in many cases nobody is even sure who owns them. Old dams can also be dangerous: if a neglected structure fails during a storm, the sudden release of water can damage property and endanger lives downstream. For owners, removal can therefore be a way of avoiding both repair bills and legal responsibility.</p>" },
          { label: 'C', html: "<p>The environmental case is equally strong. Dams block the movement of fish, many of which must travel upstream to breed. They trap sediment, the sand and gravel that rivers normally carry downstream, so that beaches and river mouths below the dam are starved of material and begin to erode. The still water behind a dam warms up in summer and may contain less oxygen, harming species adapted to cool, flowing water. Some fish passes, channels designed to let fish swim around dams, have been built, but many work poorly. Some species, such as eels and lampreys, are unable to use them at all, while others become exhausted by the effort and are caught by predators waiting at the top. Scientists have found that populations of migratory fish in European rivers have fallen by more than three quarters since 1970, and blocked rivers are considered one of the main causes of this decline.</p>" },
          { label: 'D', html: "<p>The largest dam removal project so far took place on the Elwha River in the north-western United States. Two dams, built in the early twentieth century to generate electricity, had blocked salmon from more than a hundred kilometres of river for almost a century. Between 2011 and 2014 both were demolished. The results exceeded expectations. Millions of tonnes of trapped sediment were carried down the river, rebuilding a beach and delta at its mouth, and salmon began to return to the upper river within months, some reaching areas they had not visited for a hundred years. The benefits spread beyond the fish themselves. Bears, otters and eagles, which feed on salmon, became more common along the river, and the nutrients from the bodies of dead fish enriched the soil of the surrounding forest. The project has since become a model studied by engineers and ecologists from many other countries.</p>" },
          { label: 'E', html: "<p>Dam removal is not always simple. Sediment released too quickly can bury the habitats of fish and insects downstream, and in some cases it contains pollutants from past industrial activity. Local people sometimes oppose removal because they value the lakes that dams have created, which may have become popular for fishing and boating, or because they fear that removal will increase the risk of flooding. Careful planning, including gradual removal and consultation with communities, is therefore essential. Experts also stress the need to monitor rivers for years after a dam has gone, since recovery can be slow and unpredictable, and lessons learned from one project can help to improve the next. Where a dam still provides real benefits, such as a reliable water supply, removal may not be appropriate at all, and the aim is instead to reduce its impact on wildlife.</p>" },
        ],
        questionGroups: [
          {
            id: 't26-r1-headings',
            type: 'matching_headings',
            instructionHtml: 'Reading Passage 1 has five paragraphs, A-E. Choose the correct heading for each paragraph from the list of headings below.',
            bank: [
              { key: 'i', text: 'Harm to the natural environment' },
              { key: 'ii', text: 'A change of attitude' },
              { key: 'iii', text: 'The challenges of removal' },
              { key: 'iv', text: 'A dramatic example of recovery' },
              { key: 'v', text: 'Dams that are no longer needed' },
              { key: 'vi', text: 'The cost of building new dams' },
              { key: 'vii', text: 'Electricity without dams' },
              { key: 'viii', text: 'Protecting towns from floods' },
            ],
            questions: [
              { number: 1, promptHtml: 'Paragraph A', answer: { accepted: ['ii'] }, explanationHtml: 'Paragraph A: dams were "a sign of progress", but now many are being removed.', locatorParagraph: 'A' },
              { number: 2, promptHtml: 'Paragraph B', answer: { accepted: ['v'] }, explanationHtml: 'Paragraph B: "Many dams were built for purposes that no longer exist".', locatorParagraph: 'B' },
              { number: 3, promptHtml: 'Paragraph C', answer: { accepted: ['i'] }, explanationHtml: 'Paragraph C: dams block fish, trap sediment and warm the water.', locatorParagraph: 'C' },
              { number: 4, promptHtml: 'Paragraph D', answer: { accepted: ['iv'] }, explanationHtml: 'Paragraph D: the Elwha project, where results "exceeded expectations".', locatorParagraph: 'D' },
              { number: 5, promptHtml: 'Paragraph E', answer: { accepted: ['iii'] }, explanationHtml: 'Paragraph E: "Dam removal is not always simple."', locatorParagraph: 'E' },
            ],
          },
          {
            id: 't26-r1-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              { number: 6, promptHtml: 'Some dams in Europe were built to power water mills.', answer: { accepted: ['TRUE'] }, explanationHtml: 'Paragraph B: "such as powering water mills".' },
              { number: 7, promptHtml: 'Repairing an old dam is always cheaper than removing it.', answer: { accepted: ['FALSE'] }, explanationHtml: 'Paragraph B: repair "is often greater than the cost of taking them down".' },
              { number: 8, promptHtml: 'Most fish passes are highly effective.', answer: { accepted: ['FALSE'] }, explanationHtml: 'Paragraph C: "many work poorly".' },
              { number: 9, promptHtml: 'The Elwha dams were removed at the same time.', answer: { accepted: ['NOT GIVEN'] }, explanationHtml: 'Paragraph D says both were demolished between 2011 and 2014, but not whether simultaneously.' },
              { number: 10, promptHtml: 'Salmon returned to the upper Elwha River quickly.', answer: { accepted: ['TRUE'] }, explanationHtml: 'Paragraph D: "within months".' },
            ],
          },
          {
            id: 't26-r1-matching',
            type: 'matching_features',
            instructionHtml: 'Match each item with the correct description, <strong>A-F</strong>.',
            bank: [
              { key: 'A', text: 'can bury habitats if released too fast' },
              { key: 'B', text: 'were built to generate electricity' },
              { key: 'C', text: 'may be valued for recreation' },
              { key: 'D', text: 'produce more oxygen than rivers' },
              { key: 'E', text: 'were built in the last ten years' },
              { key: 'F', text: 'are always easy to remove' },
            ],
            questions: [
              { number: 11, promptHtml: 'the Elwha dams', answer: { accepted: ['B'] }, explanationHtml: 'Paragraph D: "built ... to generate electricity".' },
              { number: 12, promptHtml: 'trapped sediment', answer: { accepted: ['A'] }, explanationHtml: 'Paragraph E: "Sediment released too quickly can bury the habitats".' },
              { number: 13, promptHtml: 'lakes created by dams', answer: { accepted: ['C'] }, explanationHtml: 'Paragraph E: "popular for fishing and boating".' },
            ],
          },
        ],
      },
      {
        order: 2,
        title: 'The world inside us',
        subtitle: 'Read the text and answer questions 14-26.',
        paragraphs: [
          { label: '', html: "<p>Every human body is home to trillions of microorganisms, most of them bacteria, living on the skin, in the mouth and, above all, in the gut. For much of the history of medicine, bacteria were regarded mainly as enemies, the causes of infections to be fought with antibiotics. In the past twenty years, however, scientists have come to realise that the community of microorganisms in our intestines, known as the gut microbiome, plays a vital role in keeping us healthy. Together, these microbes weigh roughly as much as a small bag of sugar and contain far more genes than the human body itself. Advances in genetic sequencing, which allow researchers to identify bacteria from their DNA without needing to grow them in a laboratory, have made it possible to study this hidden world in detail for the first time, since the majority of gut species cannot survive outside the body.</p>" },
          { label: '', html: "<p>The gut microbiome helps us to digest food, breaking down fibre from plants that our own bodies cannot process and producing substances that nourish the cells lining the intestine. It also produces certain vitamins and helps to train the immune system to distinguish between harmful invaders and harmless substances. Each person's microbiome is unique, shaped by their genes, their diet, the environment in which they grew up and the medicines they have taken.</p>" },
          { label: '', html: "<p>The microbiome begins to form at birth. Babies born naturally pick up bacteria from their mothers during birth, while those born by caesarean section acquire different bacteria at first, mainly from the skin and the hospital environment. Breastfeeding also shapes the developing microbiome, because breast milk contains sugars that the infant cannot digest but which feed particular beneficial bacteria. By the age of about three, a child's microbiome resembles that of an adult.</p>" },
          { label: '', html: "<p>Researchers have found links between the microbiome and a wide range of conditions, including obesity, diabetes, allergies and some diseases of the digestive system. In one well-known series of experiments, mice raised in completely sterile conditions, without any gut bacteria, were given bacteria from either lean or obese human donors. The mice that received bacteria from obese donors gained more fat, even though all the mice ate the same diet.</p>" },
          { label: '', html: "<p>Some scientists have gone further, suggesting that the microbiome may even influence mood and behaviour, through chemical signals that travel between the gut and the brain. This idea has attracted great public interest, but much of the evidence so far comes from studies of animals, and it is not yet clear how far the findings apply to humans.</p>" },
          { label: '', html: "<p>What can people do to maintain a healthy microbiome? Most researchers agree that diet is the most important factor. A varied diet rich in fibre, from vegetables, fruit, beans and whole grains, supports a greater diversity of bacteria, which is generally associated with better health. Fermented foods, such as yoghurt and some pickled vegetables, may also be beneficial. By contrast, diets high in processed food tend to reduce diversity. Antibiotics, while often essential, can kill beneficial bacteria along with harmful ones, and doctors are increasingly careful to prescribe them only when necessary.</p>" },
          { label: '', html: "<p>Supplements containing live bacteria, known as probiotics, are now widely sold, often with ambitious claims. The evidence for their benefits is mixed: some appear to help with specific conditions, such as diarrhoea caused by antibiotics, but for healthy people there is little proof that they make a significant difference. Scientists warn that the microbiome is extremely complex, and that adding a few species of bacteria in a capsule is unlikely to change it in a lasting way. For now, the best advice remains simple: eat a wide variety of plant foods.</p>" },
          { label: '', html: "<p>Looking ahead, many researchers believe that the microbiome could transform medicine. Some imagine a future in which a simple test of a patient's gut bacteria helps doctors to choose the most effective treatment or diet for that individual. Already, a procedure in which bacteria from a healthy donor are transferred to a patient has proved remarkably successful against one stubborn intestinal infection that often fails to respond to antibiotics. Others urge caution, pointing out that the field has attracted a great deal of commercial interest and that early findings have sometimes been exaggerated in the media. What is clear is that the old view of bacteria as simply germs to be destroyed has been replaced by a more complicated picture, in which humans and microbes depend on each other in ways that are only beginning to be understood.</p>" },
        ],
        questionGroups: [
          {
            id: 't26-r2-summary',
            type: 'summary_completion_bank',
            instructionHtml: 'Complete the summary using the list of words, A-Q, below.',
            bankReusable: false,
            bank: [
              { key: 'A', text: 'fibre' },
              { key: 'B', text: 'vitamins' },
              { key: 'C', text: 'immune' },
              { key: 'D', text: 'genes' },
              { key: 'E', text: 'birth' },
              { key: 'F', text: 'skin' },
              { key: 'G', text: 'sugars' },
              { key: 'H', text: 'three' },
              { key: 'I', text: 'sterile' },
              { key: 'J', text: 'fat' },
              { key: 'K', text: 'protein' },
              { key: 'L', text: 'ten' },
              { key: 'M', text: 'nervous' },
              { key: 'N', text: 'antibiotics' },
              { key: 'O', text: 'water' },
              { key: 'P', text: 'salt' },
              { key: 'Q', text: 'muscle' },
            ],
            stemHtml:
              '<p><strong>The gut microbiome</strong></p><p>Gut bacteria break down {{q14}} from plants and produce some {{q15}}. They also help to train the {{q16}} system. Each person\'s microbiome is influenced by factors including their {{q17}} and diet. The microbiome starts to develop at {{q18}}; babies born by caesarean section first acquire bacteria mainly from the {{q19}}. Breast milk contains {{q20}} that feed useful bacteria. By the age of {{q21}}, a child\'s microbiome is similar to an adult\'s. In experiments, mice raised in {{q22}} conditions were given bacteria from human donors.</p>',
            questions: [
              { number: 14, answer: { accepted: ['A'] }, explanationHtml: 'Paragraph 2: "breaking down fibre from plants".' },
              { number: 15, answer: { accepted: ['B'] }, explanationHtml: 'Paragraph 2: "It also produces certain vitamins".' },
              { number: 16, answer: { accepted: ['C'] }, explanationHtml: 'Paragraph 2: "helps to train the immune system".' },
              { number: 17, answer: { accepted: ['D'] }, explanationHtml: 'Paragraph 2: "shaped by their genes, their diet".' },
              { number: 18, answer: { accepted: ['E'] }, explanationHtml: 'Paragraph 3: "The microbiome begins to form at birth."' },
              { number: 19, answer: { accepted: ['F'] }, explanationHtml: 'Paragraph 3: "mainly from the skin and the hospital environment".' },
              { number: 20, answer: { accepted: ['G'] }, explanationHtml: 'Paragraph 3: "breast milk contains sugars".' },
              { number: 21, answer: { accepted: ['H'] }, explanationHtml: 'Paragraph 3: "By the age of about three".' },
              { number: 22, answer: { accepted: ['I'] }, explanationHtml: 'Paragraph 4: "mice raised in completely sterile conditions".' },
            ],
          },
          {
            id: 't26-r2-endings',
            type: 'matching_sentence_endings',
            instructionHtml: 'Complete each sentence with the correct ending, A-H, below.',
            bank: [
              { key: 'A', text: 'is mostly based on animal studies.' },
              { key: 'B', text: 'can kill useful bacteria as well as harmful ones.' },
              { key: 'C', text: 'tend to reduce the diversity of gut bacteria.' },
              { key: 'D', text: 'have little proven benefit for healthy people.' },
              { key: 'E', text: 'always improve mood.' },
              { key: 'F', text: 'is identical in members of the same family.' },
              { key: 'G', text: 'should be avoided completely.' },
              { key: 'H', text: 'cure most allergies.' },
            ],
            questions: [
              { number: 23, promptHtml: 'The evidence that the microbiome affects behaviour', answer: { accepted: ['A'] }, explanationHtml: 'Paragraph 5: "much of the evidence so far comes from studies of animals".' },
              { number: 24, promptHtml: 'Diets high in processed food', answer: { accepted: ['C'] }, explanationHtml: 'Paragraph 6: they "tend to reduce diversity".' },
              { number: 25, promptHtml: 'Antibiotics', answer: { accepted: ['B'] }, explanationHtml: 'Paragraph 6: they "can kill beneficial bacteria along with harmful ones".' },
              { number: 26, promptHtml: 'Probiotic supplements', answer: { accepted: ['D'] }, explanationHtml: 'Paragraph 7: "for healthy people there is little proof that they make a significant difference".' },
            ],
          },
        ],
      },
      {
        order: 3,
        title: 'Taming the horse',
        subtitle: 'Read the text and answer questions 27-40.',
        paragraphs: [
          { label: '', html: "<p>Few animals have changed human history as profoundly as the horse. For thousands of years, horses carried people and goods, pulled ploughs and wagons, and carried soldiers into battle. They allowed empires to expand, languages and ideas to spread, and trade to flourish across vast distances. Yet where and when horses were first domesticated has been one of the most difficult questions in archaeology. Other animals, such as dogs, sheep and cattle, were domesticated much earlier, and their histories are comparatively well understood. The horse, by contrast, seems to have entered human life relatively late, and the evidence for its earliest use has been scattered, incomplete and open to very different interpretations.</p>" },
          { label: '', html: "<p>Part of the difficulty is that the bones of domestic horses look very similar to those of wild horses, which were hunted for meat long before they were tamed. Finding horse bones at an ancient settlement does not, therefore, show that the people who lived there kept horses rather than hunted them. Archaeologists have had to look for other clues, such as signs of wear on horses' teeth caused by a bit, the metal or bone mouthpiece used to control a horse, or the remains of fences and enclosures.</p>" },
          { label: '', html: "<p>For many years, the strongest candidate for the earliest domestication was a culture in what is now northern Kazakhstan, where people lived about five and a half thousand years ago. At settlements belonging to this culture, archaeologists found enormous numbers of horse bones, traces of fat from horse milk in pottery, and possible signs of bit wear on teeth. Many experts concluded that these people had been the first to keep horses. Some even suggested that they rode them, although this was harder to prove, since riding leaves few traces that survive for thousands of years. The theory appeared in textbooks and museum displays, and for a generation it was widely accepted.</p>" },
          { label: '', html: "<p>Genetic research has since complicated this picture. When scientists analysed DNA from the Kazakh horses, they found that these animals were not the ancestors of modern domestic horses. Instead, they were related to Przewalski's horses, a population that survives today in Mongolia and was long believed to be the last truly wild horse. The new evidence suggested that Przewalski's horses are in fact the descendants of these early domesticated animals, which later returned to the wild.</p>" },
          { label: '', html: "<p>So where did modern domestic horses come from? In 2021, a large international team published an analysis of DNA from the remains of more than two hundred ancient horses across Europe and Asia. They concluded that the ancestors of today's horses were domesticated in the grasslands north of the Black Sea and the Caspian Sea, in what is now south-western Russia, around four thousand two hundred years ago. From there, these horses spread with remarkable speed, replacing other horse populations across Europe and Asia within a few centuries.</p>" },
          { label: '', html: "<p>The researchers identified two genetic changes that may explain this success. One was associated with a calmer temperament, which would have made the animals easier to handle; the other with a stronger back, which would have made them better suited to carrying heavy loads. The spread of these horses coincided with the appearance of light, fast chariots with spoked wheels, which transformed warfare across the region.</p>" },
          { label: '', html: "<p>The story of domestication is still being written, and new discoveries may yet change it. But the combination of archaeology and genetics has already overturned several long-held assumptions, and it shows how much can be learned when different sciences are brought together to address the same question. Archaeologists provide the context: where bones were found, how old they are and what else lay beside them. Geneticists, meanwhile, can trace relationships between populations that no visual examination of bones could reveal. Neither discipline alone could have produced the picture that is now emerging. Many questions remain unanswered, including exactly when people first began to ride horses and how the earliest riders controlled them. As more ancient remains are analysed, and as techniques for extracting DNA from old bones continue to improve, researchers expect the history of this remarkable partnership between humans and animals to become clearer still.</p>" },
        ],
        questionGroups: [
          {
            id: 't26-r3-endings',
            type: 'matching_sentence_endings',
            instructionHtml: 'Complete each sentence with the correct ending, A-G, below.',
            bank: [
              { key: 'A', text: 'do not prove that horses were kept by people.' },
              { key: 'B', text: 'were the ancestors of modern domestic horses.' },
              { key: 'C', text: 'is caused by the use of a bit.' },
              { key: 'D', text: 'may be descended from early domestic horses.' },
              { key: 'E', text: 'made horses easier to handle.' },
              { key: 'F', text: 'were used only for meat.' },
              { key: 'G', text: 'changed the nature of warfare.' },
            ],
            questions: [
              { number: 27, promptHtml: 'Horse bones found at a settlement', answer: { accepted: ['A'] }, explanationHtml: 'Paragraph 2: they do "not ... show that the people who lived there kept horses".' },
              { number: 28, promptHtml: 'A certain kind of damage to horses\' teeth', answer: { accepted: ['C'] }, explanationHtml: 'Paragraph 2: "signs of wear on horses\' teeth caused by a bit".' },
              { number: 29, promptHtml: 'Przewalski\'s horses', answer: { accepted: ['D'] }, explanationHtml: 'Paragraph 4: they "are in fact the descendants of these early domesticated animals".' },
              { number: 30, promptHtml: 'A genetic change linked to temperament', answer: { accepted: ['E'] }, explanationHtml: 'Paragraph 6: "a calmer temperament, which would have made the animals easier to handle".' },
              { number: 31, promptHtml: 'Light chariots with spoked wheels', answer: { accepted: ['G'] }, explanationHtml: 'Paragraph 6: they "transformed warfare".' },
            ],
          },
          {
            id: 't26-r3-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              { number: 32, promptHtml: 'Wild horses were hunted before they were domesticated.', answer: { accepted: ['TRUE'] }, explanationHtml: 'Paragraph 2: "hunted for meat long before they were tamed".' },
              { number: 33, promptHtml: 'The bones of wild and domestic horses are easy to tell apart.', answer: { accepted: ['FALSE'] }, explanationHtml: 'Paragraph 2: they "look very similar".' },
              { number: 34, promptHtml: 'The people in northern Kazakhstan used horse milk.', answer: { accepted: ['TRUE'] }, explanationHtml: 'Paragraph 3: "traces of fat from horse milk in pottery".' },
              { number: 35, promptHtml: 'The Kazakh settlements were the largest in Asia at that time.', answer: { accepted: ['NOT GIVEN'] }, explanationHtml: 'The passage does not compare the size of the settlements.' },
              { number: 36, promptHtml: 'Przewalski\'s horses are now found only in zoos.', answer: { accepted: ['FALSE'] }, explanationHtml: 'Paragraph 4: they survive "today in Mongolia".' },
              { number: 37, promptHtml: 'The 2021 study examined over 200 ancient horses.', answer: { accepted: ['TRUE'] }, explanationHtml: 'Paragraph 5: "more than two hundred ancient horses".' },
              { number: 38, promptHtml: 'Modern domestic horses originated around 4,200 years ago.', answer: { accepted: ['TRUE'] }, explanationHtml: 'Paragraph 5: "around four thousand two hundred years ago".' },
              { number: 39, promptHtml: 'The new horses took thousands of years to spread across Europe and Asia.', answer: { accepted: ['FALSE'] }, explanationHtml: 'Paragraph 5: "within a few centuries".' },
              { number: 40, promptHtml: 'Most archaeologists now reject the use of genetic evidence.', answer: { accepted: ['FALSE'] }, explanationHtml: 'Final paragraph praises "the combination of archaeology and genetics".' },
            ],
          },
        ],
      },
    ],
  },

  listening: {
    durationSec: 1800,
    checkTimeSec: 120,
    parts: [
      {
        order: 1,
        contextText: 'You will hear a man phoning a science museum about its evening talks for adults.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Hello, City Science Museum, events desk." },
          { speaker: 'B', voice: 'david', text: "Hi. I saw that you have talks for adults in the evenings. Could you give me some details?" },
          { speaker: 'A', voice: 'zira', text: "Certainly. We call them Science After Dark. They're held every Thursday evening, starting at seven thirty." },
          { speaker: 'B', voice: 'david', text: "And how much are tickets?" },
          { speaker: 'A', voice: 'zira', text: "Eight pounds, or five pounds for museum members." },
          { speaker: 'B', voice: 'david', text: "Where are they held?" },
          { speaker: 'A', voice: 'zira', text: "In the lecture theatre on the second floor. The main entrance is closed in the evening, so please use the side entrance on Mill Lane." },
          { speaker: 'B', voice: 'david', text: "Is there parking?" },
          { speaker: 'A', voice: 'zira', text: "There's no museum car park, but the council car park behind the library is free after six." },
          { speaker: 'B', voice: 'david', text: "And what are the next two talks?" },
          { speaker: 'A', voice: 'zira', text: "Next Thursday, the ninth, it's called 'Secrets of Sleep', given by a neuroscientist from the university. And the following week, on the sixteenth, the talk is 'Life on Mars?', by an astronomer." },
          { speaker: 'B', voice: 'david', text: "Do I need to bring anything?" },
          { speaker: 'A', voice: 'zira', text: "For the sleep talk, nothing special. For the Mars talk, the speaker will be taking people onto the roof afterwards to look at the planets, so bring warm clothes, and binoculars if you have them." },
          { speaker: 'B', voice: 'david', text: "That sounds great. Can I book both?" },
          { speaker: 'A', voice: 'zira', text: "Of course. Can I have your name?" },
          { speaker: 'B', voice: 'david', text: "Mark Lowry." },
        ],
        questionGroups: [
          {
            id: 't26-l1-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml:
              '<p><strong>Science After Dark</strong></p><p>Day: every {{q1}} at 7.30 pm<br/>Tickets: £8; members £{{q2}}<br/>Place: lecture theatre, {{q3}} floor<br/>Entrance: side entrance on {{q4}}<br/>Parking: council car park behind the {{q5}}</p>',
            questions: [
              { number: 1, answer: { accepted: ['thursday'] }, explanationHtml: '"They\'re held every Thursday evening".' },
              { number: 2, answer: { accepted: ['5', 'five'] }, explanationHtml: '"five pounds for museum members".' },
              { number: 3, answer: { accepted: ['second', '2nd'] }, explanationHtml: '"on the second floor".' },
              { number: 4, answer: { accepted: ['mill lane'] }, explanationHtml: '"use the side entrance on Mill Lane".' },
              { number: 5, answer: { accepted: ['library'] }, explanationHtml: '"the council car park behind the library".' },
            ],
          },
          {
            id: 't26-l1-table',
            type: 'table_completion',
            instructionHtml: 'Complete the table below. Write <strong>NO MORE THAN TWO WORDS</strong> for each answer.',
            wordLimit: { maxWords: 2, label: 'NO MORE THAN TWO WORDS' },
            stemHtml: table(
              ['Date', 'Talk', 'Speaker', 'Bring'],
              [
                ['9th', '\'Secrets of {{q6}}\'', 'a {{q7}}', 'nothing special'],
                ['16th', '\'Life on Mars?\'', 'an {{q8}}', '{{q9}} and {{q10}}'],
              ]
            ),
            questions: [
              { number: 6, answer: { accepted: ['sleep'] }, explanationHtml: '"it\'s called \'Secrets of Sleep\'".' },
              { number: 7, answer: { accepted: ['neuroscientist'] }, explanationHtml: '"given by a neuroscientist".' },
              { number: 8, answer: { accepted: ['astronomer'] }, explanationHtml: '"by an astronomer".' },
              { number: 9, answer: { accepted: ['warm clothes'] }, explanationHtml: '"bring warm clothes".' },
              { number: 10, answer: { accepted: ['binoculars'] }, explanationHtml: '"and binoculars if you have them".' },
            ],
          },
        ],
      },
      {
        order: 2,
        contextText: 'You will hear a talk giving information to new visitors at a ski resort.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Welcome to Glenmore Ski Resort. I'm Andy, and I'm going to give you some useful information for your stay." },
          { speaker: 'A', voice: 'david', text: "First, the lifts. The main chairlift starts from the car park at the bottom of the village, and the first lift runs at eight thirty every morning." },
          { speaker: 'A', voice: 'david', text: "The last lift up the mountain leaves at four o'clock, and all slopes close at half past four, so make sure you're heading down by then." },
          { speaker: 'A', voice: 'david', text: "If you need to hire skis or boots, the hire shop is next to the ticket office. It gets very busy in the mornings, so I'd recommend collecting your equipment the evening before." },
          { speaker: 'A', voice: 'david', text: "And please always carry your lift pass in a separate pocket from your phone, because the phone can stop the pass from working at the gates." },
          { speaker: 'A', voice: 'david', text: "Now, the different passes. The day pass lets you use all the lifts for one day. The beginner pass is cheaper, but you can only use the lifts in the nursery area at the bottom." },
          { speaker: 'A', voice: 'david', text: "The afternoon pass is valid from one o'clock, and it's popular with people who want a lie-in." },
          { speaker: 'A', voice: 'david', text: "And the family pass covers two adults and up to three children, but you need to show the children's passports when you buy it, as proof of their age." },
          { speaker: 'A', voice: 'david', text: "If you're buying a pass for five days or more, you need a passport photo, so the pass can't be passed on to someone else." },
          { speaker: 'A', voice: 'david', text: "Finally, if you'd like a break from skiing, there's plenty to do. You can go on a guided snowshoe walk through the forest, or visit the ice rink in the village. And on Tuesday and Friday evenings, there's a trip to the hot springs in the next valley. Unfortunately, the husky sledding we used to offer isn't running this season, and the cable car to the summit restaurant is closed for repairs." },
        ],
        questionGroups: [
          {
            id: 't26-l2-sentence',
            type: 'sentence_completion',
            instructionHtml: 'Complete the sentences below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            questions: [
              { number: 11, promptHtml: 'The main chairlift starts from the {{q11}}.', answer: { accepted: ['car park'] }, explanationHtml: '"The main chairlift starts from the car park".' },
              { number: 12, promptHtml: 'The last lift up leaves at {{q12}}.', answer: { accepted: ['4', '4.00', 'four', '4 pm', "four o'clock"] }, explanationHtml: '"The last lift up the mountain leaves at four o\'clock".' },
              { number: 13, promptHtml: 'It is best to collect hired equipment {{q13}}.', answer: { accepted: ['the evening before', 'evening before'] }, explanationHtml: '"collecting your equipment the evening before".' },
              { number: 14, promptHtml: 'Keep your lift pass away from your {{q14}}.', answer: { accepted: ['phone'] }, explanationHtml: '"carry your lift pass in a separate pocket from your phone".' },
            ],
          },
          {
            id: 't26-l2-table',
            type: 'table_completion',
            instructionHtml: 'Complete the table below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Type of pass', 'Details'],
              [
                ['Day', 'all lifts for one day'],
                ['Beginner', 'lifts in the {{q15}} only'],
                ['Afternoon', 'valid from {{q16}}'],
                ['{{q17}}', 'two adults and up to three children; show children\'s {{q18}}'],
                ['5 days or more', 'need a {{q19}}'],
              ]
            ),
            questions: [
              { number: 15, answer: { accepted: ['nursery area'] }, explanationHtml: '"only use the lifts in the nursery area".' },
              { number: 16, answer: { accepted: ['1', '1.00', 'one', '1 pm', "one o'clock"] }, explanationHtml: '"The afternoon pass is valid from one o\'clock".' },
              { number: 17, answer: { accepted: ['family', 'family pass'] }, explanationHtml: '"the family pass covers two adults and up to three children".' },
              { number: 18, answer: { accepted: ['passports'] }, explanationHtml: '"show the children\'s passports".' },
              { number: 19, answer: { accepted: ['passport photo', 'photo'] }, explanationHtml: '"you need a passport photo".' },
            ],
          },
          {
            id: 't26-l2-multi',
            type: 'multiple_choice_multi',
            instructionHtml: 'Choose <strong>THREE</strong> letters, A-G.',
            questions: [
              {
                number: 20,
                promptHtml: 'Which THREE activities are available at present, apart from skiing?',
                options: [
                  { key: 'A', text: 'husky sledding' },
                  { key: 'B', text: 'snowshoe walks' },
                  { key: 'C', text: 'a cable car trip' },
                  { key: 'D', text: 'ice skating' },
                  { key: 'E', text: 'a trip to hot springs' },
                  { key: 'F', text: 'paragliding' },
                  { key: 'G', text: 'a cookery class' },
                ],
                selectCount: 3,
                answer: { accepted: ['B', 'D', 'E'] },
                explanationHtml: '"a guided snowshoe walk", "the ice rink", "a trip to the hot springs". Husky sledding and the cable car are not available.',
              },
            ],
          },
        ],
      },
      {
        order: 3,
        contextText: 'You will hear a student, Laura, discussing her work placement with her university supervisor.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Right, Laura, let's review your progress on the placement at the environmental charity. At our last meeting, we agreed three targets. The first was to learn the charity's database system. How did that go?" },
          { speaker: 'B', voice: 'zira', text: "Well, I did the online training course, and I've been entering data from the volunteers' bird surveys. I spoke to the IT manager, and she's going to show me how to produce reports." },
          { speaker: 'A', voice: 'david', text: "Good. So a further action would be to practise creating a report on your own. The second target was to write an article for their newsletter." },
          { speaker: 'B', voice: 'zira', text: "Yes, I wrote it about the hedgehog project, and I've sent it to the editor. She suggested I should add some photographs." },
          { speaker: 'A', voice: 'david', text: "And the third target was about fundraising?" },
          { speaker: 'B', voice: 'zira', text: "I was supposed to help plan the summer fair, but it's been postponed until September, so there's nothing to do yet." },
          { speaker: 'A', voice: 'david', text: "OK. Let's set some new targets. First, your placement report. The deadline is the end of June. I'd like you to include a section on the charity's structure, with a diagram showing how the departments are organised." },
          { speaker: 'B', voice: 'zira', text: "OK." },
          { speaker: 'A', voice: 'david', text: "Second, a reflective diary. Write a short entry every week about what you've learnt. Keep it to about two hundred words." },
          { speaker: 'B', voice: 'zira', text: "And when should I send you the first draft of the report?" },
          { speaker: 'A', voice: 'david', text: "By the fifteenth of June, so I can give you feedback. And finally, I'd like you to give a short presentation to next year's students about your placement. That'll be in October, and it should be about ten minutes long." },
        ],
        questionGroups: [
          {
            id: 't26-l3-table',
            type: 'table_completion',
            instructionHtml: 'Complete the table below. Write <strong>NO MORE THAN THREE WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 3, maxNumbers: 1, label: 'NO MORE THAN THREE WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Previous target', 'Work completed', 'Further action'],
              [
                ['learn the database', 'did an {{q21}}; entered data from bird surveys', 'practise creating a {{q22}} alone'],
                ['write a newsletter article', 'wrote about the {{q23}}; sent to editor', 'add some {{q24}}'],
                ['help with fundraising', 'summer fair postponed until {{q25}}', 'none yet'],
              ]
            ) + table(
              ['New target', 'Details', 'Timing'],
              [
                ['placement report', 'include a {{q26}} of the departments', 'draft by {{q27}}'],
                ['reflective diary', 'about {{q28}} words each week', 'weekly'],
                ['presentation to new students', 'about {{q29}} long', 'in {{q30}}'],
              ]
            ),
            questions: [
              { number: 21, answer: { accepted: ['online training course', 'online course', 'training course'] }, explanationHtml: '"I did the online training course".' },
              { number: 22, answer: { accepted: ['report'] }, explanationHtml: '"practise creating a report on your own".' },
              { number: 23, answer: { accepted: ['hedgehog project'] }, explanationHtml: '"I wrote it about the hedgehog project".' },
              { number: 24, answer: { accepted: ['photographs', 'photos'] }, explanationHtml: '"She suggested I should add some photographs."' },
              { number: 25, answer: { accepted: ['september'] }, explanationHtml: '"it\'s been postponed until September".' },
              { number: 26, answer: { accepted: ['diagram'] }, explanationHtml: '"with a diagram showing how the departments are organised".' },
              { number: 27, answer: { accepted: ['15 june', '15th june', 'june 15', 'fifteenth of june', 'the fifteenth of june'] }, explanationHtml: '"By the fifteenth of June".' },
              { number: 28, answer: { accepted: ['200', 'two hundred'] }, explanationHtml: '"Keep it to about two hundred words."' },
              { number: 29, answer: { accepted: ['ten minutes', '10 minutes'] }, explanationHtml: '"it should be about ten minutes long".' },
              { number: 30, answer: { accepted: ['october'] }, explanationHtml: '"That\'ll be in October".' },
            ],
          },
        ],
      },
      {
        order: 4,
        contextText: 'You will hear part of a lecture about the history of the typewriter.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Today's lecture looks at the typewriter, a machine that changed the way people worked for more than a century, and whose influence is still felt every time we use a keyboard." },
          { speaker: 'A', voice: 'zira', text: "There were many attempts to build a writing machine in the eighteenth and early nineteenth centuries, some designed to help blind people write. But none was practical enough to be manufactured in large numbers." },
          { speaker: 'A', voice: 'zira', text: "The first commercially successful typewriter was developed in the United States in the late eighteen sixties by a newspaper editor and printer called Christopher Latham Sholes, working with several partners. After years of experiments, they sold the design to a company that until then had made sewing machines and guns." },
          { speaker: 'A', voice: 'zira', text: "The early machines had a serious problem. When a typist pressed keys quickly, the metal bars carrying the letters often got stuck together. The traditional explanation is that Sholes arranged the keys in the pattern we now call QWERTY in order to separate letters that are often used together, which reduced jams." },
          { speaker: 'A', voice: 'zira', text: "The first machines sold slowly. They were expensive, and they could only type capital letters. Another problem was that typists couldn't see what they were typing, because the letters were printed on the underside of the paper." },
          { speaker: 'A', voice: 'zira', text: "Nevertheless, the typewriter gradually won acceptance in offices. One of its most significant effects was social. Typing became one of the first office jobs widely open to women, and by the early twentieth century most typists in many countries were women." },
          { speaker: 'A', voice: 'zira', text: "Later developments included electric typewriters, which appeared in the nineteen thirties but only became common much later, and a famous model introduced in 1961, which replaced the separate bars with a single rotating ball carrying all the letters." },
          { speaker: 'A', voice: 'zira', text: "The computer eventually replaced the typewriter, of course. But the QWERTY layout has survived, even though the mechanical problem it was designed to solve no longer exists. It's a classic example of what economists call path dependence: once a standard has been widely adopted, it's very difficult to change, even if better alternatives exist." },
        ],
        questionGroups: [
          {
            id: 't26-l4-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, A, B or C.',
            questions: [
              { number: 31, promptHtml: 'Some early writing machines were intended for', options: [{ key: 'A', text: 'blind people.' }, { key: 'B', text: 'children.' }, { key: 'C', text: 'printers.' }], answer: { accepted: ['A'] }, explanationHtml: '"some designed to help blind people write".' },
              { number: 32, promptHtml: 'What was Sholes\'s profession?', options: [{ key: 'A', text: 'engineer' }, { key: 'B', text: 'newspaper editor' }, { key: 'C', text: 'teacher' }], answer: { accepted: ['B'] }, explanationHtml: '"a newspaper editor and printer".' },
              { number: 33, promptHtml: 'The design was sold to a company that had previously made', options: [{ key: 'A', text: 'clocks.' }, { key: 'B', text: 'sewing machines and guns.' }, { key: 'C', text: 'printing presses.' }], answer: { accepted: ['B'] }, explanationHtml: '"a company that until then had made sewing machines and guns".' },
              { number: 34, promptHtml: 'According to the traditional explanation, the QWERTY layout was designed to', options: [{ key: 'A', text: 'make typing faster.' }, { key: 'B', text: 'reduce mechanical jams.' }, { key: 'C', text: 'help beginners learn.' }], answer: { accepted: ['B'] }, explanationHtml: '"to separate letters that are often used together, which reduced jams".' },
              { number: 35, promptHtml: 'What was a limitation of the first machines?', options: [{ key: 'A', text: 'They could only type capital letters.' }, { key: 'B', text: 'They were very heavy.' }, { key: 'C', text: 'They needed electricity.' }], answer: { accepted: ['A'] }, explanationHtml: '"they could only type capital letters".' },
              { number: 36, promptHtml: 'What was a major social effect of the typewriter?', options: [{ key: 'A', text: 'It reduced the number of office jobs.' }, { key: 'B', text: 'It created jobs for women.' }, { key: 'C', text: 'It made newspapers cheaper.' }], answer: { accepted: ['B'] }, explanationHtml: '"Typing became one of the first office jobs widely open to women".' },
              { number: 37, promptHtml: 'The 1961 model used', options: [{ key: 'A', text: 'a single rotating ball.' }, { key: 'B', text: 'a screen.' }, { key: 'C', text: 'separate metal bars.' }], answer: { accepted: ['A'] }, explanationHtml: '"replaced the separate bars with a single rotating ball".' },
            ],
          },
          {
            id: 't26-l4-sentence',
            type: 'sentence_completion',
            instructionHtml: 'Complete the sentences below. Write <strong>NO MORE THAN THREE WORDS</strong> for each answer.',
            wordLimit: { maxWords: 3, label: 'NO MORE THAN THREE WORDS' },
            questions: [
              { number: 38, promptHtml: 'Early typists could not see their work because letters appeared on the {{q38}} of the paper.', answer: { accepted: ['underside'] }, explanationHtml: '"the letters were printed on the underside of the paper".' },
              { number: 39, promptHtml: 'Electric typewriters first appeared in the {{q39}}.', answer: { accepted: ['1930s', 'nineteen thirties'] }, explanationHtml: '"electric typewriters, which appeared in the nineteen thirties".' },
              { number: 40, promptHtml: 'The survival of QWERTY is an example of {{q40}}.', answer: { accepted: ['path dependence'] }, explanationHtml: '"what economists call path dependence".' },
            ],
          },
        ],
      },
    ],
  },

  writing: {
    durationSec: 3600,
    task1: {
      order: 1,
      minWords: 150,
      recommendedMin: 20,
      promptHtml:
        '<p>The chart below shows the average number of minutes per day that adults in one country spent on different leisure activities in 2008 and 2023.</p><p>Summarise the information by selecting and reporting the main features, and make comparisons where relevant.</p>',
      chart: {
        chartType: 'bar',
        title: 'Minutes per day spent on leisure activities',
        unit: 'minutes',
        categories: ['Watching TV', 'Social media', 'Reading', 'Sport and exercise', 'Seeing friends'],
        xAxisLabel: 'Activity',
        yAxisLabel: 'Minutes per day',
        series: [
          { name: '2008', data: [165, 10, 32, 21, 48] },
          { name: '2023', data: [118, 95, 22, 27, 35] },
        ],
      },
    },
    task2: {
      order: 2,
      minWords: 250,
      recommendedMin: 40,
      promptHtml:
        '<p>Some people believe that it is better for young people to go straight to university after leaving school. Others think that they should work or travel for a year first.</p><p>Discuss both these views and give your own opinion.</p>',
    },
  },
};
