// Original IELTS-style practice content (NOT copied or paraphrased from any real
// Cambridge/IELTS book). Only the exam STRUCTURE follows a standard Academic test
// layout; every topic, passage, transcript, question and answer is written from scratch.
import { table, TFNG_INSTRUCTION, YNNG_INSTRUCTION, q, paras, mc, bank } from './_html.mjs';

export default {
  slug: 'vocably-practice-test-22',
  title: 'Vocably Practice Test 22',
  difficulty: 'medium',

  reading: {
    durationSec: 3600,
    passages: [
      {
        order: 1,
        title: 'Stone memories: how fossils form',
        subtitle: 'Read the text and answer questions 1-13.',
        paragraphs: paras(
          ['A', `When a visitor to a museum stands in front of the skeleton of a dinosaur, it is natural to assume that such remains are common. In truth, a fossil is an extremely rare outcome. Only a tiny fraction of the animals and plants that have ever lived were preserved in this way, and of those, only a small proportion have been found. The great majority of organisms die, are eaten or rot away without a trace. Understanding how and why some remains survive is essential for interpreting the fossil record, since it explains what the record can tell us, and what it cannot.`],
          ['B', `Certain conditions greatly increase the chance that an organism will become a fossil. The first is rapid burial. If an animal's body is quickly covered by mud, sand or volcanic ash, it is protected from scavengers and from the weather, and it is cut off from the oxygen that fuels decay. This is why the most common fossils are of creatures that lived in or near water, where sediment is constantly being deposited, such as shellfish, fish and animals that fell into lakes and rivers. The second condition is the presence of hard parts. Bones, teeth and shells are much more durable than skin, muscle or leaves, and they form the great majority of the fossil record.`],
          ['C', `The best-known way in which fossils form is called permineralisation. After burial, groundwater rich in dissolved minerals seeps into the tiny spaces in a bone, a shell or a piece of wood. Over thousands of years, the minerals, such as silica or calcite, are left behind as the water evaporates, filling the pores and making the object harder and heavier, while retaining much of the original structure. In some cases, the original material dissolves altogether, leaving a hollow in the surrounding rock called a mould. If minerals later fill the hollow, they produce a cast, a copy of the original shape in a different substance. Most dinosaur bones in museums are fossils of this kind.`],
          ['D', `Other forms of preservation are rarer, but more revealing. Insects and spiders have been found perfectly preserved in amber, the hardened resin of ancient trees, with their legs and wings intact after forty million years. In the frozen ground of Siberia, entire woolly mammoths have been found with their skin and hair. The tar pits of southern California trapped thousands of animals, which sank into the sticky liquid, and their bones have been preserved in extraordinary numbers. There are also trace fossils, which are not parts of organisms but evidence of their activity, such as footprints, burrows and droppings, and which can tell scientists how an animal moved, lived and fed.`],
          ['E', `The fossil record is therefore biased. Species with hard parts, living in places where sediment accumulates, are heavily over-represented, while those that lived on mountains, in forests or in places where rock is worn away are scarcely represented at all. Soft-bodied creatures, such as jellyfish and worms, are hardly ever preserved. There are, however, a number of sites in which conditions were so favourable that soft tissues were preserved, and these have provided a rare glimpse of ancient life. A famous example is a deposit in the Canadian Rockies, where a landslide buried a shallow sea about five hundred million years ago, preserving hundreds of species of strange animals, many of which have no living relatives.`],
          ['F', `Fossils are of little use unless their age can be established. In the past, geologists used the order in which layers of rock were laid down, with younger layers lying above older ones, and identified layers by the fossils they contained, particularly those of species that lived for a short time and were widespread. Today, a more exact method is available. Some rocks, especially volcanic ones, contain radioactive elements that decay at a known rate, and by measuring how much of the element has changed into its product, scientists can calculate how long ago the rock formed. A fossil lying between two layers of volcanic ash can therefore be dated with a high degree of precision.`],
          ['G', `New technology is now revealing details that could not be seen before. Scanners that use X-rays allow researchers to look inside a fossil without damaging it, revealing the shape of a brain or the structure of an ear. Chemical analysis of feathers, preserved in fine-grained rock, has identified the remains of the structures that produce colour, so that scientists have been able to reconstruct the plumage of a small dinosaur as black, grey and reddish-brown. Every advance of this kind shows that fossils hold more information than the first scientists to study them could have imagined, and that the stones in museums still have much to tell.`]
        ),
        questionGroups: [
          {
            id: 't22-r1-headings',
            type: 'matching_headings',
            instructionHtml: 'Reading Passage 1 has seven paragraphs, A-G. Choose the correct heading for paragraphs B-G from the list of headings below.<br/><em>Example: Paragraph A — ix</em>',
            bank: [
              { key: 'i', text: 'New tools reveal hidden detail' },
              { key: 'ii', text: 'A record with gaps' },
              { key: 'iii', text: 'The hunt for the largest dinosaurs' },
              { key: 'iv', text: 'Putting dates on fossils' },
              { key: 'v', text: 'Unusual ways in which remains survive' },
              { key: 'vi', text: 'Fossil fuels and the modern economy' },
              { key: 'vii', text: 'How minerals turn bone to stone' },
              { key: 'viii', text: 'Ideal conditions for preservation' },
              { key: 'ix', text: 'A rare outcome' },
            ],
            questions: [
              q(1, 'Paragraph B', 'viii', 'Paragraph B: rapid burial and hard parts.', 'B'),
              q(2, 'Paragraph C', 'vii', 'Paragraph C: permineralisation.', 'C'),
              q(3, 'Paragraph D', 'v', 'Paragraph D: amber, ice, tar pits and trace fossils.', 'D'),
              q(4, 'Paragraph E', 'ii', 'Paragraph E: "The fossil record is therefore biased."', 'E'),
              q(5, 'Paragraph F', 'iv', 'Paragraph F: methods of dating fossils.', 'F'),
              q(6, 'Paragraph G', 'i', 'Paragraph G: scanners and chemical analysis.', 'G'),
            ],
          },
          {
            id: 't22-r1-summary',
            type: 'summary_completion',
            instructionHtml: 'Complete the summary of paragraphs C and D below. Choose <strong>ONE WORD ONLY</strong> from the passage for each answer.',
            wordLimit: { maxWords: 1, label: 'ONE WORD ONLY' },
            stemHtml: '<p>After burial, groundwater rich in {{q7}} seeps into the spaces in a bone, leaving behind minerals such as {{q8}} or calcite. This is called {{q9}}. When the original material dissolves, it leaves a {{q10}} in the rock, and if minerals later fill the hollow, they form a {{q11}}. Insects can be perfectly preserved in {{q12}}, while footprints and burrows are known as {{q13}} fossils.</p>',
            questions: [
              q(7, null, ['minerals'], 'Paragraph C: "groundwater rich in dissolved minerals".', 'C'),
              q(8, null, ['silica'], 'Paragraph C: "silica or calcite".', 'C'),
              q(9, null, ['permineralisation', 'permineralization'], 'Paragraph C: "permineralisation".', 'C'),
              q(10, null, ['mould', 'mold'], 'Paragraph C: "a mould".', 'C'),
              q(11, null, ['cast'], 'Paragraph C: "they produce a cast".', 'C'),
              q(12, null, ['amber'], 'Paragraph D: "preserved in amber".', 'D'),
              q(13, null, ['trace'], 'Paragraph D: "trace fossils".', 'D'),
            ],
          },
        ],
      },
      {
        order: 2,
        title: 'What\'s in a name?',
        subtitle: 'Read the text and answer questions 14-26.',
        paragraphs: paras(
          ['A', `Choose a name for a baby, and you are taking part in one of the most powerful trends in society, whether you know it or not. Names go in and out of fashion in the same way as clothes, and with comparable speed. A hundred and forty years ago, a large share of boys were given one of only ten names, and the most popular girl's name might be borne by one girl in every twenty. Today, parents in most countries choose from a much wider range, and the top ten names together account for only a small fraction of births. The fashion for variety is a recent one, and it has made the naming of children more a matter of individual taste than of tradition.`],
          ['B', `Why does fashion change? One theory, sometimes called the pendulum effect, holds that each generation reacts against the one before. Parents are reluctant to give their children names that remind them of their own parents or their contemporaries at school, and so they look further back, to their grandparents' generation, or choose something entirely new. Names that were once common therefore fall away, but they return after about three generations, when they sound fresh again. Linguists have also observed patterns in sound: in English-speaking countries, the proportion of girls' names ending in a vowel has risen steadily over a century, suggesting that some sounds come to seem more attractive than others.`],
          ['C', `Popular culture has an obvious effect. The name of a hero in a film, a character in a television series or a sports star can rise rapidly in popularity within a year or two. A fantasy series that became a worldwide success was followed by an increase in the number of children given the names of its characters, including some that had hardly ever been used before. Not every name benefits, of course: only a small number of the many names that appear in popular series become fashionable, and some of those that are associated with villains or disgraced figures disappear almost entirely.`],
          ['D', `Social class is another factor. Studies in several countries have found that new names are usually introduced by parents from the upper ranks of society, and then spread gradually down the social scale. As a name becomes more widely used, it loses its distinctiveness, and the original adopters abandon it in favour of something new, so that the process begins again. In this way, names act as a kind of badge, marking membership of a group, and then passing from one group to another. This explains why names that are associated with high status in one generation can become ordinary, or even old-fashioned, in the next.`],
          ['E', `Many parents today say that they want their child to have a name that is distinctive but not odd. The desire to stand out has been helped by the internet, which allows parents to search for names in other languages and cultures, and to check that no one else in their town has chosen the same one. It has also encouraged new spellings, in which an old name is given a fresh look. Whether the name makes any difference to a child's prospects is disputed. In one well-known experiment in the United States, researchers sent thousands of identical applications for jobs, with some bearing names that were typical of one ethnic group and some of another, and found that the applications with the names more often associated with the majority received significantly more replies. The result suggests that names can affect the way people are treated, even if they do not determine success.`],
          ['F', `Researchers are helped by the availability of data. In the United States, the Social Security Administration has published the number of babies given each name since 1880, and the information has been turned into interactive charts that allow anyone to trace the rise and fall of a name over more than a century. Similar records exist in other countries. Statisticians have used such data to predict which names will rise in popularity, with some success, by looking at how fast a name is growing and whether its sound resembles that of other rising names. Nevertheless, the predictions are far from perfect: fashion, after all, is a product of millions of separate choices.`],
          ['G', `Choosing a name is, in the end, an act of hope and of belonging. It expresses what parents want for their child, how they see themselves and which community they wish to join. That the choice is so influenced by forces that parents are only dimly aware of is no reason to regret it; on the contrary, it suggests that the name of a child, however private it seems, reflects the wider life of the society in which he or she is born.`]
        ),
        questionGroups: [
          {
            id: 't22-r2-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              q(14, 'Names have always gone in and out of fashion at the same speed.', 'FALSE', 'Paragraph A: names go in and out of fashion "with comparable speed" to clothes; today there is a much wider range than in the past, so fashion is changing.', 'A'),
              q(15, 'In the past, a large share of boys were given one of a small number of popular names.', 'TRUE', 'Paragraph A: "a large share of boys were given one of only ten names".', 'A'),
              q(16, 'Parents tend to avoid names that remind them of their own parents\' generation.', 'TRUE', 'Paragraph B: "reluctant to give their children names that remind them of their own parents".', 'B'),
              q(17, 'The proportion of girls\' names ending in a vowel has risen over a century.', 'TRUE', 'Paragraph B: "has risen steadily over a century".', 'B'),
              q(18, 'All names that appear in popular television series become fashionable.', 'FALSE', 'Paragraph C: "only a small number ... become fashionable".', 'C'),
              q(19, 'Children with unusual spellings of their names are more likely to be successful.', 'NOT GIVEN', 'Paragraph E mentions new spellings but not their effect on success.', 'E'),
            ],
          },
          {
            id: 't22-r2-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B, C or D</strong>.',
            questions: [
              mc(20, 'What does paragraph D suggest about names and social class?', ['Names are chosen at random.', 'New names spread from the upper ranks down and are then abandoned by those who introduced them.', 'Lower classes invent all new names.', 'Names never change class.'], 'B', 'Paragraph D: "spread gradually down the social scale ... the original adopters abandon it".', 'D'),
              mc(21, 'The "pendulum effect" refers to', ['names becoming shorter', 'each generation reacting against the preceding one', 'the movement of families between countries', 'the rise of celebrity names'], 'B', 'Paragraph B: "each generation reacts against the one before".', 'B'),
              mc(22, 'In the experiment described in paragraph E, researchers found that', ['names made no difference', 'applications with some names received more replies than others', 'most applications were rejected', 'applicants with unusual names were favoured'], 'B', 'Paragraph E: applications "received significantly more replies".', 'E'),
              mc(23, 'Names that fall out of favour often return after about', ['ten years', 'one generation', 'three generations', 'a thousand years'], 'C', 'Paragraph B: "return after about three generations".', 'B'),
            ],
          },
          {
            id: 't22-r2-matchinfo',
            type: 'matching_information',
            instructionHtml: 'Reading Passage 2 has seven paragraphs, A-G. Which paragraph contains the following information? <em>Choose the correct letter, A-G.</em>',
            questions: [
              q(24, 'a reference to a source of long-term data on names', 'F', 'Paragraph F: "published the number of babies given each name since 1880".', 'F'),
              q(25, 'a suggestion that many parents want their children to stand out', 'E', 'Paragraph E: "The desire to stand out".', 'E'),
              q(26, 'a reference to the influence of a television series on names', 'C', 'Paragraph C: "A fantasy series that became a worldwide success".', 'C'),
            ],
          },
        ],
      },
      {
        order: 3,
        title: 'The building that thinks',
        subtitle: 'Read the text and answer questions 27-40.',
        paragraphs: paras(
          ['A', `Offices, homes, schools and shops together consume roughly a third of the world's energy and are responsible for an even larger share of the emissions that cause climate change, through heating, cooling, lighting and the manufacture of materials. If the world is to cut its emissions, buildings must therefore be a central part of the solution. One of the most promising ideas is the smart building: a structure fitted with sensors and computer systems that monitor its own condition and adjust its operation automatically to save energy and improve comfort. The idea has been around for decades, but it is only now, as sensors have become cheap and connectivity widespread, that it is entering the mainstream.`],
          ['B', `The simplest forms are already familiar. A motion sensor in a corridor switches off the lights when nobody is there, and a thermostat turns down the heating at night. More advanced systems combine hundreds of sensors that measure temperature, light, humidity and occupancy in every room, and send the information to a central computer, which controls the heating, cooling, ventilation and lighting. Studies of buildings fitted with such systems suggest that they can cut energy use by between ten and thirty per cent, depending on how wasteful the building was to begin with, and that the savings are greatest in offices, where large spaces are heated and lit for people who are often absent.`],
          ['C', `Three technologies are attracting particular interest. The first is the adaptive facade, in which the outer skin of the building responds to the weather. Some windows contain a layer that darkens when the sun is strong, reducing the heat that enters and the need for air conditioning, and lightens again when it is cloudy. Others are shaded by blinds that move during the day to follow the sun. The second is the predictive system, which uses weather forecasts and records of how the building was used in the past to decide when to start heating or cooling, so that a room is at the right temperature when people arrive rather than earlier. The third is the occupant application, which lets people use their phones to report that they are too hot or too cold, or to book a desk, and so to adjust their own surroundings. Researchers have found that people who feel they have some control over their environment are more satisfied with it, even when the temperature is unchanged.`],
          ['D', `Health is another area of interest. Sensors can measure the level of carbon dioxide in a room, which rises when it is crowded and poorly ventilated, and when it does, the system can bring in fresh air. A study that tested office workers in rooms with different qualities of air found that those who worked in well-ventilated rooms scored noticeably better in tests of decision-making than those who worked in rooms where the air was stale, and similar results have been reported for classrooms. Such findings suggest that the economic case for smart buildings may rest as much on the productivity of the people inside as on the savings in energy.`],
          ['E', `There are, however, risks. A smart building collects a great deal of information about the people who use it: when they arrive, where they go, how long they stay in each room and, in some systems, what they say. The data could be valuable to an employer, and dangerous in the hands of criminals. Systems that are connected to the internet can also be attacked, and security experts have warned that poorly protected control systems could allow a hacker to switch off the heating of a hospital or unlock the doors of an office. Designers are therefore being urged to build privacy and security into the systems from the start, rather than adding them afterwards.`],
          ['F', `Cost is another consideration. The equipment and installation for a large building may cost millions, and although the savings may eventually repay the investment, the period required is commonly between three and seven years, which many owners find too long. Old buildings, which account for most of the energy wasted, can be fitted with sensors, but it is more expensive than building them into a new structure, and different manufacturers often use incompatible systems, so that equipment from one company cannot talk to that of another. Standards that allow different devices to work together are being developed, but progress has been slow.`],
          ['G', `In my opinion, the most valuable smart building is not the one with the most sophisticated technology, but the one in which the technology is hardly noticed. Too many systems are so complex that the people who manage them cannot understand them, and they end up switched to manual operation, with the savings lost. The best designs begin with a simple question: what do the people using this building actually need? A building that is well insulated, well ventilated and sensibly arranged will always use less energy than a badly designed one fitted with the latest gadgets, and sensors should be regarded as a means of making good design work better, not as a substitute for it.`]
        ),
        questionGroups: [
          {
            id: 't22-r3-classify',
            type: 'matching_features',
            instructionHtml: 'Look at the following statements (Questions 27-33) and the list of technologies below. Match each statement with the correct technology, <strong>A, B or C</strong>.<br/>You may use any letter more than once.',
            bankReusable: true,
            bank: [
              { key: 'A', text: 'adaptive facades' },
              { key: 'B', text: 'predictive systems' },
              { key: 'C', text: 'occupant applications' },
            ],
            questions: [
              q(27, 'uses weather forecasts to decide when to start heating', 'B', 'Paragraph C: "uses weather forecasts ... to decide when to start heating or cooling".', 'C'),
              q(28, 'lets people report that they are too hot or too cold', 'C', 'Paragraph C: "report that they are too hot or too cold".', 'C'),
              q(29, 'includes windows that darken in strong sun', 'A', 'Paragraph C: "a layer that darkens when the sun is strong".', 'C'),
              q(30, 'can reduce the need for air conditioning', 'A', 'Paragraph C: "reducing the heat that enters and the need for air conditioning".', 'C'),
              q(31, 'relies on records of how the building was used in the past', 'B', 'Paragraph C: "records of how the building was used in the past".', 'C'),
              q(32, 'gives people a sense of control over their surroundings', 'C', 'Paragraph C: "people who feel they have some control".', 'C'),
              q(33, 'includes blinds that move during the day to follow the sun', 'A', 'Paragraph C: "blinds that move during the day to follow the sun".', 'C'),
            ],
          },
          {
            id: 't22-r3-ynng',
            type: 'yes_no_notgiven',
            instructionHtml: YNNG_INSTRUCTION,
            questions: [
              q(34, 'Buildings are responsible for a large share of the world\'s energy use.', 'YES', 'Paragraph A: "roughly a third of the world\'s energy".', 'A'),
              q(35, 'Smart systems reduce energy consumption by thirty per cent in every building.', 'NO', 'Paragraph B: "between ten and thirty per cent, depending on how wasteful the building was".', 'B'),
              q(36, 'Better ventilation can improve the performance of people working in offices.', 'YES', 'Paragraph D: those in well-ventilated rooms "scored noticeably better".', 'D'),
              q(37, 'The data collected in smart buildings could raise concerns about privacy.', 'YES', 'Paragraph E: "The data could be valuable to an employer, and dangerous in the hands of criminals."', 'E'),
              q(38, 'Smart systems always pay for themselves within three years.', 'NO', 'Paragraph F: "commonly between three and seven years".', 'F'),
              q(39, 'Old buildings cannot be made smart.', 'NO', 'Paragraph F: old buildings "can be fitted with sensors".', 'F'),
              q(40, 'Developers should be forbidden from installing cameras in offices.', 'NOT GIVEN', 'Cameras are not discussed.'),
            ],
          },
        ],
      },
    ],
  },

  listening: {
    durationSec: 1800,
    checkTimeSec: 120,
    parts: [
      {
        order: 1,
        contextText: 'You will hear a man phoning a photography club to ask about joining.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Hello, Riverdale Photography Club." },
          { speaker: 'B', voice: 'david', text: "Hello. I saw your leaflet in the library, and I'd like to find out about joining the club." },
          { speaker: 'A', voice: 'zira', text: "Wonderful. We'd be delighted to have you. Could I take your name?" },
          { speaker: 'B', voice: 'david', text: "It's Oscar Lindgren. Lindgren is L-I-N-D-G-R-E-N." },
          { speaker: 'A', voice: 'zira', text: "Thank you. Are you a beginner, or have you been taking photographs for a while?" },
          { speaker: 'B', voice: 'david', text: "I've been using a simple camera for about two years, mostly for landscapes, but I'd like to learn to use my new camera properly." },
          { speaker: 'A', voice: 'zira', text: "That's ideal. We meet every Wednesday evening at seven-thirty in the community hall on Bridge Road. The first half hour is for news and coffee, then there's a talk or a practical session." },
          { speaker: 'B', voice: 'david', text: "What's the subscription?" },
          { speaker: 'A', voice: 'zira', text: "It's forty pounds a year, or twenty-five for students and retired people. You can also pay five pounds for a single evening if you'd like to try us first." },
          { speaker: 'B', voice: 'david', text: "That's good. Are there trips as well?" },
          { speaker: 'A', voice: 'zira', text: "Yes, about once a month, we go to interesting places. Next month, it's a day at a nature reserve on the coast, and in the summer, we have a weekend trip to the Lake District." },
          { speaker: 'B', voice: 'david', text: "I'd love that. Do you hold exhibitions?" },
          { speaker: 'A', voice: 'zira', text: "Every November, we display members' work in the library, and there's a competition with three categories: landscapes, portraits and black-and-white." },
          { speaker: 'B', voice: 'david', text: "Do I need any special equipment?" },
          { speaker: 'A', voice: 'zira', text: "Only your camera, and a tripod for some of the practical sessions. We have a few spare ones that members can borrow." },
          { speaker: 'B', voice: 'david', text: "Thank you. I'll come along next Wednesday." },
          { speaker: 'A', voice: 'zira', text: "Lovely. Ask for Pauline, the secretary. And could I have your address, so that we can send you our programme?" },
          { speaker: 'B', voice: 'david', text: "It's eighteen Mill Lane, Ashford." },
        ],
        questionGroups: [
          {
            id: 't22-l1-form',
            type: 'form_completion',
            instructionHtml: 'Complete the form below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Riverdale Photography Club: Enquiry', ''],
              [
                ['Surname', '{{q1}}'],
                ['Heard about the club in the', '{{q2}}'],
                ['Experience', 'about {{q3}} years; mostly landscapes'],
                ['Meetings', 'every {{q4}} evening at 7.30'],
                ['Place', 'community hall on {{q5}} Road'],
                ['Annual subscription', '£{{q6}}'],
                ['Single evening', '£{{q7}}'],
                ['Next trip', 'a nature reserve on the {{q8}}'],
                ['Exhibition in', '{{q9}}, at the library'],
                ['Address', '{{q10}} Mill Lane, Ashford'],
              ]
            ),
            questions: [
              q(1, null, ['lindgren'], 'Spelled out: L-I-N-D-G-R-E-N.'),
              q(2, null, ['library'], '"your leaflet in the library".'),
              q(3, null, ['2', 'two'], '"for about two years".'),
              q(4, null, ['wednesday'], '"every Wednesday evening".'),
              q(5, null, ['bridge'], '"community hall on Bridge Road".'),
              q(6, null, ['40', 'forty'], '"forty pounds a year".'),
              q(7, null, ['5', 'five'], '"five pounds for a single evening".'),
              q(8, null, ['coast'], '"a nature reserve on the coast".'),
              q(9, null, ['november'], '"Every November".'),
              q(10, null, ['18', 'eighteen'], '"eighteen Mill Lane".'),
            ],
          },
        ],
      },
      {
        order: 2,
        contextText: 'You will hear a presenter talking about the volunteer programme at a city farm.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Hello, everyone, and thank you for coming to this information evening about volunteering at Greenfield City Farm. I'm Lucy, the volunteer coordinator." },
          { speaker: 'A', voice: 'david', text: "The farm opened thirty years ago on a site that had been a rubbish dump. Today, it covers three hectares in the middle of the city, and it has sheep, pigs, goats, chickens and a pair of donkeys. More than forty thousand people visit every year, including school groups, who come to learn where food comes from." },
          { speaker: 'A', voice: 'david', text: "We couldn't run the farm without our volunteers, of whom there are about a hundred and fifty. They work in six areas. The first is animal care, which involves feeding, cleaning out the pens and helping the vet. It starts at seven in the morning, so it suits early risers." },
          { speaker: 'A', voice: 'david', text: "The second is the garden, where we grow vegetables for the farm café. The work includes digging, planting and harvesting, and it's ideal for people who enjoy being outdoors. There's also a team that looks after the orchard, which has over forty apple and pear trees." },
          { speaker: 'A', voice: 'david', text: "Third, there's the education team, who lead tours and activities for school groups. You don't need to be a teacher, but you must enjoy working with children, and all volunteers in this role must have a background check, which takes two weeks." },
          { speaker: 'A', voice: 'david', text: "Fourth, there's the café, which serves lunch and cakes made from our own produce. Fifth, the shop, which sells eggs, vegetables and honey. And sixth, the events team, which organises fairs and festivals, including our harvest festival in October, which raises about ten thousand pounds for the farm." },
          { speaker: 'A', voice: 'david', text: "We ask all volunteers to commit to a minimum of four hours a week for at least three months. You'll receive training in health and safety and, if you work with animals, in animal handling. We provide gloves and boots, but you'll need to bring your own waterproof clothing." },
          { speaker: 'A', voice: 'david', text: "There are no fees, and we can pay your travel costs within the city, up to a limit of five pounds a day. Lunch is provided on days when you work a full shift." },
          { speaker: 'A', voice: 'david', text: "If you'd like to apply, please pick up a form from the table by the door, or fill it in on our website. We'll ring you within a week to arrange a visit. Now, are there any questions?" },
        ],
        questionGroups: [
          {
            id: 't22-l2-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(11, 'Before it became a farm, the site was', ['a market', 'a rubbish dump', 'a school'], 'B', '"a site that had been a rubbish dump".'),
              mc(12, 'How many volunteers does the farm have?', ['about 50', 'about 100', 'about 150'], 'C', '"about a hundred and fifty".'),
              mc(13, 'Animal care volunteers start work at', ['7 a.m.', '9 a.m.', '11 a.m.'], 'A', '"It starts at seven in the morning".'),
              mc(14, 'Volunteers in the education team must', ['be qualified teachers', 'have a background check', 'speak another language'], 'B', '"must have a background check".'),
              mc(15, 'The harvest festival in October raises about', ['£1,000', '£10,000', '£100,000'], 'B', '"about ten thousand pounds".'),
            ],
          },
          {
            id: 't22-l2-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Volunteering at the farm</strong></p><p>• the farm covers {{q16}} hectares<br/>• the orchard has over {{q17}} apple and pear trees<br/>• minimum commitment: {{q18}} hours a week for at least three months<br/>• volunteers must bring their own {{q19}} clothing<br/>• travel costs paid up to £{{q20}} a day</p>',
            questions: [
              q(16, null, ['3', 'three'], '"three hectares".'),
              q(17, null, ['40', 'forty'], '"over forty apple and pear trees".'),
              q(18, null, ['4', 'four'], '"a minimum of four hours a week".'),
              q(19, null, ['waterproof'], '"bring your own waterproof clothing".'),
              q(20, null, ['5', 'five'], '"up to five pounds a day".'),
            ],
          },
        ],
      },
      {
        order: 3,
        contextText: 'You will hear two business students, Ali and Sophie, discussing a case study on a failed product with their tutor.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david2', text: "Good afternoon, both. You're writing a case study on a product that failed. Which one did you choose?" },
          { speaker: 'B', voice: 'zira', text: "A smart mirror that could display the weather and news while you brushed your teeth. The company spent three years developing it, and it was withdrawn after only eight months." },
          { speaker: 'A', voice: 'david2', text: "Interesting. Why did it fail?" },
          { speaker: 'C', voice: 'david', text: "We've found three main reasons. First, the price: it cost six hundred pounds, which was far more than customers were willing to pay for a bathroom gadget." },
          { speaker: 'B', voice: 'zira', text: "Second, there was no clear need. People already had phones in their pockets that did the same things, and they didn't see why they should buy a separate device." },
          { speaker: 'A', voice: 'david2', text: "That's a classic problem: a solution in search of a problem. And the third?" },
          { speaker: 'C', voice: 'david', text: "Technical faults. The screen was damaged by steam, which anyone could have predicted in a bathroom." },
          { speaker: 'A', voice: 'david2', text: "That suggests they did too little testing. Did you find any evidence of market research?" },
          { speaker: 'B', voice: 'zira', text: "Only a survey of two hundred people, all of them employees of the company, so the results were unreliable." },
          { speaker: 'A', voice: 'david2', text: "A good point to emphasise. Now, how will you structure the study?" },
          { speaker: 'C', voice: 'david', text: "We thought of starting with a description of the company, then the product, then an analysis of the failure, and finally some recommendations." },
          { speaker: 'A', voice: 'david2', text: "That's fine, but I'd suggest you use a framework in your analysis, such as the four Ps: product, price, place and promotion. It helps to organise your arguments." },
          { speaker: 'B', voice: 'zira', text: "Should we include a comparison with a successful product?" },
          { speaker: 'A', voice: 'david2', text: "Yes, a short one. Choose a product in the same category, perhaps a fitness tracker, and explain what it did differently." },
          { speaker: 'C', voice: 'david', text: "That's a good idea. How long should the case study be?" },
          { speaker: 'A', voice: 'david2', text: "Three thousand words, and it must include at least eight sources, of which at least three should be academic. The deadline is the twelfth of May." },
          { speaker: 'B', voice: 'zira', text: "And will we present it?" },
          { speaker: 'A', voice: 'david2', text: "Yes, for ten minutes, in the week after the deadline. You'll be marked individually on your part of the presentation." },
        ],
        questionGroups: [
          {
            id: 't22-l3-match',
            type: 'matching_features',
            instructionHtml: 'Which reason for the product\'s failure does each comment describe? Choose the correct letter, <strong>A-E</strong>, next to Questions 21-25.',
            bank: [
              { key: 'A', text: 'The price was too high.' },
              { key: 'B', text: 'There was no clear need.' },
              { key: 'C', text: 'It was damaged by steam.' },
              { key: 'D', text: 'The market research was unreliable.' },
              { key: 'E', text: 'It was launched too late.' },
            ],
            questions: [
              q(21, 'It cost six hundred pounds.', 'A', '"the price: it cost six hundred pounds".'),
              q(22, 'Customers already had phones that did the same things.', 'B', '"no clear need. People already had phones in their pockets".'),
              q(23, 'The screen was faulty in the bathroom.', 'C', '"The screen was damaged by steam".'),
              q(24, 'A survey was made of only company employees.', 'D', '"a survey of two hundred people, all of them employees of the company".'),
              q(25, 'Customers were unwilling to pay so much for a bathroom gadget.', 'A', '"far more than customers were willing to pay".'),
            ],
          },
          {
            id: 't22-l3-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Case study plan</strong></p><p>• product: a smart {{q26}}; withdrawn after {{q27}} months<br/>• use the four {{q28}} as a framework<br/>• compare with a successful product, such as a fitness {{q29}}<br/>• length: 3000 words; deadline: {{q30}} May</p>',
            questions: [
              q(26, null, ['mirror'], '"A smart mirror".'),
              q(27, null, ['8', 'eight'], '"withdrawn after only eight months".'),
              q(28, null, ['ps', "p's", 'ps framework'], '"the four Ps".'),
              q(29, null, ['tracker'], '"perhaps a fitness tracker".'),
              q(30, null, ['12th', 'twelfth', '12'], '"the twelfth of May".'),
            ],
          },
        ],
      },
      {
        order: 4,
        contextText: 'You will hear part of a lecture about how honeybees communicate.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "A honeybee colony contains up to sixty thousand bees, and must make decisions every day: where to find food, when to swarm, where to build a new nest. Today I'll describe how bees communicate, which was the subject of a famous research programme." },
          { speaker: 'A', voice: 'zira', text: "In the nineteen-thirties, an Austrian scientist, Karl von Frisch, noticed that when a forager bee found a good source of nectar and returned to the hive, other bees soon turned up at the same place. He placed glass-sided hives in his laboratory and watched carefully, and discovered that the returning bee performed a dance on the vertical surface of the honeycomb." },
          { speaker: 'A', voice: 'zira', text: "There are two main dances. If the food is close to the hive, within about fifty metres, the bee performs the round dance, in which she runs in circles, first one way and then the other. This tells the others that food is nearby, but not in which direction." },
          { speaker: 'A', voice: 'zira', text: "If the food is further away, the bee performs the waggle dance. She runs in a straight line while shaking her body from side to side, then circles back to the start and repeats. The angle of the straight run, in relation to the vertical, shows the direction of the food in relation to the sun. A run straight up the comb means that the food is in the direction of the sun, and a run at sixty degrees to the right means that it lies sixty degrees to the right of the sun." },
          { speaker: 'A', voice: 'zira', text: "The duration of the waggle run tells the distance: roughly one second for every kilometre. The vigour of the dance shows the quality of the food. A dancing bee may repeat the dance dozens of times, and her audience follow her movements in the dark, using touch and smell." },
          { speaker: 'A', voice: 'zira', text: "Von Frisch's work was so influential that he received a Nobel Prize in nineteen seventy-three. But some scientists doubted that bees really used the information in the dance, suggesting that they simply followed the smell of flowers clinging to the dancer. In the nineteen-eighties and later, researchers used a robotic bee to reproduce the dance, and found that other bees flew to the place indicated, which confirmed the original idea." },
          { speaker: 'A', voice: 'zira', text: "Bees also use dance to choose a nest. When a swarm leaves the hive, scouts search for a suitable cavity, and on returning, dance to advertise their discoveries. Other scouts visit the sites and, if they agree, join the dancing. Eventually, when enough scouts agree, typically about fifteen, the swarm moves to the chosen site. It's a remarkable example of collective decision-making, and it has been compared to a democratic vote." },
          { speaker: 'A', voice: 'zira', text: "Not all bees have a dance language. The other species of bee, and some other insects, use only smell or simple signals. The dance of the honeybee may have evolved as a way of dealing with the problem of finding flowers, which bloom in patches that change from day to day and which may lie at a distance from the hive." },
        ],
        questionGroups: [
          {
            id: 't22-l4-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>How bees communicate</strong></p><p><em>Discovery</em><br/>• Karl von Frisch used hives with {{q31}} sides in the 1930s<br/>• returning foragers performed a dance on the vertical surface of the {{q32}}</p><p><em>Round dance</em><br/>• used when the food is within about {{q33}} metres<br/>• shows that food is nearby but not the {{q34}}</p><p><em>Waggle dance</em><br/>• the bee runs in a straight line while shaking her {{q35}}<br/>• the angle of the run shows the direction in relation to the {{q36}}<br/>• the duration of the run shows the {{q37}}: roughly one second per kilometre</p><p><em>Later research</em><br/>• von Frisch received a {{q38}} Prize in 1973<br/>• a {{q39}} bee reproduced the dance, and other bees flew to the place indicated<br/>• in choosing a nest, the swarm moves when about {{q40}} scouts agree</p>',
            questions: [
              q(31, null, ['glass'], '"glass-sided hives".'),
              q(32, null, ['honeycomb', 'comb'], '"the vertical surface of the honeycomb".'),
              q(33, null, ['50', 'fifty'], '"within about fifty metres".'),
              q(34, null, ['direction'], '"but not in which direction".'),
              q(35, null, ['body'], '"shaking her body from side to side".'),
              q(36, null, ['sun'], '"in relation to the sun".'),
              q(37, null, ['distance'], '"The duration of the waggle run tells the distance".'),
              q(38, null, ['nobel'], '"a Nobel Prize in nineteen seventy-three".'),
              q(39, null, ['robotic', 'robot'], '"a robotic bee".'),
              q(40, null, ['15', 'fifteen'], '"typically about fifteen".'),
            ],
          },
        ],
      },
    ],
  },

  writing: {
    durationSec: 3600,
    task1: {
      order: 1,
      minWords: 150,
      recommendedMin: 20,
      promptHtml:
        '<p>The graph below shows the energy use per square metre of office buildings in a country between 2000 and 2020, for three types of building.</p><p>Summarise the information by selecting and reporting the main features, and make comparisons where relevant.</p>',
      chart: {
        chartType: 'line',
        title: 'Energy use in office buildings (kWh per square metre)',
        unit: 'kWh per m²',
        categories: ['2000', '2005', '2010', '2015', '2020'],
        xAxisLabel: 'Year',
        yAxisLabel: 'kWh per square metre',
        series: [
          { name: 'Old buildings', data: [280, 275, 268, 260, 255] },
          { name: 'Modern buildings', data: [210, 190, 165, 140, 120] },
          { name: 'Smart buildings', data: [150, 135, 110, 85, 65] },
        ],
      },
    },
    task2: {
      order: 2,
      minWords: 250,
      recommendedMin: 40,
      promptHtml:
        '<p>Some people believe that parents should choose traditional names for their children. Others think that parents should be free to choose any name they like.</p><p>Discuss both views and give your own opinion.</p>',
    },
  },
};
