// Original IELTS-style practice content (NOT copied or paraphrased from any real
// Cambridge/IELTS book). Only the exam STRUCTURE follows a standard Academic test
// layout; every topic, passage, transcript, question and answer is written from scratch.
import { table, TFNG_INSTRUCTION, YNNG_INSTRUCTION, q, paras, mc, bank } from './_html.mjs';

export default {
  slug: 'vocably-practice-test-24',
  title: 'Vocably Practice Test 24',
  difficulty: 'medium',

  reading: {
    durationSec: 3600,
    passages: [
      {
        order: 1,
        title: 'Forests in the tide',
        subtitle: 'Read the text and answer questions 1-13.',
        paragraphs: paras(
          ['A', `Along tropical and subtropical coasts, in places where fresh water from rivers mixes with the sea, grow some of the strangest forests on Earth. Mangrove trees stand with their roots in salt water, which would kill most plants, and in mud that has almost no oxygen. They are found in about a hundred and twenty countries, from Indonesia and Brazil to Nigeria and Australia, and together they cover about fifteen million hectares, an area roughly the size of Greece and Bulgaria combined. To the visitor paddling through them in a canoe, they appear as a maze of tangled roots and dark water, often alive with birds, crabs and insects. To scientists, they are among the most valuable ecosystems in the world.`],
          ['B', `Living in such conditions requires remarkable adaptations. Many mangroves have roots that arch out from the trunk like stilts, which support the tree in soft mud and allow it to withstand the pounding of waves. In others, upright roots called pneumatophores stick up out of the mud like hundreds of small pencils, and take in the oxygen that the mud lacks. The trees also have to cope with salt. Some species have roots that filter most of it out of the water they take up, while others excrete the salt through their leaves, which are often coated with white crystals. A third adaptation concerns reproduction. Many mangroves are viviparous, which means that the seed germinates while still attached to the parent tree, and the seedling, which may be as long as a pencil, falls into the water and can float for months before taking root in the mud.`],
          ['C', `Mangroves protect the coast. Their dense roots slow the movement of water, absorbing the energy of waves, and studies suggest that a belt of mangroves a hundred metres wide can reduce the height of waves by more than half. After the tsunami that struck the Indian Ocean in 2004, researchers noted that several villages that lay behind stands of mangroves suffered far less damage than those on open beaches nearby, and many governments have since replanted mangroves as a cheaper alternative to sea walls. The roots also trap sediment, so that the land behind them builds up over time, which helps it to keep pace with rising sea levels.`],
          ['D', `Mangroves are also nurseries. Young fish, prawns and crabs shelter among the roots, where the water is shallow and murky, and larger predators cannot easily reach them. As they grow, many move out to reefs and the open sea, where they are caught by fishermen, and it is estimated that a large share of the fish caught in tropical waters spent part of their lives in mangroves or in estuaries. For coastal communities, the trees also provide firewood, timber, honey and medicinal plants, and in some places, a living from tourism.`],
          ['E', `A more recent discovery concerns the trees' role in climate. The mud in which mangroves grow is rich in organic matter, which decays very slowly because of the lack of oxygen, and so the forests store enormous quantities of carbon. Some measurements suggest that, hectare for hectare, mangroves hold up to four times as much carbon as tropical rainforests, most of it in the soil. The term blue carbon has been coined for carbon stored in coastal ecosystems of this kind. When mangroves are cleared, this carbon is released, and so the destruction of these forests contributes to climate change on a scale out of proportion to their small area.`],
          ['F', `Despite their value, mangroves have been disappearing. Over the past half-century, about a fifth of the world's mangrove forests have been lost, mainly to the construction of shrimp ponds, to agriculture and to the development of ports and hotels. The rate of loss has slowed in recent years, as awareness has increased and some countries have introduced protection. Attention has turned to restoration, but it is not as simple as planting seedlings. Many projects have failed because the trees were planted in the wrong place, where the water flow or the salt level was unsuitable, and the seedlings died. The most successful projects begin by repairing the flow of water, and then let the forest regrow naturally, and involve local people in managing it, since they have the strongest interest in its survival.`]
        ),
        questionGroups: [
          {
            id: 't24-r1-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B, C or D</strong>.',
            questions: [
              mc(1, 'What is the function of pneumatophores?', ['to support the tree in soft mud', 'to take in oxygen', 'to remove salt', 'to produce seeds'], 'B', 'Paragraph B: upright roots "take in the oxygen that the mud lacks".', 'B'),
              mc(2, 'How do some mangroves deal with salt?', ['They store it in their roots.', 'They excrete it through their leaves.', 'They grow only in fresh water.', 'They lose their bark.'], 'B', 'Paragraph B: "excrete the salt through their leaves".', 'B'),
              mc(3, 'What does "viviparous" mean in this passage?', ['The seed germinates while still on the parent tree.', 'The tree reproduces without seeds.', 'The seeds are carried by birds.', 'The tree flowers underwater.'], 'A', 'Paragraph B: "the seed germinates while still attached to the parent tree".', 'B'),
              mc(4, 'What did researchers find after the 2004 tsunami?', ['Mangroves were destroyed.', 'Villages behind mangroves suffered less damage.', 'Sea walls worked best.', 'Mangroves had no effect.'], 'B', 'Paragraph C: villages behind mangroves "suffered far less damage".', 'C'),
              mc(5, 'What is the main cause of mangrove loss?', ['tsunamis', 'clearance for shrimp ponds, agriculture and development', 'disease', 'fishing'], 'B', 'Paragraph F: "mainly to the construction of shrimp ponds, to agriculture and to the development of ports and hotels".', 'F'),
            ],
          },
          {
            id: 't24-r1-sentences',
            type: 'sentence_completion',
            instructionHtml: 'Complete the sentences below. Choose <strong>ONE WORD ONLY</strong> from the passage for each answer.',
            wordLimit: { maxWords: 1, label: 'ONE WORD ONLY' },
            questions: [
              q(6, 'Mangrove forests cover about fifteen million {{q6}}.', ['hectares'], 'Paragraph A: "about fifteen million hectares".', 'A'),
              q(7, 'The roots of some mangroves arch out from the trunk like {{q7}}.', ['stilts'], 'Paragraph B: "like stilts".', 'B'),
              q(8, 'Young fish, prawns and crabs shelter among the {{q8}}.', ['roots'], 'Paragraph D: "shelter among the roots".', 'D'),
              q(9, 'Mangroves hold up to {{q9}} times as much carbon as tropical rainforests.', ['four'], 'Paragraph E: "up to four times as much carbon".', 'E'),
            ],
          },
          {
            id: 't24-r1-ynng',
            type: 'yes_no_notgiven',
            instructionHtml: YNNG_INSTRUCTION,
            questions: [
              q(10, 'Planting mangrove seedlings always leads to successful restoration.', 'NO', 'Paragraph F: "Many projects have failed".', 'F'),
              q(11, 'Local people should be involved in managing mangrove forests.', 'YES', 'Paragraph F: the most successful projects "involve local people in managing it".', 'F'),
              q(12, 'Coastal protection is the most important benefit of mangroves.', 'NOT GIVEN', 'The writer does not rank the benefits.'),
              q(13, 'The rate at which mangroves are being lost has slowed in recent years.', 'YES', 'Paragraph F: "The rate of loss has slowed in recent years".', 'F'),
            ],
          },
        ],
      },
      {
        order: 2,
        title: 'Why do we speak with accents?',
        subtitle: 'Read the text and answer questions 14-26.',
        paragraphs: paras(
          ['A', `Everybody has an accent. It is a common mistake to think of accents as something that other people have, while one's own speech is neutral, but this is an illusion caused by familiarity. An accent is a way of pronouncing a language, and it should be distinguished from a dialect, which is a variety of a language that also differs in vocabulary and grammar. Two people from different regions may speak the same dialect, in the sense that they use the same words and grammatical structures, but have distinctly different accents, and the reverse is also true. Linguists treat all accents as equally valid forms of speech, but in everyday life, they are often treated very differently.`],
          ['B', `Why should accents vary at all? The answer lies in the history of communities. When groups of people are separated by mountains, rivers or sea, or simply by distance in a world without modern transport, their speech gradually drifts apart, because each small change that arises in one place is not heard in another. Migration adds to the variety, as settlers bring the speech of their homeland to a new place, where it mixes with that of the people already there. The pronunciation of English is especially unstable because of a change known as the Great Vowel Shift, which took place between the fifteenth and eighteenth centuries, during which the long vowels of the language were all altered; spelling, which had by then become fixed, did not follow, which is why the spelling of English so often fails to match its sounds.`],
          ['C', `Accents are acquired early in life. Young children pick up the speech of those around them, and by the age of about seven, most have settled into the accent of their community, although the process continues to some extent through adolescence. After that, it becomes much harder to change. Adults who move to another region may adopt some features of the local speech, such as a few vowels or intonation patterns, but they seldom lose their original accent completely, and those who move to a foreign country as adults rarely lose the accent of their first language. Researchers suggest that the ability to learn new sounds declines as the brain becomes specialised in the sounds it hears most.`],
          ['D', `Accents carry social meaning, and not always fairly. Experiments in which listeners are asked to judge speakers from recordings have found that people form impressions about a speaker's intelligence, trustworthiness and education within seconds, and that these impressions are influenced by accent. In Britain, for example, some regional accents are rated as less intelligent than the accent traditionally used by the professional and upper classes, even when the speakers say exactly the same words. Such prejudice can affect opportunities: studies of job interviews suggest that candidates with stigmatised accents are at a disadvantage, and in some countries, complaints about discrimination on the grounds of accent have reached the courts.`],
          ['E', `Accents are also changing. New features appear constantly, and spread through communities. In southern England, a style of speech known as Estuary English, with its glottal stops and modified vowels, has spread well beyond its origins in London. Young speakers in many countries have adopted a rising intonation at the end of statements, which was once regarded as a fault, but has become widespread. Many people assume that television and social media are the main cause of such changes. Linguists have generally found little evidence for this: children who watch a great deal of television from another region do not pick up its accent, and researchers believe that regular face-to-face contact with real speakers is far more important than anything heard on a screen.`],
          ['F', `Technology has raised a new question. Voice-activated devices and speech-recognition systems are trained on recordings of speech, and they work best with the accents that are most strongly represented in the training material. Studies have found that these systems make more errors with speakers of some regional and foreign accents, and in particular with speakers from minority groups, which means that the benefits of the technology are not shared equally. Developers are now trying to collect a wider range of voices, and to develop systems that can adapt to the speaker, but the problem illustrates how attitudes to accent can be built into technology without anyone intending it.`],
          ['G', `There are signs that attitudes are changing. A generation ago, newsreaders in many countries spoke in a uniform prestige accent, and regional speakers who wanted a career in broadcasting were often advised to change their speech. Today, broadcasters employ presenters with a wide range of accents, and in some workplaces, employers have been asked to consider training in awareness of bias. For many speakers, an accent is a valued part of their identity, which links them to a place, a family and a history, and it is increasingly seen not as a defect to be corrected but as a part of the variety of human speech.`]
        ),
        questionGroups: [
          {
            id: 't24-r2-matchinfo',
            type: 'matching_information',
            instructionHtml: 'Reading Passage 2 has seven paragraphs, A-G. Which paragraph contains the following information? <em>Choose the correct letter, A-G.</em>',
            questions: [
              q(14, 'a distinction between two linguistic terms', 'A', 'Paragraph A: an accent is distinguished from a dialect.', 'A'),
              q(15, 'a historical change that explains why English spelling does not match its sounds', 'B', 'Paragraph B: the Great Vowel Shift.', 'B'),
              q(16, 'a reference to the age by which an accent is usually established', 'C', 'Paragraph C: "by the age of about seven".', 'C'),
              q(17, 'a finding about how listeners judge speakers\' intelligence', 'D', 'Paragraph D: some accents "are rated as less intelligent".', 'D'),
              q(18, 'a claim that television has less influence on accents than is often assumed', 'E', 'Paragraph E: "little evidence for this".', 'E'),
              q(19, 'a technological problem that arises from differences in accents', 'F', 'Paragraph F: speech-recognition systems make more errors.', 'F'),
            ],
          },
          {
            id: 't24-r2-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              q(20, 'Everybody has an accent.', 'TRUE', 'Paragraph A: "Everybody has an accent."', 'A'),
              q(21, 'Communities that are separated tend to develop different pronunciations.', 'TRUE', 'Paragraph B: "their speech gradually drifts apart".', 'B'),
              q(22, 'Most adults who move to another region completely lose their original accent.', 'FALSE', 'Paragraph C: "they seldom lose their original accent completely".', 'C'),
              q(23, 'All listeners judge regional accents to be less intelligent than other accents.', 'FALSE', 'Paragraph D: "some regional accents are rated as less intelligent".', 'D'),
              q(24, 'Children acquire their accents mainly from television.', 'FALSE', 'Paragraph E: face-to-face contact "is far more important".', 'E'),
              q(25, 'Speech-recognition systems are equally accurate for all accents.', 'FALSE', 'Paragraph F: "more errors with speakers of some ... accents".', 'F'),
              q(26, 'Some broadcasters now employ presenters with a wide range of accents.', 'TRUE', 'Paragraph G: "broadcasters employ presenters with a wide range of accents".', 'G'),
            ],
          },
        ],
      },
      {
        order: 3,
        title: 'Will robots take our jobs?',
        subtitle: 'Read the text and answer questions 27-40.',
        paragraphs: paras(
          ['A', `In 1811, groups of textile workers in the north of England, known as Luddites, broke into mills and smashed the machines that they feared would take their jobs. Two centuries later, the same anxiety has returned. Computers now translate languages, diagnose diseases from scans and write simple reports, and robots in warehouses sort parcels faster than any person. A much-discussed study in 2013 estimated that nearly half of all jobs in the United States were at high risk of being automated within a decade or two, and the figure was repeated in newspapers around the world. Is this the beginning of mass unemployment, or is it another false alarm?`],
          ['B', `History offers some reassurance. Technological change has always destroyed some jobs, but it has created others, and on balance, it has raised living standards. In 1900, about forty per cent of American workers were employed in agriculture; today, the proportion is about two per cent, yet the country has not run out of work. The machines that replaced farmworkers made food cheaper, which left consumers with more money to spend on other things, and whole new industries, from cars to computers, grew up to supply them. Most of the jobs that exist today, such as software developer or social media manager, did not exist a century ago.`],
          ['C', `Some economists, however, argue that this time may be different. The speed of change is greater than in the past, which leaves less time for workers and institutions to adjust, and the machines of today are doing more than replace muscle: they can do tasks that require perception, judgement and language, which were once thought to be uniquely human. If machines can do everything that people can do, at lower cost, then the argument that new jobs will always appear loses much of its force, since the new jobs might also be done by machines.`],
          ['D', `Closer study suggests that the threat is more complicated than the early headlines implied. Jobs consist of many tasks, and while machines can perform some of them, few occupations consist entirely of tasks that can be automated. One influential analysis found that fewer than one in twenty occupations could be fully automated with existing technology, but that about six in ten included at least a third of activities that could be. This suggests that for most people the main effect will be not the loss of a job, but a change in what the job involves, as machines take over the routine parts and leave the rest to humans.`],
          ['E', `Some kinds of work are more vulnerable than others. Routine manual jobs, such as assembly-line work, were the first to decline as factories installed robots. More recently, routine office tasks have come under threat: software can now do much of the data entry, basic accounting and administrative work that once kept large numbers of clerks busy. Jobs that depend on social skills, such as nursing, teaching and caring for the elderly, have proved much harder to automate, since they require an understanding of how people feel and the ability to persuade and reassure them. So have jobs that demand complex creativity, for example in design and research, although some of these, too, are being changed by new tools. The result has been a polarisation: employment has grown at the top and bottom of the skill ladder, but has shrunk in the middle.`],
          ['F', `What can be done? Most economists agree that the first priority is education and training. Workers who can learn new skills will be better able to move into the jobs that are created, and schools and colleges may need to place more emphasis on the abilities that machines lack, such as creativity and cooperation. Governments can also help by making it easier for people to retrain during their working lives, and by providing support during the gaps between jobs. Some have gone further, and experimented with giving every adult a basic income, without conditions. Small trials, such as one in Finland, found that recipients were happier and less stressed, but it remains to be seen whether such a scheme could be afforded on a national scale.`],
          ['G', `There is also a concern about inequality. If machines replace workers, the profits from their use go to those who own them, and so the gap between the owners of capital and the rest of society could widen. Some have proposed that companies which replace workers with robots should pay a special tax, the proceeds of which would be used to support those who lose their jobs, but critics reply that such a tax would discourage innovation, and that it would be difficult to define what counts as a robot. The debate over who should benefit from automation is likely to be one of the main political questions of the coming decades.`],
          ['H', `My own view is that neither panic nor complacency is justified. Automation will certainly change the labour market, and some people will lose out, but the evidence does not support the claim that there will be no work left for humans to do. The danger lies less in the machines than in the failure to prepare for them: to ensure that workers have the skills they need, that the gains are fairly shared and that those who are displaced are supported. A society that does these things has little to fear from the next wave of technology; one that does not may find that the fears of the Luddites were not entirely misplaced.`]
        ),
        questionGroups: [
          {
            id: 't24-r3-headings',
            type: 'matching_headings',
            instructionHtml: 'Reading Passage 3 has eight paragraphs, A-H. Choose the correct heading for paragraphs B-H from the list of headings below.<br/><em>Example: Paragraph A — x</em>',
            bank: [
              { key: 'i', text: 'Tasks rather than whole jobs' },
              { key: 'ii', text: 'Why the past may not be a reliable guide' },
              { key: 'iii', text: 'The case for neither panic nor complacency' },
              { key: 'iv', text: 'Education, training and new forms of support' },
              { key: 'v', text: 'Lessons from earlier technological change' },
              { key: 'vi', text: 'Who will own the machines?' },
              { key: 'vii', text: 'The history of the textile industry' },
              { key: 'viii', text: 'Jobs at greater and lesser risk' },
              { key: 'ix', text: 'The high cost of building robots' },
              { key: 'x', text: 'An old fear in a new form' },
            ],
            questions: [
              q(27, 'Paragraph B', 'v', 'Paragraph B: agriculture and the creation of new industries.', 'B'),
              q(28, 'Paragraph C', 'ii', 'Paragraph C: "this time may be different".', 'C'),
              q(29, 'Paragraph D', 'i', 'Paragraph D: "Jobs consist of many tasks".', 'D'),
              q(30, 'Paragraph E', 'viii', 'Paragraph E: "Some kinds of work are more vulnerable than others."', 'E'),
              q(31, 'Paragraph F', 'iv', 'Paragraph F: education, retraining and basic income.', 'F'),
              q(32, 'Paragraph G', 'vi', 'Paragraph G: profits go to "those who own them".', 'G'),
              q(33, 'Paragraph H', 'iii', 'Paragraph H: "neither panic nor complacency is justified".', 'H'),
            ],
          },
          {
            id: 't24-r3-classify',
            type: 'matching_features',
            instructionHtml: 'Look at the following statements (Questions 34-40) and the list of types of work below. Match each statement with the correct type, <strong>A, B or C</strong>.<br/>You may use any letter more than once.',
            bankReusable: true,
            bank: [
              { key: 'A', text: 'routine manual jobs' },
              { key: 'B', text: 'routine office tasks' },
              { key: 'C', text: 'jobs that depend on social skills or creativity' },
            ],
            questions: [
              q(34, 'assembly-line work', 'A', 'Paragraph E: "Routine manual jobs, such as assembly-line work".', 'E'),
              q(35, 'data entry and basic accounting', 'B', 'Paragraph E: "data entry, basic accounting and administrative work".', 'E'),
              q(36, 'nursing and caring for the elderly', 'C', 'Paragraph E: "such as nursing, teaching and caring for the elderly".', 'E'),
              q(37, 'design and research requiring complex creativity', 'C', 'Paragraph E: "complex creativity, for example in design and research".', 'E'),
              q(38, 'the first to decline when factories installed robots', 'A', 'Paragraph E: "the first to decline as factories installed robots".', 'E'),
              q(39, 'administrative work that software can now handle', 'B', 'Paragraph E: "software can now do much of the ... administrative work".', 'E'),
              q(40, 'jobs that require persuading and reassuring people', 'C', 'Paragraph E: "the ability to persuade and reassure them".', 'E'),
            ],
          },
        ],
      },
    ],
  },

  listening: {
    durationSec: 1800,
    checkTimeSec: 120,
    parts: [
      {
        order: 1,
        contextText: 'You will hear a woman phoning an evening institute to enrol on a cookery course.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Greenwood Evening Institute, good afternoon." },
          { speaker: 'B', voice: 'zira', text: "Good afternoon. I'd like to enrol on one of your cookery courses, please." },
          { speaker: 'A', voice: 'david', text: "Certainly. We have several. Do you have a particular cuisine in mind?" },
          { speaker: 'B', voice: 'zira', text: "I'd like to learn Indian cooking, if you have it." },
          { speaker: 'A', voice: 'david', text: "Yes, we have a ten-week course called Flavours of India, on Tuesday evenings. It starts on the eighteenth of September, from seven until nine." },
          { speaker: 'B', voice: 'zira', text: "That sounds perfect. How much is it?" },
          { speaker: 'A', voice: 'david', text: "It's a hundred and thirty-five pounds, plus a charge of thirty pounds for ingredients, which is paid to the tutor in the first week." },
          { speaker: 'B', voice: 'zira', text: "Do I need to bring my own equipment?" },
          { speaker: 'A', voice: 'david', text: "Just an apron and a few containers to take your food home in. Everything else is provided in the kitchen." },
          { speaker: 'B', voice: 'zira', text: "Is it suitable for complete beginners? I can hardly boil an egg." },
          { speaker: 'A', voice: 'david', text: "Absolutely. The tutor, Mr Bhatt, has taught the course for eight years, and he specialises in helping people who lack confidence. There are twelve places, and at the moment, three are free." },
          { speaker: 'B', voice: 'zira', text: "I'll book one, then. Are there any concessions?" },
          { speaker: 'A', voice: 'david', text: "Yes, students and people over sixty get twenty per cent off. Are you in either group?" },
          { speaker: 'B', voice: 'zira', text: "No, I'm afraid not. I work as an accountant." },
          { speaker: 'A', voice: 'david', text: "Then the full price applies. Can I have your name?" },
          { speaker: 'B', voice: 'zira', text: "Nora Ashworth. A-S-H-W-O-R-T-H." },
          { speaker: 'A', voice: 'david', text: "And your address?" },
          { speaker: 'B', voice: 'zira', text: "Number seven, Elm Crescent, Hadley." },
          { speaker: 'A', voice: 'david', text: "And a telephone number?" },
          { speaker: 'B', voice: 'zira', text: "Oh-seven-seven-oh-oh, nine-oh-oh, four-one-seven." },
        ],
        questionGroups: [
          {
            id: 't24-l1-form',
            type: 'form_completion',
            instructionHtml: 'Complete the form below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Greenwood Evening Institute: Enrolment', ''],
              [
                ['Course', 'Flavours of {{q1}}'],
                ['Length', '{{q2}} weeks'],
                ['Day', '{{q3}} evenings'],
                ['Start date', '{{q4}} September'],
                ['Time', '7 p.m. to {{q5}} p.m.'],
                ['Course fee', '£{{q6}}'],
                ['Charge for ingredients', '£{{q7}}'],
                ['Tutor', 'Mr {{q8}}'],
                ['Surname', '{{q9}}'],
                ['Address', '7 {{q10}}, Hadley'],
              ]
            ),
            questions: [
              q(1, null, ['india'], '"Flavours of India".'),
              q(2, null, ['10', 'ten'], '"a ten-week course".'),
              q(3, null, ['tuesday'], '"on Tuesday evenings".'),
              q(4, null, ['18th', 'eighteenth', '18'], '"the eighteenth of September".'),
              q(5, null, ['9', 'nine'], '"from seven until nine".'),
              q(6, null, ['135', 'a hundred and thirty-five', 'one hundred and thirty-five'], '"a hundred and thirty-five pounds".'),
              q(7, null, ['30', 'thirty'], '"thirty pounds for ingredients".'),
              q(8, null, ['bhatt'], '"Mr Bhatt".'),
              q(9, null, ['ashworth'], 'Spelled out: A-S-H-W-O-R-T-H.'),
              q(10, null, ['elm crescent'], '"Number seven, Elm Crescent".'),
            ],
          },
        ],
      },
      {
        order: 2,
        contextText: 'You will hear a guide on a canal boat describing places of interest along the route.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Good morning, everyone, and welcome aboard the Ada Lovelace. I'm Jenny, and I'll be your guide on this two-hour cruise along the Heritage Canal. The canal was built in seventeen ninety-four to carry coal and iron from the hills to the city, and it was used for commerce for nearly two centuries." },
          { speaker: 'A', voice: 'zira', text: "It fell into disuse in the nineteen-sixties, when lorries took over its trade, and it became choked with weeds and rubbish. Thanks to a group of volunteers, who began to clear it in nineteen seventy-four, it was reopened in nineteen ninety, and today it's popular with walkers, cyclists and boat owners." },
          { speaker: 'A', voice: 'zira', text: "Our first landmark, about ten minutes from here, is the iron bridge, which was cast in nineteen-ten and is still in use. Just after it, on the left, you'll see the old brewery, now converted into apartments. The original chimney is still standing." },
          { speaker: 'A', voice: 'zira', text: "Next, we'll reach the Bell Tower lock, the first of the eight locks on this route. A lock is like a water lift, and raises the boat by about three metres. It takes about ten minutes, and you're welcome to get off and watch. The lock-keeper, Mr Davies, has been operating it for thirty years." },
          { speaker: 'A', voice: 'zira', text: "After the lock, we go through a tunnel which is four hundred and fifty metres long. There is no towpath, so in the days of horse-drawn barges, the boatmen had to push the barge through by lying on their backs and walking their feet along the walls, which was known as legging." },
          { speaker: 'A', voice: 'zira', text: "Emerging from the tunnel, we come to the aqueduct, a bridge carrying the canal over a river, which is thirty metres high and is the tallest in the country. It's a little alarming to look down, but it's perfectly safe." },
          { speaker: 'A', voice: 'zira', text: "On the far side of the aqueduct is the nature reserve, where you may see herons, kingfishers and swans. The reserve is managed by a wildlife trust, and it's especially beautiful in spring, when the banks are covered with flowers." },
          { speaker: 'A', voice: 'zira', text: "Our turning point is the village of Stoneford, where we'll stop for twenty minutes. There's a café by the water, and a small museum in a former warehouse, with displays on canal life. We'll then return by the same route." },
          { speaker: 'A', voice: 'zira', text: "Please stay in your seats when the boat is moving through the lock and the tunnel, and do watch your heads. Tea and coffee are available from the galley. Now, if you're all comfortable, let's cast off." },
        ],
        questionGroups: [
          {
            id: 't24-l2-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(11, 'The canal was built in', ['1794', '1874', '1974'], 'A', '"built in seventeen ninety-four".'),
              mc(12, 'Who began to clear the canal in 1974?', ['the council', 'a group of volunteers', 'a company'], 'B', '"a group of volunteers, who began to clear it in nineteen seventy-four".'),
              mc(13, 'The canal was reopened in', ['1974', '1984', '1990'], 'C', '"reopened in nineteen ninety".'),
              mc(14, 'How long is the tunnel?', ['250 metres', '450 metres', '650 metres'], 'B', '"four hundred and fifty metres long".'),
              mc(15, 'The aqueduct is', ['the tallest in the country', 'the oldest in the country', 'the longest in the country'], 'A', '"the tallest in the country".'),
            ],
          },
          {
            id: 't24-l2-match',
            type: 'matching_features',
            instructionHtml: 'What is each landmark used for today, or known for? Choose the correct answer and write the correct letter, <strong>A-G</strong>, next to Questions 16-20.',
            bank: [
              { key: 'A', text: 'converted into apartments' },
              { key: 'B', text: 'still in use, cast in 1910' },
              { key: 'C', text: 'raises the boat about three metres' },
              { key: 'D', text: 'boatmen had to push barges by "legging"' },
              { key: 'E', text: 'managed by a wildlife trust' },
              { key: 'F', text: 'houses displays on canal life' },
              { key: 'G', text: 'sells tea and cakes' },
            ],
            questions: [
              q(16, 'the iron bridge', 'B', '"the iron bridge, which was cast in nineteen-ten and is still in use".'),
              q(17, 'the old brewery', 'A', '"now converted into apartments".'),
              q(18, 'the Bell Tower lock', 'C', '"raises the boat by about three metres".'),
              q(19, 'the tunnel', 'D', '"pushing the barge ... known as legging".'),
              q(20, 'the nature reserve', 'E', '"managed by a wildlife trust".'),
            ],
          },
        ],
      },
      {
        order: 3,
        contextText: 'You will hear three students, Felix, Noor and Grace, preparing for a debate with their tutor.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david2', text: "Right, let's talk about next week's debate. The motion is: 'This house believes that social media does more harm than good.' Noor, you're proposing. Felix and Grace, you're opposing. Is that right?" },
          { speaker: 'B', voice: 'zira', text: "Yes. I've found some useful studies on the effects of social media on teenagers' sleep and self-esteem." },
          { speaker: 'C', voice: 'david', text: "We'll need to argue that the benefits outweigh the harm: keeping in touch, sharing information, giving a voice to people who've been excluded." },
          { speaker: 'D', voice: 'zira2', text: "And I think we should point out that the evidence of harm is mixed. Some studies find a link with poor mental health, but others find almost none." },
          { speaker: 'A', voice: 'david2', text: "Good. A strong opposing argument is to challenge the proposers' evidence. Noor, be ready for that. Make sure that your studies are recent and that you can explain how they were carried out." },
          { speaker: 'B', voice: 'zira', text: "I'll check the sample sizes. One of my studies only surveyed a hundred students." },
          { speaker: 'A', voice: 'david2', text: "Then I'd lead with a larger one. Now, structure. Each speaker has four minutes. The first speaker presents the main arguments, the second rebuts and adds new points, and the third sums up." },
          { speaker: 'C', voice: 'david', text: "Who should speak first for our side?" },
          { speaker: 'A', voice: 'david2', text: "Felix, I think you should. You're the most confident. Grace can rebut, and Noor, you'll close for your side, since you've done the most research." },
          { speaker: 'D', voice: 'zira2', text: "What should we do about examples? Personal stories are persuasive." },
          { speaker: 'A', voice: 'david2', text: "They are, but use them sparingly. Judges will be looking for logic and evidence, and a single story can be answered by another. One or two short ones, at most." },
          { speaker: 'B', voice: 'zira', text: "How are we scored?" },
          { speaker: 'A', voice: 'david2', text: "Four criteria: content, which counts for forty per cent, structure, style and response to the other side, which together make up the rest. Speak clearly, don't read from a script, and keep eye contact with the judges." },
          { speaker: 'C', voice: 'david', text: "What if we run out of time?" },
          { speaker: 'A', voice: 'david2', text: "A bell rings after three minutes and at four. Finish your sentence, and stop. Going over the limit loses marks." },
          { speaker: 'D', voice: 'zira2', text: "When exactly is the debate?" },
          { speaker: 'A', voice: 'david2', text: "Thursday the seventh, at two o'clock, in Lecture Theatre Three. Please be there at half past one to set up." },
        ],
        questionGroups: [
          {
            id: 't24-l3-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(21, 'Which side is Noor on?', ['proposing the motion', 'opposing the motion', 'the judges'], 'A', '"Noor, you\'re proposing".'),
              mc(22, 'What does Grace say about the evidence of harm?', ['It is clear.', 'It is mixed.', 'It does not exist.'], 'B', '"the evidence of harm is mixed".'),
              mc(23, 'The tutor advises Noor to', ['use only one study', 'check the sample sizes and lead with a larger study', 'avoid statistics'], 'B', '"I\'d lead with a larger one".'),
              mc(24, 'How long does each speaker have?', ['three minutes', 'four minutes', 'five minutes'], 'B', '"Each speaker has four minutes."'),
              mc(25, 'Who will close for the opposing side?', ['Felix', 'Grace', 'Noor'], 'C', '"Noor, you\'ll close".'),
            ],
          },
          {
            id: 't24-l3-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Debate advice</strong></p><p>• use personal {{q26}} sparingly<br/>• content counts for {{q27}} per cent of the marks<br/>• do not read from a {{q28}}; keep eye contact with the judges<br/>• a {{q29}} rings after three minutes and at four<br/>• debate on Thursday the seventh at {{q30}} o\'clock</p>',
            questions: [
              q(26, null, ['stories', 'examples', 'story'], '"Personal stories are persuasive ... use them sparingly".'),
              q(27, null, ['40', 'forty'], '"content, which counts for forty per cent".'),
              q(28, null, ['script'], '"don\'t read from a script".'),
              q(29, null, ['bell'], '"A bell rings".'),
              q(30, null, ['2', 'two'], '"at two o\'clock".'),
            ],
          },
        ],
      },
      {
        order: 4,
        contextText: 'You will hear part of a lecture about the origins of jazz.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Jazz is often called America's classical music, and it is one of the country's greatest contributions to world culture. Today I'll explain where it came from, and how it developed." },
          { speaker: 'A', voice: 'david', text: "Jazz emerged around the turn of the twentieth century in New Orleans, a port city at the mouth of the Mississippi, where people of many backgrounds met: African Americans, Creoles of mixed French, Spanish and African descent, and immigrants from Europe and the Caribbean. The city was full of music: brass bands played at parades and funerals, and dance halls and clubs offered entertainment every night." },
          { speaker: 'A', voice: 'david', text: "The roots of jazz lie in a number of earlier forms. One was the blues, a style of song that grew out of the experiences of African Americans in the southern states, with its expressive, bending notes and its themes of hardship and hope. Another was ragtime, a lively piano music with syncopated rhythms, which was popular in the eighteen-nineties. A third was the music of the brass bands, with their marches and hymns." },
          { speaker: 'A', voice: 'david', text: "What made jazz new was improvisation. Musicians did not simply play a written tune; they invented new melodies on the spur of the moment, over a repeating pattern of chords. A typical performance had a band playing a theme together, then each player taking a solo in turn, and then the band returning to the theme. This gave the music a spontaneous quality, and every performance was different." },
          { speaker: 'A', voice: 'david', text: "The first jazz recording was made in nineteen seventeen, by a white group called the Original Dixieland Jazz Band, and it sold over a million copies. The music spread northwards with the great migration of African Americans to cities such as Chicago and New York, in search of work. In the nineteen-twenties, which are often called the Jazz Age, the music became the soundtrack of a new, freer lifestyle, with dances such as the Charleston." },
          { speaker: 'A', voice: 'david', text: "The trumpeter Louis Armstrong, who came from New Orleans, was one of the most influential musicians of this period. He helped to change jazz from collective improvisation to a music of brilliant solos, and his singing and wit made him famous worldwide." },
          { speaker: 'A', voice: 'david', text: "In the nineteen-thirties, larger bands, playing written arrangements with a strong beat, became popular in a style known as swing, and leaders such as Duke Ellington built orchestras with distinctive sounds. After the Second World War, a younger generation of players turned to a faster, more complex style called bebop, which was intended for listening rather than dancing." },
          { speaker: 'A', voice: 'david', text: "Jazz has since spread all over the world, and absorbed influences from many cultures, from Latin American rhythms to Indian scales. It has also influenced other kinds of music, including rock and hip-hop. Its central idea, that a musician can create something new in the moment, continues to inspire performers everywhere." },
        ],
        questionGroups: [
          {
            id: 't24-l4-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Origins of jazz</strong></p><p><em>Where and when</em><br/>• emerged around 1900 in {{q31}}, a port city at the mouth of the Mississippi<br/>• people of many backgrounds, including {{q32}} of mixed French, Spanish and African descent<br/>• brass bands played at parades and {{q33}}</p><p><em>Roots</em><br/>• the blues; {{q34}}, a lively piano music with syncopated rhythms; music of brass bands</p><p><em>What made jazz new</em><br/>• {{q35}}: musicians invented new melodies on the spur of the moment<br/>• typical performance: the theme, then a {{q36}} for each player, then the theme again</p><p><em>Development</em><br/>• first jazz recording in {{q37}}; it sold over a million copies<br/>• 1920s called the {{q38}} Age<br/>• Louis Armstrong helped to change jazz to a music of brilliant {{q39}}<br/>• after the Second World War, {{q40}} was intended for listening rather than dancing</p>',
            questions: [
              q(31, null, ['new orleans'], '"in New Orleans".'),
              q(32, null, ['creoles'], '"Creoles of mixed French, Spanish and African descent".'),
              q(33, null, ['funerals'], '"at parades and funerals".'),
              q(34, null, ['ragtime'], '"ragtime, a lively piano music".'),
              q(35, null, ['improvisation'], '"What made jazz new was improvisation."'),
              q(36, null, ['solo'], '"each player taking a solo in turn".'),
              q(37, null, ['1917'], '"made in nineteen seventeen".'),
              q(38, null, ['jazz'], '"often called the Jazz Age".'),
              q(39, null, ['solos'], '"a music of brilliant solos".'),
              q(40, null, ['bebop'], '"a faster, more complex style called bebop".'),
            ],
          },
        ],
      },
    ],
  },

  writing: {
    durationSec: 3600,
    task1: {
      order: 1,
      minWords: 150,
      recommendedMin: 20,
      promptHtml:
        '<p>The graph below shows the percentage of jobs in three sectors of an economy that were estimated to be at high risk of automation in 2010, 2020 and 2030 (projected).</p><p>Summarise the information by selecting and reporting the main features, and make comparisons where relevant.</p>',
      chart: {
        chartType: 'line',
        title: 'Jobs at high risk of automation (% of sector)',
        unit: '%',
        categories: ['2010', '2020', '2030'],
        xAxisLabel: 'Year',
        yAxisLabel: 'Percentage of jobs at risk',
        series: [
          { name: 'Manufacturing', data: [48, 57, 62] },
          { name: 'Office administration', data: [35, 52, 66] },
          { name: 'Healthcare', data: [12, 14, 15] },
        ],
      },
    },
    task2: {
      order: 2,
      minWords: 250,
      recommendedMin: 40,
      promptHtml:
        '<p>Some people believe that robots and artificial intelligence will create more jobs than they destroy. Others think that they will lead to widespread unemployment.</p><p>Discuss both views and give your own opinion.</p>',
    },
  },
};
