// Original IELTS-style practice content (NOT copied or paraphrased from any real
// Cambridge/IELTS book). Only the exam STRUCTURE follows a standard Academic test
// layout; every topic, passage, transcript, question and answer is written from scratch.
import { table, TFNG_INSTRUCTION, YNNG_INSTRUCTION, q, paras, mc, bank } from './_html.mjs';

export default {
  slug: 'vocably-practice-test-6',
  title: 'Vocably Practice Test 6',
  difficulty: 'medium',

  reading: {
    durationSec: 3600,
    passages: [
      {
        order: 1,
        title: 'Words that came back',
        subtitle: 'Read the text and answer questions 1-13.',
        paragraphs: paras(
          ['A', `Of the roughly seven thousand languages spoken in the world today, linguists estimate that about half may fall silent before the end of this century. A language usually dies in three generations: grandparents speak it fluently, their children understand it but answer in another language, and their grandchildren know only a few words. Once the last fluent speaker dies, the vocabulary, the stories and the way of seeing the world that the language carried disappear with them. Yet a handful of languages that seemed to be heading for extinction have been brought back into everyday use, and their histories have given researchers a clearer idea of what makes such recoveries possible.`],
          ['B', `The best-known example is Hebrew. For nearly two thousand years it survived as a language of prayer and scholarship, read and written by educated men but spoken in the home by no one. In the late nineteenth century, a small group of scholars in Jerusalem, led by Eliezer Ben-Yehuda, decided to make it a language of daily life. Ben-Yehuda insisted that his own household should speak only Hebrew, and his eldest son is often described as the first child in modern times to be raised in it. A committee later known as the Hebrew Language Academy created new words for objects and ideas that did not exist in ancient times, from the names of machines to the vocabulary of politics and science. Within a few decades, Hebrew had become the main language of schools, newspapers and government in the region.`],
          ['C', `The story of Welsh is different, because it never stopped being spoken; it was simply pushed aside. For much of the nineteenth and twentieth centuries, children in Wales were discouraged, and sometimes punished, for using Welsh at school, and the numbers of speakers fell steadily. In the 1960s, campaigners began to demand equal status for the language, organising protests and refusing to fill in official forms that were available only in English. Their efforts led to new laws, to Welsh-medium schools and, in 1982, to a Welsh-language television channel, which gave the language a presence in people's homes that it had not had for generations. Today, about a fifth of the population of Wales can speak Welsh, and the proportion among young people is higher.`],
          ['D', `In Hawaii, the native language was banned from schools in 1896, and by the 1980s only a few dozen children could speak it. A group of teachers and parents looked to New Zealand, where Maori communities had created pre-school centres known as language nests, in which elders speak only the native language to very young children. The Hawaiian version opened its first centres in 1983. Children who graduated from the nests needed somewhere to continue, so the founders campaigned for immersion schools, and eventually for a route to university study entirely in Hawaiian. Some of the first children to pass through the system are now teaching in it themselves.`],
          ['E', `Researchers who have compared these cases suggest that successful revivals share three features. The first is political support: governments that allow a language to be used in courts, schools and public life give it a value beyond the family. The second is education, because a language that children meet only at home rarely survives adolescence. The third, and probably the hardest to achieve, is everyday use. Unless people have reasons to speak a language when they shop, work and relax, it tends to become a subject to be studied rather than a means of communication.`],
          ['F', `Revival also brings complications. Children who learn a language at school may speak it differently from the last native speakers, using different sounds, simpler grammar or vocabulary borrowed from the dominant language, and some elderly speakers find the results painful to hear. Others argue that a living language must change, and that a language frozen in its original form is not alive at all. Technology is making the task easier. Online dictionaries, recorded conversations with elders and mobile applications allow learners to practise at home, although few teachers believe that any of these can replace regular conversation.`],
          ['G', `Not every community wants a revival on the scale of Hebrew. Some aim only to keep a language alive for ceremonies or songs, and regard this as success. Others would like to see it in every part of daily life, but recognise that this may take generations. Whatever their goals, most of those involved argue that the value of a language cannot be measured only by the number of people who speak it. For the communities concerned, it is a link with their ancestors and a statement about who they are, and that, they say, is reason enough to keep it going.`]
        ),
        questionGroups: [
          {
            id: 't6-r1-matchinfo',
            type: 'matching_information',
            instructionHtml: 'Reading Passage 1 has seven paragraphs, A-G. Which paragraph contains the following information? <em>Choose the correct letter, A-G.</em><br/><strong>NB</strong> You may use any letter more than once.',
            bankReusable: true,
            questions: [
              q(1, 'a language that was written and read but not used for conversation at home', 'B', 'Paragraph B: Hebrew was "a language of prayer and scholarship ... spoken in the home by no one".', 'B'),
              q(2, 'a reference to a language being forbidden in schools', 'D', 'Paragraph D: "banned from schools in 1896".', 'D'),
              q(3, 'an example of television helping a language', 'C', 'Paragraph C: "a Welsh-language television channel".', 'C'),
              q(4, 'a reason why some communities set modest goals for their language', 'G', 'Paragraph G: some "aim only to keep a language alive for ceremonies or songs".', 'G'),
              q(5, 'a prediction about how many languages may disappear', 'A', 'Paragraph A: "about half may fall silent before the end of this century".', 'A'),
            ],
          },
          {
            id: 't6-r1-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              q(6, 'Ben-Yehuda\'s eldest son is often said to have been the first child in modern times raised in Hebrew.', 'TRUE', 'Paragraph B: "often described as the first child in modern times to be raised in it".', 'B'),
              q(7, 'A majority of people in Wales now speak Welsh.', 'FALSE', 'Paragraph C: "about a fifth of the population".', 'C'),
              q(8, 'Language nests were first developed in Hawaii.', 'FALSE', 'Paragraph D: Hawaii copied the idea from New Zealand.', 'D'),
              q(9, 'Mobile applications are more effective than classroom teaching for revived languages.', 'NOT GIVEN', 'Paragraph F says few teachers think applications can replace conversation, but no comparison with classes is made.', 'F'),
            ],
          },
          {
            id: 't6-r1-short',
            type: 'short_answer',
            instructionHtml: 'Answer the questions below. Choose <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> from the passage for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            questions: [
              q(10, 'What did the Hebrew Language Academy create for ideas that did not exist in ancient times?', ['new words'], 'Paragraph B: "created new words for objects and ideas".', 'B'),
              q(11, 'In which year did the Welsh-language television channel begin?', ['1982'], 'Paragraph C: "in 1982".', 'C'),
              q(12, 'Who speak only the native language to young children in language nests?', ['elders'], 'Paragraph D: "in which elders speak only the native language".', 'D'),
              q(13, 'What kind of support from governments do researchers say is needed, along with education and everyday use?', ['political support', 'political'], 'Paragraph E: "The first is political support".', 'E'),
            ],
          },
        ],
      },
      {
        order: 2,
        title: 'The mathematics of waiting',
        subtitle: 'Read the text and answer questions 14-26.',
        paragraphs: paras(
          ['A', `Everyone has stood in a queue that seemed to move more slowly than the one next to it, and most people assume that this is simply bad luck. In fact, waiting in line is one of the most carefully studied problems in applied mathematics. Queueing theory, as the field is known, is used to plan telephone networks, hospital emergency departments, airports, supermarkets and the servers that deliver web pages, and its conclusions are often surprising. Some of the most useful are not about speed at all, but about how people feel while they wait.`],
          ['B', `The subject began in 1909, when a Danish engineer named Agner Erlang was asked to work out how many telephone lines a small exchange needed. Calls did not arrive at regular intervals; they came at random, and sometimes several arrived at once. If the exchange had too few lines, callers were blocked; if it had too many, expensive equipment sat idle. Erlang developed formulas that predicted how often a system of a given size would be overloaded, and these formulas, in various forms, are still used today.`],
          ['C', `His work revealed a principle that most people find counter-intuitive: queues are caused less by the average speed of a service than by its variability. A bank clerk who serves one customer every two minutes, with customers arriving exactly every two minutes, would never produce a queue. But if customers arrive at random, and some need thirty seconds and others ten minutes, waiting lines appear even though the clerk is, on average, fast enough. The more variable the arrivals and the service times, the longer the queue.`],
          ['D', `A second discovery concerns how busy a service is. When a server is occupied half of the time, waits are short. As the proportion of time spent working rises towards one hundred per cent, waiting times do not increase gradually; they rise steeply, and at very high levels of use, a small increase in demand can double the wait. This explains why a motorway that flows smoothly at eighty per cent of capacity can come to a standstill after a single minor incident, and why hospitals that run at almost full capacity cannot cope with a sudden increase in patients.`],
          ['E', `The layout of a queue also matters. Many supermarkets offer separate lines for each till, which means that one slow customer can delay everyone behind them, while the neighbouring line moves quickly. A single line that feeds several servers, the system used in most banks and airports, averages out the differences, so that the waits of different customers are much more alike, even if the average wait is similar. The mathematics of this was established in the 1960s, when the American mathematician John Little proved a simple relationship between the average number of people in a system, the rate at which they arrive and the average time each spends there.`],
          ['F', `Psychologists have shown that the experience of waiting depends on more than its length. Time that is occupied seems to pass more quickly than time that is empty, which is why mirrors were once installed near lifts: people who look at their reflections are less bored, and complaints fall. Uncertainty makes waiting worse, so an honest estimate of the delay is often more welcome than a short wait with no information. People also dislike waiting more when they feel that the system is unfair, and will often tolerate a long delay in a single line more readily than a shorter one in which others seem to be overtaking them.`],
          ['G', `Managers of theme parks have turned these findings into practice. Signs display the estimated waiting time at each ride, often slightly longer than the real time so that visitors are pleasantly surprised. Lines wind through shaded areas with entertainment and displays, and visitors can reserve places in a virtual queue through an application, leaving them free to spend the time elsewhere. None of these measures reduces the number of people who want to ride, yet surveys consistently show that they increase satisfaction.`],
          ['H', `The lesson of queueing theory is therefore partly technical and partly human. Extra capacity is always the most effective way to shorten queues, but it is expensive and cannot always be provided. Careful design, honest information and a little entertainment cost far less, and they change not the length of the wait but the way it feels, which, for most people standing in line, is what matters most.`]
        ),
        questionGroups: [
          {
            id: 't6-r2-headings',
            type: 'matching_headings',
            instructionHtml: 'Reading Passage 2 has eight paragraphs, A-H. Choose the correct heading for paragraphs B-G from the list of headings below.<br/><em>Example: Paragraph A — viii</em>',
            bank: [
              { key: 'i', text: 'Why a busy system cannot cope with extra demand' },
              { key: 'ii', text: 'How the subject began' },
              { key: 'iii', text: 'Putting psychological findings to commercial use' },
              { key: 'iv', text: 'The feelings of people who wait' },
              { key: 'v', text: 'Why unpredictable timing matters more than average speed' },
              { key: 'vi', text: 'The history of the supermarket till' },
              { key: 'vii', text: 'One line or many?' },
              { key: 'viii', text: 'A common experience with a scientific explanation' },
              { key: 'ix', text: 'The cost of building faster machines' },
            ],
            questions: [
              q(14, 'Paragraph B', 'ii', 'Paragraph B: "The subject began in 1909".', 'B'),
              q(15, 'Paragraph C', 'v', 'Paragraph C: queues are caused "less by the average speed ... than by its variability".', 'C'),
              q(16, 'Paragraph D', 'i', 'Paragraph D: near full capacity "a small increase in demand can double the wait".', 'D'),
              q(17, 'Paragraph E', 'vii', 'Paragraph E compares separate lines with a single line feeding several servers.', 'E'),
              q(18, 'Paragraph F', 'iv', 'Paragraph F: how boredom, uncertainty and unfairness affect the experience of waiting.', 'F'),
              q(19, 'Paragraph G', 'iii', 'Paragraph G: theme parks "turned these findings into practice".', 'G'),
            ],
          },
          {
            id: 't6-r2-summary',
            type: 'summary_completion_bank',
            instructionHtml: 'Complete the summary using the list of words, A-J, below.',
            bankReusable: false,
            bank: bank(['mirrors', 'random', 'steadily', 'honest', 'capacity', 'entertainment', 'steeply', 'regular', 'technical', 'slower']),
            stemHtml: '<p><strong>Queues and their causes</strong></p><p>Erlang found that calls reached a telephone exchange at {{q20}} intervals rather than at a steady rate. Later studies showed that as a service approaches full use, waiting times rise {{q21}}. Psychologists note that an {{q22}} estimate of the delay can make waiting easier to bear, while the only certain way to shorten queues is to increase {{q23}}.</p>',
            questions: [
              q(20, null, 'B', 'Paragraph B: calls "came at random".', 'B'),
              q(21, null, 'G', 'Paragraph D: waiting times "rise steeply".', 'D'),
              q(22, null, 'D', 'Paragraph F: "an honest estimate of the delay is often more welcome".', 'F'),
              q(23, null, 'E', 'Paragraph H: "Extra capacity is always the most effective way to shorten queues".', 'H'),
            ],
          },
          {
            id: 't6-r2-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B, C or D</strong>.',
            questions: [
              mc(24, 'The example of the bank clerk in paragraph C shows that', ['fast clerks never cause queues', 'queues can form even when a server is fast enough on average', 'customers should arrive at random', 'ten-minute services are too long'], 'B', 'Paragraph C: queues "appear even though the clerk is, on average, fast enough".', 'C'),
              mc(25, 'According to paragraph E, a single line feeding several servers', ['always reduces the average wait', 'makes the waits of different customers more similar', 'is used in most supermarkets', 'was proposed by Erlang'], 'B', 'Paragraph E: "the waits of different customers are much more alike".', 'E'),
              mc(26, 'Why do theme parks sometimes display slightly longer waiting times than the real ones?', ['to discourage visitors from riding', 'to keep the lines shorter', 'so that visitors are pleasantly surprised', 'because the estimates are difficult to calculate'], 'C', 'Paragraph G: "so that visitors are pleasantly surprised".', 'G'),
            ],
          },
        ],
      },
      {
        order: 3,
        title: 'Stairways for salmon',
        subtitle: 'Read the text and answer questions 27-40.',
        paragraphs: paras(
          ['A', `Every autumn, in rivers across the northern hemisphere, salmon set out on one of the most remarkable journeys in the animal kingdom. Born in gravel beds in the upper reaches of a river, they migrate to the sea, where they spend several years feeding and growing, and then return to the very stream in which they hatched to spawn and, in most species, to die. The journey may cover thousands of kilometres, and the last stage involves swimming against strong currents and leaping up waterfalls. For thousands of years the fish managed this unaided. Then people began to build dams.`],
          ['B', `A dam across a river is an impassable wall for a migrating fish. Hundreds of thousands of dams, built for water supply, irrigation, flood control and electricity, now interrupt the world's rivers, and in many of them the populations of salmon, trout, shad and eels have fallen sharply. Because these fish bring nutrients from the sea to inland ecosystems, and because bears, eagles and even trees benefit from their bodies, the loss of a run affects far more than the fish itself. Engineers have been trying to solve the problem for centuries. The simplest solution is a fishway, or fish ladder, which allows fish to climb past an obstacle.`],
          ['C', `The oldest and most common design is the pool-and-weir ladder. It consists of a series of small pools, each about thirty centimetres higher than the last, separated by low walls with gaps through which water flows. A fish can leap or swim from one pool to the next, resting in each, and in this way climbs a slope that would otherwise be impossible. This design is cheap to build and easy to maintain, but it works best for strong jumpers such as salmon and trout, and it is of little use to weaker swimmers.`],
          ['D', `A more recent design is the vertical-slot fishway, in which a narrow opening runs from top to bottom of each dividing wall. Water moves through the slot at varying speeds, and fish can choose the depth and speed that suit them, which makes the ladder usable by a wider range of species and sizes. Because the water level can change without blocking the route, it is also suitable for rivers where the flow varies greatly over the year. Vertical-slot ladders cost more to build, and they need more space.`],
          ['E', `For very high dams, where a ladder would have to be impossibly long, engineers use fish lifts, which work like elevators. Fish swim into a hopper at the base of the dam, attracted by a current of water. The hopper is then raised, and its contents are released into the reservoir above. Lifts are expensive to run and they handle large numbers of fish less smoothly than ladders, but at some of the tallest dams they are the only practical method.`],
          ['F', `Even well-designed fishways have limits. Studies in several countries have found that many ladders allow only a fraction of the fish that reach them to pass, and that delays cost fish energy they need for spawning. Species that do not leap, such as lampreys and sturgeon, are often unable to use them at all. Young fish face a separate danger on the way back to the sea, since those that are swept into the turbines of hydroelectric stations may be killed or injured. In some rivers, operators have therefore added screens, bypass channels and temporary shutdowns during the main migration.`],
          ['G', `In my view, fish ladders should be treated as a compromise rather than a solution. They are valuable where a dam provides something society needs, such as water or energy, and cannot be removed. But the most effective way to restore a river is to take the barrier away, and a growing number of small, obsolete dams have been demolished in recent years. The results are often striking: within a few seasons of one removal in the United States, fish were found miles upstream of places they had not reached for over a century. The challenge now is to decide, dam by dam, which are worth keeping.`]
        ),
        questionGroups: [
          {
            id: 't6-r3-ynng',
            type: 'yes_no_notgiven',
            instructionHtml: YNNG_INSTRUCTION,
            questions: [
              q(27, 'The loss of a salmon run has consequences beyond the fish themselves.', 'YES', 'Paragraph B: "the loss of a run affects far more than the fish itself".', 'B'),
              q(28, 'Fish ladders are a perfect solution to the problem of dams.', 'NO', 'Paragraph G: "fish ladders should be treated as a compromise rather than a solution".', 'G'),
              q(29, 'Fish lifts should be used at all dams in place of ladders.', 'NOT GIVEN', 'Paragraph E says lifts suit tall dams but does not recommend them everywhere.', 'E'),
              q(30, 'Removing obsolete dams is the most effective way to restore a river.', 'YES', 'Paragraph G: "the most effective way to restore a river is to take the barrier away".', 'G'),
              q(31, 'All of the dams that have been built should eventually be demolished.', 'NO', 'Paragraph G: fish ladders are valuable "where a dam provides something society needs"; the writer wants a dam-by-dam decision.', 'G'),
            ],
          },
          {
            id: 't6-r3-classify',
            type: 'matching_features',
            instructionHtml: 'Look at the following features (Questions 32-36) and the list of fishway designs below. Match each feature with the correct design, <strong>A, B or C</strong>.<br/>You may use any letter more than once.',
            bankReusable: true,
            bank: [
              { key: 'A', text: 'pool-and-weir ladder' },
              { key: 'B', text: 'vertical-slot fishway' },
              { key: 'C', text: 'fish lift' },
            ],
            questions: [
              q(32, 'is suitable for rivers where the flow changes a great deal', 'B', 'Paragraph D: suitable "where the flow varies greatly over the year".', 'D'),
              q(33, 'is the only practical method at some very tall dams', 'C', 'Paragraph E: "at some of the tallest dams they are the only practical method".', 'E'),
              q(34, 'is cheap to build and easy to maintain', 'A', 'Paragraph C: "cheap to build and easy to maintain".', 'C'),
              q(35, 'lets fish choose the depth and speed of the water', 'B', 'Paragraph D: "fish can choose the depth and speed that suit them".', 'D'),
              q(36, 'depends on fish being attracted by a current into a hopper', 'C', 'Paragraph E: "attracted by a current of water".', 'E'),
            ],
          },
          {
            id: 't6-r3-sentences',
            type: 'sentence_completion',
            instructionHtml: 'Complete the sentences below. Choose <strong>NO MORE THAN TWO WORDS</strong> from the passage for each answer.',
            wordLimit: { maxWords: 2, label: 'NO MORE THAN TWO WORDS' },
            questions: [
              q(37, 'Salmon return to the stream where they hatched in order to {{q37}}.', 'spawn', 'Paragraph A: "return to the very stream in which they hatched to spawn".', 'A'),
              q(38, 'Each pool in a pool-and-weir ladder is about {{q38}} higher than the last.', ['thirty centimetres', '30 centimetres', '30 cm'], 'Paragraph C: "about thirty centimetres higher".', 'C'),
              q(39, 'Fish that do not leap, such as lampreys and {{q39}}, often cannot use ladders.', 'sturgeon', 'Paragraph F: "lampreys and sturgeon".', 'F'),
              q(40, 'Young fish may be killed or injured if they are swept into {{q40}}.', 'turbines', 'Paragraph F: "swept into the turbines of hydroelectric stations".', 'F'),
            ],
          },
        ],
      },
    ],
  },

  listening: {
    durationSec: 1800,
    checkTimeSec: 120,
    parts: [
      {
        order: 1,
        contextText: 'You will hear a man phoning a council office to ask about renting a room in a community arts centre.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Fairfield Arts Centre, good morning." },
          { speaker: 'B', voice: 'david', text: "Good morning. I'm hoping to rent a room for a weekly drama class for teenagers. Could you tell me what's available?" },
          { speaker: 'A', voice: 'zira', text: "Certainly. We have three rooms. The Garden Room is the smallest, and holds about fifteen people. The Studio holds thirty, and it has a wooden floor, which is popular with dance and drama groups." },
          { speaker: 'B', voice: 'david', text: "I'd have about twenty students, so the Studio sounds right. Is it free on Thursday evenings?" },
          { speaker: 'A', voice: 'zira', text: "Let me check. Yes, it's free on Thursdays from half past five until eight. The price is twenty-two pounds an hour for community groups." },
          { speaker: 'B', voice: 'david', text: "That's reasonable. Is there a discount if we book for a whole term?" },
          { speaker: 'A', voice: 'zira', text: "Yes, ten per cent off for a booking of ten weeks or more. You'll also need public liability insurance. If your group doesn't have its own, we can arrange a policy for you for a small fee." },
          { speaker: 'B', voice: 'david', text: "We don't have one yet, so please do that. What facilities are there in the room?" },
          { speaker: 'A', voice: 'zira', text: "There's a sound system, a projector and a small stage area. We also have a storage cupboard, which you can use for costumes, but it has to be locked at the end of each session." },
          { speaker: 'B', voice: 'david', text: "Excellent. Is there parking?" },
          { speaker: 'A', voice: 'zira', text: "There's a car park behind the building, but it can get full. Most parents use the street in front, which is free after six." },
          { speaker: 'B', voice: 'david', text: "Good to know. Could I have the booking in the name of the Lantern Youth Theatre? That's L-A-N-T-E-R-N." },
          { speaker: 'A', voice: 'zira', text: "Of course. And a contact name?" },
          { speaker: 'B', voice: 'david', text: "Marcus Dunn, D-U-N-N. My mobile number is oh-seven-seven-oh-oh, nine-oh-oh, three-two-one." },
          { speaker: 'A', voice: 'zira', text: "Thank you, Mr Dunn. I'll email you a booking form this afternoon. Your first session could start in two weeks' time." },
        ],
        questionGroups: [
          {
            id: 't6-l1-form',
            type: 'form_completion',
            instructionHtml: 'Complete the form below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Fairfield Arts Centre: Room booking', ''],
              [
                ['Activity', 'weekly {{q1}} class for teenagers'],
                ['Number of students', 'about {{q2}}'],
                ['Room', 'the {{q3}}'],
                ['Day and time', 'Thursday, from {{q4}} until 8 p.m.'],
                ['Price', '£{{q5}} per hour'],
                ['Discount', '{{q6}} per cent for bookings of ten weeks or more'],
                ['Insurance', 'centre will arrange a {{q7}}'],
                ['Facilities', 'sound system, projector and small {{q8}}'],
                ['Group name', 'Lantern Youth {{q9}}'],
                ['Contact surname', '{{q10}}'],
              ]
            ),
            questions: [
              q(1, null, ['drama'], '"a weekly drama class for teenagers".'),
              q(2, null, ['20', 'twenty'], '"I\'d have about twenty students".'),
              q(3, null, ['studio'], '"the Studio sounds right".'),
              q(4, null, ['5.30', '5:30', 'half past five', 'five thirty', '17:30'], '"from half past five until eight".'),
              q(5, null, ['22', 'twenty-two', 'twenty two'], '"twenty-two pounds an hour".'),
              q(6, null, ['10', 'ten'], '"ten per cent off".'),
              q(7, null, ['policy', 'insurance policy'], '"we can arrange a policy for you".'),
              q(8, null, ['stage', 'stage area'], '"a small stage area".'),
              q(9, null, ['theatre'], '"the Lantern Youth Theatre".'),
              q(10, null, ['dunn'], 'Spelled out: D-U-N-N.'),
            ],
          },
        ],
      },
      {
        order: 2,
        contextText: 'You will hear a warden welcoming visitors to a coastal nature reserve and describing the walks on offer.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Good morning, everyone, and welcome to Saltmarsh Point Nature Reserve. I'm Tom, the warden, and I'll explain how to get the most out of your visit today." },
          { speaker: 'A', voice: 'david', text: "The reserve is open from dawn until dusk every day, and entry is free, although we'd be grateful for donations, which help to pay for the wardens and the repair of footpaths." },
          { speaker: 'A', voice: 'david', text: "We have three marked walks. The shortest is the Marsh Trail, which is a one-kilometre boardwalk over the wettest part of the reserve. It's suitable for wheelchairs and pushchairs, and it's the best place to see wading birds such as redshanks and curlews." },
          { speaker: 'A', voice: 'david', text: "The second walk is the Dune Path, which is three kilometres long and takes about ninety minutes. It climbs over the sand dunes, and from the top there's a wonderful view of the estuary. Be careful, though: please keep to the path, because the dune plants are very fragile and easily damaged." },
          { speaker: 'A', voice: 'david', text: "The longest walk is the Headland Circuit, which is eight kilometres. It's a fairly demanding route over rough ground, so you'll need strong shoes. You'll probably see seals at the far end, resting on the sandbanks, but please stay at least fifty metres away from them." },
          { speaker: 'A', voice: 'david', text: "Dogs are allowed on the Dune Path if kept on a lead, but not on the Marsh Trail, because they disturb the birds." },
          { speaker: 'A', voice: 'david', text: "There are two hides, small wooden shelters where you can watch birds without being seen. The first is near the car park, and the second is at the end of the boardwalk. Please speak quietly and don't open the windows more than you need to." },
          { speaker: 'A', voice: 'david', text: "The visitor centre has a café, which is open from ten until four, and a small shop. On Sundays, we run a free guided walk at two o'clock, which lasts about an hour, and no booking is needed." },
          { speaker: 'A', voice: 'david', text: "Finally, the tide comes in quickly on the far side of the reserve, so please check the tide table on the noticeboard before you set off. Enjoy your visit." },
        ],
        questionGroups: [
          {
            id: 't6-l2-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Saltmarsh Point Nature Reserve</strong></p><p>• open from dawn until {{q11}}; donations help to pay for the wardens and for footpath {{q12}}<br/>• <em>Marsh Trail</em>: 1 km boardwalk; good for seeing {{q13}} birds<br/>• <em>Dune Path</em>: 3 km; view of the {{q14}}; visitors must not damage the fragile {{q15}}<br/>• <em>Headland Circuit</em>: {{q16}} km; wear strong {{q17}}; keep 50 metres from the {{q18}}<br/>• dogs are not allowed on the {{q19}}<br/>• free guided walk on Sundays at {{q20}} o\'clock</p>',
            questions: [
              q(11, null, ['dusk'], '"open from dawn until dusk".'),
              q(12, null, ['repair', 'repairs'], '"the repair of footpaths".'),
              q(13, null, ['wading'], '"wading birds such as redshanks and curlews".'),
              q(14, null, ['estuary'], '"a wonderful view of the estuary".'),
              q(15, null, ['dune plants', 'plants'], '"the dune plants are very fragile".'),
              q(16, null, ['8', 'eight'], '"The longest walk is the Headland Circuit, which is eight kilometres."'),
              q(17, null, ['shoes'], '"you\'ll need strong shoes".'),
              q(18, null, ['seals'], '"stay at least fifty metres away from them" (the seals).'),
              q(19, null, ['marsh trail'], '"not on the Marsh Trail".'),
              q(20, null, ['2', 'two'], '"a free guided walk at two o\'clock".'),
            ],
          },
        ],
      },
      {
        order: 3,
        contextText: 'You will hear two students, Leah and Sam, discussing a psychology experiment with their lecturer, Dr Morgan.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david2', text: "Good afternoon, Leah, Sam. You wanted to talk about your experiment on memory and music." },
          { speaker: 'B', voice: 'zira', text: "Yes, Dr Morgan. We want to test whether background music affects how well people remember a list of words." },
          { speaker: 'A', voice: 'david2', text: "That's been done before, of course, so what's new in your approach?" },
          { speaker: 'C', voice: 'david', text: "Most earlier studies only tested classical music. We're comparing three conditions: music with lyrics, music without lyrics, and silence." },
          { speaker: 'A', voice: 'david2', text: "Good. How many participants are you planning to use?" },
          { speaker: 'B', voice: 'zira', text: "We originally thought sixty, but with three conditions, we realised we needed at least ninety, thirty in each group." },
          { speaker: 'A', voice: 'david2', text: "Sensible. Where will you recruit them?" },
          { speaker: 'C', voice: 'david', text: "We'd planned to ask first-year psychology students, but they're not very typical of the general population, so we're going to advertise on the student union noticeboard as well, to get students from other courses." },
          { speaker: 'A', voice: 'david2', text: "That should help. And the word lists?" },
          { speaker: 'B', voice: 'zira', text: "Each participant will see twenty words on a screen for two minutes, then do a short arithmetic task for one minute, and then write down as many as they can." },
          { speaker: 'A', voice: 'david2', text: "Why the arithmetic task?" },
          { speaker: 'B', voice: 'zira', text: "To stop them rehearsing the words in their heads, so we're measuring memory rather than repetition." },
          { speaker: 'A', voice: 'david2', text: "Good. What about the volume of the music? That could be a hidden variable." },
          { speaker: 'C', voice: 'david', text: "We'll keep it the same for everyone, at a moderate level, using headphones so that other sounds don't interfere." },
          { speaker: 'A', voice: 'david2', text: "One more suggestion: consider asking participants whether they normally study with music. Habit might affect the results." },
          { speaker: 'B', voice: 'zira', text: "That's a good idea. We'll add a question to the form." },
          { speaker: 'A', voice: 'david2', text: "You'll also need ethical approval before you begin. The committee meets on the first Tuesday of each month, and forms must be in a week before. Submit yours by the twenty-fifth if you want to start in March." },
          { speaker: 'C', voice: 'david', text: "We'll do that this week. Thank you." },
        ],
        questionGroups: [
          {
            id: 't6-l3-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(21, 'What is new about the students\' experiment?', ['It tests people of different ages.', 'It compares music with lyrics, music without lyrics and silence.', 'It uses classical music only.'], 'B', '"we\'re comparing three conditions: music with lyrics, music without lyrics, and silence".'),
              mc(22, 'How many participants do the students now plan to use?', ['60', '90', '120'], 'B', '"we needed at least ninety, thirty in each group".'),
              mc(23, 'Why will they advertise on the student union noticeboard?', ['to recruit students from other courses', 'to pay participants', 'to find a quiet room'], 'A', '"to get students from other courses".'),
              mc(24, 'The arithmetic task is included to', ['make the experiment more interesting', 'stop participants rehearsing the words', 'test mathematical ability'], 'B', '"To stop them rehearsing the words in their heads".'),
              mc(25, 'What does Dr Morgan suggest adding to the form?', ['a question about studying habits', 'a hearing test', 'a question about age'], 'A', '"asking participants whether they normally study with music".'),
            ],
          },
          {
            id: 't6-l3-table',
            type: 'table_completion',
            instructionHtml: 'Complete the table below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Stage', 'Details'],
              [
                ['Word list', '{{q26}} words shown on a screen for two minutes'],
                ['Distraction task', 'simple {{q27}} for one minute'],
                ['Recall', 'participants write down as many words as they can'],
                ['Music volume', 'the same for everyone; heard through {{q28}}'],
                ['Ethics committee', 'meets on the first {{q29}} of each month'],
                ['Form deadline', 'submit by the {{q30}} to start in March'],
              ]
            ),
            questions: [
              q(26, null, ['20', 'twenty'], '"twenty words on a screen for two minutes".'),
              q(27, null, ['arithmetic', 'arithmetic task'], '"a short arithmetic task for one minute".'),
              q(28, null, ['headphones'], '"using headphones".'),
              q(29, null, ['tuesday'], '"the first Tuesday of each month".'),
              q(30, null, ['25th', 'twenty-fifth', '25', 'twenty fifth'], '"Submit yours by the twenty-fifth".'),
            ],
          },
        ],
      },
      {
        order: 4,
        contextText: 'You will hear part of a lecture about the history of the lighthouse keeper\'s nearest relative, the lightship.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Today I want to talk about lightships, which are ships anchored in place to act as floating lighthouses, and which once guarded some of the most dangerous stretches of sea in the world." },
          { speaker: 'A', voice: 'david', text: "The first lightship in the world was moored off the east coast of England in seventeen thirty-two. Its owner was a man named Robert Hamblin, who was given permission to place a vessel with lanterns on the mast at the mouth of the Thames." },
          { speaker: 'A', voice: 'david', text: "The reason for using a ship was simple. Some of the most dangerous hazards for sailors are sandbanks lying far from any land, where it is impossible to build a stone tower on the shifting sand. A ship can be anchored nearby and moved if the bank changes." },
          { speaker: 'A', voice: 'david', text: "Early lightships carried oil lamps hung from the mast, and later lamps were placed inside a glass lantern that could be raised and lowered with ropes. In the twentieth century, electric lights replaced oil, and powerful horns were added to warn ships in fog." },
          { speaker: 'A', voice: 'david', text: "Life on board was hard. The crew typically spent four weeks at a time on the ship, followed by two weeks ashore. Because the vessels had no engines, they could not move under their own power, so in a storm the ship simply had to ride it out, pitching and rolling at anchor. Seasickness was common, even among experienced sailors." },
          { speaker: 'A', voice: 'david', text: "Lightships were also at great risk themselves. Being anchored in a fixed position in busy shipping lanes, they were sometimes struck by passing vessels that failed to see them in fog. A number of ships were lost in this way, often with all of their crew." },
          { speaker: 'A', voice: 'david', text: "Yet for many years, lightships were seen as a romantic part of seafaring life, and communities on the shore often adopted the vessel and its crew. Children sent letters and gifts at Christmas, and the crews sometimes kept pets, including cats and even pigs." },
          { speaker: 'A', voice: 'david', text: "From the nineteen-sixties, lightships began to disappear, as they were replaced by automatic light towers built on legs fixed to the sea bed, which cost much less to run because they needed no crew. The last lightship staffed by a crew in this country was withdrawn in the nineteen-seventies." },
          { speaker: 'A', voice: 'david', text: "Several old lightships have survived as museums, cafés or floating radio stations, and one is now a hotel. They remain a reminder of a time when keeping the sea safe needed not just a light, but a crew prepared to live in the middle of the ocean." },
        ],
        questionGroups: [
          {
            id: 't6-l4-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Lightships</strong></p><p><em>History</em><br/>• first lightship anchored in {{q31}} near the Thames<br/>• useful where it was impossible to build a tower on {{q32}}</p><p><em>Equipment</em><br/>• early ships hung {{q33}} from the mast<br/>• in the twentieth century, electric lights and {{q34}} were used</p><p><em>Life on board</em><br/>• crew spent {{q35}} weeks on board at a time<br/>• ships had no {{q36}}, so could not move in storms<br/>• danger from passing ships that could not see them in {{q37}}</p><p><em>Community</em><br/>• children sent letters and {{q38}} at Christmas<br/>• crews sometimes kept cats and even {{q39}}</p><p><em>Decline</em><br/>• replaced by automatic towers with {{q40}} fixed to the sea bed</p>',
            questions: [
              q(31, null, ['1732'], '"in seventeen thirty-two".'),
              q(32, null, ['sand', 'shifting sand', 'sandbanks'], '"impossible to build a stone tower on the shifting sand".'),
              q(33, null, ['oil lamps', 'lamps'], '"oil lamps hung from the mast".'),
              q(34, null, ['horns', 'powerful horns'], '"powerful horns were added to warn ships in fog".'),
              q(35, null, ['4', 'four'], '"four weeks at a time".'),
              q(36, null, ['engines'], '"the vessels had no engines".'),
              q(37, null, ['fog'], '"failed to see them in fog".'),
              q(38, null, ['gifts'], '"letters and gifts at Christmas".'),
              q(39, null, ['pigs'], '"cats and even pigs".'),
              q(40, null, ['legs'], '"built on legs fixed to the sea bed".'),
            ],
          },
        ],
      },
    ],
  },

  writing: {
    durationSec: 3600,
    task1: {
      order: 1,
      minWords: 150,
      recommendedMin: 20,
      promptHtml:
        '<p>The graph below shows the number of international tourists visiting three countries between 2000 and 2020.</p><p>Summarise the information by selecting and reporting the main features, and make comparisons where relevant.</p>',
      chart: {
        chartType: 'line',
        title: 'International tourist arrivals, 2000-2020 (millions)',
        unit: 'millions',
        categories: ['2000', '2005', '2010', '2015', '2020'],
        xAxisLabel: 'Year',
        yAxisLabel: 'Millions of visitors',
        series: [
          { name: 'Country A', data: [12, 15, 19, 26, 9] },
          { name: 'Country B', data: [30, 34, 36, 41, 18] },
          { name: 'Country C', data: [5, 9, 14, 22, 6] },
        ],
      },
    },
    task2: {
      order: 2,
      minWords: 250,
      recommendedMin: 40,
      promptHtml:
        '<p>In many countries, the number of people who live alone is increasing.</p><p>Why is this happening? Do you think it is a positive or negative development?</p>',
    },
  },
};
