// Original IELTS-style practice content (NOT copied or paraphrased from any real
// Cambridge/IELTS book). Only the exam STRUCTURE follows a standard Academic test
// layout; every topic, passage, transcript, question and answer is written from scratch.
import { table, TFNG_INSTRUCTION, YNNG_INSTRUCTION, q, paras, mc, bank } from './_html.mjs';

export default {
  slug: 'vocably-practice-test-16',
  title: 'Vocably Practice Test 16',
  difficulty: 'medium',

  reading: {
    durationSec: 3600,
    passages: [
      {
        order: 1,
        title: 'The banana\'s uncertain future',
        subtitle: 'Read the text and answer questions 1-13.',
        paragraphs: paras(
          ['A', `The banana is the most widely exported fruit in the world, and in many tropical countries, it is also a staple food on which millions of people depend. Yet the fruit that arrives in our supermarkets is far more fragile than it appears. The bananas we eat today are all of a single type, and scientists have warned for years that this lack of variety may lead to disaster. The warning is not theoretical: it has happened before. Bananas are grown in more than a hundred and thirty countries, and for some of the poorest of them, exports of the fruit bring in more foreign currency than any other crop, so the stakes are high for growers, traders and families who rely on their wages.`],
          ['B', `Until the 1950s, the banana that dominated international trade was not the one we know now, but a variety called Gros Michel, which was larger, sweeter and more tolerant of rough handling during long sea voyages. It was grown on huge plantations in Central America, and millions of tonnes were shipped each year. Then a soil-living fungus, which causes what is called Panama disease, began to destroy the plantations. The fungus enters the plant through its roots and blocks the vessels that carry water, so that the leaves turn yellow and the plant dies. Once it is in the soil, it can remain there for decades, and no chemical treatment has been found that will remove it. Within a few years, the trade in Gros Michel had collapsed.`],
          ['C', `The industry was saved by a variety called Cavendish, which happened to be resistant to the strain of the fungus that was then spreading. Growers replaced their plantations, and Cavendish quickly became the standard. It is smaller and less sweet than its predecessor, and its skin is more easily damaged, but it survived, and by the end of the twentieth century, it accounted for nearly all of the bananas that entered international markets. The industry had solved the problem, but it had done so by putting its future in the hands of a single variety.`],
          ['D', `The difficulty lies in the way in which bananas reproduce. The fruit we eat is sterile: it contains no seeds that could be planted to produce new plants. Instead, growers take cuttings, or suckers, from the base of an existing plant and grow them on, which means that every Cavendish banana in the world is a clone, genetically identical to the plant from which it came. A population of clones has no variety for natural selection to work on, and a disease that can kill one plant can kill all of them. The same lack of diversity that made it possible to supply the world with a uniform, predictable product also made it fatally vulnerable.`],
          ['E', `That vulnerability is now being tested. A new strain of the fungus, known as Tropical Race 4, emerged in South-East Asia in the 1990s and attacked Cavendish plantations, which had been safe from the earlier strain. It spread to Africa and the Middle East, and in 2019, it was confirmed in Colombia, the first time it had been detected in Latin America, which produces most of the bananas eaten in Europe and North America. Quarantine measures, such as disinfecting boots and vehicles, have slowed the spread but are unlikely to stop it, and plantation owners have found that once the fungus is in a field, the land cannot be used for bananas again.`],
          ['F', `Scientists are searching for solutions. Breeding new varieties by conventional means is extremely difficult, because the plants are sterile and most wild relatives produce fruit full of hard seeds. Genetic modification offers a faster route, and researchers in northern Australia have trialled a Cavendish into which a gene from a wild banana has been inserted, which has proved resistant to Tropical Race 4 in the field. Whether consumers and regulators will accept it is another question. Others argue that the industry should diversify, since there are hundreds of varieties grown by farmers in Africa and Asia, many of them eaten cooked rather than raw. Whatever the answer, few experts doubt that the days of a single banana for the whole world are numbered.`]
        ),
        questionGroups: [
          {
            id: 't16-r1-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              q(1, 'The Gros Michel was the main banana in international trade until the 1950s.', 'TRUE', 'Paragraph B: "Until the 1950s, the banana that dominated international trade ... was Gros Michel".', 'B'),
              q(2, 'Farmers grow new Cavendish plants from seeds.', 'FALSE', 'Paragraph D: the fruit "is sterile"; growers "take cuttings".', 'D'),
              q(3, 'All Cavendish bananas are genetically identical.', 'TRUE', 'Paragraph D: "every Cavendish banana in the world is a clone".', 'D'),
              q(4, 'Panama disease can be removed from soil by chemical treatment.', 'FALSE', 'Paragraph B: "no chemical treatment has been found that will remove it".', 'B'),
              q(5, 'Tropical Race 4 had reached Latin America by 2019.', 'TRUE', 'Paragraph E: "in 2019, it was confirmed in Colombia".', 'E'),
              q(6, 'Consumers are willing to pay more for disease-resistant bananas.', 'NOT GIVEN', 'Paragraph F says acceptance is "another question".', 'F'),
            ],
          },
          {
            id: 't16-r1-sentences',
            type: 'sentence_completion',
            instructionHtml: 'Complete the sentences below. Choose <strong>NO MORE THAN TWO WORDS</strong> from the passage for each answer.',
            wordLimit: { maxWords: 2, label: 'NO MORE THAN TWO WORDS' },
            questions: [
              q(7, 'Growers replaced Gros Michel with a variety called {{q7}}.', ['cavendish'], 'Paragraph C: "a variety called Cavendish".', 'C'),
              q(8, 'New banana plants are produced from {{q8}} rather than seeds.', ['cuttings', 'suckers'], 'Paragraph D: "take cuttings, or suckers".', 'D'),
              q(9, 'Because the plants are identical, a single {{q9}} can kill all of them.', ['disease'], 'Paragraph D: "a disease that can kill one plant can kill all of them".', 'D'),
              q(10, 'The fungus can remain in the {{q10}} for decades.', ['soil'], 'Paragraph B: "Once it is in the soil, it can remain there for decades".', 'B'),
              q(11, 'Conventional breeding is difficult because the plants are {{q11}}.', ['sterile'], 'Paragraph F: "the plants are sterile".', 'F'),
              q(12, 'Researchers in northern {{q12}} have trialled a modified Cavendish.', ['australia'], 'Paragraph F: "researchers in northern Australia".', 'F'),
              q(13, 'In Africa and Asia, many varieties are eaten {{q13}} rather than raw.', ['cooked'], 'Paragraph F: "eaten cooked rather than raw".', 'F'),
            ],
          },
        ],
      },
      {
        order: 2,
        title: 'How we decide whom to trust',
        subtitle: 'Read the text and answer questions 14-26.',
        paragraphs: paras(
          ['A', `Trust is the invisible foundation of social life. We trust doctors to prescribe the right medicine, banks to look after our money and strangers to give us correct directions, and without this trust, economies and societies could hardly function. Yet we make decisions about whom to trust remarkably quickly and, often, with very little evidence. In a well-known series of experiments, psychologists showed volunteers photographs of unfamiliar faces for a fraction of a second, and found that their judgements of trustworthiness after only a tenth of a second were very similar to those made when they were given as long as they liked.`],
          ['B', `What are people looking at? Research suggests that faces with slightly raised eyebrows and an upturned mouth tend to be judged as trustworthy, while those with lowered brows and a downturned mouth appear untrustworthy. It is probable that these judgements reflect a deep-rooted tendency to link expressions of friendliness with good intentions. The trouble is that they are not reliable. When researchers compared people's impressions of faces with how the people behaved in experiments, they found almost no relationship. A face that looks honest is not more likely to belong to an honest person; it is simply a face that looks honest.`],
          ['C', `More accurate judgements come from experience. Economists have studied trust using a simple game in which one player, the investor, is given a sum of money and may send any part of it to a second player, the trustee. The amount sent is tripled on the way, and the trustee then decides how much to return. The investor risks everything but may gain by trusting. On average, investors send about half of their money, and trustees return a little less than they receive. In repeated games, the amounts rise as players build a record of behaviour. Some studies have found that a hormone, oxytocin, increases the amount that investors send, although other researchers have failed to reproduce the result and the question remains disputed.`],
          ['D', `The internet has created situations in which people must trust strangers they will never meet. People rent rooms in the houses of unknown hosts, buy goods from unfamiliar sellers and get into cars with drivers they have found on an app. Most of these systems rely on ratings and reviews, which serve as a record of past behaviour. Research on one home-sharing site found that hosts who included a clear photograph of themselves received more bookings, presumably because the picture made them seem real. Reviews can be faked, of course, and the platforms spend large sums on trying to detect dishonest ones, but on the whole, people trust them more than they trust traditional advertising.`],
          ['E', `Levels of trust differ greatly between countries. Surveys that ask people whether they think most others can be trusted find high levels in Scandinavia and much lower levels in many other parts of the world. In a remarkable experiment, researchers handed in more than seventeen thousand apparently lost wallets at banks, hotels and offices in forty countries, some empty and some containing money, and recorded how many were returned. The wallets were returned more often when they contained a larger amount of cash, a result that surprised even the researchers, who had expected that temptation would make people less honest. The explanation, they suggested, is that people do not like to think of themselves as thieves, and taking a large sum makes that identity harder to ignore.`],
          ['F', `Trust is slow to build and quick to destroy. Psychologists have found that negative information about a person carries more weight than positive information: a single dishonest act can undo the effect of many honest ones, perhaps because the cost of being wrongly trusting is greater than the cost of being wrongly suspicious. Rebuilding lost trust is difficult. Studies suggest that an apology helps, particularly when it accepts responsibility without excuses, but that what matters most is a sustained record of reliable behaviour afterwards.`],
          ['G', `What practical lessons follow? First, we should be wary of trusting our first impressions, particularly of faces. Second, we should look for evidence of past behaviour, such as reputation or references, wherever it exists. Third, we should remember that trusting is not an all-or-nothing choice: in most situations, the sensible approach is to extend limited trust, and to increase it as it is justified. Or, as the old saying has it, trust, but verify.`]
        ),
        questionGroups: [
          {
            id: 't16-r2-matchinfo',
            type: 'matching_information',
            instructionHtml: 'Reading Passage 2 has seven paragraphs, A-G. Which paragraph contains the following information? <em>Choose the correct letter, A-G.</em><br/><strong>NB</strong> You may use any letter more than once.',
            bankReusable: true,
            questions: [
              q(14, 'a reference to the very short time in which judgements about faces are made', 'A', 'Paragraph A: "a tenth of a second".', 'A'),
              q(15, 'a description of an experiment in which money is passed between two players', 'C', 'Paragraph C: investor and trustee.', 'C'),
              q(16, 'an unexpected result involving lost wallets', 'E', 'Paragraph E: wallets returned more often when they contained more cash.', 'E'),
              q(17, 'an example of a system in which strangers rely on ratings and reviews', 'D', 'Paragraph D: home-sharing site.', 'D'),
              q(18, 'a possible reason why negative information has more effect than positive information', 'F', 'Paragraph F: "the cost of being wrongly trusting is greater".', 'F'),
              q(19, 'evidence that judgements based on faces are unreliable', 'B', 'Paragraph B: "almost no relationship".', 'B'),
              q(20, 'a comparison of levels of trust between countries', 'E', 'Paragraph E: "Levels of trust differ greatly between countries."', 'E'),
            ],
          },
          {
            id: 't16-r2-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B, C or D</strong>.',
            questions: [
              mc(21, 'In the experiments described in paragraph A, judgements about trustworthiness', ['improved when people had more time', 'were similar whether made quickly or slowly', 'were different for men and women', 'depended on the photograph\'s quality'], 'B', 'Paragraph A: judgements "were very similar to those made when they were given as long as they liked".', 'A'),
              mc(22, 'What does the writer say about faces with an upturned mouth?', ['They are more trustworthy.', 'They tend to be judged trustworthy, but this is not a reliable guide.', 'They are less common.', 'They are judged more harshly.'], 'B', 'Paragraph B: judged trustworthy, but "they are not reliable".', 'B'),
              mc(23, 'In the trust game, how much do investors send on average?', ['almost nothing', 'about half', 'about a third', 'everything'], 'B', 'Paragraph C: "on average, investors send about half of their money".', 'C'),
              mc(24, 'What is said about oxytocin?', ['It always increases trust.', 'It has no effect.', 'The results of studies are disputed.', 'It is produced by trustees.'], 'C', 'Paragraph C: "the question remains disputed".', 'C'),
              mc(25, 'Why might hosts who include a photograph receive more bookings?', ['The photographs are attractive.', 'The picture makes them seem real.', 'They charge lower prices.', 'They live in better houses.'], 'B', 'Paragraph D: "presumably because the picture made them seem real".', 'D'),
              mc(26, 'What advice does the writer give in paragraph G?', ['Never trust strangers.', 'Always trust first impressions.', 'Extend limited trust and increase it as it is justified.', 'Rely on reviews only.'], 'C', 'Paragraph G: "extend limited trust, and ... increase it as it is justified".', 'G'),
            ],
          },
        ],
      },
      {
        order: 3,
        title: 'The invention of the public park',
        subtitle: 'Read the text and answer questions 27-40.',
        paragraphs: paras(
          ['A', `It is easy to assume that parks have always been part of city life. In fact, the public park, open to all and paid for by the community, is barely two centuries old. Before then, green spaces in and around towns were almost all private: the hunting grounds of kings, the gardens of noblemen and the grounds of great houses, closed to ordinary people. Townspeople had only the commons, where they grazed animals, and the churchyard. The idea that everyone has a right to open space, and that the authorities have a duty to provide it, was a product of the industrial age.`],
          ['B', `The pressure came from the conditions in the new factory towns. As populations grew fast, workers were crowded into poor housing, with little light, poor air and no places to play. Epidemics of cholera and other diseases spread rapidly. In 1833, a committee of the British parliament examined the issue and recommended that public walks should be created near towns, to give the working classes a healthy alternative to the public house. The first park in the world to be built with public money was opened in Birkenhead, near Liverpool, in 1847. Designed by a gardener named Joseph Paxton, it had lakes, winding paths, hills made of excavated earth and carefully placed trees.`],
          ['C', `Birkenhead had an influence well beyond Britain. In 1850, a young American named Frederick Law Olmsted visited it, and was astonished to find that its facilities were available to everybody, rich or poor, without charge. He later recalled that he had never seen anything to match it. A few years afterwards, he and a partner won the competition to design a huge park in the middle of New York, now called Central Park. Their design used a number of ingenious devices: paths that wound through the landscape to hide the city from view, artificial lakes and, most importantly, roads sunk below the level of the park, so that carriages could cross it without disturbing walkers.`],
          ['D', `The founders of early parks had motives that went beyond pleasure. Many were reformers who believed that contact with nature would improve the character of the working classes, reduce drunkenness and crime, and encourage good behaviour. Parks were accordingly governed by lengthy rules. Signs listed what was forbidden, from walking on the grass to playing noisy games, and park keepers were employed to enforce them. Some historians see the parks as an attempt to control the lower classes; others argue that ordinary people valued them for their own reasons and ignored the rules when they could.`],
          ['E', `Modern research has given a scientific basis to some of the reformers' hopes. Studies in many countries have found that people who live near green spaces have lower levels of stress, and tend to be healthier and live longer than those who do not, even when differences of income are taken into account. Trees cool the air in summer, which is increasingly important as cities grow hotter, and they absorb rainwater and pollution. Children with access to parks get more exercise, and property near a well-kept park generally costs more than similar property elsewhere.`],
          ['F', `Keeping parks in good condition costs money, and in many cities, the funds have been cut. Flower beds have been replaced by grass, toilets and cafés have closed and, in some places, the land has been sold for building. One response has been the growth of volunteer groups, known as friends of the park, which raise money, plant trees and organise events. Their work is valuable, but critics point out that it tends to be strongest in wealthy neighbourhoods, which are least in need of it, leaving parks in poorer districts to decline. Some city governments have therefore started to share the money raised in richer areas with those that have fewer resources, an approach that supporters call fair and critics call unwelcome interference.`],
          ['G', `New kinds of park are appearing. Small spaces, sometimes no larger than a few parking spaces, have been converted into pocket parks, and old industrial sites have been given new lives. The best-known is the High Line in New York, a disused elevated railway that was turned into a linear park in 2009, and which has inspired similar projects around the world, from disused canals to abandoned motorways. The park, whatever its form, remains one of the few places in a city where people of different backgrounds can meet without charge, and in a period in which so much public life has moved online or behind paid entry, that seems more valuable than ever.`]
        ),
        questionGroups: [
          {
            id: 't16-r3-headings',
            type: 'matching_headings',
            instructionHtml: 'Reading Passage 3 has seven paragraphs, A-G. Choose the correct heading for paragraphs B-G from the list of headings below.<br/><em>Example: Paragraph A — ix</em>',
            bank: [
              { key: 'i', text: 'Doubts about the real purpose of early parks' },
              { key: 'ii', text: 'A foreign visitor and a famous design' },
              { key: 'iii', text: 'Evidence of benefits to health and the environment' },
              { key: 'iv', text: 'Problems of money and unequal support' },
              { key: 'v', text: 'Crowded towns and the first publicly funded park' },
              { key: 'vi', text: 'The decline of the commons' },
              { key: 'vii', text: 'Parks and the rules that governed them' },
              { key: 'viii', text: 'The cost of land in city centres' },
              { key: 'ix', text: 'Private gardens before public ones' },
              { key: 'x', text: 'New forms of park for a modern city' },
            ],
            questions: [
              q(27, 'Paragraph B', 'v', 'Paragraph B: factory towns and Birkenhead Park, the first built with public money.', 'B'),
              q(28, 'Paragraph C', 'ii', 'Paragraph C: Olmsted visited Birkenhead and designed Central Park.', 'C'),
              q(29, 'Paragraph D', 'vii', 'Paragraph D: signs listed what was forbidden and keepers enforced the rules.', 'D'),
              q(30, 'Paragraph E', 'iii', 'Paragraph E: stress, health, cooling and rainwater.', 'E'),
              q(31, 'Paragraph F', 'iv', 'Paragraph F: budget cuts and friends groups strongest in wealthy areas.', 'F'),
              q(32, 'Paragraph G', 'x', 'Paragraph G: pocket parks and the High Line.', 'G'),
            ],
          },
          {
            id: 't16-r3-ynng',
            type: 'yes_no_notgiven',
            instructionHtml: YNNG_INSTRUCTION,
            questions: [
              q(33, 'Before the nineteenth century, ordinary people had no access to any open space.', 'NO', 'Paragraph A: "Townspeople had only the commons ... and the churchyard."', 'A'),
              q(34, 'Birkenhead Park influenced the design of Central Park.', 'YES', 'Paragraph C: Olmsted visited Birkenhead and later designed Central Park.', 'C'),
              q(35, 'Parks have been shown to reduce crime.', 'NOT GIVEN', 'Paragraph D says reformers believed parks would reduce crime, but no evidence is given.', 'D'),
              q(36, 'Access to green space is associated with better health.', 'YES', 'Paragraph E: "lower levels of stress, and tend to be healthier".', 'E'),
              q(37, 'Governments should be legally required to fund public parks.', 'NOT GIVEN', 'The writer expresses no view on legal requirements.', 'F'),
            ],
          },
          {
            id: 't16-r3-short',
            type: 'short_answer',
            instructionHtml: 'Answer the questions below. Choose <strong>NO MORE THAN THREE WORDS</strong> from the passage for each answer.',
            wordLimit: { maxWords: 3, label: 'NO MORE THAN THREE WORDS' },
            questions: [
              q(38, 'Who designed Birkenhead Park?', ['joseph paxton', 'paxton'], 'Paragraph B: "Designed by a gardener named Joseph Paxton".', 'B'),
              q(39, 'What did the designers of Central Park use so that carriages did not disturb walkers?', ['sunken roads', 'roads sunk below', 'roads sunk'], 'Paragraph C: "roads sunk below the level of the park".', 'C'),
              q(40, 'What was the High Line before it became a park?', ['a disused elevated railway', 'elevated railway', 'disused elevated railway', 'railway'], 'Paragraph G: "a disused elevated railway".', 'G'),
            ],
          },
        ],
      },
    ],
  },

  listening: {
    durationSec: 1800,
    checkTimeSec: 120,
    parts: [
      {
        order: 1,
        contextText: 'You will hear a woman phoning a dental surgery to register as a new patient.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Parkside Dental Surgery, good morning." },
          { speaker: 'B', voice: 'zira', text: "Good morning. I've just moved to the area and I'd like to register as a new patient, please." },
          { speaker: 'A', voice: 'david', text: "Of course. I'll need some details. What's your full name?" },
          { speaker: 'B', voice: 'zira', text: "Miriam Castellano. That's M-I-R-I-A-M, and Castellano is C-A-S-T-E-L-L-A-N-O." },
          { speaker: 'A', voice: 'david', text: "Thank you. And your date of birth?" },
          { speaker: 'B', voice: 'zira', text: "The eleventh of March, nineteen eighty-eight." },
          { speaker: 'A', voice: 'david', text: "Your address?" },
          { speaker: 'B', voice: 'zira', text: "Flat six, Orchard Court, Grange Road." },
          { speaker: 'A', voice: 'david', text: "And when did you last visit a dentist?" },
          { speaker: 'B', voice: 'zira', text: "About eighteen months ago, for a check-up and a clean. I haven't had any trouble since, except that one of my back teeth is sensitive to cold drinks." },
          { speaker: 'A', voice: 'david', text: "I'll note that. Are you allergic to anything, such as a medicine or latex?" },
          { speaker: 'B', voice: 'zira', text: "Yes, I'm allergic to penicillin." },
          { speaker: 'A', voice: 'david', text: "That's important, thank you. A new patient appointment lasts forty minutes and includes an examination, X-rays if they're needed, and a cleaning by the hygienist. It costs sixty pounds." },
          { speaker: 'B', voice: 'zira', text: "That's fine. What's the earliest appointment?" },
          { speaker: 'A', voice: 'david', text: "We have one on Tuesday the fourteenth, at twenty past nine. Would that suit you?" },
          { speaker: 'B', voice: 'zira', text: "Yes, that would be perfect." },
          { speaker: 'A', voice: 'david', text: "Good. Please arrive ten minutes early to fill in a medical form, and bring some identification, such as your driving licence." },
          { speaker: 'B', voice: 'zira', text: "Is there parking?" },
          { speaker: 'A', voice: 'david', text: "There's a small car park behind the building, but there are only six spaces, so you might prefer the bus. The number twenty-two stops right outside." },
          { speaker: 'B', voice: 'zira', text: "Thank you very much. I'll see you on Tuesday." },
        ],
        questionGroups: [
          {
            id: 't16-l1-form',
            type: 'form_completion',
            instructionHtml: 'Complete the form below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Parkside Dental Surgery: New patient', ''],
              [
                ['Surname', '{{q1}}'],
                ['Date of birth', '{{q2}} March 1988'],
                ['Address', 'Flat 6, Orchard Court, {{q3}} Road'],
                ['Last dental visit', 'about {{q4}} months ago'],
                ['Problem', 'a back tooth is sensitive to cold {{q5}}'],
                ['Allergy', '{{q6}}'],
                ['Length of appointment', '{{q7}} minutes'],
                ['Cost', '£{{q8}}'],
                ['Appointment', 'Tuesday 14th at {{q9}} a.m.'],
                ['Bus number', '{{q10}}'],
              ]
            ),
            questions: [
              q(1, null, ['castellano'], 'Spelled out: C-A-S-T-E-L-L-A-N-O.'),
              q(2, null, ['11', 'eleventh', '11th'], '"The eleventh of March".'),
              q(3, null, ['grange'], '"Grange Road".'),
              q(4, null, ['18', 'eighteen'], '"About eighteen months ago".'),
              q(5, null, ['drinks'], '"sensitive to cold drinks".'),
              q(6, null, ['penicillin'], '"I\'m allergic to penicillin."'),
              q(7, null, ['40', 'forty'], '"lasts forty minutes".'),
              q(8, null, ['60', 'sixty'], '"sixty pounds".'),
              q(9, null, ['9.20', '9:20', 'twenty past nine', 'nine twenty'], '"twenty past nine".'),
              q(10, null, ['22', 'twenty-two', 'twenty two'], '"The number twenty-two".'),
            ],
          },
        ],
      },
      {
        order: 2,
        contextText: 'You will hear the manager of a cycling holiday company describing a six-day tour.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Thank you for joining this briefing for the Coast and Castles cycling tour. I'm Graham, the tour manager, and I'd like to outline what you can expect." },
          { speaker: 'A', voice: 'david', text: "The tour lasts six days, starting and finishing in the town of Harlech, in Wales. The total distance is about two hundred and ten kilometres, and the route follows quiet lanes and cycle paths, so you won't need to ride on busy roads." },
          { speaker: 'A', voice: 'david', text: "On the first day, we cycle thirty kilometres along the coast to a village called Llanbedr, where we stay at a small hotel beside the beach. The second day is a little longer, at forty kilometres, and includes a visit to a ruined castle. We'll have a picnic there, which is included in the price." },
          { speaker: 'A', voice: 'david', text: "Day three is the hardest, with forty-five kilometres and a long climb through a forest, but I promise that the view from the top is worth it. We stay that night in a farmhouse, where the owners cook a traditional dinner." },
          { speaker: 'A', voice: 'david', text: "On day four, we have a rest from cycling in the morning, and take a steam train through the mountains, before cycling twenty-five kilometres in the afternoon. On day five, we cycle forty kilometres, mostly downhill, to the coast, and stay in a seaside town, where you'll have free time to explore." },
          { speaker: 'A', voice: 'david', text: "On the last day, there's a gentle thirty-kilometre ride back to Harlech, where we finish with a celebration dinner at the hotel where you started." },
          { speaker: 'A', voice: 'david', text: "Now, some practical points. The price is six hundred and ninety pounds, which includes accommodation, most meals, a support van that carries your luggage, and bike hire. You'll need to pay for lunches on three of the days, and for drinks." },
          { speaker: 'A', voice: 'david', text: "You can bring your own bicycle if you prefer, but we find that most people prefer to use ours, which are light and have plenty of gears. Helmets are compulsory, and I'd recommend padded shorts, as a long day in the saddle can be uncomfortable." },
          { speaker: 'A', voice: 'david', text: "The weather in Wales can change quickly, so bring a waterproof jacket, even in summer. Our van will meet you at lunchtime every day if you need to put on or take off anything." },
        ],
        questionGroups: [
          {
            id: 't16-l2-table',
            type: 'table_completion',
            instructionHtml: 'Complete the table below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Day', 'Distance / activity', 'Notes'],
              [
                ['1', '{{q11}} km along the coast', 'stay in a small hotel beside the beach'],
                ['2', '40 km; visit a ruined {{q12}}', 'picnic included'],
                ['3', '45 km; long climb through a {{q13}}', 'stay in a {{q14}}; traditional dinner'],
                ['4', 'morning: steam train; afternoon: {{q15}} km', ''],
                ['5', '40 km, mostly {{q16}}', 'free time in a seaside town'],
                ['6', '30 km back to Harlech', 'celebration dinner'],
              ]
            ),
            questions: [
              q(11, null, ['30', 'thirty'], '"we cycle thirty kilometres along the coast".'),
              q(12, null, ['castle'], '"a visit to a ruined castle".'),
              q(13, null, ['forest'], '"a long climb through a forest".'),
              q(14, null, ['farmhouse'], '"We stay that night in a farmhouse".'),
              q(15, null, ['25', 'twenty-five', 'twenty five'], '"cycling twenty-five kilometres in the afternoon".'),
              q(16, null, ['downhill'], '"mostly downhill".'),
            ],
          },
          {
            id: 't16-l2-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Practical information</strong></p><p>• total distance: about {{q17}} km<br/>• price: £{{q18}}, including a support van that carries {{q19}}<br/>• compulsory equipment: {{q20}}</p>',
            questions: [
              q(17, null, ['210', 'two hundred and ten'], '"about two hundred and ten kilometres".'),
              q(18, null, ['690', 'six hundred and ninety'], '"six hundred and ninety pounds".'),
              q(19, null, ['luggage'], '"a support van that carries your luggage".'),
              q(20, null, ['helmets', 'helmet'], '"Helmets are compulsory".'),
            ],
          },
        ],
      },
      {
        order: 3,
        contextText: 'You will hear a tutor and two students, Leo and Aisha, discussing a seminar presentation on renewable energy.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david2', text: "Let's plan your presentation on renewable energy. Leo, Aisha, tell me what you've done so far." },
          { speaker: 'B', voice: 'david', text: "We've divided the topic into four parts: solar, wind, hydro and geothermal. But we can't agree who should do what." },
          { speaker: 'C', voice: 'zira', text: "I'd like to do solar, because I've been to a solar farm, and I can use my own photographs." },
          { speaker: 'A', voice: 'david2', text: "That's a good reason. Leo, would you prefer wind?" },
          { speaker: 'B', voice: 'david', text: "Yes, I've read a lot about offshore turbines. But I'm less confident about the economics." },
          { speaker: 'A', voice: 'david2', text: "Then the two of you should check each other's sections. Who will cover hydro?" },
          { speaker: 'C', voice: 'zira', text: "I think Leo could do both wind and hydro, since they're similar, and I'll do solar and geothermal." },
          { speaker: 'B', voice: 'david', text: "Fine by me, as long as the hydro part isn't too long." },
          { speaker: 'A', voice: 'david2', text: "Keep it short. Now, structure. You have twenty minutes altogether. I suggest two minutes for the introduction, four minutes for each of the four types, then a summary comparing their costs, and a final minute for the conclusion." },
          { speaker: 'C', voice: 'zira', text: "That adds up to nineteen. Should we use the extra minute for the question at the start?" },
          { speaker: 'A', voice: 'david2', text: "A good idea. Open with a question to the audience, such as which source provides the most electricity worldwide. It tends to get people's attention." },
          { speaker: 'B', voice: 'david', text: "What about visuals? We have lots of graphs." },
          { speaker: 'A', voice: 'david2', text: "Choose only the ones that make a point. Every graph should have a clear title, and you should tell the audience what to look for before you show it." },
          { speaker: 'C', voice: 'zira', text: "And handouts?" },
          { speaker: 'A', voice: 'david2', text: "A one-page summary with the main figures and a list of sources is enough. Give it out at the end, not at the beginning, or people will read it instead of listening." },
          { speaker: 'B', voice: 'david', text: "We'll rehearse twice before the day, and time ourselves." },
          { speaker: 'A', voice: 'david2', text: "Excellent. The seminar is on the eighteenth, in room twelve. And do try to finish with a clear recommendation, not just a list of facts." },
        ],
        questionGroups: [
          {
            id: 't16-l3-match',
            type: 'matching_features',
            instructionHtml: 'Which student will cover each topic? Choose the correct answer and write the correct letter, <strong>A, B or C</strong>, next to Questions 21-24.',
            bankReusable: true,
            bank: [
              { key: 'A', text: 'Leo' },
              { key: 'B', text: 'Aisha' },
              { key: 'C', text: 'both students' },
            ],
            questions: [
              q(21, 'solar energy', 'B', 'Aisha: "I\'ll do solar and geothermal."'),
              q(22, 'wind energy', 'A', 'Leo: "Yes, I\'ve read a lot about offshore turbines" and Aisha: "Leo could do both wind and hydro".'),
              q(23, 'hydro energy', 'A', 'Aisha: "Leo could do both wind and hydro".'),
              q(24, 'geothermal energy', 'B', 'Aisha: "I\'ll do solar and geothermal."'),
            ],
          },
          {
            id: 't16-l3-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(25, 'How long is the presentation?', ['15 minutes', '20 minutes', '25 minutes'], 'B', '"You have twenty minutes altogether."'),
              mc(26, 'How long does the tutor suggest for each of the four types of energy?', ['two minutes', 'four minutes', 'five minutes'], 'B', '"four minutes for each of the four types".'),
            ],
          },
          {
            id: 't16-l3-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Presentation advice</strong></p><p>• open with a {{q27}} to the audience<br/>• every graph should have a clear {{q28}}<br/>• one-page handout with main figures and a list of {{q29}}, given out at the end<br/>• seminar on the {{q30}}, in room twelve</p>',
            questions: [
              q(27, null, ['question'], '"Open with a question to the audience".'),
              q(28, null, ['title'], '"Every graph should have a clear title".'),
              q(29, null, ['sources'], '"a list of sources".'),
              q(30, null, ['18th', 'eighteenth', '18'], '"The seminar is on the eighteenth".'),
            ],
          },
        ],
      },
      {
        order: 4,
        contextText: 'You will hear part of a lecture about the migration of monarch butterflies.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Each autumn, millions of monarch butterflies make one of the most remarkable journeys in the insect world. Today I'll describe how they do it, and why their numbers have fallen." },
          { speaker: 'A', voice: 'zira', text: "Monarchs that live in eastern North America spend the summer in Canada and the northern United States. When the days shorten in autumn, they fly south, sometimes more than four thousand kilometres, to a small area of mountain forest in central Mexico." },
          { speaker: 'A', voice: 'zira', text: "What is extraordinary is that the butterflies that make the journey have never been there before. Individual monarchs live for only a few weeks in summer, but the generation born in late summer is different: it lives for eight months, and its task is to migrate. The butterflies that arrive in Mexico are the great-grandchildren of those that left the previous spring." },
          { speaker: 'A', voice: 'zira', text: "How do they find their way? Scientists have discovered that monarchs use the position of the sun, together with an internal clock that compensates for its movement across the sky. On cloudy days, they seem to rely on the Earth's magnetic field, which they can sense with special cells in their antennae." },
          { speaker: 'A', voice: 'zira', text: "In Mexico, the butterflies gather in enormous clusters on fir trees, sometimes millions to a hectare. The forest is cool, so the butterflies use little energy, and the dense trees protect them from wind and frost. They remain there until March, when they begin to fly north, laying eggs on milkweed plants on the way." },
          { speaker: 'A', voice: 'zira', text: "Milkweed is essential. It is the only plant on which monarch caterpillars can feed, and it contains toxins that the caterpillars store in their bodies, making them poisonous to birds. The bright orange of the adults is a warning to predators." },
          { speaker: 'A', voice: 'zira', text: "The monarch population has declined steeply over the last twenty years, by more than eighty per cent in some counts. Three main causes have been identified. First, the use of weedkillers in farmland, which has removed milkweed from huge areas. Second, illegal logging in the Mexican forests, which has removed the trees on which the butterflies roost. And third, climate change, which makes the weather less predictable and may disrupt the timing of migration." },
          { speaker: 'A', voice: 'zira', text: "Conservationists are working to reverse the decline. Schools and gardeners across North America are being asked to plant milkweed, and in Mexico, local communities are being paid to protect the forests. Whether these efforts will be enough is still uncertain, but the public interest in the monarch has helped." },
        ],
        questionGroups: [
          {
            id: 't16-l4-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Monarch butterflies</strong></p><p><em>Migration</em><br/>• fly south in autumn, more than {{q31}} km, to mountain forest in central {{q32}}<br/>• the migrating generation lives for {{q33}} months<br/>• navigation: the position of the {{q34}} and an internal clock; on cloudy days, the Earth\'s {{q35}} field</p><p><em>In Mexico</em><br/>• clusters on {{q36}} trees; cool forest saves energy<br/>• return north in {{q37}}, laying eggs on milkweed</p><p><em>Decline</em><br/>• milkweed contains toxins that make caterpillars poisonous to {{q38}}<br/>• causes: weedkillers, illegal {{q39}} and climate change<br/>• numbers have fallen by more than {{q40}} per cent in some counts</p>',
            questions: [
              q(31, null, ['4000', '4,000', 'four thousand'], '"more than four thousand kilometres".'),
              q(32, null, ['mexico'], '"central Mexico".'),
              q(33, null, ['8', 'eight'], '"it lives for eight months".'),
              q(34, null, ['sun'], '"the position of the sun".'),
              q(35, null, ['magnetic'], '"the Earth\'s magnetic field".'),
              q(36, null, ['fir'], '"on fir trees".'),
              q(37, null, ['march'], '"until March, when they begin to fly north".'),
              q(38, null, ['birds'], '"poisonous to birds".'),
              q(39, null, ['logging'], '"illegal logging".'),
              q(40, null, ['80', 'eighty'], '"more than eighty per cent".'),
            ],
          },
        ],
      },
    ],
  },

  writing: {
    durationSec: 3600,
    task1: {
      order: 1,
      minWords: 150,
      recommendedMin: 20,
      promptHtml:
        '<p>The chart below shows the average yearly earnings of men and women in five different occupations in a European country.</p><p>Summarise the information by selecting and reporting the main features, and make comparisons where relevant.</p>',
      chart: {
        chartType: 'bar',
        title: 'Average yearly earnings by occupation (thousand euros)',
        unit: 'thousand euros',
        categories: ['Teaching', 'Nursing', 'Engineering', 'Retail', 'Law'],
        xAxisLabel: 'Occupation',
        yAxisLabel: 'Thousand euros per year',
        series: [
          { name: 'Men', data: [38, 34, 52, 24, 68] },
          { name: 'Women', data: [36, 33, 46, 21, 55] },
        ],
      },
    },
    task2: {
      order: 2,
      minWords: 250,
      recommendedMin: 40,
      promptHtml:
        '<p>Some people say that the best way to protect the environment is for governments to create more parks and protected areas. Others think that individuals must change their own behaviour.</p><p>Discuss both views and give your own opinion.</p>',
    },
  },
};
