// Original IELTS-style practice content (NOT copied or paraphrased from any real
// Cambridge/IELTS book). Only the exam STRUCTURE follows a standard Academic test
// layout; every topic, passage, transcript, question and answer is written from scratch.
import { table, TFNG_INSTRUCTION, YNNG_INSTRUCTION, q, paras, mc, bank } from './_html.mjs';

export default {
  slug: 'vocably-practice-test-14',
  title: 'Vocably Practice Test 14',
  difficulty: 'medium',

  reading: {
    durationSec: 3600,
    passages: [
      {
        order: 1,
        title: 'Closing the gap: the story of the zip',
        subtitle: 'Read the text and answer questions 1-13.',
        paragraphs: paras(
          ['A', `Few inventions are as familiar, or as little noticed, as the zip. It holds together our trousers, jackets, bags and tents, and most of us use one several times a day without thought. Yet it took some twenty years, and the efforts of several people, to turn a clever idea into a product that worked. As so often happens in the history of technology, the person who is remembered for the first step is not always the person who deserves most credit for the last, and the story of the zip is a good example of how an invention is really made.`],
          ['B', `The first attempt was made in 1851 by Elias Howe, the American who is better known for his sewing machine. He patented an "automatic, continuous clothing closure", a row of small clasps joined by a string, but he never put it on the market, and the idea was forgotten. The next step was taken more than forty years later by Whitcomb Judson, an engineer from Chicago, who was looking for an alternative to the long rows of hooks that people then used to fasten their boots. His "clasp locker", shown at a world fair in 1893, consisted of hooks and eyes that were closed by sliding a guide along them. It was clumsy, it tended to spring open, and it rusted in the wash. The only significant order came from the United States Post Office, which bought twenty for its mailbags, and the company founded to manufacture them nearly went bankrupt.`],
          ['C', `The man who solved the problems was Gideon Sundback, a Swedish-born engineer who joined Judson's company in 1906 and later married the manager's daughter. In 1913, he produced a new design that he called the Hookless Fastener. Instead of hooks and eyes, he used two rows of tiny interlocking teeth, each shaped like a scoop with a matching hollow, and a slider that drew them together or pushed them apart. Whereas Judson's fastener had about four hooks to the inch, Sundback's had more than ten, which made the fastening far stronger and more flexible. He also designed the machine that cut and fixed the teeth to a cloth tape at high speed, which brought the price down and made mass production possible.`],
          ['D', `The name by which we know the fastener appeared later. In 1923, a rubber company in Ohio ordered a large number of the fasteners for a new kind of waterproof boot. Its president is said to have been delighted by the sound as the slider closed, and he coined the name "Zipper" for the boots. The word soon came to be used for the fastener itself. The military were among the first customers, using zips on flying suits and sleeping bags in the First World War. The fashion industry was slow to adopt them, but in the 1930s, manufacturers of children's clothes began to advertise them as a way for young children to dress themselves, and designers of men's trousers replaced rows of buttons with a zip, which was quicker and, it was said, more comfortable.`],
          ['E', `Today, the zip is made in billions every year, with the largest producer being a Japanese company that supplies fashion houses and sportswear makers around the world. Its basic design has hardly changed since 1913, although modern zips are made in a huge variety of materials and sizes, from tiny plastic ones for a pencil case to giant ones strong enough to seal the doors of a tent or an aircraft hangar. Engineers have experimented with magnetic fasteners and other alternatives, but none has matched the combination of strength, cost and simplicity.`],
          ['F', `Who, then, invented the zip? Howe had the idea but did nothing with it; Judson made a version that worked in principle but not in practice. It was Sundback who, through years of careful experiment, made the zip into the dependable device we know. In my view, he deserves to be regarded as its true inventor, yet his name is known to very few. The lesson is a wider one. Important inventions are rarely the work of a single mind in a single moment; they are built up gradually, and credit tends to go to those who came first or who were best at publicity, rather than to those who quietly did the work of making things function.`]
        ),
        questionGroups: [
          {
            id: 't14-r1-ynng',
            type: 'yes_no_notgiven',
            instructionHtml: YNNG_INSTRUCTION,
            questions: [
              q(1, 'The zip is an invention whose importance is easily overlooked.', 'YES', 'Paragraph A: "as little noticed" and "used ... without thought".', 'A'),
              q(2, 'Elias Howe deserves more credit than he receives for the modern zip.', 'NO', 'Paragraph B: he "never put it on the market, and the idea was forgotten"; paragraph F says Sundback deserves the credit.', 'B'),
              q(3, 'Judson\'s first fasteners worked reliably.', 'NO', 'Paragraph B: "clumsy ... tended to spring open, and ... rusted".', 'B'),
              q(4, 'Sundback\'s most important contribution was a design with many more teeth to the inch.', 'YES', 'Paragraph C: "more than ten" teeth to the inch "made the fastening far stronger and more flexible".', 'C'),
              q(5, 'Fashion designers were quick to use zips in all types of clothing.', 'NO', 'Paragraph D: "The fashion industry was slow to adopt them".', 'D'),
              q(6, 'Zips are likely to be replaced by magnetic fasteners within a few years.', 'NOT GIVEN', 'Paragraph E mentions magnetic fasteners only as unsuccessful experiments.', 'E'),
            ],
          },
          {
            id: 't14-r1-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B, C or D</strong>.',
            questions: [
              mc(7, 'What does the passage say about Elias Howe\'s patent?', ['It was refused by the patent office.', 'It was never put on the market.', 'It was used for boots.', 'It was sold to Judson.'], 'B', 'Paragraph B: "he never put it on the market".', 'B'),
              mc(8, 'What did the United States Post Office do?', ['It rejected Judson\'s fastener.', 'It bought twenty fasteners for mailbags.', 'It lent money to Judson\'s company.', 'It made its own fasteners.'], 'B', 'Paragraph B: "bought twenty for its mailbags".', 'B'),
              mc(9, 'How did the word "zipper" come to be used?', ['It was invented by Sundback.', 'It was used in advertisements for children.', 'A rubber company used it for boots and it spread to the fastener.', 'It was the name of the military sleeping bag.'], 'C', 'Paragraph D: "coined the name \'Zipper\' for the boots. The word soon came to be used for the fastener itself."', 'D'),
            ],
          },
          {
            id: 't14-r1-summary',
            type: 'summary_completion_bank',
            instructionHtml: 'Complete the summary using the list of words, A-H, below.',
            bankReusable: false,
            bank: bank(['teeth', 'slider', 'machine', 'independence', 'hooks', 'buttons', 'boots', 'uniforms']),
            stemHtml: '<p>Sundback\'s fastener had two rows of interlocking {{q10}}, which were drawn together by a {{q11}}. He also designed a {{q12}} to make them at high speed. In the 1930s, zips in children\'s clothes were advertised as a way for young children to gain {{q13}}.</p>',
            questions: [
              q(10, null, 'A', 'Paragraph C: "two rows of tiny interlocking teeth".', 'C'),
              q(11, null, 'B', 'Paragraph C: "a slider that drew them together".', 'C'),
              q(12, null, 'C', 'Paragraph C: "the machine that cut and fixed the teeth".', 'C'),
              q(13, null, 'D', 'Paragraph D: "a way for young children to dress themselves" (independence).', 'D'),
            ],
          },
        ],
      },
      {
        order: 2,
        title: 'How the brain learns to read',
        subtitle: 'Read the text and answer questions 14-26.',
        paragraphs: paras(
          ['A', `Speech is as old as our species, and every healthy child learns to talk without being taught. Reading is a different matter. Writing was invented only about five thousand years ago, far too recently for evolution to have produced a brain circuit designed for it, and for most of history, most people could not read. Yet today, billions of people do so effortlessly. How the brain achieves this feat is one of the most interesting questions in neuroscience, and the answer, researchers have discovered, is that the brain recycles: a child learning to read takes over regions that evolved for other purposes, notably the recognition of objects and the understanding of spoken language, and trains them to work together in a new way.`],
          ['B', `The key region has been named the visual word form area. It lies in the left temporal lobe, at the side of the brain, and it responds when a person sees letters and words, but not when they see other shapes of similar complexity. Its position is almost identical in readers of very different languages, from English to Chinese to Hebrew, which suggests that the brain has a limited number of suitable places in which to learn to recognise written symbols. Brain scans of children show that the area begins to respond to letters only after they start to be taught, and that the response becomes stronger as reading improves. Illiterate adults, by contrast, show little activity in the same region.`],
          ['C', `Learning to read requires a child to connect the shapes of letters with the sounds of speech, a skill known as phonics. Experiments in many countries have shown that children who are taught to do this explicitly learn to read faster and more accurately than those who are encouraged to guess words from pictures or context. The task is easier in some languages than others. In Italian, a letter or a pair of letters generally stands for a single sound, and most children read confidently after a year. English, by contrast, has about forty sounds, which can be spelled in more than a thousand different ways, and English-speaking children take considerably longer to become fluent.`],
          ['D', `Some children find the task far harder than their classmates, although they are of normal intelligence. Dyslexia, which is estimated to affect between five and ten per cent of people, is characterised by difficulty in linking letters and sounds. Brain scans show that dyslexic readers have less activity than others in areas of the left hemisphere that are used for this purpose, and they appear to compensate by using other regions. The condition is partly inherited, but early help is very effective. Children who receive specialised teaching in the first years of school make striking progress, and their brain activity begins to resemble that of typical readers.`],
          ['E', `Scripts differ, and the brain adapts to them. Readers of Chinese, where each character stands for a word or a part of one, use some additional regions involved in the analysis of shape and in the control of hand movements, presumably because learning to write the characters is a central part of learning to read them. The same is true of those who learn to read languages written from right to left, who scan text in the opposite direction but use essentially the same regions. The brain, it seems, finds ways of adjusting a basic template to the demands of each writing system.`],
          ['F', `The arrival of the screen has raised new questions. A number of studies have compared readers of long texts on paper and on screens, and many have found that people understand and remember a little less when reading on screen, especially when the text is long or difficult. The differences are small, and researchers disagree about the reasons. Some suggest that the physical feel of a book helps readers to build a mental map of where things are in the text, while others point to the distractions that a screen offers. Most agree that the differences are much smaller than the advantage of having the text in front of one at all.`],
          ['G', `Perhaps the most remarkable finding is that the brain can rewire itself at any age. In a study of adults in rural India who had never been to school, researchers taught a group of them to read over several months. Brain scans before and after showed that the visual areas of the brain had changed, with greater responses to written words, and that the areas used for speech had become more sensitive to the sounds of language. The findings suggest that it is never too late to learn, and they provide support for programmes that teach adults to read.`]
        ),
        questionGroups: [
          {
            id: 't14-r2-headings',
            type: 'matching_headings',
            instructionHtml: 'Reading Passage 2 has seven paragraphs, A-G. Choose the correct heading for paragraphs B-G from the list of headings below.<br/><em>Example: Paragraph A — viii</em>',
            bank: [
              { key: 'i', text: 'Differences between writing systems' },
              { key: 'ii', text: 'Evidence that learning can take place in adulthood' },
              { key: 'iii', text: 'A brain region devoted to written symbols' },
              { key: 'iv', text: 'Reading on paper and on screen' },
              { key: 'v', text: 'Why some languages are harder to learn than others' },
              { key: 'vi', text: 'A learning difficulty and how it can be helped' },
              { key: 'vii', text: 'The origins of the alphabet' },
              { key: 'viii', text: 'A skill the brain was not designed for' },
              { key: 'ix', text: 'The effects of reading on memory' },
            ],
            questions: [
              q(14, 'Paragraph B', 'iii', 'Paragraph B: "The key region has been named the visual word form area."', 'B'),
              q(15, 'Paragraph C', 'v', 'Paragraph C compares Italian with English, where spelling is more complicated.', 'C'),
              q(16, 'Paragraph D', 'vi', 'Paragraph D: dyslexia and the effect of early teaching.', 'D'),
              q(17, 'Paragraph E', 'i', 'Paragraph E: Chinese characters and right-to-left scripts.', 'E'),
              q(18, 'Paragraph F', 'iv', 'Paragraph F: comparisons of paper and screens.', 'F'),
              q(19, 'Paragraph G', 'ii', 'Paragraph G: adults in India learned to read.', 'G'),
            ],
          },
          {
            id: 't14-r2-sentences',
            type: 'sentence_completion',
            instructionHtml: 'Complete the sentences below. Choose <strong>NO MORE THAN TWO WORDS</strong> from the passage for each answer.',
            wordLimit: { maxWords: 2, label: 'NO MORE THAN TWO WORDS' },
            questions: [
              q(20, 'Writing was invented about five thousand {{q20}} ago.', ['years'], 'Paragraph A: "about five thousand years ago".', 'A'),
              q(21, 'Children learning to read use brain regions that evolved for recognising objects and understanding {{q21}}.', ['spoken language', 'language', 'speech'], 'Paragraph A: "the understanding of spoken language".', 'A'),
              q(22, 'The visual word form area lies in the left {{q22}} lobe.', ['temporal'], 'Paragraph B: "the left temporal lobe".', 'B'),
              q(23, 'English has about forty sounds, which can be spelled in more than {{q23}} different ways.', ['a thousand', 'one thousand', '1000', '1,000'], 'Paragraph C: "more than a thousand different ways".', 'C'),
              q(24, 'In Italian, most children read {{q24}} after a year.', ['confidently'], 'Paragraph C: "most children read confidently after a year".', 'C'),
              q(25, 'Dyslexia is characterised by difficulty in linking {{q25}} and sounds.', ['letters'], 'Paragraph D: "linking letters and sounds".', 'D'),
              q(26, 'In the study in India, the visual areas of the brain showed greater responses to written {{q26}}.', ['words'], 'Paragraph G: "greater responses to written words".', 'G'),
            ],
          },
        ],
      },
      {
        order: 3,
        title: 'The memory palace',
        subtitle: 'Read the text and answer questions 27-40.',
        paragraphs: paras(
          ['A', `According to a story told by the Roman writer Cicero, a Greek poet named Simonides was dining at a banquet when he was called outside by a messenger. While he was away, the roof of the hall collapsed, killing everyone inside, and the bodies were so badly crushed that the relatives could not identify them. Simonides, however, was able to name each of the guests by remembering where they had been sitting. From this experience, it is said, he worked out the principle of a technique for improving the memory, now known as the method of loci, from the Latin word for places.`],
          ['B', `The technique is simple to describe. The learner chooses a building they know well, such as their own home, and imagines walking through it along a fixed route. Each item to be remembered is turned into a vivid mental picture and placed at a particular point along the route: a loaf of bread on the doormat, an elephant in the hallway. To recall the list, the person simply retraces the route in their mind, and "sees" each image in turn. The method works because of the way the brain has evolved. Our ancestors depended on remembering the layout of their surroundings, where to find water and where danger lay, and human beings have an exceptional capacity for spatial memory, which the technique exploits.`],
          ['C', `In the ancient world, the method was the basis of rhetoric. Roman orators, who were expected to speak for hours without notes, placed the sections of their speeches in the rooms of an imaginary house and walked through them as they spoke. Medieval monks used cloisters and churches to memorise prayers and sermons, and in the sixteenth century, an Italian missionary, Matteo Ricci, amazed Chinese officials by teaching them what he called a memory palace, which allowed them to memorise long texts for the civil service examinations. The technique seemed to lose its place when printing made books cheap, but it never disappeared.`],
          ['D', `Today, it is the foundation of memory sport. Competitors at world championships memorise a shuffled pack of cards in well under a minute, hundreds of random digits in a few minutes and the names and faces of dozens of strangers. Nearly all of them say that they use the method of loci, sometimes with palaces of several hundred locations, which they have built over years and which they reuse by clearing them of images after each competition.`],
          ['E', `Is there something special about the brains of these competitors? A study of memory champions, using brain scans, found no difference in the size or structure of their brains compared with those of ordinary people. But when they were given a memory task, they showed unusual patterns of activity, particularly in regions involved in spatial navigation. A second experiment then took a group of volunteers with average memories and trained them in the method for thirty minutes a day over six weeks. Their performance rose from about thirty words remembered from a list to more than sixty, and brain scans showed that their patterns of activity had begun to resemble those of the champions.`],
          ['F', `Critics point out that the method has limits. It is excellent for memorising ordered lists, such as the names of the American presidents, but it does little to help with understanding, which most educators regard as the real goal. A student who has memorised the parts of the nervous system in an imaginary house does not necessarily know how they function. There is also the argument that in a world where information is available in seconds on a phone, memorising facts is increasingly pointless. Supporters reply that a knowledge store in one's own head is the basis of thinking, since one cannot analyse or compare what one cannot recall.`],
          ['G', `For those who wish to try, experts offer some advice. Use a place you know extremely well, so that the route is automatic, and keep to a fixed order. Make each image as unusual, exaggerated, funny or emotional as possible, since ordinary pictures are soon forgotten. Place only a few items in each room, and review the palace regularly, to keep it fresh. A palace can be reused for different lists, provided that the old images are cleared out first.`],
          ['H', `Technology is now being applied to the method. Several apps help users to build palaces and to track their progress, and researchers are experimenting with virtual reality, in which a learner walks through a computer-generated building with items placed in it. Early studies suggest that such virtual palaces may be at least as effective as imagined ones for some people, particularly those who find it difficult to form clear mental images. Whatever the tools, the idea at the heart of the method is more than two thousand years old: that we remember best what we can place.`]
        ),
        questionGroups: [
          {
            id: 't14-r3-matchinfo',
            type: 'matching_information',
            instructionHtml: 'Reading Passage 3 has eight paragraphs, A-H. Which paragraph contains the following information? <em>Choose the correct letter, A-H.</em>',
            questions: [
              q(27, 'a story about how the technique originated', 'A', 'Paragraph A: the story of Simonides and the banquet.', 'A'),
              q(28, 'an explanation of why the method suits the human brain', 'B', 'Paragraph B: "an exceptional capacity for spatial memory, which the technique exploits".', 'B'),
              q(29, 'a reference to a foreigner who taught the method in China', 'C', 'Paragraph C: Matteo Ricci.', 'C'),
              q(30, 'a description of skills shown by competitors in memory contests', 'D', 'Paragraph D: memorising a shuffled pack of cards.', 'D'),
              q(31, 'a finding about the brain structure of people with exceptional memories', 'E', 'Paragraph E: "no difference in the size or structure of their brains".', 'E'),
              q(32, 'an argument that the technique does not promote understanding', 'F', 'Paragraph F: "it does little to help with understanding".', 'F'),
              q(33, 'advice on how to make mental pictures more memorable', 'G', 'Paragraph G: "unusual, exaggerated, funny or emotional".', 'G'),
            ],
          },
          {
            id: 't14-r3-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              q(34, 'Simonides was able to identify the guests by remembering where they had been sitting.', 'TRUE', 'Paragraph A: "able to name each of the guests by remembering where they had been sitting".', 'A'),
              q(35, 'Roman speakers used the method to speak for hours without notes.', 'TRUE', 'Paragraph C: "expected to speak for hours without notes".', 'C'),
              q(36, 'Matteo Ricci taught the memory palace to officials in Europe.', 'FALSE', 'Paragraph C: Chinese officials.', 'C'),
              q(37, 'Memory champions have physically larger brains than ordinary people.', 'FALSE', 'Paragraph E: "no difference in the size or structure".', 'E'),
              q(38, 'Volunteers who were trained in the method for six weeks roughly doubled the number of words they recalled.', 'TRUE', 'Paragraph E: "from about thirty words ... to more than sixty".', 'E'),
              q(39, 'Students who use memory palaces always understand the subject better.', 'FALSE', 'Paragraph F: "does not necessarily know how they function".', 'F'),
              q(40, 'Virtual reality memory palaces are more effective than imagined ones for all learners.', 'NOT GIVEN', 'Paragraph H says "at least as effective ... for some people", not for all learners.', 'H'),
            ],
          },
        ],
      },
    ],
  },

  listening: {
    durationSec: 1800,
    checkTimeSec: 120,
    parts: [
      {
        order: 1,
        contextText: 'You will hear a woman phoning a community hall to ask about hiring it for a party.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Elmwood Community Hall, good afternoon." },
          { speaker: 'B', voice: 'zira', text: "Good afternoon. I'd like to hire a room for my father's seventieth birthday party, please." },
          { speaker: 'A', voice: 'david', text: "Certainly. When were you thinking of?" },
          { speaker: 'B', voice: 'zira', text: "Saturday the fourth of October, from about six in the evening until eleven." },
          { speaker: 'A', voice: 'david', text: "Let me check. How many guests will there be?" },
          { speaker: 'B', voice: 'zira', text: "About sixty." },
          { speaker: 'A', voice: 'david', text: "Then I'd recommend the Main Hall, which holds up to eighty. It's eighty-five pounds an hour, and there's a minimum booking of four hours. The smaller Garden Room only holds forty." },
          { speaker: 'B', voice: 'zira', text: "The Main Hall, then. Is there a kitchen?" },
          { speaker: 'A', voice: 'david', text: "Yes, with a large fridge, an oven and a dishwasher. You can bring your own food, or use a caterer, but alcohol must be served by a licensed bar, which we can arrange for an additional hundred and twenty pounds." },
          { speaker: 'B', voice: 'zira', text: "That seems fine. Could we have music?" },
          { speaker: 'A', voice: 'david', text: "Yes, there's a sound system, but live music has to stop at ten-thirty because of the neighbours. A disc jockey can carry on until eleven, as long as the volume is reasonable." },
          { speaker: 'B', voice: 'zira', text: "That's fine. Could I come and see the room first?" },
          { speaker: 'A', voice: 'david', text: "Of course. The caretaker, Mr Patel, is there every morning between nine and twelve. There's a deposit of a hundred and fifty pounds, which is refunded if there's no damage, and you'll need to leave the hall clean and tidy." },
          { speaker: 'B', voice: 'zira', text: "And what about decorating? I'd like to hang some banners and balloons." },
          { speaker: 'A', voice: 'david', text: "That's fine, but please don't use tape or pins on the walls. There are hooks along the ceiling for that. Finally, can I take your name and number?" },
          { speaker: 'B', voice: 'zira', text: "Yes, it's Laura Whitfield. W-H-I-T-F-I-E-L-D. The number is oh-seven-seven-oh-oh, nine-oh-oh, six-seven-eight." },
          { speaker: 'A', voice: 'david', text: "Thank you, Ms Whitfield. I'll put a provisional booking on the diary, and you can confirm it after you've seen the room." },
        ],
        questionGroups: [
          {
            id: 't14-l1-form',
            type: 'form_completion',
            instructionHtml: 'Complete the form below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Elmwood Community Hall: Booking enquiry', ''],
              [
                ['Occasion', '{{q1}} birthday party'],
                ['Date', 'Saturday {{q2}} October'],
                ['Time', 'from 6 p.m. until {{q3}} p.m.'],
                ['Number of guests', 'about {{q4}}'],
                ['Room', 'the {{q5}}'],
                ['Cost per hour', '£{{q6}}'],
                ['Extra cost for licensed bar', '£{{q7}}'],
                ['Live music must stop at', '{{q8}}'],
                ['Deposit', '£{{q9}}'],
                ['Contact surname', '{{q10}}'],
              ]
            ),
            questions: [
              q(1, null, ['70th', 'seventieth', '70', 'seventy'], '"my father\'s seventieth birthday party".'),
              q(2, null, ['4th', 'fourth', '4'], '"Saturday the fourth of October".'),
              q(3, null, ['11', 'eleven'], '"until eleven".'),
              q(4, null, ['60', 'sixty'], '"About sixty."'),
              q(5, null, ['main hall'], '"I\'d recommend the Main Hall".'),
              q(6, null, ['85', 'eighty-five', 'eighty five'], '"eighty-five pounds an hour".'),
              q(7, null, ['120', 'a hundred and twenty', 'one hundred and twenty'], '"an additional hundred and twenty pounds".'),
              q(8, null, ['10.30', '10:30', 'ten thirty', 'ten-thirty', 'half past ten'], '"live music has to stop at ten-thirty".'),
              q(9, null, ['150', 'a hundred and fifty', 'one hundred and fifty'], '"a deposit of a hundred and fifty pounds".'),
              q(10, null, ['whitfield'], 'Spelled out: W-H-I-T-F-I-E-L-D.'),
            ],
          },
        ],
      },
      {
        order: 2,
        contextText: 'You will hear a ranger talking about a new visitor centre at a national park.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Hello, everyone, and thank you for coming to the opening of the new visitor centre at Grey Fell National Park. I'm Hannah, the chief ranger, and I'd like to tell you something about what you'll find here." },
          { speaker: 'A', voice: 'zira', text: "The old visitor centre was a wooden hut, built in the nineteen-sixties, which could hold no more than twenty people. The new building is four times the size, and was designed to fit into the landscape: it has a grass roof and is built of local stone and timber." },
          { speaker: 'A', voice: 'zira', text: "It took eighteen months to build and cost just over three million pounds. Half of that came from the national lottery, and the rest from the park authority and donations from local businesses." },
          { speaker: 'A', voice: 'zira', text: "Inside, the main feature is an exhibition about the geology and wildlife of the park, which includes a large model of the mountains that you can touch. Children especially enjoy the interactive displays, where they can follow the life cycle of a salmon, or listen to recordings of birdsong." },
          { speaker: 'A', voice: 'zira', text: "There's also a cinema, with a twelve-minute film showing the park through the seasons. It runs every half hour, and is free." },
          { speaker: 'A', voice: 'zira', text: "The café serves hot meals and snacks, most of which are made with local produce. It's open from nine until five, and in summer until seven. There's also a shop that sells maps, guidebooks and gifts. All the profits go towards the maintenance of the footpaths." },
          { speaker: 'A', voice: 'zira', text: "One of the most important facilities is the information desk, where rangers can advise you on routes and the weather conditions. The mountains can change very quickly, so please check before you set off, particularly if you intend to go above the tree line. You can also hire equipment here, such as walking poles and maps in waterproof cases." },
          { speaker: 'A', voice: 'zira', text: "The car park has room for a hundred and fifty cars, and the charge is four pounds for the day, which is refunded if you spend more than ten pounds in the café or shop. There's a minibus service from the railway station, which runs every hour at weekends." },
          { speaker: 'A', voice: 'zira', text: "We're also delighted to announce that the centre has been awarded a prize for its environmental design. It generates much of its own electricity from solar panels, and rainwater is collected and used in the toilets." },
          { speaker: 'A', voice: 'zira', text: "Now, if you'd like to look around, please do, and I'll be here to answer any questions." },
        ],
        questionGroups: [
          {
            id: 't14-l2-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(11, 'The old visitor centre', ['was built in the 1960s', 'could hold forty people', 'had a grass roof'], 'A', '"a wooden hut, built in the nineteen-sixties".'),
              mc(12, 'How long did the new building take to construct?', ['12 months', '18 months', '24 months'], 'B', '"It took eighteen months to build".'),
              mc(13, 'Half of the cost was paid by', ['the national lottery', 'local businesses', 'the park authority'], 'A', '"Half of that came from the national lottery".'),
              mc(14, 'How long is the film in the cinema?', ['8 minutes', '12 minutes', '30 minutes'], 'B', '"a twelve-minute film".'),
              mc(15, 'Profits from the shop are used to', ['pay the rangers', 'maintain the footpaths', 'build a car park'], 'B', '"All the profits go towards the maintenance of the footpaths."'),
            ],
          },
          {
            id: 't14-l2-table',
            type: 'table_completion',
            instructionHtml: 'Complete the table below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Facility', 'Details'],
              [
                ['Exhibition', 'large model of the {{q16}} that visitors can touch'],
                ['Café', 'open until {{q17}} p.m. in summer'],
                ['Information desk', 'check {{q18}} conditions before going above the tree line'],
                ['Equipment hire', 'walking poles and maps in {{q19}} cases'],
                ['Car park', '{{q20}} cars; £4 for the day'],
              ]
            ),
            questions: [
              q(16, null, ['mountains'], '"a large model of the mountains".'),
              q(17, null, ['7', 'seven'], '"in summer until seven".'),
              q(18, null, ['weather'], '"advise you on routes and the weather conditions".'),
              q(19, null, ['waterproof'], '"maps in waterproof cases".'),
              q(20, null, ['150', 'a hundred and fifty', 'one hundred and fifty'], '"room for a hundred and fifty cars".'),
            ],
          },
        ],
      },
      {
        order: 3,
        contextText: 'You will hear two students, Marta and Sean, discussing an assignment on advertising with their tutor.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david2', text: "Hello, Marta, hello, Sean. You wanted to discuss your assignment on advertising to children." },
          { speaker: 'B', voice: 'zira', text: "Yes. We've been told to choose one aspect of the topic, and we're not sure which would be best." },
          { speaker: 'A', voice: 'david2', text: "What options are you considering?" },
          { speaker: 'C', voice: 'david', text: "Either the use of cartoon characters on food packaging, or advertising on children's television, or the use of social media influencers." },
          { speaker: 'A', voice: 'david2', text: "I'd steer you away from television. It's a well-worn topic, and children watch much less than they did." },
          { speaker: 'B', voice: 'zira', text: "I agree. I prefer the influencers, because it's so current. But I'm worried that there won't be enough academic research." },
          { speaker: 'A', voice: 'david2', text: "There's a growing body of work, particularly from the last five years, and some from the regulators, who have begun to publish guidelines. But the cartoon characters have decades of research, which would make your literature review easier." },
          { speaker: 'C', voice: 'david', text: "I'd like to do that. There's an experiment in which children were offered identical food in plain packaging and in packaging with a cartoon character, and most said the second tasted better." },
          { speaker: 'A', voice: 'david2', text: "Yes, that's a classic study. Could you carry out something like it yourselves?" },
          { speaker: 'B', voice: 'zira', text: "We thought of it, but we'd need permission to work with children, and ethical approval takes a long time." },
          { speaker: 'A', voice: 'david2', text: "Then I suggest a survey of parents instead. You could ask how often their children ask for products because of the character on the pack." },
          { speaker: 'C', voice: 'david', text: "That's much more manageable. How many parents would we need?" },
          { speaker: 'A', voice: 'david2', text: "Fifty would be enough for a small study like this one. You can approach them outside a local school, with the head teacher's permission." },
          { speaker: 'B', voice: 'zira', text: "And how should we present the results?" },
          { speaker: 'A', voice: 'david2', text: "Charts are fine, but don't fill the report with them. Describe the main patterns in words and choose two or three charts that support your argument." },
          { speaker: 'C', voice: 'david', text: "And the word limit is three thousand, isn't it?" },
          { speaker: 'A', voice: 'david2', text: "Yes, plus or minus ten per cent. The deadline is the twelfth of November. Please send me an outline by the end of the month." },
        ],
        questionGroups: [
          {
            id: 't14-l3-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(21, 'Why does the tutor discourage the students from choosing television?', ['It is a well-worn topic.', 'There is too little research.', 'It is too expensive.'], 'A', '"It\'s a well-worn topic".'),
              mc(22, 'What worries Marta about influencers?', ['There may not be enough academic research.', 'They are not popular.', 'It is too complicated.'], 'A', '"I\'m worried that there won\'t be enough academic research."'),
              mc(23, 'Why does the tutor think cartoon characters would be easier?', ['There are decades of research.', 'Children like them.', 'They are cheaper.'], 'A', '"decades of research, which would make your literature review easier".'),
              mc(24, 'Why can\'t the students replicate the packaging experiment?', ['They do not have a budget.', 'They would need ethical approval to work with children.', 'They cannot find packaging.'], 'B', '"we\'d need permission to work with children, and ethical approval takes a long time".'),
              mc(25, 'What does the tutor suggest instead?', ['a survey of parents', 'interviews with teachers', 'a television analysis'], 'A', '"a survey of parents instead".'),
            ],
          },
          {
            id: 't14-l3-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Assignment plan</strong></p><p>• topic: cartoon characters on food {{q26}}<br/>• survey {{q27}} parents outside a local school (need the head teacher\'s permission)<br/>• present the main patterns in {{q28}}, with only two or three charts<br/>• word limit: {{q29}} words<br/>• deadline: {{q30}} November</p>',
            questions: [
              q(26, null, ['packaging', 'packages'], '"food packaging".'),
              q(27, null, ['50', 'fifty'], '"Fifty would be enough".'),
              q(28, null, ['words'], '"Describe the main patterns in words".'),
              q(29, null, ['3000', '3,000', 'three thousand'], '"three thousand".'),
              q(30, null, ['12th', 'twelfth', '12'], '"the twelfth of November".'),
            ],
          },
        ],
      },
      {
        order: 4,
        contextText: 'You will hear part of a lecture about research in the canopy of tropical rainforests.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "For many years, scientists who studied tropical rainforests worked on the ground, yet most of the life in a rainforest lives far above it, in the canopy, the upper layer of branches and leaves, thirty to fifty metres above the forest floor. Today I want to explain how scientists reach this hidden world, and what they've discovered." },
          { speaker: 'A', voice: 'david', text: "The first method was the simplest: climbing. Researchers shot a line over a high branch with a crossbow, used it to pull up a stronger rope and then ascended with climbing equipment. It is cheap, but slow and dangerous, and it allows access to only one tree at a time." },
          { speaker: 'A', voice: 'david', text: "In the nineteen-eighties, scientists began to build walkways of rope and wood between the tops of trees. The longest of these extends for more than three hundred metres. They allow researchers to move around the canopy and stay for long periods, and have become a tourist attraction in some countries." },
          { speaker: 'A', voice: 'david', text: "A more ambitious approach was the canopy crane. A construction crane is installed in the forest, with a gondola that can carry scientists to any point within a circle of about a hundred metres across. This allows repeated visits to the same branches, and makes it possible to study changes across the year." },
          { speaker: 'A', voice: 'david', text: "Even more unusual was the use of an inflatable raft. In the nineteen-eighties, a French team lowered a huge net raft from an airship onto the treetops, where scientists lived for weeks, studying the animals and plants." },
          { speaker: 'A', voice: 'david', text: "More recently, researchers have used drones, which can photograph and sample leaves from the canopy without anyone leaving the ground. They can also carry sensors, which measure temperature and humidity, and they can be used to map the forest in great detail." },
          { speaker: 'A', voice: 'david', text: "What have these methods shown? The canopy is home to a huge proportion of the animal species in the forest, including many insects that have never been described. Some creatures spend their entire lives there, never touching the ground. Frogs breed in pools of water held by plants called bromeliads, growing on the branches, and some species of ant make nests made of leaves." },
          { speaker: 'A', voice: 'david', text: "The canopy also plays a major role in the climate. The leaves release water vapour, which forms clouds and produces rainfall, and they absorb large quantities of carbon dioxide. Understanding how this changes with temperature is vital for predicting the consequences of global warming." },
        ],
        questionGroups: [
          {
            id: 't14-l4-table',
            type: 'table_completion',
            instructionHtml: 'Complete the table below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Method', 'Details'],
              [
                ['Climbing', 'a line is shot over a high branch with a {{q31}}; slow and dangerous; one tree at a time'],
                ['Walkways', 'made of rope and {{q32}}; the longest is over {{q33}} metres'],
                ['Canopy crane', 'a {{q34}} carries scientists within a circle about 100 metres across'],
                ['Inflatable raft', 'lowered onto the treetops from an {{q35}}'],
                ['Drones', 'photograph the canopy and sample {{q36}}; carry sensors for temperature and {{q37}}'],
                ['Findings', 'many insects never described; frogs breed in pools held by {{q38}}'],
                ['Climate', 'leaves release water vapour, which forms {{q39}}; absorb carbon dioxide'],
                ['Importance', 'vital for predicting the effects of {{q40}}'],
              ]
            ),
            questions: [
              q(31, null, ['crossbow'], '"with a crossbow".'),
              q(32, null, ['wood'], '"rope and wood".'),
              q(33, null, ['300', 'three hundred'], '"more than three hundred metres".'),
              q(34, null, ['gondola'], '"a gondola that can carry scientists".'),
              q(35, null, ['airship'], '"from an airship".'),
              q(36, null, ['leaves'], '"sample leaves from the canopy".'),
              q(37, null, ['humidity'], '"temperature and humidity".'),
              q(38, null, ['bromeliads'], '"plants called bromeliads".'),
              q(39, null, ['clouds'], '"forms clouds".'),
              q(40, null, ['global warming'], '"the consequences of global warming".'),
            ],
          },
        ],
      },
    ],
  },

  writing: {
    durationSec: 3600,
    task1: {
      order: 1,
      minWords: 150,
      recommendedMin: 20,
      promptHtml:
        '<p>The graph below shows the amount of plastic waste collected for recycling in three countries between 2000 and 2020.</p><p>Summarise the information by selecting and reporting the main features, and make comparisons where relevant.</p>',
      chart: {
        chartType: 'line',
        title: 'Plastic waste collected for recycling (thousand tonnes)',
        unit: 'thousand tonnes',
        categories: ['2000', '2005', '2010', '2015', '2020'],
        xAxisLabel: 'Year',
        yAxisLabel: 'Thousand tonnes',
        series: [
          { name: 'Germany', data: [480, 700, 950, 1100, 1250] },
          { name: 'Japan', data: [330, 410, 620, 580, 540] },
          { name: 'Brazil', data: [90, 140, 210, 330, 450] },
        ],
      },
    },
    task2: {
      order: 2,
      minWords: 250,
      recommendedMin: 40,
      promptHtml:
        '<p>More and more people are working from home rather than in an office.</p><p>Do the advantages of this development outweigh the disadvantages?</p>',
    },
  },
};
