// Original IELTS-style practice content (NOT copied or paraphrased from any real
// Cambridge/IELTS book). Only the exam STRUCTURE follows a standard Academic test
// layout; every topic, passage, transcript, question and answer is written from scratch.
import { table, TFNG_INSTRUCTION, YNNG_INSTRUCTION, q, paras, mc, bank } from './_html.mjs';

export default {
  slug: 'vocably-practice-test-9',
  title: 'Vocably Practice Test 9',
  difficulty: 'medium',

  reading: {
    durationSec: 3600,
    passages: [
      {
        order: 1,
        title: 'The mountain of clothes',
        subtitle: 'Read the text and answer questions 1-13.',
        paragraphs: paras(
          ['A', `A T-shirt that costs less than a sandwich would have seemed impossible to a shopper in the 1960s, when a garment was an investment to be mended, altered and handed down. Today, clothing is so cheap that many people treat it as disposable. Surveys suggest that the average consumer now buys about sixty per cent more garments than at the start of the century, and keeps each item for only half as long. The shops that sell these clothes have a name, fast fashion, and their success has changed the way the world dresses, and the way it pays for what it wears. To understand how a garment can be sold so cheaply, and who bears the costs that do not appear on the price tag, it is necessary to follow it from the factory to the shop and, eventually, to the rubbish bin.`],
          ['B', `The business model is built on speed. In a traditional fashion house, designs for the coming season are shown on catwalks months before the clothes reach the shops. Fast-fashion chains take the most popular styles from those shows and produce cheaper versions, sometimes within a few weeks. Instead of two collections a year, they bring out new items every week, in small batches, so that shoppers feel that if they do not buy something now, it will be gone. Customers who visit a shop often, knowing that the stock will have changed, buy more, and the chains have built their profits on frequent, low-priced purchases.`],
          ['C', `The environmental cost is considerable. Growing the cotton for a single shirt can require thousands of litres of water, and the chemicals used to dye and finish fabrics pollute rivers in the countries where most clothes are made. Half of all garments are now made of synthetic fibres such as polyester, which come from oil, and every time they are washed, they release tiny plastic particles that pass through sewage works and end up in the sea. Estimates of the industry's share of global greenhouse gas emissions vary widely, from as little as two per cent to as much as ten, partly because so much of the production chain is hard to measure.`],
          ['D', `Behind the low prices are the people who make the clothes. Most garments are sewn in factories in countries where wages are low, often by women who work long hours for little more than the legal minimum. In 2013, a factory building in Bangladesh collapsed, killing more than a thousand workers who had been ordered to go to work despite visible cracks in the walls. The disaster shocked consumers and led to an agreement, signed by many international brands, to improve safety in factories. Campaigners say progress has been uneven, and that the pressure to cut prices still pushes suppliers to cut corners.`],
          ['E', `What happens to clothes when they are no longer wanted is another problem. In wealthy countries, charity shops cannot sell all the garments they are given, and large quantities are sold by the tonne to dealers who export them, often to countries in Africa and Asia, where they are sorted and resold. Much of what arrives is of poor quality and ends up dumped or burned. Only a tiny fraction of used clothing is recycled into new garments, because most fabrics contain mixtures of fibres that are very hard to separate. Sorting by hand is slow and expensive, and machines that can identify different materials reliably are only now being developed. Until they are widely available, the cheapest way to deal with unwanted clothes will remain the least responsible one.`],
          ['F', `Responses are beginning to appear. Some companies rent clothes for a monthly fee, so that customers can wear a new outfit for each occasion without owning it. Others offer repair services, or collect old garments in their shops so that the fibres can be reused. Online platforms make it easy for individuals to resell clothes they no longer want, and sales of second-hand clothing are growing faster than those of new. Governments are also acting: France has made it illegal for retailers to destroy unsold goods, and the European Union is preparing rules that would make producers responsible for the cost of collecting and recycling the clothes they sell. Consumers, however, will have to change their habits for any of this to succeed.`]
        ),
        questionGroups: [
          {
            id: 't9-r1-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              q(1, 'Consumers today buy more clothes than they did at the start of the century.', 'TRUE', 'Paragraph A: "about sixty per cent more garments".', 'A'),
              q(2, 'Fast-fashion shops bring out new collections twice a year.', 'FALSE', 'Paragraph B: "Instead of two collections a year, they bring out new items every week".', 'B'),
              q(3, 'Fast-fashion companies pay catwalk designers for the use of their ideas.', 'NOT GIVEN', 'Paragraph B says styles are taken from catwalk shows but does not mention payment.', 'B'),
              q(4, 'Synthetic fabrics release tiny plastic particles when they are washed.', 'TRUE', 'Paragraph C: "they release tiny plastic particles".', 'C'),
              q(5, 'All experts agree on the industry\'s share of global emissions.', 'FALSE', 'Paragraph C: estimates "vary widely".', 'C'),
              q(6, 'More than a thousand workers died when a factory building collapsed in Bangladesh.', 'TRUE', 'Paragraph D: "killing more than a thousand workers".', 'D'),
              q(7, 'Most second-hand clothing exported to Africa is sold at a profit.', 'NOT GIVEN', 'Paragraph E does not give figures on profits.', 'E'),
            ],
          },
          {
            id: 't9-r1-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Choose <strong>ONE WORD ONLY</strong> from paragraph F for each answer.',
            wordLimit: { maxWords: 1, label: 'ONE WORD ONLY' },
            stemHtml: '<p><strong>Responses to fast fashion</strong></p><p>• Some companies rent clothes for a monthly {{q8}}.<br/>• Others provide {{q9}} services.<br/>• Old garments are collected in shops so that the {{q10}} can be reused.<br/>• Sales of {{q11}} clothing are growing faster than sales of new clothing.<br/>• France has banned the destruction of {{q12}} goods.<br/>• EU rules would make {{q13}} pay for collecting and recycling clothes.</p>',
            questions: [
              q(8, null, ['fee'], 'Paragraph F: "for a monthly fee".', 'F'),
              q(9, null, ['repair'], 'Paragraph F: "repair services".', 'F'),
              q(10, null, ['fibres', 'fibers'], 'Paragraph F: "so that the fibres can be reused".', 'F'),
              q(11, null, ['second-hand', 'second hand'], 'Paragraph F: "sales of second-hand clothing".', 'F'),
              q(12, null, ['unsold'], 'Paragraph F: "destroy unsold goods".', 'F'),
              q(13, null, ['producers'], 'Paragraph F: "make producers responsible for the cost".', 'F'),
            ],
          },
        ],
      },
      {
        order: 2,
        title: 'Why do we dream?',
        subtitle: 'Read the text and answer questions 14-26.',
        paragraphs: paras(
          ['A', `Every night, an average person spends about two hours dreaming, which adds up to around six years of a long life. Yet for most of history nobody knew when dreams occurred, or what the sleeping brain was doing. The breakthrough came in 1953, when researchers at a university in Chicago noticed that, at certain times during the night, the eyes of sleeping volunteers began to move rapidly beneath their closed lids. When the volunteers were woken during these periods, most said they had been dreaming. The discovery of what became known as rapid eye movement, or REM, sleep showed that dreams were linked to a particular stage of sleep, and made it possible to study them scientifically for the first time. Researchers soon found that a night's sleep is divided into cycles of about ninety minutes, and that REM periods grow longer towards morning, which is why the dreams people remember are usually the ones that occur just before waking.`],
          ['B', `Long before then, people had their own explanations. In ancient Egypt, dreams were recorded on papyrus, and priests were consulted to interpret them, in the belief that they were messages from the gods. Many cultures treated dreams as a means of prophecy, a view that survived for thousands of years. In the early twentieth century, psychologists proposed that dreams were a disguised expression of hidden wishes, a theory that was enormously influential, but which proved difficult to test and has few supporters among scientists today. More recent approaches have tended to start from what can be measured: how the brain behaves, what happens to people who are deprived of REM sleep, and how dreams change over a lifetime.`],
          ['C', `Modern brain imaging has revealed what happens during REM sleep. The prefrontal cortex, the part of the brain that handles logic and planning, is much less active than usual, while the amygdala, which is involved in emotion, is more active. This combination may explain the character of dreams: events that would be absurd in waking life, such as flying or meeting someone long dead, seem perfectly natural, while feelings of fear, joy and embarrassment are felt strongly. The dreaming brain, in other words, is emotionally alert but largely without its usual critic.`],
          ['D', `One of the best-supported ideas is that sleep helps the brain to store memories. In a series of experiments, students who were asked to learn a list of word pairs recalled more of them after a night's sleep than after the same period awake. Brain recordings suggest that patterns of activity present during learning are replayed during sleep, and some researchers believe that dreams may be a conscious by-product of this process. However, the content of most dreams bears little obvious relation to what a person did the day before, and the theory cannot easily explain why.`],
          ['E', `A rival suggestion, sometimes called the threat rehearsal theory, holds that dreaming evolved to allow our ancestors to practise dealing with danger in safety. Supporters point out that dreams frequently involve being chased, attacked or falling, and that people in dangerous environments tend to report more threatening dreams. Critics respond that only a minority of dreams contain serious threats, and that many are about everyday matters such as work, relationships and travel. If dreams were primarily about rehearsing danger, they argue, the balance would be very different.`],
          ['F', `A third view emphasises the role of dreams in managing emotion. Experiments suggest that REM sleep reduces the emotional intensity of memories, so that upsetting events are recalled with less distress after sleep. People who have experienced trauma often suffer from repeated nightmares, which some researchers interpret as a sign that this process has failed. Therapies that help patients to rewrite the endings of their nightmares while awake have reduced their frequency, suggesting that the link between dreaming and emotional health is a genuine one.`],
          ['G', `Which of these theories is correct? Quite possibly, more than one. Dreaming may have no single function, but serve several at once, or it may be a by-product of other processes in the sleeping brain, with no purpose of its own. Researchers are now using new methods, including recordings of brain activity made while volunteers describe their dreams in real time, to tackle the question, but for the moment the answer remains one of the most intriguing puzzles in science.`]
        ),
        questionGroups: [
          {
            id: 't9-r2-headings',
            type: 'matching_headings',
            instructionHtml: 'Reading Passage 2 has seven paragraphs, A-G. Choose the correct heading for paragraphs B-F from the list of headings below.<br/><em>Example: Paragraph A — vii</em>',
            bank: [
              { key: 'i', text: 'The brain\'s part in the strange content of dreams' },
              { key: 'ii', text: 'Dreams as practice for danger' },
              { key: 'iii', text: 'Ancient explanations and their successors' },
              { key: 'iv', text: 'Sleep and the storage of memories' },
              { key: 'v', text: 'Dreams and the handling of feelings' },
              { key: 'vi', text: 'The dreams of people who are blind' },
              { key: 'vii', text: 'How scientists began to study dreaming' },
              { key: 'viii', text: 'Drugs that affect dreaming' },
            ],
            questions: [
              q(14, 'Paragraph B', 'iii', 'Paragraph B: Egyptian beliefs and early-twentieth-century theories.', 'B'),
              q(15, 'Paragraph C', 'i', 'Paragraph C: less active prefrontal cortex may explain dream content.', 'C'),
              q(16, 'Paragraph D', 'iv', 'Paragraph D: sleep and recall of word pairs.', 'D'),
              q(17, 'Paragraph E', 'ii', 'Paragraph E: threat rehearsal theory.', 'E'),
              q(18, 'Paragraph F', 'v', 'Paragraph F: REM sleep "reduces the emotional intensity of memories".', 'F'),
            ],
          },
          {
            id: 't9-r2-short',
            type: 'short_answer',
            instructionHtml: 'Answer the questions below. Choose <strong>NO MORE THAN THREE WORDS AND/OR A NUMBER</strong> from the passage for each answer.',
            wordLimit: { maxWords: 3, maxNumbers: 1, label: 'NO MORE THAN THREE WORDS AND/OR A NUMBER' },
            questions: [
              q(19, 'In which year was rapid eye movement sleep first noticed?', ['1953'], 'Paragraph A: "in 1953".', 'A'),
              q(20, 'What do the initials REM stand for?', ['rapid eye movement'], 'Paragraph A: "rapid eye movement, or REM".', 'A'),
              q(21, 'Which part of the brain, involved in emotion, is more active during REM sleep?', ['amygdala', 'the amygdala'], 'Paragraph C: "the amygdala".', 'C'),
              q(22, 'What did students learn before sleeping in the memory experiments?', ['word pairs', 'a list of word pairs', 'list of word pairs'], 'Paragraph D: "a list of word pairs".', 'D'),
            ],
          },
          {
            id: 't9-r2-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              q(23, 'The threat rehearsal theory is supported by the frequency of dreams about danger.', 'TRUE', 'Paragraph E: "dreams frequently involve being chased, attacked or falling".', 'E'),
              q(24, 'Most dreams contain a serious threat.', 'FALSE', 'Paragraph E: "only a minority of dreams contain serious threats".', 'E'),
              q(25, 'People who have experienced trauma often suffer from repeated nightmares.', 'TRUE', 'Paragraph F: "often suffer from repeated nightmares".', 'F'),
              q(26, 'Scientists now agree that dreaming has a single function.', 'FALSE', 'Paragraph G: "Dreaming may have no single function".', 'G'),
            ],
          },
        ],
      },
      {
        order: 3,
        title: 'Growing food in the city',
        subtitle: 'Read the text and answer questions 27-40.',
        paragraphs: paras(
          ['A', `By the middle of this century, about two-thirds of the world's population is expected to live in cities, most of them depending on food that has been grown far away and transported over long distances. Against this background, a movement has grown up in many countries to bring farming back into urban areas. Its supporters include environmental campaigners, entrepreneurs, community groups and city authorities, and their projects range from small vegetable plots on vacant lots to huge indoor farms in converted warehouses. The three main types differ greatly in their methods, costs and aims.`],
          ['B', `Community gardens are the oldest and simplest. Volunteers take over a piece of unused land, such as a disused car park or the space between buildings, and divide it into plots for vegetables, herbs and flowers. The produce is usually shared among the members, or given to neighbours and local food banks, rather than sold. The yields are modest, but supporters stress other benefits: gardens bring together people from different backgrounds, give children a chance to learn where food comes from and make neglected areas more attractive. Organisers must often test the soil before planting, since land in old industrial areas may be contaminated with metals and other pollutants.`],
          ['C', `Rooftop farms use another kind of unused space: the flat roofs of offices, shops and apartment blocks. Crops are grown either in containers of soil or in shallow trays fed by nutrient-rich water. A layer of plants insulates the building beneath, keeping it cooler in summer and warmer in winter, and the soil absorbs rainwater that would otherwise run off into the drains and, in heavy storms, contribute to flooding. The main constraint is weight, since a roof with a garden on it carries far more than an empty one, and engineers must check that the structure can bear the load. Many rooftop farms are commercial, supplying restaurants and shops in the neighbourhood with fresh vegetables and herbs.`],
          ['D', `Vertical farms are the most technologically ambitious. They grow crops indoors in stacked trays, in rooms that may be many storeys tall, without soil or sunlight. The plants' roots are bathed in a nutrient solution, and their light comes from energy-efficient lamps tuned to the wavelengths that plants use best. Because the water is recycled, these farms can use up to ninety-five per cent less water than conventional agriculture, and because conditions are controlled, they can harvest all year round, free from pests and bad weather. Their limitation is that almost all of their output consists of leafy vegetables and herbs, which are light and quick to grow, whereas staples such as wheat and rice need far more space and energy than such systems can supply.`],
          ['E', `Whether urban farms can make money is another matter. Land in cities is expensive, and for vertical farms, the biggest single cost is electricity for the lamps and ventilation. A number of well-funded vertical farming companies have closed in recent years after failing to make their sums add up, and many others depend on investment rather than on sales. Some city governments have offered subsidies or cheap land, reasoning that the wider benefits justify the support, but the question of who should pay remains unresolved.`],
          ['F', `The environmental case is also more complicated than it first appears. Supporters often claim that growing food close to consumers reduces the emissions from transport, but studies show that transport accounts for only a small share of the greenhouse gases produced by the food system as a whole; most comes from the way food is grown. By that measure, an urban farm that uses heated and lit buildings may actually do worse than a conventional farm in a sunny region. Urban agriculture does, however, offer benefits that are harder to count, such as fresher produce, local jobs and education about food.`],
          ['G', `In my view, it is a mistake to judge urban farming by whether it can feed cities, because it will not. Even in the most optimistic calculations, it can supply only a small fraction of what a large city eats. What it can do is add variety and resilience to the food supply, connect residents with the origins of their meals and make use of spaces that would otherwise be wasted. Seen as a complement to conventional agriculture rather than a replacement for it, it deserves more support than its critics allow, and more realism than its most enthusiastic supporters display.`]
        ),
        questionGroups: [
          {
            id: 't9-r3-classify',
            type: 'matching_features',
            instructionHtml: 'Look at the following statements (Questions 27-34) and the list of types of urban farm below. Match each statement with the correct type, <strong>A, B or C</strong>.<br/>You may use any letter more than once.',
            bankReusable: true,
            bank: [
              { key: 'A', text: 'community gardens' },
              { key: 'B', text: 'rooftop farms' },
              { key: 'C', text: 'vertical farms' },
            ],
            questions: [
              q(27, 'The produce is usually shared among the people who work there.', 'A', 'Paragraph B: "usually shared among the members".', 'B'),
              q(28, 'Crops are grown without soil, under artificial light.', 'C', 'Paragraph D: "without soil or sunlight".', 'D'),
              q(29, 'Engineers must check that the building can bear the extra weight.', 'B', 'Paragraph C: "engineers must check that the structure can bear the load".', 'C'),
              q(30, 'The ground may need to be tested for pollutants.', 'A', 'Paragraph B: "test the soil before planting".', 'B'),
              q(31, 'They help to keep the building below cooler in summer.', 'B', 'Paragraph C: "keeping it cooler in summer".', 'C'),
              q(32, 'They can use up to ninety-five per cent less water than conventional farming.', 'C', 'Paragraph D: "up to ninety-five per cent less water".', 'D'),
              q(33, 'Their output consists almost entirely of leafy vegetables and herbs.', 'C', 'Paragraph D: "almost all of their output consists of leafy vegetables and herbs".', 'D'),
              q(34, 'They absorb rainwater that might otherwise cause flooding.', 'B', 'Paragraph C: "the soil absorbs rainwater".', 'C'),
            ],
          },
          {
            id: 't9-r3-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              q(35, 'Most of the world\'s people are expected to live in cities by the middle of this century.', 'TRUE', 'Paragraph A: "about two-thirds of the world\'s population".', 'A'),
              q(36, 'Electricity is the largest single cost for vertical farms.', 'TRUE', 'Paragraph E: "the biggest single cost is electricity".', 'E'),
              q(37, 'Community gardens have been shown to reduce crime in the areas around them.', 'NOT GIVEN', 'Crime is not mentioned.'),
              q(38, 'Transport causes most of the greenhouse gases produced by the food system.', 'FALSE', 'Paragraph F: transport "accounts for only a small share".', 'F'),
              q(39, 'No city government has offered financial support to urban farms.', 'FALSE', 'Paragraph E: "Some city governments have offered subsidies or cheap land".', 'E'),
              q(40, 'The writer believes that urban farming has no value.', 'FALSE', 'Paragraph G: it "deserves more support than its critics allow".', 'G'),
            ],
          },
        ],
      },
    ],
  },

  listening: {
    durationSec: 1800,
    checkTimeSec: 120,
    parts: [
      {
        order: 1,
        contextText: 'You will hear a woman phoning an employment agency to register for temporary work.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Brightside Recruitment, good afternoon." },
          { speaker: 'B', voice: 'zira', text: "Hello. I'm looking for temporary work for the summer, and I'd like to register with your agency." },
          { speaker: 'A', voice: 'david', text: "Of course. I'll take some details. Could I have your full name?" },
          { speaker: 'B', voice: 'zira', text: "Yes, it's Helena Marsh. M-A-R-S-H." },
          { speaker: 'A', voice: 'david', text: "And your current occupation?" },
          { speaker: 'B', voice: 'zira', text: "I'm a student. I've just finished my second year of a degree in languages, and I'm free until the end of September." },
          { speaker: 'A', voice: 'david', text: "What sort of work are you interested in?" },
          { speaker: 'B', voice: 'zira', text: "Office work, ideally, like reception or data entry. I've done some of that before, at a travel agency." },
          { speaker: 'A', voice: 'david', text: "Good. Do you have any other skills we should note?" },
          { speaker: 'B', voice: 'zira', text: "I speak fluent Spanish and some German, and I can type quite fast, about sixty words a minute." },
          { speaker: 'A', voice: 'david', text: "That's very useful. Are you looking for full-time work?" },
          { speaker: 'B', voice: 'zira', text: "Yes, but I can't start before the twenty-second of June, because I have exams until then." },
          { speaker: 'A', voice: 'david', text: "That's fine. What rate of pay are you hoping for?" },
          { speaker: 'B', voice: 'zira', text: "I'd like at least eleven pounds an hour." },
          { speaker: 'A', voice: 'david', text: "That should be possible for the sort of work you describe. Now, how would you travel to work?" },
          { speaker: 'B', voice: 'zira', text: "I don't have a car, so it needs to be somewhere near a train station. I live in Hadley, in Bridge Street." },
          { speaker: 'A', voice: 'david', text: "Right. We'll need two references. Could you give me the name of a previous employer?" },
          { speaker: 'B', voice: 'zira', text: "Yes, Mr Andrew Keane, at Sunway Travel. And my tutor at university can be the other." },
          { speaker: 'A', voice: 'david', text: "Perfect. Could you come in to our office on Thursday morning to do a short typing test and to bring your passport?" },
          { speaker: 'B', voice: 'zira', text: "Yes, what time?" },
          { speaker: 'A', voice: 'david', text: "Half past nine, at forty Castle Street, on the second floor." },
        ],
        questionGroups: [
          {
            id: 't9-l1-form',
            type: 'form_completion',
            instructionHtml: 'Complete the form below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Brightside Recruitment: Registration', ''],
              [
                ['Surname', '{{q1}}'],
                ['Occupation', '{{q2}}'],
                ['Type of work wanted', 'office work, e.g. reception or {{q3}}'],
                ['Languages', 'Spanish and some {{q4}}'],
                ['Typing speed', '{{q5}} words per minute'],
                ['Earliest start date', '{{q6}} June'],
                ['Minimum pay', '£{{q7}} per hour'],
                ['Home street', '{{q8}} Street'],
                ['Referee', 'Mr Andrew Keane, {{q9}} Travel'],
                ['Appointment on Thursday', '{{q10}} a.m.'],
              ]
            ),
            questions: [
              q(1, null, ['marsh'], 'Spelled out: M-A-R-S-H.'),
              q(2, null, ['student'], '"I\'m a student".'),
              q(3, null, ['data entry'], '"reception or data entry".'),
              q(4, null, ['german'], '"some German".'),
              q(5, null, ['60', 'sixty'], '"about sixty words a minute".'),
              q(6, null, ['22', 'twenty-second', '22nd', 'twenty second'], '"the twenty-second of June".'),
              q(7, null, ['11', 'eleven'], '"at least eleven pounds an hour".'),
              q(8, null, ['bridge'], '"in Bridge Street".'),
              q(9, null, ['sunway'], '"Mr Andrew Keane, at Sunway Travel".'),
              q(10, null, ['9.30', '9:30', 'half past nine', 'nine thirty'], '"Half past nine".'),
            ],
          },
        ],
      },
      {
        order: 2,
        contextText: 'You will hear a guide giving information about a city bus tour.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Good morning, everyone, and welcome aboard the Old Town Explorer. I'm Claire, and I'll be your guide for the next ninety minutes." },
          { speaker: 'A', voice: 'zira', text: "Our tour begins here in Market Square, goes past the cathedral and the river, and finishes at the castle, where you can get off if you wish. Your ticket is valid all day, so you can get on and off at any of the twelve stops." },
          { speaker: 'A', voice: 'zira', text: "Buses run every twenty minutes. The first leaves at nine thirty, and the last at four fifteen. If you want to visit the castle, I recommend that you go in the morning, because it's very crowded after lunch." },
          { speaker: 'A', voice: 'zira', text: "Our first stop, about ten minutes from here, is the cathedral. It was built in the twelfth century, and its tower is the tallest medieval structure in the region. Tours of the tower are available, but you need to book in advance at the information desk, and the climb is three hundred steps." },
          { speaker: 'A', voice: 'zira', text: "The second stop is the Museum of Local History, which has free entry. It's particularly good for children, who can dress up in costumes from different periods." },
          { speaker: 'A', voice: 'zira', text: "Next, we cross the old stone bridge, which dates from the fifteenth century, and stop at Riverside Gardens. There's a café there, and in summer there are free concerts on Sunday afternoons." },
          { speaker: 'A', voice: 'zira', text: "After that, we travel through the old market district, which has many small shops and restaurants, before the bus climbs the hill to the castle. The castle is open from ten until five, and the entrance fee is eight pounds for adults, though there's a reduction for students." },
          { speaker: 'A', voice: 'zira', text: "For the return journey, the bus takes a different route, past the university and the new science park, back to Market Square." },
          { speaker: 'A', voice: 'zira', text: "Please remember to keep your ticket with you, and if you have any questions, just ask me or the driver. If you'd like to take photos, the best views are from the upper deck, but do hold on when we're moving." },
        ],
        questionGroups: [
          {
            id: 't9-l2-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Old Town Explorer</strong></p><p>• tour lasts {{q11}} minutes; {{q12}} stops in total<br/>• buses every 20 minutes; last bus leaves at {{q13}}<br/>• visit the castle in the {{q14}} because it is crowded after lunch<br/>• <em>Cathedral</em>: built in the twelfth century; climb has {{q15}} steps; tower tours must be booked at the information desk<br/>• <em>Museum of Local History</em>: free; children can dress up in {{q16}}<br/>• <em>Old stone bridge</em>: dates from the {{q17}} century<br/>• <em>Riverside Gardens</em>: free {{q18}} on Sundays in summer<br/>• <em>Castle</em>: open 10 a.m. to {{q19}}; entrance £{{q20}} for adults</p>',
            questions: [
              q(11, null, ['90', 'ninety'], '"the next ninety minutes".'),
              q(12, null, ['12', 'twelve'], '"any of the twelve stops".'),
              q(13, null, ['4.15', '4:15', 'four fifteen', 'quarter past four', '16:15'], '"the last at four fifteen".'),
              q(14, null, ['morning'], '"I recommend that you go in the morning".'),
              q(15, null, ['300', 'three hundred'], '"the climb is three hundred steps".'),
              q(16, null, ['costumes'], '"dress up in costumes from different periods".'),
              q(17, null, ['15th', 'fifteenth', 'fifteen'], '"dates from the fifteenth century".'),
              q(18, null, ['concerts'], '"free concerts on Sunday afternoons".'),
              q(19, null, ['5', 'five', '5 p.m.', '5pm'], '"open from ten until five".'),
              q(20, null, ['8', 'eight'], '"eight pounds for adults".'),
            ],
          },
        ],
      },
      {
        order: 3,
        contextText: 'You will hear a student, Rafi, talking to a university librarian about finding sources for his research project.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Hello, how can I help you?" },
          { speaker: 'B', voice: 'david', text: "Hi. I'm doing a project on renewable energy in rural communities, and I'm finding it hard to locate good sources." },
          { speaker: 'A', voice: 'zira', text: "Let's see. Have you tried the library's main search page?" },
          { speaker: 'B', voice: 'david', text: "Yes, but I get thousands of results, and most of them are newspaper articles, which isn't what my tutor wants." },
          { speaker: 'A', voice: 'zira', text: "I see. You can narrow the search by choosing 'peer-reviewed journals' from the menu on the left. That removes magazines and newspapers." },
          { speaker: 'B', voice: 'david', text: "That's helpful. What about books?" },
          { speaker: 'A', voice: 'zira', text: "Books on the subject are on the second floor, in the section marked with the number six-two-one. But a lot of the most recent work is in journals, since books take years to be published." },
          { speaker: 'B', voice: 'david', text: "I see. I've also found some interesting reports on government websites. Can I use those?" },
          { speaker: 'A', voice: 'zira', text: "Yes, official reports are fine, as long as you say clearly where they come from. But be careful with websites run by companies, because they tend to present information that favours their products." },
          { speaker: 'B', voice: 'david', text: "That makes sense. How do I keep track of everything I've read?" },
          { speaker: 'A', voice: 'zira', text: "We offer free software that stores your references and produces a bibliography automatically in any style you need. There's a workshop on it on Wednesday afternoons, and it only takes about forty minutes." },
          { speaker: 'B', voice: 'david', text: "I'll go to that. And if an article isn't available online?" },
          { speaker: 'A', voice: 'zira', text: "You can request it through the inter-library loan service. It's free for students, but it takes about a week, so plan ahead." },
          { speaker: 'B', voice: 'david', text: "And what's the deadline for returning books?" },
          { speaker: 'A', voice: 'zira', text: "Normally three weeks, and you can renew them twice online, unless someone else has reserved them. Late returns cost fifty pence a day." },
          { speaker: 'B', voice: 'david', text: "Thanks, that's really useful. I'll start with the journals." },
        ],
        questionGroups: [
          {
            id: 't9-l3-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(21, 'What is Rafi\'s problem with the library search?', ['It gives too many results, mostly newspaper articles.', 'It gives no results.', 'It does not include books.'], 'A', '"I get thousands of results, and most of them are newspaper articles".'),
              mc(22, 'How can he exclude magazines and newspapers?', ['by choosing "peer-reviewed journals"', 'by searching by author', 'by using the catalogue'], 'A', '"choosing \'peer-reviewed journals\' from the menu".'),
              mc(23, 'Why are journals useful for recent work?', ['They are free.', 'Books take years to be published.', 'They are shorter.'], 'B', '"books take years to be published".'),
              mc(24, 'What does the librarian say about company websites?', ['They are reliable.', 'They may favour their own products.', 'They are not allowed.'], 'B', '"they tend to present information that favours their products".'),
              mc(25, 'The workshop on reference software is held', ['on Wednesday afternoons', 'on Friday mornings', 'every day'], 'A', '"a workshop on it on Wednesday afternoons".'),
            ],
          },
          {
            id: 't9-l3-table',
            type: 'table_completion',
            instructionHtml: 'Complete the table below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Library service', 'Details'],
              [
                ['Books on the subject', 'second floor, section number {{q26}}'],
                ['Reference software', 'workshop takes about {{q27}} minutes'],
                ['Inter-library loan', 'free for students; takes about one {{q28}}'],
                ['Book loans', 'normally {{q29}} weeks; can be renewed twice'],
                ['Late returns', '{{q30}} pence per day'],
              ]
            ),
            questions: [
              q(26, null, ['621', 'six two one', 'six-two-one'], '"the number six-two-one".'),
              q(27, null, ['40', 'forty'], '"about forty minutes".'),
              q(28, null, ['week'], '"it takes about a week".'),
              q(29, null, ['3', 'three'], '"Normally three weeks".'),
              q(30, null, ['50', 'fifty'], '"fifty pence a day".'),
            ],
          },
        ],
      },
      {
        order: 4,
        contextText: 'You will hear part of a lecture about the history of the postal service.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "In today's lecture, I'm going to trace the history of the postal service, which, in one form or another, has existed for over two thousand years." },
          { speaker: 'A', voice: 'david', text: "The earliest organised postal systems were created by rulers who needed to send orders to distant parts of their empires. In ancient Persia, riders on horseback carried messages along a royal road that was more than two thousand kilometres long, changing horses at stations every day's ride. The system was so efficient that a message could cross the empire in about a week, instead of three months on foot." },
          { speaker: 'A', voice: 'david', text: "The Romans developed a similar network, but it was reserved for official use, and private citizens had to rely on friends, merchants or slaves to carry their letters." },
          { speaker: 'A', voice: 'david', text: "In medieval Europe, universities and merchant guilds ran their own messenger services. It was not until the sixteenth century that postal services began to be opened to the public, and in England the crown allowed ordinary people to send letters through the royal post from sixteen thirty-five, although the recipient, not the sender, paid the charge." },
          { speaker: 'A', voice: 'david', text: "That system had serious problems. Charges depended on the distance travelled and the number of sheets of paper used, which made letters very expensive, and recipients could refuse to accept a letter, leaving the carrier unpaid. A teacher named Rowland Hill proposed a solution in eighteen thirty-seven: a uniform rate based on weight, paid in advance by the sender, using a small piece of paper stuck to the envelope." },
          { speaker: 'A', voice: 'david', text: "The first adhesive postage stamp, the Penny Black, was issued in eighteen forty. The number of letters sent in the country doubled within two years, and within a decade, many other countries had introduced stamps of their own." },
          { speaker: 'A', voice: 'david', text: "Railways transformed the speed of the post. Letters were sorted on moving trains, so that by the time they reached their destination station, they were ready for delivery. In some cities, there were as many as twelve deliveries a day, which meant that a letter posted in the morning could be answered on the same afternoon." },
          { speaker: 'A', voice: 'david', text: "The twentieth century brought new challenges, from the telephone to email, and today, postal services in many countries are delivering fewer letters than they did decades ago. However, the growth of online shopping has led to a surge in parcels, which has allowed many postal services to continue." },
        ],
        questionGroups: [
          {
            id: 't9-l4-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>History of the postal service</strong></p><p><em>Ancient systems</em><br/>• Persia: riders on horseback changed {{q31}} at stations along a royal road<br/>• messages crossed the empire in about one {{q32}}<br/>• Romans: network reserved for {{q33}} use</p><p><em>Medieval and early modern</em><br/>• run by universities and merchant {{q34}}<br/>• royal post opened to the public in {{q35}}; the {{q36}} paid the charge</p><p><em>Reform</em><br/>• Rowland Hill proposed a uniform rate based on {{q37}}, paid in advance<br/>• first stamp: the {{q38}}, issued in 1840</p><p><em>Later developments</em><br/>• letters sorted on moving {{q39}}<br/>• online shopping has caused a surge in {{q40}}</p>',
            questions: [
              q(31, null, ['horses'], '"changing horses at stations".'),
              q(32, null, ['week'], '"in about a week".'),
              q(33, null, ['official'], '"reserved for official use".'),
              q(34, null, ['guilds'], '"merchant guilds".'),
              q(35, null, ['1635'], '"from sixteen thirty-five".'),
              q(36, null, ['recipient', 'receiver'], '"the recipient, not the sender, paid the charge".'),
              q(37, null, ['weight'], '"a uniform rate based on weight".'),
              q(38, null, ['penny black'], '"The first adhesive postage stamp, the Penny Black".'),
              q(39, null, ['trains'], '"sorted on moving trains".'),
              q(40, null, ['parcels'], '"a surge in parcels".'),
            ],
          },
        ],
      },
    ],
  },

  writing: {
    durationSec: 3600,
    task1: {
      order: 1,
      minWords: 150,
      recommendedMin: 20,
      promptHtml:
        '<p>The graph below shows the average daily number of hours that adults in a European country spent watching television, reading and using the internet between 2000 and 2020.</p><p>Summarise the information by selecting and reporting the main features, and make comparisons where relevant.</p>',
      chart: {
        chartType: 'line',
        title: 'Average daily hours spent on three activities, 2000-2020',
        unit: 'hours',
        categories: ['2000', '2005', '2010', '2015', '2020'],
        xAxisLabel: 'Year',
        yAxisLabel: 'Hours per day',
        series: [
          { name: 'Television', data: [3.2, 3.3, 3.1, 2.6, 2.1] },
          { name: 'Reading', data: [1.1, 1.0, 0.8, 0.7, 0.6] },
          { name: 'Internet', data: [0.2, 0.7, 1.4, 2.3, 3.0] },
        ],
      },
    },
    task2: {
      order: 2,
      minWords: 250,
      recommendedMin: 40,
      promptHtml:
        '<p>Some people think that university education should be free for everyone. Others believe that students should pay for their own studies.</p><p>Discuss both views and give your own opinion.</p>',
    },
  },
};
