// Original IELTS-style practice content (NOT copied or paraphrased from any real
// Cambridge/IELTS book). Only the exam STRUCTURE follows a standard Academic test
// layout; every topic, passage, transcript, question and answer is written from scratch.
import { table, TFNG_INSTRUCTION, YNNG_INSTRUCTION, q, paras, mc, bank } from './_html.mjs';

export default {
  slug: 'vocably-practice-test-8',
  title: 'Vocably Practice Test 8',
  difficulty: 'medium',

  reading: {
    durationSec: 3600,
    passages: [
      {
        order: 1,
        title: 'The giants of the sky',
        subtitle: 'Read the text and answer questions 1-13.',
        paragraphs: paras(
          ['A', `In the 1930s, the largest flying machines ever built drifted silently over the cities of Europe and the Americas. The airship Hindenburg was 245 metres long, more than three of today's biggest passenger aircraft placed end to end, and it could carry seventy passengers in comfort across the Atlantic. Crowds gathered in the streets to watch it pass, and for a brief time it seemed that these gigantic vessels might become the normal way to travel long distances. Within a decade, however, they had almost disappeared, and the story of why they vanished, and why some engineers now want to bring them back, is a revealing one.`],
          ['B', `An airship stays in the air without wings. It is filled with a gas that is lighter than air, and the difference in weight produces a lifting force in the same way that a cork floats on water. The early rigid airships had a skeleton of lightweight aluminium girders, shaped like a long cigar. Inside this frame hung a number of large gas cells, each filled with hydrogen, and over the whole structure was stretched an outer covering of cotton fabric, painted with a substance that reflected the sunlight. Engines mounted in pods on the sides pushed the craft forward, and large fins at the rear, like those of a ship, kept it steady.`],
          ['C', `The rigid airship was the creation of a German army officer, Count Ferdinand von Zeppelin, whose first craft made its maiden flight in 1900. Early machines were fragile and often damaged by wind, but within a decade a company had begun to carry paying passengers on short sightseeing flights. During the First World War, the military used airships to watch the sea and bomb cities, and although they proved vulnerable to aircraft, the technology continued to improve. By the 1930s, regular services across the Atlantic were possible. The crossing took about two and a half days, roughly half the time needed by the fastest ocean liner.`],
          ['D', `Travel by airship was an experience of unusual elegance. Passengers slept in small cabins with folding beds, dined in a restaurant with tables set with silver cutlery and linen, and relaxed in a lounge that contained a piano made from aluminium to keep its weight down. Large windows along the sides allowed them to look down at the ocean, at a height low enough to see ships and whales. Because of the danger of fire, smoking was not allowed in the passenger areas, but a special smoking room, sealed by an airlock and pressurised to keep gas out, was provided, where a steward lit every cigarette. Tickets were expensive, and most passengers were wealthy business people and celebrities.`],
          ['E', `The end came suddenly. In May 1937, as the Hindenburg approached its mooring mast in New Jersey after a flight from Germany, it burst into flames and was destroyed in less than a minute. Thirty-six people died, although most of those on board survived, and the event was filmed and broadcast around the world. The cause has been debated ever since, but the fact that the craft was filled with hydrogen, which burns fiercely, was widely blamed. The Germans had wanted to use helium, a non-flammable gas, but the main supply was controlled by the United States, which refused to sell it. Public confidence collapsed, and as aeroplanes became faster and more reliable, there was little reason to revive the airship.`],
          ['F', `Today, however, the giants are returning. Modern airships use helium, and are made of light, strong synthetic materials, and they are being designed for jobs that aircraft cannot do easily. Companies are developing airships to carry heavy cargo to remote places with no roads or airports, such as mining sites in the far north, and to provide platforms for observation, advertising and scientific research. Some engineers argue that an airship uses far less fuel for each tonne of cargo than an aircraft does, and that electric versions could produce little pollution. The obstacles remain considerable: airships move slowly, at not much more than a hundred kilometres an hour, and strong winds make them difficult to handle. Whether they will ever again carry passengers across the ocean remains to be seen.`]
        ),
        questionGroups: [
          {
            id: 't8-r1-headings',
            type: 'matching_headings',
            instructionHtml: 'Reading Passage 1 has six paragraphs, A-F. Choose the correct heading for paragraphs B-F from the list of headings below.<br/><em>Example: Paragraph A — vii</em>',
            bank: [
              { key: 'i', text: 'Reasons for a possible revival' },
              { key: 'ii', text: 'A disaster and the decline that followed' },
              { key: 'iii', text: 'An aircraft without wings: how it stays up' },
              { key: 'iv', text: 'The military origins of air travel' },
              { key: 'v', text: 'Passengers in comfort' },
              { key: 'vi', text: 'From experiments to regular services' },
              { key: 'vii', text: 'A giant in the sky' },
              { key: 'viii', text: 'The high cost of hydrogen' },
            ],
            questions: [
              q(1, 'Paragraph B', 'iii', 'Paragraph B explains lifting gas, frame and engines.', 'B'),
              q(2, 'Paragraph C', 'vi', 'Paragraph C: first flight in 1900 to regular transatlantic services by the 1930s.', 'C'),
              q(3, 'Paragraph D', 'v', 'Paragraph D describes cabins, dining and the lounge.', 'D'),
              q(4, 'Paragraph E', 'ii', 'Paragraph E: the Hindenburg fire and loss of public confidence.', 'E'),
              q(5, 'Paragraph F', 'i', 'Paragraph F: "the giants are returning".', 'F'),
            ],
          },
          {
            id: 't8-r1-flow',
            type: 'flowchart_completion',
            instructionHtml: 'Complete the flow-chart below. Choose <strong>NO MORE THAN TWO WORDS</strong> from paragraph B for each answer.',
            wordLimit: { maxWords: 2, label: 'NO MORE THAN TWO WORDS' },
            stemHtml: '<p>1. A skeleton of lightweight {{q6}} girders forms a long frame.</p><p>2. Inside the frame, large {{q7}} hold the hydrogen.</p><p>3. The whole structure is covered with {{q8}}, painted to reflect sunlight.</p>',
            questions: [
              q(6, null, ['aluminium', 'aluminum'], 'Paragraph B: "lightweight aluminium girders".', 'B'),
              q(7, null, ['gas cells'], 'Paragraph B: "a number of large gas cells".', 'B'),
              q(8, null, ['cotton fabric', 'cotton'], 'Paragraph B: "an outer covering of cotton fabric".', 'B'),
            ],
          },
          {
            id: 't8-r1-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              q(9, 'The Hindenburg was longer than three of today\'s largest passenger aircraft placed end to end.', 'TRUE', 'Paragraph A: "more than three of today\'s biggest passenger aircraft placed end to end".', 'A'),
              q(10, 'Count von Zeppelin\'s first craft flew in 1900.', 'TRUE', 'Paragraph C: "maiden flight in 1900".', 'C'),
              q(11, 'An airship crossing of the Atlantic took about half as long as a journey by the fastest liner.', 'TRUE', 'Paragraph C: "roughly half the time needed by the fastest ocean liner".', 'C'),
              q(12, 'Smoking was forbidden everywhere on board the Hindenburg.', 'FALSE', 'Paragraph D: a special smoking room was provided.', 'D'),
              q(13, 'Helium was cheaper to produce than hydrogen.', 'NOT GIVEN', 'Paragraph E says helium was controlled by the United States, but costs are not compared.', 'E'),
            ],
          },
        ],
      },
      {
        order: 2,
        title: 'Ants and the art of cooperation',
        subtitle: 'Read the text and answer questions 14-26.',
        paragraphs: paras(
          ['A', `A large ant colony may contain a million individuals, yet it has no leader. The queen lays eggs, but she gives no orders; nor does any other ant tell the rest what to do. Each worker follows a small number of simple rules, responding to smells, touch and the presence of other ants, and from these countless small interactions emerges behaviour that appears to be planned: nests are built, food is gathered, enemies are driven off and the young are cared for. Some scientists describe a colony as a single living unit, a superorganism, in which individual ants are like the cells of a body. The key to the puzzle is communication.`],
          ['B', `Ants communicate largely by chemicals known as pheromones. When a scout finds food, she returns to the nest leaving a trail of pheromone on the ground. Other ants that find the trail follow it, and on their return journey, add their own pheromone, making the trail stronger. The chemical evaporates in time, so a trail that is not reinforced fades away. This has a remarkable consequence. In a classic experiment, researchers gave Argentine ants a choice of two routes, one short and one long, between their nest and a food source, in the form of a bridge with two branches. At first, ants used both branches, but within minutes, most were using the short one, because ants taking it completed their journeys faster and so laid pheromone more often. No ant had compared the routes; the colony had found the shortest one by itself.`],
          ['C', `Ant colonies also divide their work. Some ants care for the young, some maintain the nest, some forage for food, and some defend the entrance. There is no central plan; instead, an ant's task depends on what she encounters. A worker that meets many others returning with food may be prompted to go out and forage, while one that meets few may stay inside. In many species, workers change jobs as they age, with the youngest working safely inside the nest, and the oldest, whose lives are nearly over, taking on the most dangerous work of foraging outside. This arrangement, researchers suggest, protects the colony's most valuable members.`],
          ['D', `Some of the most extraordinary ants live in the tropics. Army ants have no permanent nest. At night, they form a temporary shelter, called a bivouac, from their own bodies, linking their legs together in a living ball that may contain hundreds of thousands of individuals, with the queen and larvae in the centre. By day, they march out in columns to hunt, and a single raid may involve up to two hundred thousand ants. When they meet a gap, they build a bridge with their bodies, over which the rest pass. Leafcutter ants, meanwhile, are farmers. They cut pieces of leaf, carry them to underground chambers and use them not as food, but as material on which to grow a fungus, which is what the colony eats. Bacteria that live on the ants' bodies produce antibiotics to protect the fungus from disease.`],
          ['E', `Computer scientists have taken a close interest. In the 1990s, an Italian researcher, Marco Dorigo, developed a method of solving complex problems called ant colony optimisation, in which virtual ants explore possible solutions and leave digital trails that make good solutions more likely to be chosen. The method has been used for planning the routes of delivery vehicles, scheduling work in factories and directing messages through telecommunications networks, where it can adapt quickly to sudden changes such as a broken cable.`],
          ['F', `Engineers who build robots have also learnt from ants. A team of simple machines, each following a few basic rules, can together carry out tasks that would be difficult for a single complex one, such as searching a collapsed building or exploring a disaster zone. Because there is no central controller that can fail, the group continues to function even if some of its members break down. Researchers are also studying swarms that can cooperate to build simple structures, as termites and ants do.`],
          ['G', `It would be a mistake, however, to imagine that ants are simple machines following fixed programs. Experiments show that colonies vary their behaviour according to conditions, that individual ants differ in temperament and that some can learn from experience. Scientists who study them caution that descriptions of ant behaviour as a neat system of rules have sometimes been too tidy, and that the real world of the colony is more flexible and more surprising than any model can capture.`]
        ),
        questionGroups: [
          {
            id: 't8-r2-matchinfo',
            type: 'matching_information',
            instructionHtml: 'Reading Passage 2 has seven paragraphs, A-G. Which paragraph contains the following information? <em>Choose the correct letter, A-G.</em><br/><strong>NB</strong> You may use any letter more than once.',
            bankReusable: true,
            questions: [
              q(14, 'an explanation of how a colony can function without a leader', 'A', 'Paragraph A: each worker follows simple rules and organised behaviour "emerges".', 'A'),
              q(15, 'how a chemical trail disappears if it is not renewed', 'B', 'Paragraph B: "a trail that is not reinforced fades away".', 'B'),
              q(16, 'how the jobs ants do depend on how often they meet other ants', 'C', 'Paragraph C: "an ant\'s task depends on what she encounters".', 'C'),
              q(17, 'a practical use of ant-based methods in planning routes', 'E', 'Paragraph E: "planning the routes of delivery vehicles".', 'E'),
              q(18, 'a group of machines that can keep working if some members fail', 'F', 'Paragraph F: "the group continues to function even if some of its members break down".', 'F'),
              q(19, 'a warning against describing ants as too predictable', 'G', 'Paragraph G: "It would be a mistake ... to imagine that ants are simple machines".', 'G'),
            ],
          },
          {
            id: 't8-r2-classify',
            type: 'matching_features',
            instructionHtml: 'Look at the following statements (Questions 20-22) and the list of ants below. Match each statement with the correct ants, <strong>A, B or C</strong>.',
            bank: [
              { key: 'A', text: 'army ants' },
              { key: 'B', text: 'leafcutter ants' },
              { key: 'C', text: 'Argentine ants' },
            ],
            questions: [
              q(20, 'They build temporary living structures from their own bodies.', 'A', 'Paragraph D: "a temporary shelter, called a bivouac, from their own bodies".', 'D'),
              q(21, 'They grow a fungus in underground chambers.', 'B', 'Paragraph D: "underground chambers ... on which to grow a fungus".', 'D'),
              q(22, 'They were used in an experiment with a bridge that had two branches.', 'C', 'Paragraph B: "Argentine ants a choice of two routes".', 'B'),
            ],
          },
          {
            id: 't8-r2-short',
            type: 'short_answer',
            instructionHtml: 'Answer the questions below. Choose <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> from the passage for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            questions: [
              q(23, 'What chemicals do ants mainly use to communicate?', ['pheromones', 'pheromone'], 'Paragraph B: "largely by chemicals known as pheromones".', 'B'),
              q(24, 'Which ants usually take on the most dangerous work of foraging outside the nest?', ['the oldest', 'oldest', 'the oldest ants', 'oldest ants'], 'Paragraph C: "the oldest ... taking on the most dangerous work".', 'C'),
              q(25, 'How many ants may take part in a single army ant raid?', ['200,000', '200000', 'two hundred thousand', 'up to 200,000'], 'Paragraph D: "up to two hundred thousand ants".', 'D'),
              q(26, 'What do the bacteria on leafcutter ants\' bodies produce to protect the fungus?', ['antibiotics'], 'Paragraph D: "produce antibiotics".', 'D'),
            ],
          },
        ],
      },
      {
        order: 3,
        title: 'The price of attention',
        subtitle: 'Read the text and answer questions 27-40.',
        paragraphs: paras(
          ['A', `In 1971, the economist Herbert Simon made a prediction that seemed odd at the time. A wealth of information, he wrote, creates a poverty of attention. Half a century later, his observation looks prophetic. Every person with a smartphone has access to more books, news, music and video than they could consume in several lifetimes, and what is scarce is no longer content but the time and mental effort to engage with it. Many of the most successful technology companies make their money by selling advertising, and so their service is free to users, who pay with their attention instead. The more time people spend using a product, the more money it earns.`],
          ['B', `To capture that attention, designers have borrowed ideas from behavioural psychology. Infinite scroll, in which new content appears continuously as the user moves down the page, removes the natural point at which a person might stop. Automatic playing of the next video works in the same way, by making continuation the default and stopping a deliberate choice. Notifications, often marked by a small red badge, signal that something unseen is waiting. The pull-to-refresh gesture, in which users drag a page downwards to see new content, delivers an unpredictable reward each time, a principle borrowed from slot machines, which are designed to be hard to leave. Designers say that such techniques are not necessarily sinister, since they are also used to make products easier and more enjoyable to use. But their power is hard to deny.`],
          ['C', `The effects on behaviour are the subject of intense research. Surveys suggest that people in some countries check their phones dozens of times a day, often without any particular reason. A study in the United States found that the mere presence of a phone on a desk, even when switched off, could reduce a person's available cognitive capacity on tests, apparently because part of the mind was occupied in resisting the urge to check it. Other researchers have failed to reproduce this result, and the evidence on the wider effects on wellbeing remains mixed, with some studies finding clear harm and others finding very little.`],
          ['D', `Critics have found allies among those who built the systems. Several former employees of major technology companies have spoken publicly about the techniques they helped to develop, and some have founded organisations that campaign for what they call humane design. Politicians have begun to take notice: a number of countries have introduced rules that limit the use of automatic playing and similar features in products used by children, and regulators in several regions are considering further measures.`],
          ['E', `Defenders of the industry make two main arguments. The first is that users remain free to choose: no one is forced to pick up a phone, and most people find the services they use valuable. The second is that new forms of entertainment have always caused alarm. Novels were once blamed for corrupting the young, and later generations feared the effects of radio, cinema and television. Each time, society adapted, and the feared disasters did not occur. These arguments have some force, but they overlook an important difference: a novel does not reshape itself to hold a particular reader's attention, and a television programme does not learn from millions of viewers which tricks work best.`],
          ['F', `Individuals have developed their own defences. Some switch their phone screens to black and white, which makes them less appealing, others turn off most notifications or keep their phones out of the bedroom, and a growing number set aside regular periods with no devices at all. Evidence that these habits make people happier is still limited, but many who adopt them report that they feel more in control. The approach has a weakness, though: it places the burden on the user, who is pitted against teams of highly skilled professionals.`],
          ['G', `The most important question, in my view, is not whether technology is good or bad, but who decides the defaults. Most people accept the settings they are given, and so those who design the settings hold enormous influence over how a large share of humanity spends its time. A fairer arrangement would give users real control, for example by making it easy to set limits and by providing services that do not depend on maximising the time spent. Such a change would cost companies some revenue, but it would respect the resource on which, as Simon foresaw, everything else now depends.`]
        ),
        questionGroups: [
          {
            id: 't8-r3-ynng',
            type: 'yes_no_notgiven',
            instructionHtml: YNNG_INSTRUCTION,
            questions: [
              q(27, 'The amount of information available today has made attention a scarce resource.', 'YES', 'Paragraph A: "what is scarce is no longer content but the time and mental effort".', 'A'),
              q(28, 'All persuasive design techniques are intended to harm users.', 'NO', 'Paragraph B: "not necessarily sinister".', 'B'),
              q(29, 'Schools should ban smartphones.', 'NOT GIVEN', 'The writer does not discuss schools.'),
              q(30, 'Earlier technologies also caused public anxiety.', 'YES', 'Paragraph E: "new forms of entertainment have always caused alarm".', 'E'),
            ],
          },
          {
            id: 't8-r3-classify',
            type: 'matching_features',
            instructionHtml: 'Look at the following descriptions (Questions 31-34) and the list of design techniques below. Match each description with the correct technique, <strong>A, B or C</strong>.<br/>You may use any letter more than once.',
            bankReusable: true,
            bank: [
              { key: 'A', text: 'infinite scroll and automatic playing' },
              { key: 'B', text: 'notifications' },
              { key: 'C', text: 'pull-to-refresh' },
            ],
            questions: [
              q(31, 'removes a natural point at which a user might stop', 'A', 'Paragraph B: infinite scroll "removes the natural point at which a person might stop".', 'B'),
              q(32, 'uses a small red symbol to draw attention to unseen content', 'B', 'Paragraph B: "marked by a small red badge".', 'B'),
              q(33, 'delivers an unpredictable reward each time it is used', 'C', 'Paragraph B: "an unpredictable reward each time".', 'B'),
              q(34, 'makes continuing the default and stopping a deliberate choice', 'A', 'Paragraph B: "making continuation the default".', 'B'),
            ],
          },
          {
            id: 't8-r3-sentences',
            type: 'sentence_completion',
            instructionHtml: 'Complete the sentences below. Choose <strong>NO MORE THAN TWO WORDS</strong> from the passage for each answer.',
            wordLimit: { maxWords: 2, label: 'NO MORE THAN TWO WORDS' },
            questions: [
              q(35, 'Herbert Simon wrote that a wealth of information creates a poverty of {{q35}}.', ['attention'], 'Paragraph A: "a poverty of attention".', 'A'),
              q(36, 'Companies that offer free services earn money mainly from {{q36}}.', ['advertising'], 'Paragraph A: "selling advertising".', 'A'),
              q(37, 'A study suggested that a switched-off phone on a desk could reduce a person\'s {{q37}}.', ['cognitive capacity', 'available cognitive capacity'], 'Paragraph C: "reduce a person\'s available cognitive capacity".', 'C'),
            ],
          },
          {
            id: 't8-r3-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B, C or D</strong>.',
            questions: [
              mc(38, 'What does the writer say about designers in paragraph B?', ['They are all trying to mislead users.', 'Their techniques have other uses but are undeniably powerful.', 'They rarely study psychology.', 'They have rejected slot machine principles.'], 'B', 'Paragraph B: "not necessarily sinister ... But their power is hard to deny."', 'B'),
              mc(39, 'The writer\'s attitude to the arguments of defenders in paragraph E is that they', ['are entirely mistaken', 'have some force but overlook a difference', 'prove that no action is needed', 'apply only to television'], 'B', 'Paragraph E: "These arguments have some force, but they overlook an important difference".', 'E'),
              mc(40, 'What is the writer\'s main point in paragraph G?', ['Technology should be banned for children.', 'Users should spend less time online.', 'The key issue is who controls the default settings.', 'Companies should stop selling advertising.'], 'C', 'Paragraph G: "The most important question ... is who decides the defaults."', 'G'),
            ],
          },
        ],
      },
    ],
  },

  listening: {
    durationSec: 1800,
    checkTimeSec: 120,
    parts: [
      {
        order: 1,
        contextText: 'You will hear a man phoning a travel company to ask about a cycling holiday.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Good morning, Open Road Holidays. How can I help?" },
          { speaker: 'B', voice: 'david', text: "Good morning. I saw your advertisement for a cycling holiday in the Loire Valley, and I'd like some more information." },
          { speaker: 'A', voice: 'zira', text: "Of course. Could I take your name?" },
          { speaker: 'B', voice: 'david', text: "It's Fraser. That's F-R-A-S-E-R." },
          { speaker: 'A', voice: 'zira', text: "And how many people will be travelling?" },
          { speaker: 'B', voice: 'david', text: "Four of us: my wife, our two grown-up daughters and me." },
          { speaker: 'A', voice: 'zira', text: "Lovely. The holiday lasts eight days, and the next departure with spaces is on the fourteenth of September." },
          { speaker: 'B', voice: 'david', text: "That would suit us. How far do we cycle each day?" },
          { speaker: 'A', voice: 'zira', text: "About thirty-five kilometres a day on average, mostly on flat paths beside the river, so it's suitable for all levels of fitness." },
          { speaker: 'B', voice: 'david', text: "And where do we stay?" },
          { speaker: 'A', voice: 'zira', text: "In small family-run guesthouses, and on two nights in restored farmhouses. Breakfast is included every day, and dinner on the first and last nights." },
          { speaker: 'B', voice: 'david', text: "What about the bicycles?" },
          { speaker: 'A', voice: 'zira', text: "They're included in the price. Standard bikes are provided, but for an extra forty pounds per person, you can upgrade to an electric bike, which is helpful on the few hills." },
          { speaker: 'B', voice: 'david', text: "My wife might like that. And the price?" },
          { speaker: 'A', voice: 'zira', text: "It's six hundred and forty pounds per person, which includes the bike, the accommodation, the ferry crossing and luggage transfer from one guesthouse to the next." },
          { speaker: 'B', voice: 'david', text: "Good. Do we have to arrange travel insurance ourselves?" },
          { speaker: 'A', voice: 'zira', text: "Yes, but we can recommend a company. And you'll need to bring your own helmets, although we can lend them if you ask when you book." },
          { speaker: 'B', voice: 'david', text: "Thank you. Could you send me the brochure by email?" },
          { speaker: 'A', voice: 'zira', text: "Certainly. What's your address?" },
          { speaker: 'B', voice: 'david', text: "It's fraser dot cycling at mailbox dot com." },
        ],
        questionGroups: [
          {
            id: 't8-l1-form',
            type: 'form_completion',
            instructionHtml: 'Complete the form below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Open Road Holidays: Enquiry', ''],
              [
                ['Customer\'s surname', '{{q1}}'],
                ['Destination', 'the {{q2}} Valley'],
                ['Number of people', '{{q3}}'],
                ['Length of holiday', '{{q4}} days'],
                ['Departure date', '{{q5}} September'],
                ['Distance per day', 'about {{q6}} km'],
                ['Accommodation', 'guesthouses and two nights in {{q7}}'],
                ['Extra cost for electric bike', '£{{q8}} per person'],
                ['Price per person', '£{{q9}}'],
                ['Helmets', 'can be {{q10}} if requested when booking'],
              ]
            ),
            questions: [
              q(1, null, ['fraser'], 'Spelled out: F-R-A-S-E-R.'),
              q(2, null, ['loire'], '"the Loire Valley".'),
              q(3, null, ['4', 'four'], '"Four of us".'),
              q(4, null, ['8', 'eight'], '"The holiday lasts eight days".'),
              q(5, null, ['14', 'fourteenth', '14th'], '"the fourteenth of September".'),
              q(6, null, ['35', 'thirty-five', 'thirty five'], '"About thirty-five kilometres a day".'),
              q(7, null, ['farmhouses', 'restored farmhouses'], '"two nights in restored farmhouses".'),
              q(8, null, ['40', 'forty'], '"an extra forty pounds per person".'),
              q(9, null, ['640', 'six hundred and forty'], '"six hundred and forty pounds per person".'),
              q(10, null, ['lent', 'borrowed'], '"we can lend them if you ask when you book".'),
            ],
          },
        ],
      },
      {
        order: 2,
        contextText: 'You will hear a festival organiser talking to volunteers about the jobs available at a summer music festival.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Thank you all for coming. I'm Jon Carter, the volunteer coordinator for the Harbourside Music Festival, which takes place over the last weekend of July. We need about two hundred volunteers, and I'd like to explain the different roles." },
          { speaker: 'A', voice: 'david', text: "First, the stewards. They guide the audience, check tickets and keep the entrances clear. Stewards must be at least eighteen years old, because they may need to deal with difficult situations." },
          { speaker: 'A', voice: 'david', text: "Second, the stage crew. This is the heaviest work: carrying instruments and equipment on and off the stage. You must be able to lift heavy items, and it's quite physical, but it's also the best place to see the performers close up." },
          { speaker: 'A', voice: 'david', text: "Third, the information tent. You'll answer visitors' questions about timetables, lost property and so on. Anyone who speaks a foreign language is especially welcome here, since we get many visitors from abroad." },
          { speaker: 'A', voice: 'david', text: "Fourth, the recycling team. Their job is to sort waste into bins, and to persuade people to use them. It's not glamorous, but it's important, because last year we cut the waste sent to landfill by half. The recycling team starts very early, at six in the morning, before the gates open." },
          { speaker: 'A', voice: 'david', text: "And finally the first-aid assistants, who help the paramedics. You need a current first-aid certificate for this, so it's not suitable for everyone." },
          { speaker: 'A', voice: 'david', text: "Now, some practical points. Every volunteer works one shift of four hours a day for the three days. In return, you'll receive a free ticket for the days you aren't working, a meal voucher for each shift and a festival T-shirt." },
          { speaker: 'A', voice: 'david', text: "There's a compulsory briefing on the Thursday evening before the festival, at seven o'clock in the main tent, where you'll be given your timetable and meet your team leader. Please don't miss it." },
          { speaker: 'A', voice: 'david', text: "You can camp on site for free if you wish. There's a separate area for volunteers, near the shower block." },
          { speaker: 'A', voice: 'david', text: "If you'd like to apply, please fill in the form at the back, stating your first and second choice of role, and hand it in before you leave." },
        ],
        questionGroups: [
          {
            id: 't8-l2-match',
            type: 'matching_features',
            instructionHtml: 'What is required for each volunteer role? Choose <strong>FIVE</strong> answers from the box and write the correct letter, A-G, next to Questions 11-15.',
            bank: [
              { key: 'A', text: 'must be at least 18 years old' },
              { key: 'B', text: 'must be able to lift heavy items' },
              { key: 'C', text: 'must hold a first-aid certificate' },
              { key: 'D', text: 'should speak a foreign language' },
              { key: 'E', text: 'must start work at 6 a.m.' },
              { key: 'F', text: 'must have previous festival experience' },
              { key: 'G', text: 'must be a student' },
            ],
            questions: [
              q(11, 'stewards', 'A', '"Stewards must be at least eighteen years old".'),
              q(12, 'stage crew', 'B', '"You must be able to lift heavy items".'),
              q(13, 'information tent', 'D', '"Anyone who speaks a foreign language is especially welcome".'),
              q(14, 'recycling team', 'E', '"starts very early, at six in the morning".'),
              q(15, 'first-aid assistants', 'C', '"You need a current first-aid certificate".'),
            ],
          },
          {
            id: 't8-l2-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: '<p><strong>Volunteer information</strong></p><p>• number of volunteers needed: about {{q16}}<br/>• shift length: {{q17}} hours<br/>• benefits: a free ticket, a {{q18}} for each shift and a T-shirt<br/>• briefing on Thursday at {{q19}} o\'clock in the main tent<br/>• free camping near the {{q20}}</p>',
            questions: [
              q(16, null, ['200', 'two hundred'], '"about two hundred volunteers".'),
              q(17, null, ['4', 'four'], '"one shift of four hours a day".'),
              q(18, null, ['meal voucher', 'voucher'], '"a meal voucher for each shift".'),
              q(19, null, ['7', 'seven'], '"at seven o\'clock in the main tent".'),
              q(20, null, ['shower block'], '"near the shower block".'),
            ],
          },
        ],
      },
      {
        order: 3,
        contextText: 'You will hear two architecture students, Hugo and Anya, talking to their tutor about an essay on public buildings.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david2', text: "Hello, Hugo, hello, Anya. Come in. I understand you'd like to talk about your essay on the design of public libraries." },
          { speaker: 'B', voice: 'david', text: "Yes. I'm trying to decide between two case studies, and I'm not sure which would be better." },
          { speaker: 'A', voice: 'david2', text: "Tell me about them." },
          { speaker: 'B', voice: 'david', text: "One is a new library in a Scandinavian city, which has a huge glass roof and open spaces. The other is a traditional Victorian building that's been converted for modern use." },
          { speaker: 'C', voice: 'zira', text: "I think the Victorian one's more interesting, because you can compare the original design with the changes. With the new building, there's nothing to compare it with." },
          { speaker: 'A', voice: 'david2', text: "That's a fair point, Anya. But Hugo, what attracts you to the glass building?" },
          { speaker: 'B', voice: 'david', text: "It's extremely popular. They get about two thousand visitors a day, and there's a lot of published research on how people use the space." },
          { speaker: 'A', voice: 'david2', text: "That's a strong advantage, since you'll have plenty of evidence. My advice is to choose the one for which you can find enough sources. A good essay needs more than your own opinion." },
          { speaker: 'B', voice: 'david', text: "OK. I'll stick with the glass building, then." },
          { speaker: 'A', voice: 'david2', text: "Anya, what about your essay on hospitals?" },
          { speaker: 'C', voice: 'zira', text: "I've been reading about how natural light and views of gardens help patients recover faster. But I'm worried that some of the studies are quite old." },
          { speaker: 'A', voice: 'david2', text: "Check when they were published, and look for more recent work that confirms or challenges them. It would also strengthen your essay to include a hospital designed on these principles." },
          { speaker: 'C', voice: 'zira', text: "I was thinking of a children's hospital that has a rooftop garden." },
          { speaker: 'A', voice: 'david2', text: "Excellent. Now, on the structure: start with a clear statement of what you'll argue, not simply a history of the subject. I often find that students write two pages of background before they say anything new." },
          { speaker: 'B', voice: 'david', text: "I'll bear that in mind. What length should the introduction be?" },
          { speaker: 'A', voice: 'david2', text: "About ten per cent of the total, so roughly two hundred and fifty words for a twenty-five-hundred-word essay. And remember, the deadline is the fourth of December, and I won't accept late submissions." },
          { speaker: 'C', voice: 'zira', text: "Thank you. That's really helpful." },
        ],
        questionGroups: [
          {
            id: 't8-l3-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, <strong>A, B or C</strong>.',
            questions: [
              mc(21, 'What problem does Hugo have?', ['He cannot choose between two case studies.', 'He has not started reading.', 'He has lost his notes.'], 'A', '"I\'m trying to decide between two case studies".'),
              mc(22, 'Why does Anya prefer the Victorian building?', ['It is better known.', 'It allows a comparison of the original and the changes.', 'It is closer to the university.'], 'B', '"you can compare the original design with the changes".'),
              mc(23, 'What attracts Hugo to the glass building?', ['It has a lot of published research.', 'It is cheaper to visit.', 'It is more beautiful.'], 'A', '"there\'s a lot of published research".'),
              mc(24, 'Anya is worried that some of her sources', ['are too difficult', 'are quite old', 'are not relevant'], 'B', '"some of the studies are quite old".'),
              mc(25, 'The tutor advises Anya to', ['include a hospital designed on these principles', 'write a longer introduction', 'choose a different topic'], 'A', '"include a hospital designed on these principles".'),
            ],
          },
          {
            id: 't8-l3-sentences',
            type: 'sentence_completion',
            instructionHtml: 'Complete the sentences below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            questions: [
              q(26, 'The Scandinavian library has a huge {{q26}} roof.', ['glass'], '"a huge glass roof".'),
              q(27, 'The library receives about {{q27}} visitors a day.', ['2000', '2,000', 'two thousand'], '"about two thousand visitors a day".'),
              q(28, 'Anya has read that patients recover faster with natural light and views of {{q28}}.', ['gardens', 'a garden', 'garden'], '"views of gardens".'),
              q(29, 'The tutor says students often write too much {{q29}} in their introductions.', ['background'], '"two pages of background before they say anything new".'),
              q(30, 'The deadline for the essay is the {{q30}} of December.', ['4th', 'fourth', '4'], '"the fourth of December".'),
            ],
          },
        ],
      },
      {
        order: 4,
        contextText: 'You will hear part of a lecture about coral reefs.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Coral reefs cover less than one per cent of the ocean floor, yet they support about a quarter of all marine species. Today I want to explain why they are so productive, and why they are in danger." },
          { speaker: 'A', voice: 'david', text: "Corals are animals, not plants. Each coral is made up of many tiny creatures called polyps, which build a hard skeleton of limestone around themselves. Over thousands of years, these skeletons accumulate to form the reef." },
          { speaker: 'A', voice: 'david', text: "The key to the reef's success is a partnership. Inside the tissues of each polyp live microscopic algae, which use sunlight to make sugars, and pass most of them to the coral. In return, the coral gives the algae shelter and the chemicals they need. This is why reefs are found only in clear, shallow water, where enough sunlight can reach them." },
          { speaker: 'A', voice: 'david', text: "The algae also give corals their colour. When the water becomes too warm, the corals expel the algae, and turn white, a process known as bleaching. A bleached coral is not dead, but it is starving, and if the warm conditions last for more than a few weeks, it will die." },
          { speaker: 'A', voice: 'david', text: "Warming is not the only threat. Runoff from farmland carries fertilisers into the sea, which makes seaweed grow too fast and smother the coral. Fishing with explosives or poison destroys large areas at once. And tourism can cause damage, when boats drop anchors on the reef and divers touch or break fragile structures." },
          { speaker: 'A', voice: 'david', text: "The oceans are also becoming more acidic, as they absorb carbon dioxide from the air. This makes it harder for corals to build their skeletons, and in the long run, it may weaken the reefs so that storms break them apart." },
          { speaker: 'A', voice: 'david', text: "Yet there are grounds for hope. Scientists have found that some corals can tolerate higher temperatures, and they are now growing these heat-resistant corals in nurseries and attaching them to damaged reefs. In several countries, coastal communities have created protected areas where fishing is banned, and the fish populations there have recovered within a few years." },
          { speaker: 'A', voice: 'david', text: "Reefs also protect coasts. They absorb up to ninety per cent of the energy of waves, which reduces flooding and erosion, and the value of this protection alone has been estimated at billions of dollars every year." },
        ],
        questionGroups: [
          {
            id: 't8-l4-table',
            type: 'table_completion',
            instructionHtml: 'Complete the table below. Write <strong>NO MORE THAN TWO WORDS AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 2, maxNumbers: 1, label: 'NO MORE THAN TWO WORDS AND/OR A NUMBER' },
            stemHtml: table(
              ['Topic', 'Notes'],
              [
                ['Importance of reefs', 'cover less than 1% of the ocean floor but support about a {{q31}} of marine species'],
                ['What corals are', 'animals made up of tiny {{q32}} that build a skeleton of limestone'],
                ['Partnership', 'microscopic {{q33}} make sugars using sunlight, and pass most to the coral'],
                ['Bleaching', 'occurs when the water is too {{q34}}; corals turn white'],
                ['Threats', 'fertilisers make {{q35}} grow and smother coral; explosives and poison; damage from {{q36}} dropped by boats'],
                ['Acidification', 'oceans absorb {{q37}} from the air, making it harder to build skeletons'],
                ['Solutions', 'growing heat-resistant corals in {{q38}}; protected areas where {{q39}} is banned'],
                ['Coastal protection', 'reefs absorb up to {{q40}} per cent of wave energy'],
              ]
            ),
            questions: [
              q(31, null, ['quarter', 'a quarter'], '"about a quarter of all marine species".'),
              q(32, null, ['polyps'], '"tiny creatures called polyps".'),
              q(33, null, ['algae'], '"microscopic algae".'),
              q(34, null, ['warm', 'warmer', 'hot'], '"When the water becomes too warm".'),
              q(35, null, ['seaweed'], '"makes seaweed grow too fast".'),
              q(36, null, ['anchors'], '"boats drop anchors on the reef".'),
              q(37, null, ['carbon dioxide', 'co2'], '"absorb carbon dioxide from the air".'),
              q(38, null, ['nurseries'], '"growing these heat-resistant corals in nurseries".'),
              q(39, null, ['fishing'], '"protected areas where fishing is banned".'),
              q(40, null, ['90', 'ninety'], '"up to ninety per cent".'),
            ],
          },
        ],
      },
    ],
  },

  writing: {
    durationSec: 3600,
    task1: {
      order: 1,
      minWords: 150,
      recommendedMin: 20,
      promptHtml:
        '<p>The chart below shows the percentage of adults who took part in different types of physical activity in a European country in 2010 and in 2020.</p><p>Summarise the information by selecting and reporting the main features, and make comparisons where relevant.</p>',
      chart: {
        chartType: 'bar',
        title: 'Adults taking part in physical activity (%)',
        unit: '%',
        categories: ['Walking', 'Swimming', 'Gym', 'Cycling', 'Team sports'],
        xAxisLabel: 'Activity',
        yAxisLabel: 'Percentage of adults',
        series: [
          { name: '2010', data: [48, 22, 15, 18, 14] },
          { name: '2020', data: [57, 17, 24, 23, 9] },
        ],
      },
    },
    task2: {
      order: 2,
      minWords: 250,
      recommendedMin: 40,
      promptHtml:
        '<p>Some people think that governments should spend money on railways and public transport rather than on building new roads.</p><p>To what extent do you agree or disagree?</p>',
    },
  },
};
