// Original IELTS-style practice content (NOT copied or paraphrased from any real
// Cambridge/IELTS book). Only the exam STRUCTURE — section order, question types,
// question counts and word limits — follows a standard Academic test layout; every
// topic, passage, transcript, question and answer is written from scratch. See
// practice-test-2.mjs for the shared format notes.
import { TFNG_INSTRUCTION, YNNG_INSTRUCTION } from './_html.mjs';

export default {
  slug: 'vocably-practice-test-42',
  title: 'Vocably Practice Test 42',
  difficulty: 'medium',

  reading: {
    durationSec: 3600,
    passages: [
      {
        order: 1,
        title: 'The box that changed world trade',
        subtitle: 'Read the text and answer questions 1-13.',
        paragraphs: [
          { label: 'A', html: "<p>For centuries, loading and unloading a ship was one of the slowest and most expensive parts of trade. Goods arrived at the docks in sacks, barrels, crates and bundles of every shape and size, and each item had to be lifted by hand or by crane into the ship's hold, where dock workers stacked it so that it would not move during the voyage. A large ship could spend a week or more in port, and the cost of handling the cargo was often greater than the cost of carrying it across the ocean. Theft was common, and damage even more so. Some experiments with standard-sized boxes had been made earlier in the century, particularly on railways, but none had changed the basic way that cargo was handled at sea.</p>" },
          { label: 'B', html: "<p>The man usually credited with changing this was not a sailor but a lorry owner. Malcolm McLean had built up a successful trucking business in the United States, and he was frustrated by the hours his drivers spent waiting at ports while their loads were transferred to ships. His idea was simple: instead of unloading the lorry, why not lift the whole trailer body onto the ship and deliver it, still sealed, to another lorry at the other end? In April 1956, a converted tanker named the Ideal X sailed from New Jersey to Texas carrying fifty-eight metal boxes on its deck.</p>" },
          { label: 'C', html: "<p>The savings were dramatic. McLean calculated that the cost of loading a ton of cargo had fallen to a small fraction of what it had been under the old methods. Ships could now be loaded and unloaded in hours rather than days, and because the boxes were sealed, theft and damage fell sharply. Yet for several years the new system spread only slowly. Different companies used boxes of different sizes, so that one firm's containers would not fit another firm's ships or cranes, and ports were reluctant to invest in expensive new equipment until it was clear which system would win.</p>" },
          { label: 'D', html: "<p>The solution was standardisation. During the 1960s, after long negotiations, international agreements established a small number of standard container sizes, together with a standard design for the corner fittings by which containers are lifted and locked together. From then on, a container could travel by lorry, train and ship anywhere in the world without its contents ever being touched. Today the most common measure of a port's capacity, the 'twenty-foot equivalent unit', is based on one of those original standard sizes.</p>" },
          { label: 'E', html: "<p>The social effects were profound. Traditional dock work, which had employed huge numbers of men in port cities, largely disappeared, often with little warning, and many dock communities suffered years of unemployment. Old city-centre ports, with narrow docks and no space for the vast storage areas that containers require, lost their trade to new ports built on open land, sometimes far from the old city. In several major cities, the abandoned docklands were later redeveloped as offices, apartments and museums.</p>" },
          { label: 'F', html: "<p>Containers also changed the geography of manufacturing. When transport was expensive, factories were usually built close to their customers. Once the cost of shipping goods across the world became a tiny part of their final price, companies could make each component wherever it was cheapest, and assemble products from parts produced in many different countries. Some economists argue that the container did more to encourage international trade than all the trade agreements of the second half of the twentieth century combined. Others are more cautious, pointing out that containers spread at the same time as other important changes, such as faster communication and lower import taxes, which makes it difficult to measure the effect of any single factor.</p>" },
          { label: 'G', html: "<p>The system is not without weaknesses. Because it depends on huge ships and a small number of very large ports, a problem in one place can cause delays around the world, as happened when a giant container ship blocked a major canal for several days in 2021. Containers can also be used to hide illegal goods, and only a small proportion of the millions that pass through ports each year can be inspected. And the enormous ships that carry them burn large quantities of fuel, making shipping a significant source of carbon emissions. Nevertheless, the plain steel box remains the foundation on which modern global trade is built.</p>" },
        ],
        questionGroups: [
          {
            id: 't42-r1-headings',
            type: 'matching_headings',
            instructionHtml: 'Reading Passage 1 has seven paragraphs, A-G. Choose the correct heading for each paragraph from the list of headings below.',
            bank: [
              { key: 'i', text: 'Vulnerabilities of the modern system' },
              { key: 'ii', text: 'Early benefits and early obstacles' },
              { key: 'iii', text: 'An idea from outside the shipping industry' },
              { key: 'iv', text: 'The end of a way of life' },
              { key: 'v', text: 'Agreeing on common measurements' },
              { key: 'vi', text: 'A slow and costly process' },
              { key: 'vii', text: 'Making things in many places' },
              { key: 'viii', text: 'The rise of air freight' },
              { key: 'ix', text: 'Protecting workers\' rights' },
            ],
            questions: [
              { number: 1, promptHtml: 'Paragraph A', answer: { accepted: ['vi'] }, explanationHtml: 'Paragraph A: loading was "one of the slowest and most expensive parts of trade".', locatorParagraph: 'A' },
              { number: 2, promptHtml: 'Paragraph B', answer: { accepted: ['iii'] }, explanationHtml: 'Paragraph B: McLean "was not a sailor but a lorry owner".', locatorParagraph: 'B' },
              { number: 3, promptHtml: 'Paragraph C', answer: { accepted: ['ii'] }, explanationHtml: 'Paragraph C: dramatic savings, "Yet ... the new system spread only slowly".', locatorParagraph: 'C' },
              { number: 4, promptHtml: 'Paragraph D', answer: { accepted: ['v'] }, explanationHtml: 'Paragraph D: agreements "established a small number of standard container sizes".', locatorParagraph: 'D' },
              { number: 5, promptHtml: 'Paragraph E', answer: { accepted: ['iv'] }, explanationHtml: 'Paragraph E: "Traditional dock work ... largely disappeared".', locatorParagraph: 'E' },
              { number: 6, promptHtml: 'Paragraph F', answer: { accepted: ['vii'] }, explanationHtml: 'Paragraph F: companies could "make each component wherever it was cheapest".', locatorParagraph: 'F' },
              { number: 7, promptHtml: 'Paragraph G', answer: { accepted: ['i'] }, explanationHtml: 'Paragraph G: "The system is not without weaknesses."', locatorParagraph: 'G' },
            ],
          },
          {
            id: 't42-r1-tfng',
            type: 'true_false_notgiven',
            instructionHtml: TFNG_INSTRUCTION,
            questions: [
              { number: 8, promptHtml: 'Before containers, handling cargo sometimes cost more than transporting it by sea.', answer: { accepted: ['TRUE'] }, explanationHtml: 'Paragraph A: "the cost of handling the cargo was often greater than the cost of carrying it".', locatorParagraph: 'A' },
              { number: 9, promptHtml: 'The Ideal X was a new ship built specially to carry containers.', answer: { accepted: ['FALSE'] }, explanationHtml: 'Paragraph B: it was "a converted tanker".', locatorParagraph: 'B' },
              { number: 10, promptHtml: 'McLean became one of the richest men in the United States.', answer: { accepted: ['NOT GIVEN'] }, explanationHtml: 'The passage does not mention McLean\'s personal wealth.', locatorParagraph: 'B' },
              { number: 11, promptHtml: 'Ports were quick to buy new equipment for containers.', answer: { accepted: ['FALSE'] }, explanationHtml: 'Paragraph C: "ports were reluctant to invest in expensive new equipment".', locatorParagraph: 'C' },
              { number: 12, promptHtml: 'Some old dock areas have been turned into museums.', answer: { accepted: ['TRUE'] }, explanationHtml: 'Paragraph E: "abandoned docklands were later redeveloped as offices, apartments and museums".', locatorParagraph: 'E' },
              { number: 13, promptHtml: 'Most containers passing through ports are inspected.', answer: { accepted: ['FALSE'] }, explanationHtml: 'Paragraph G: "only a small proportion ... can be inspected".', locatorParagraph: 'G' },
            ],
          },
        ],
      },
      {
        order: 2,
        title: 'Why do we yawn?',
        subtitle: 'Read the text and answer questions 14-26.',
        paragraphs: [
          { label: 'A', html: "<p>Yawning is one of the most familiar of human behaviours, and one of the least understood. We all do it, typically several times a day, and so do most other vertebrates, from fish and birds to dogs and chimpanzees. A yawn follows a regular pattern: a long, deep breath with the mouth wide open, a stretching of the jaw and often of the whole body, and then a shorter breath out. It lasts on average around six seconds and, once started, is almost impossible to stop halfway. People yawn most often in the hour after waking and in the hour before going to sleep, and yawning is also common during periods of boredom or inactivity. Athletes often report yawning before a competition, and musicians before a performance, which suggests that it is not simply a sign of being tired.</p>" },
          { label: 'B', html: "<p>Yawning begins remarkably early. Ultrasound scans have shown that babies yawn in the womb from around the eleventh week of pregnancy. The French doctor Olivier Walusinski, who has spent many years studying the subject, has suggested that yawning at this stage may play a role in the development of the joints and muscles of the jaw and face. Whatever its purpose, the fact that it appears so early suggests that it is a very ancient and basic behaviour.</p>" },
          { label: 'C', html: "<p>The most common popular explanation is that we yawn because we need more oxygen. This idea has been tested and appears to be wrong. In experiments carried out by the American psychologist Robert Provine, volunteers who breathed air with higher levels of carbon dioxide did not yawn more often, and those who breathed pure oxygen did not yawn less. Provine concluded that yawning and breathing are controlled by separate mechanisms. He also observed that physical exercise, which greatly increases the body's need for oxygen, does not make people yawn more, although it certainly makes them breathe faster. Provine went on to study yawning for many years and was among the first scientists to treat it as a serious subject for research rather than a curiosity.</p>" },
          { label: 'D', html: "<p>An alternative theory, proposed by the psychologist Andrew Gallup, is that yawning helps to cool the brain. When we yawn, the deep breath and the stretching of the jaw increase the flow of blood to the head, and the cooler air drawn in may help to carry away heat. In support of this, Gallup found that people yawned less when they held a cold pack against their forehead, and that people were more likely to yawn in moderate temperatures than in very hot or very cold weather. The theory would explain why we often yawn when we are tired or bored, states in which the brain's temperature may rise slightly. Critics point out, however, that the amount of cooling produced by a single yawn is likely to be very small, and that the theory does not easily explain why yawning should be contagious.</p>" },
          { label: 'E', html: "<p>Perhaps the most intriguing feature of yawning is that it is contagious. Seeing, hearing or even reading about someone yawning makes many people yawn themselves. In one study using brain scanning, the neuroscientist Steven Platek found that watching other people yawn activated areas of the brain associated with understanding what others are thinking and feeling. Other researchers have reported that people are more likely to catch a yawn from family members and close friends than from strangers, which has led to the suggestion that contagious yawning is linked to empathy.</p>" },
          { label: 'F', html: "<p>Contagious yawning appears only gradually in childhood, usually around the age of four or five, and some studies have found that it is less common in people who find social interaction difficult. It is not limited to humans. Chimpanzees catch yawns from each other, and in 2008 a team led by the psychologist Atsushi Senju reported that pet dogs yawned after watching a human yawn. Not all researchers accept the link with empathy, however: some large studies involving hundreds of volunteers, who were asked to watch short videos of people yawning while researchers counted how often they yawned in response, have found that the tendency to catch yawns is more strongly related to age, with older people catching yawns less often, than to any measure of social ability.</p>" },
        ],
        questionGroups: [
          {
            id: 't42-r2-matchinfo',
            type: 'matching_information',
            instructionHtml: 'Reading Passage 2 has six paragraphs, A-F. Which paragraph contains the following information? <em>Choose the correct letter, A-F.</em>',
            questions: [
              { number: 14, promptHtml: 'the age at which children start to catch yawns from others', answer: { accepted: ['F'] }, explanationHtml: 'Paragraph F: "usually around the age of four or five".', locatorParagraph: 'F' },
              { number: 15, promptHtml: 'a description of what happens during a yawn', answer: { accepted: ['A'] }, explanationHtml: 'Paragraph A: "a long, deep breath with the mouth wide open, a stretching of the jaw".', locatorParagraph: 'A' },
              { number: 16, promptHtml: 'an explanation for why tiredness may cause yawning', answer: { accepted: ['D'] }, explanationHtml: 'Paragraph D: tired or bored states "in which the brain\'s temperature may rise slightly".', locatorParagraph: 'D' },
              { number: 17, promptHtml: 'a widely held belief that has been shown to be false', answer: { accepted: ['C'] }, explanationHtml: 'Paragraph C: the oxygen explanation "has been tested and appears to be wrong".', locatorParagraph: 'C' },
            ],
          },
          {
            id: 't42-r2-people',
            type: 'matching_features',
            instructionHtml: 'Look at the following statements and the list of researchers below. Match each statement with the correct researcher, <strong>A-E</strong>.',
            bank: [
              { key: 'A', text: 'Olivier Walusinski' },
              { key: 'B', text: 'Robert Provine' },
              { key: 'C', text: 'Andrew Gallup' },
              { key: 'D', text: 'Steven Platek' },
              { key: 'E', text: 'Atsushi Senju' },
            ],
            questions: [
              { number: 18, promptHtml: 'Yawning may help an unborn baby\'s face to develop.', answer: { accepted: ['A'] }, explanationHtml: 'Paragraph B: Walusinski suggested it "may play a role in the development of the joints and muscles of the jaw and face".', locatorParagraph: 'B' },
              { number: 19, promptHtml: 'Animals can catch yawns from a different species.', answer: { accepted: ['E'] }, explanationHtml: 'Paragraph F: Senju\'s team "reported that pet dogs yawned after watching a human yawn".', locatorParagraph: 'F' },
              { number: 20, promptHtml: 'The rate of yawning is not affected by the level of oxygen in the air.', answer: { accepted: ['B'] }, explanationHtml: 'Paragraph C: in Provine\'s experiments, oxygen and carbon dioxide levels made no difference.', locatorParagraph: 'C' },
              { number: 21, promptHtml: 'Seeing someone yawn produces activity in parts of the brain linked to understanding others.', answer: { accepted: ['D'] }, explanationHtml: 'Paragraph E: Platek found it "activated areas of the brain associated with understanding what others are thinking".', locatorParagraph: 'E' },
              { number: 22, promptHtml: 'Cooling the head reduces how often people yawn.', answer: { accepted: ['C'] }, explanationHtml: 'Paragraph D: "people yawned less when they held a cold pack against their forehead".', locatorParagraph: 'D' },
            ],
          },
          {
            id: 't42-r2-sentence',
            type: 'sentence_completion',
            instructionHtml: 'Complete the sentences below. Choose <strong>NO MORE THAN TWO WORDS</strong> from the passage for each answer.',
            wordLimit: { maxWords: 2, label: 'NO MORE THAN TWO WORDS' },
            questions: [
              { number: 23, promptHtml: 'A typical yawn lasts about {{q23}}.', answer: { accepted: ['six seconds', '6 seconds'] }, explanationHtml: 'Paragraph A: "It lasts on average around six seconds".', locatorParagraph: 'A' },
              { number: 24, promptHtml: 'People yawn more often in {{q24}} than in very hot or cold conditions.', answer: { accepted: ['moderate temperatures'] }, explanationHtml: 'Paragraph D: "more likely to yawn in moderate temperatures".', locatorParagraph: 'D' },
              { number: 25, promptHtml: 'People are more likely to catch yawns from family and {{q25}} than from strangers.', answer: { accepted: ['close friends', 'friends'] }, explanationHtml: 'Paragraph E: "from family members and close friends than from strangers".', locatorParagraph: 'E' },
              { number: 26, promptHtml: 'Some large studies suggest that catching yawns is more closely linked to {{q26}} than to social ability.', answer: { accepted: ['age'] }, explanationHtml: 'Paragraph F: "more strongly related to age".', locatorParagraph: 'F' },
            ],
          },
        ],
      },
      {
        order: 3,
        title: 'Do we still need experts?',
        subtitle: 'Read the text and answer questions 27-40.',
        paragraphs: [
          { label: '', html: "<p>Never in history has so much knowledge been so easily available. Anyone with a phone, wherever they happen to be, can look up the symptoms of a disease, the history of a war or the method for repairing a washing machine in seconds. It is tempting to conclude that the expert, the person who has spent years acquiring specialist knowledge, is becoming less necessary. Why pay a professional when the answer is only a search away? Surveys in several countries suggest that trust in experts of many kinds, from scientists to economists, has fallen over the past two decades, and some politicians have openly declared that people have had enough of them.</p>" },
          { label: '', html: "<p>I believe this view rests on a misunderstanding of what expertise is. Knowing facts is only a small part of it. What distinguishes an expert is the ability to judge which facts are relevant, how reliable they are, and what they mean in a particular situation. A patient who reads about a disease online may learn a great deal of information, but a doctor who has seen hundreds of cases knows which symptoms matter, which are misleading, and which combination of signs calls for urgent action. That kind of judgement cannot be downloaded. It is built slowly, through years of practice, mistakes and feedback, and much of it cannot even be put into words: experienced professionals often sense that something is wrong before they can explain why.</p>" },
          { label: '', html: "<p>Indeed, the abundance of information makes expertise more valuable, not less. The internet contains excellent material alongside a great deal that is out of date, incomplete or simply false, and it does not label which is which. Without some knowledge of a subject, it is very difficult to tell a reliable source from an unreliable one. Research on how people search for health information has found that many choose sources that confirm what they already believe, and that confident, simple answers are often preferred to cautious, accurate ones.</p>" },
          { label: '', html: "<p>That said, experts have sometimes contributed to their own loss of public trust. They have made predictions that turned out to be badly wrong, and have not always admitted it. They have often failed to explain their reasoning in language that ordinary people can understand, giving the impression that they regard the public as unable to follow an argument. And on some occasions, experts have been influenced by the interests of those who pay them, which has understandably made people suspicious. When a study of the health effects of a product turns out to have been funded by the company that makes it, it is hardly surprising that the public begins to wonder how many other studies were paid for in the same way. Professional bodies have introduced rules requiring researchers to declare such funding, but these rules are not always followed, and they do little to repair trust once it has been lost.</p>" },
          { label: '', html: "<p>It is also true that expertise has limits. Experts are usually most reliable within a narrow field, and their judgement on matters outside it may be no better than anyone else's. In complex areas such as economics or long-term weather patterns, even the best specialists can only offer probabilities, not certainties. When experts present uncertain predictions as if they were facts, they risk damaging their credibility when events turn out differently.</p>" },
          { label: '', html: "<p>The answer, in my view, is not to abandon expertise but to develop a more mature relationship with it. Citizens should feel free to question experts, and experts should be willing to explain not only what they think but how confident they are and why. A good expert says 'I don't know' when that is the truth, and changes his or her mind when the evidence changes. These are signs of reliability, not of weakness, although they are frequently mistaken for the latter.</p>" },
          { label: '', html: "<p>Schools have a part to play too. Rather than simply teaching facts, which students can easily look up, they should teach students how knowledge is produced: how scientists test ideas, why a single study is rarely conclusive, and how to recognise the difference between an informed opinion and a guess. They should also learn that disagreement between experts is a normal part of how knowledge advances, not evidence that nobody knows anything. Students who understand these things will be better placed both to use expert advice wisely and to recognise when it should be challenged.</p>" },
        ],
        questionGroups: [
          {
            id: 't42-r3-summary',
            type: 'summary_completion_bank',
            instructionHtml: 'Complete the summary using the list of words, A-L, below.',
            bankReusable: false,
            bank: [
              { key: 'A', text: 'judgement' },
              { key: 'B', text: 'facts' },
              { key: 'C', text: 'sources' },
              { key: 'D', text: 'beliefs' },
              { key: 'E', text: 'patients' },
              { key: 'F', text: 'cases' },
              { key: 'G', text: 'answers' },
              { key: 'H', text: 'politicians' },
              { key: 'I', text: 'costs' },
              { key: 'J', text: 'labels' },
              { key: 'K', text: 'machines' },
              { key: 'L', text: 'questions' },
            ],
            stemHtml:
              '<p><strong>What makes an expert?</strong></p><p>Being an expert involves much more than knowing {{q27}}. Experts have the {{q28}} to decide which information is relevant and reliable, based, for example, on having seen many {{q29}}. Online information does not come with {{q30}} that show whether it can be trusted, and people often choose material that supports their existing {{q31}}.</p>',
            questions: [
              { number: 27, answer: { accepted: ['B'] }, explanationHtml: 'Paragraph 2: "Knowing facts is only a small part of it."' },
              { number: 28, answer: { accepted: ['A'] }, explanationHtml: 'Paragraph 2: "That kind of judgement cannot be downloaded."' },
              { number: 29, answer: { accepted: ['F'] }, explanationHtml: 'Paragraph 2: "a doctor who has seen hundreds of cases".' },
              { number: 30, answer: { accepted: ['J'] }, explanationHtml: 'Paragraph 3: the internet "does not label which is which".' },
              { number: 31, answer: { accepted: ['D'] }, explanationHtml: 'Paragraph 3: "sources that confirm what they already believe".' },
            ],
          },
          {
            id: 't42-r3-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, A, B, C or D.',
            questions: [
              { number: 32, promptHtml: 'What does the writer say about the large amount of information online?', options: [{ key: 'A', text: 'It has made experts unnecessary.' }, { key: 'B', text: 'It increases the value of expertise.' }, { key: 'C', text: 'Most of it is unreliable.' }, { key: 'D', text: 'It is mainly used by young people.' }], answer: { accepted: ['B'] }, explanationHtml: 'Paragraph 3: "the abundance of information makes expertise more valuable, not less".' },
              { number: 33, promptHtml: 'Which of the following does the writer give as a reason for loss of trust in experts?', options: [{ key: 'A', text: 'Experts charge too much for their advice.' }, { key: 'B', text: 'Experts have become too numerous.' }, { key: 'C', text: 'Experts have not explained their thinking clearly.' }, { key: 'D', text: 'Experts disagree with each other too often.' }], answer: { accepted: ['C'] }, explanationHtml: 'Paragraph 4: they "failed to explain their reasoning in language that ordinary people can understand".' },
              { number: 34, promptHtml: 'According to the fifth paragraph, experts are most reliable when', options: [{ key: 'A', text: 'they work in a narrow field.' }, { key: 'B', text: 'they make long-term predictions.' }, { key: 'C', text: 'they work in economics.' }, { key: 'D', text: 'they are paid by independent bodies.' }], answer: { accepted: ['A'] }, explanationHtml: 'Paragraph 5: "Experts are usually most reliable within a narrow field".' },
              { number: 35, promptHtml: 'What does the writer suggest schools should do?', options: [{ key: 'A', text: 'teach more facts' }, { key: 'B', text: 'invite experts to give talks' }, { key: 'C', text: 'teach how knowledge is created' }, { key: 'D', text: 'discourage students from using the internet' }], answer: { accepted: ['C'] }, explanationHtml: 'Final paragraph: "they should teach students how knowledge is produced".' },
            ],
          },
          {
            id: 't42-r3-ynng',
            type: 'yes_no_notgiven',
            instructionHtml: YNNG_INSTRUCTION,
            questions: [
              { number: 36, promptHtml: 'It is understandable that people have become suspicious of experts who are influenced by those who pay them.', answer: { accepted: ['YES'] }, explanationHtml: 'Paragraph 4: this "has understandably made people suspicious".' },
              { number: 37, promptHtml: 'Weather forecasters are less reliable than economists.', answer: { accepted: ['NOT GIVEN'] }, explanationHtml: 'The writer mentions both fields but does not compare their reliability.' },
              { number: 38, promptHtml: 'Experts should present uncertain predictions as definite facts to maintain public confidence.', answer: { accepted: ['NO'] }, explanationHtml: 'Paragraph 5: doing so risks "damaging their credibility".' },
              { number: 39, promptHtml: 'Admitting uncertainty is often wrongly seen as a weakness.', answer: { accepted: ['YES'] }, explanationHtml: 'Paragraph 6: "These are signs of reliability, not of weakness, although they are frequently mistaken for the latter."' },
              { number: 40, promptHtml: 'Most students already understand why one study is rarely enough to prove something.', answer: { accepted: ['NOT GIVEN'] }, explanationHtml: 'The writer says schools should teach this but does not say what most students already understand.' },
            ],
          },
        ],
      },
    ],
  },

  listening: {
    durationSec: 1800,
    checkTimeSec: 120,
    parts: [
      {
        order: 1,
        contextText: 'You will hear a man phoning to ask about joining a community choir.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "Hello, Riverside Community Choir, Eleanor speaking." },
          { speaker: 'B', voice: 'david', text: "Oh, hello. I saw your poster in the library and I'm interested in joining. I haven't sung in a choir since I was at school, though. Is that a problem?" },
          { speaker: 'A', voice: 'zira', text: "Not at all. About half our members had never sung in a choir before they joined. You don't need to be able to read music, either. We teach everything by ear." },
          { speaker: 'B', voice: 'david', text: "That's a relief. When do you rehearse?" },
          { speaker: 'A', voice: 'zira', text: "Every Tuesday evening, from half past seven until nine thirty. We used to meet on Thursdays, but we moved because of the hall." },
          { speaker: 'B', voice: 'david', text: "And where are the rehearsals?" },
          { speaker: 'A', voice: 'zira', text: "At St Mark's church hall, on Cavendish Street. There's a car park at the back, but it's quite small, so most people come by bus or walk." },
          { speaker: 'B', voice: 'david', text: "OK. How much does it cost to join?" },
          { speaker: 'A', voice: 'zira', text: "The membership fee is sixty pounds a term. That covers the hall hire and the conductor's fee. We also ask for a small extra payment when we buy new music." },
          { speaker: 'B', voice: 'david', text: "Sixty pounds a term. That seems fair. Do I need to do an audition?" },
          { speaker: 'A', voice: 'zira', text: "No audition. The conductor will just listen to you sing a few notes on your first evening, to find out which part suits your voice. Do you know whether you're a tenor or a bass?" },
          { speaker: 'B', voice: 'david', text: "I've no idea, really. I think my voice is quite low." },
          { speaker: 'A', voice: 'zira', text: "Then you'll probably be a bass. We're always short of men, so you'd be very welcome." },
          { speaker: 'B', voice: 'david', text: "What sort of music do you sing?" },
          { speaker: 'A', voice: 'zira', text: "A real mixture. At the moment we're learning some songs from musicals, and we always do some folk songs from different countries. We give two main concerts a year. The next one is in December, in the town hall, and all the money from ticket sales goes to a local children's hospice." },
          { speaker: 'B', voice: 'david', text: "That's lovely. Is there anything I should bring on the first evening?" },
          { speaker: 'A', voice: 'zira', text: "Just a pencil, so you can mark your music, and a bottle of water. Singing for two hours is thirsty work!" },
          { speaker: 'B', voice: 'david', text: "And who should I ask for when I arrive?" },
          { speaker: 'A', voice: 'zira', text: "Ask for Patrick. He's the membership secretary. That's Patrick Tennant, T-E-double N-A-N-T. He'll give you a welcome pack." },
          { speaker: 'B', voice: 'david', text: "Great. I'll see you next Tuesday, then." },
        ],
        questionGroups: [
          {
            id: 't42-l1-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>ONE WORD AND/OR A NUMBER</strong> for each answer.',
            wordLimit: { maxWords: 1, maxNumbers: 1, label: 'ONE WORD AND/OR A NUMBER' },
            stemHtml:
              '<p><strong>Riverside Community Choir</strong></p>' +
              '<p>• no need to read music: everything is taught by {{q1}}<br/>• rehearsals: {{q2}} evenings, 7.30-9.30<br/>• place: St Mark\'s church hall, {{q3}} Street<br/>• fee: £{{q4}} per term (covers hall and conductor)<br/>• no {{q5}}; conductor listens to find the right part<br/>• likely voice part: {{q6}}</p>' +
              '<p><em>Music and concerts</em><br/>• currently learning songs from {{q7}}<br/>• December concert raises money for a children\'s {{q8}}</p>' +
              '<p><em>First evening</em><br/>• bring a {{q9}} and some water<br/>• ask for Patrick {{q10}}</p>',
            questions: [
              { number: 1, answer: { accepted: ['ear'] }, explanationHtml: '"We teach everything by ear."' },
              { number: 2, answer: { accepted: ['tuesday', 'tuesdays'] }, explanationHtml: '"Every Tuesday evening". They used to meet on Thursdays.' },
              { number: 3, answer: { accepted: ['cavendish'] }, explanationHtml: '"St Mark\'s church hall, on Cavendish Street".' },
              { number: 4, answer: { accepted: ['60', 'sixty'] }, explanationHtml: '"The membership fee is sixty pounds a term."' },
              { number: 5, answer: { accepted: ['audition'] }, explanationHtml: '"No audition."' },
              { number: 6, answer: { accepted: ['bass'] }, explanationHtml: '"Then you\'ll probably be a bass."' },
              { number: 7, answer: { accepted: ['musicals'] }, explanationHtml: '"we\'re learning some songs from musicals".' },
              { number: 8, answer: { accepted: ['hospice'] }, explanationHtml: '"goes to a local children\'s hospice".' },
              { number: 9, answer: { accepted: ['pencil'] }, explanationHtml: '"Just a pencil, so you can mark your music".' },
              { number: 10, answer: { accepted: ['tennant'] }, explanationHtml: 'Spelled "T-E-double N-A-N-T".' },
            ],
          },
        ],
      },
      {
        order: 2,
        contextText: 'You will hear a guide talking to visitors at a botanical garden that has recently reopened.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Good morning, and welcome to the Westfield Botanical Garden. I'm Alan, one of the guides, and I'm delighted to welcome you just a few weeks after the garden reopened to the public." },
          { speaker: 'A', voice: 'david', text: "As some of you may know, the garden was closed for two years. Many people assumed this was because of storm damage, and it's true that we did lose some trees in a storm. But the main reason for the closure was to replace the old heating system in the glasshouses, which was using enormous amounts of energy. The new system uses heat pumps, and our energy bills have fallen by more than half." },
          { speaker: 'A', voice: 'david', text: "The work was paid for mainly by a lottery grant. The city council contributed, but only a small amount." },
          { speaker: 'A', voice: 'david', text: "A few things have changed for visitors. Entry used to be free, and it still is for local residents, but other visitors now pay a small charge. And the opening hours have been extended in summer, so the garden now stays open until eight in the evening from May to August." },
          { speaker: 'A', voice: 'david', text: "We're also very keen to attract more young people, so we've started a programme of evening events aimed at students, with music and talks about plants and the environment." },
          { speaker: 'A', voice: 'david', text: "Now, let me tell you about the different areas of the garden. First, the Rose Garden, just in front of us. This has been completely replanted, and all the roses are now old varieties that were grown in the nineteenth century. It's at its best in June." },
          { speaker: 'A', voice: 'david', text: "Behind it is the Desert House, the largest of the glasshouses. It contains cacti and other plants from dry regions, and some of our cacti are over a hundred years old. Because it's kept very dry, it's also where we store some of our rare seeds." },
          { speaker: 'A', voice: 'david', text: "To the east is the Japanese Garden. It was designed by a garden designer from Kyoto, and it's the quietest part of the garden. We ask visitors not to use their phones there, so that everyone can enjoy the peace." },
          { speaker: 'A', voice: 'david', text: "Next to the main gate is the new Children's Garden. It has a small maze, and children can plant their own seeds in pots and take them home." },
          { speaker: 'A', voice: 'david', text: "The Herb Garden, near the café, contains plants used for cooking and medicine. The café actually uses herbs from this garden in its soups and salads, so do try them." },
          { speaker: 'A', voice: 'david', text: "And finally, the Lake. It's home to a family of otters, which returned to the garden last year for the first time in fifty years. You're most likely to see them early in the morning, so come back one day at opening time if you can." },
          { speaker: 'A', voice: 'david', text: "OK, let's start with the roses." },
        ],
        questionGroups: [
          {
            id: 't42-l2-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, A, B or C.',
            questions: [
              { number: 11, promptHtml: 'What was the main reason for closing the garden?', options: [{ key: 'A', text: 'damage caused by a storm' }, { key: 'B', text: 'to install new heating' }, { key: 'C', text: 'to build a new glasshouse' }], answer: { accepted: ['B'] }, explanationHtml: '"the main reason for the closure was to replace the old heating system".' },
              { number: 12, promptHtml: 'The work was mostly funded by', options: [{ key: 'A', text: 'the city council.' }, { key: 'B', text: 'visitors\' donations.' }, { key: 'C', text: 'a lottery grant.' }], answer: { accepted: ['C'] }, explanationHtml: '"The work was paid for mainly by a lottery grant."' },
              { number: 13, promptHtml: 'Which of the following is true about entry to the garden now?', options: [{ key: 'A', text: 'It is free for local people.' }, { key: 'B', text: 'Everyone must pay.' }, { key: 'C', text: 'It is free in the evenings.' }], answer: { accepted: ['A'] }, explanationHtml: '"it still is [free] for local residents, but other visitors now pay".' },
              { number: 14, promptHtml: 'The new evening events are intended for', options: [{ key: 'A', text: 'families.' }, { key: 'B', text: 'students.' }, { key: 'C', text: 'gardeners.' }], answer: { accepted: ['B'] }, explanationHtml: '"a programme of evening events aimed at students".' },
            ],
          },
          {
            id: 't42-l2-areas',
            type: 'matching_features',
            instructionHtml:
              'What feature does the guide mention for each of the following areas? Choose <strong>SIX</strong> answers from the box and write the correct letter, A-I, next to Questions 15-20.',
            bank: [
              { key: 'A', text: 'plants that are used in the café' },
              { key: 'B', text: 'a place where phones should not be used' },
              { key: 'C', text: 'plants from a particular historical period' },
              { key: 'D', text: 'wild animals that recently returned' },
              { key: 'E', text: 'a place where seeds are kept' },
              { key: 'F', text: 'an activity that visitors can take home' },
              { key: 'G', text: 'a new picnic area' },
              { key: 'H', text: 'guided tours every hour' },
              { key: 'I', text: 'plants for sale' },
            ],
            questions: [
              { number: 15, promptHtml: 'Rose Garden', answer: { accepted: ['C'] }, explanationHtml: '"all the roses are now old varieties that were grown in the nineteenth century".' },
              { number: 16, promptHtml: 'Desert House', answer: { accepted: ['E'] }, explanationHtml: '"it\'s also where we store some of our rare seeds".' },
              { number: 17, promptHtml: 'Japanese Garden', answer: { accepted: ['B'] }, explanationHtml: '"We ask visitors not to use their phones there".' },
              { number: 18, promptHtml: 'Children\'s Garden', answer: { accepted: ['F'] }, explanationHtml: '"children can plant their own seeds in pots and take them home".' },
              { number: 19, promptHtml: 'Herb Garden', answer: { accepted: ['A'] }, explanationHtml: '"The café actually uses herbs from this garden".' },
              { number: 20, promptHtml: 'Lake', answer: { accepted: ['D'] }, explanationHtml: '"a family of otters, which returned to the garden last year".' },
            ],
          },
        ],
      },
      {
        order: 3,
        contextText: 'You will hear two environmental science students, Nadia and Leo, discussing a documentary film they watched for their course.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'zira', text: "So, Leo, what did you think of the documentary about coral reefs?" },
          { speaker: 'B', voice: 'david', text: "I thought it was really well made. The underwater photography was amazing, and I liked the way they followed the same group of scientists over several years." },
          { speaker: 'A', voice: 'zira', text: "Me too. And they explained the science clearly without making it too simple. What did you think was the main message?" },
          { speaker: 'B', voice: 'david', text: "That reefs can recover, if we give them a chance. Most films about reefs are so depressing, but this one was quite hopeful." },
          { speaker: 'A', voice: 'zira', text: "Yes, although I thought they didn't spend enough time on the causes of the damage. They mentioned warming seas, but they hardly talked about pollution from farms, which is a big problem in that area." },
          { speaker: 'B', voice: 'david', text: "That's true. And I would have liked to hear more from the local fishing communities. They only interviewed one fisherman." },
          { speaker: 'A', voice: 'zira', text: "Right. Which part of the restoration work did you find most interesting?" },
          { speaker: 'B', voice: 'david', text: "The coral nurseries, where they grow small pieces of coral on frames before planting them on the reef. I hadn't realised they could grow so fast." },
          { speaker: 'A', voice: 'zira', text: "I was more interested in the part about sound. The way they played recordings of healthy reefs through underwater speakers to attract young fish back to damaged areas." },
          { speaker: 'B', voice: 'david', text: "Oh yes, that was clever. Though I wasn't sure how much difference it really made in the long term." },
          { speaker: 'A', voice: 'zira', text: "Nor was the scientist, to be fair. She said the results were promising but they needed more data." },
          { speaker: 'B', voice: 'david', text: "Now, for our assignment, we have to compare the documentary with the academic research. Did you find any articles?" },
          { speaker: 'A', voice: 'zira', text: "A couple. One of them said that the success rates in the film were higher than in most restoration projects. The film showed a site where almost all the coral survived, but the average is much lower." },
          { speaker: 'B', voice: 'david', text: "So the film was a bit selective. I suppose they wanted a positive story." },
          { speaker: 'A', voice: 'zira', text: "Probably. The other article pointed out that restoration is very expensive, and it can only ever cover a tiny area compared with the size of the reefs. That's something the film didn't mention at all." },
          { speaker: 'B', voice: 'david', text: "We should make that point. Although I'd say the film is still valuable, because it might persuade people to support conservation." },
          { speaker: 'A', voice: 'zira', text: "I agree. So how should we structure our assignment? Shall we start with a summary of the film?" },
          { speaker: 'B', voice: 'david', text: "I think we should keep the summary very short, because the tutor has seen it. Let's spend most of the word count on the comparison with the research." },
          { speaker: 'A', voice: 'zira', text: "Good idea. And we could finish by suggesting what a follow-up film might include." },
          { speaker: 'B', voice: 'david', text: "Like the pollution issue and the cost. OK, let's divide it up." },
        ],
        questionGroups: [
          {
            id: 't42-l3-multi1',
            type: 'multiple_choice_multi',
            instructionHtml: 'Choose <strong>TWO</strong> letters, A-E.',
            questions: [
              {
                number: 21,
                promptHtml: 'Which TWO things did the students like about the documentary?',
                options: [
                  { key: 'A', text: 'the music' },
                  { key: 'B', text: 'the underwater photography' },
                  { key: 'C', text: 'the interviews with fishermen' },
                  { key: 'D', text: 'the clear scientific explanations' },
                  { key: 'E', text: 'the length of the film' },
                ],
                selectCount: 2,
                answer: { accepted: ['B', 'D'] },
                explanationHtml: '"The underwater photography was amazing" and "they explained the science clearly".',
              },
            ],
          },
          {
            id: 't42-l3-multi2',
            type: 'multiple_choice_multi',
            instructionHtml: 'Choose <strong>TWO</strong> letters, A-E.',
            questions: [
              {
                number: 22,
                promptHtml: 'Which TWO criticisms of the documentary do the students make?',
                options: [
                  { key: 'A', text: 'It was too depressing.' },
                  { key: 'B', text: 'It did not deal enough with pollution from farms.' },
                  { key: 'C', text: 'It included too many scientists.' },
                  { key: 'D', text: 'It gave too few views from local fishing communities.' },
                  { key: 'E', text: 'Its scientific explanations were too simple.' },
                ],
                selectCount: 2,
                answer: { accepted: ['B', 'D'] },
                explanationHtml: '"they hardly talked about pollution from farms" and "They only interviewed one fisherman."',
              },
            ],
          },
          {
            id: 't42-l3-mc',
            type: 'multiple_choice_single',
            instructionHtml: 'Choose the correct letter, A, B or C.',
            questions: [
              { number: 23, promptHtml: 'According to Leo, what was the main message of the film?', options: [{ key: 'A', text: 'Reefs are able to recover.' }, { key: 'B', text: 'Most reefs will disappear.' }, { key: 'C', text: 'Scientists disagree about reefs.' }], answer: { accepted: ['A'] }, explanationHtml: '"That reefs can recover, if we give them a chance."' },
              { number: 24, promptHtml: 'Which part of the restoration work did Leo find most interesting?', options: [{ key: 'A', text: 'the use of underwater speakers' }, { key: 'B', text: 'growing coral on frames' }, { key: 'C', text: 'counting young fish' }], answer: { accepted: ['B'] }, explanationHtml: '"The coral nurseries, where they grow small pieces of coral on frames".' },
              { number: 25, promptHtml: 'What was the purpose of playing recordings of healthy reefs?', options: [{ key: 'A', text: 'to frighten away predators' }, { key: 'B', text: 'to help coral grow faster' }, { key: 'C', text: 'to attract young fish' }], answer: { accepted: ['C'] }, explanationHtml: '"to attract young fish back to damaged areas".' },
              { number: 26, promptHtml: 'What did the scientist say about the results of the sound experiment?', options: [{ key: 'A', text: 'More evidence was needed.' }, { key: 'B', text: 'They were disappointing.' }, { key: 'C', text: 'They had been proved.' }], answer: { accepted: ['A'] }, explanationHtml: '"the results were promising but they needed more data".' },
              { number: 27, promptHtml: 'According to one article, the success rates shown in the film were', options: [{ key: 'A', text: 'typical of most projects.' }, { key: 'B', text: 'higher than average.' }, { key: 'C', text: 'based on old data.' }], answer: { accepted: ['B'] }, explanationHtml: '"the success rates in the film were higher than in most restoration projects".' },
              { number: 28, promptHtml: 'What point from the second article did the film not mention?', options: [{ key: 'A', text: 'the cost of restoration' }, { key: 'B', text: 'the effect of rising temperatures' }, { key: 'C', text: 'the number of scientists involved' }], answer: { accepted: ['A'] }, explanationHtml: '"restoration is very expensive ... That\'s something the film didn\'t mention at all."' },
              { number: 29, promptHtml: 'Why does Leo still think the film is valuable?', options: [{ key: 'A', text: 'It is scientifically accurate.' }, { key: 'B', text: 'It may encourage support for conservation.' }, { key: 'C', text: 'It shows a typical restoration site.' }], answer: { accepted: ['B'] }, explanationHtml: '"it might persuade people to support conservation".' },
              { number: 30, promptHtml: 'How do the students decide to organise their assignment?', options: [{ key: 'A', text: 'with a long summary of the film' }, { key: 'B', text: 'with most space given to comparing the film and research' }, { key: 'C', text: 'with a section on how the film was made' }], answer: { accepted: ['B'] }, explanationHtml: '"Let\'s spend most of the word count on the comparison with the research."' },
            ],
          },
        ],
      },
      {
        order: 4,
        contextText: 'You will hear part of a lecture about the history of the pencil.',
        gapAfterSec: 30,
        transcriptLines: [
          { speaker: 'A', voice: 'david', text: "Today, as part of our course on the history of design, I want to look at an object so ordinary that we rarely give it a second thought: the pencil." },
          { speaker: 'A', voice: 'david', text: "The story begins in the sixteenth century in the north of England, in an area now known as the Lake District. There, local people discovered a large deposit of an unusually pure form of graphite. At first, nobody was sure what it was, and it was thought to be a type of lead, which is why we still talk about pencil 'lead' today, even though pencils have never contained any." },
          { speaker: 'A', voice: 'david', text: "One of the first uses of the graphite was very practical. Farmers used it to mark their sheep, so that they could tell which animals belonged to them. It soon became clear that it was also excellent for writing and drawing, because it left a dark mark but could be rubbed out." },
          { speaker: 'A', voice: 'david', text: "The graphite was so valuable that the mine was guarded, and at times it was opened for only a few weeks a year to keep prices high. Early pencils were simply sticks of graphite, often wrapped in string to keep the user's fingers clean." },
          { speaker: 'A', voice: 'david', text: "The next big development came from France. At the end of the eighteenth century, France was at war with Britain and could no longer obtain English graphite. The French government asked an engineer, Nicolas-Jacques Conté, to find an alternative. His solution was to mix powdered graphite of lower quality with clay, form the mixture into thin rods, and bake them in a kiln." },
          { speaker: 'A', voice: 'david', text: "This was a crucial discovery, because by changing the amount of clay, Conté could make the pencil harder or softer. More clay produced a harder pencil and a lighter line. This is the basis of the grading system still used today." },
          { speaker: 'A', voice: 'david', text: "The wooden case also developed over time. The ideal wood needs to be soft enough to sharpen easily but not to split, and in the nineteenth century, manufacturers found that the best was a type of cedar. Most pencils are still made from cedar today." },
          { speaker: 'A', voice: 'david', text: "What about the shape? Early pencils were often round, but many manufacturers switched to a hexagonal shape. There were two reasons. It's more comfortable to hold, and, perhaps more importantly, it doesn't roll off a desk." },
          { speaker: 'A', voice: 'david', text: "In 1858, an American inventor received a patent for attaching a rubber to the end of a pencil. Interestingly, in many European countries, pencils are still usually sold without one." },
          { speaker: 'A', voice: 'david', text: "And finally, colour. In the late nineteenth century, a company began painting its best pencils yellow, which in some countries was associated with high quality, and competitors quickly copied it. So in North America, most pencils are still yellow." },
          { speaker: 'A', voice: 'david', text: "Despite computers and tablets, billions of pencils are still made every year. They're cheap, they work in any temperature, and, unlike pens, they can even write upside down, which is why astronauts have used them in space." },
        ],
        questionGroups: [
          {
            id: 't42-l4-notes',
            type: 'note_completion',
            instructionHtml: 'Complete the notes below. Write <strong>ONE WORD ONLY</strong> for each answer.',
            wordLimit: { maxWords: 1, label: 'ONE WORD ONLY' },
            stemHtml:
              '<p><strong>The history of the pencil</strong></p>' +
              '<p><em>England</em><br/>• pure graphite found; wrongly thought to be {{q31}}<br/>• first used by farmers to mark {{q32}}<br/>• the mine was {{q33}} because the graphite was so valuable<br/>• early pencils wrapped in {{q34}}</p>' +
              '<p><em>France</em><br/>• Conté mixed graphite with {{q35}} and baked it in a kiln<br/>• this allowed pencils to be made harder or {{q36}}</p>' +
              '<p><em>Design</em><br/>• case usually made of {{q37}}<br/>• hexagonal shape: comfortable and does not {{q38}}<br/>• in 1858, a {{q39}} was attached to the end<br/>• in North America, most pencils are painted {{q40}}</p>',
            questions: [
              { number: 31, answer: { accepted: ['lead'] }, explanationHtml: '"it was thought to be a type of lead".' },
              { number: 32, answer: { accepted: ['sheep'] }, explanationHtml: '"Farmers used it to mark their sheep".' },
              { number: 33, answer: { accepted: ['guarded'] }, explanationHtml: '"the mine was guarded".' },
              { number: 34, answer: { accepted: ['string'] }, explanationHtml: '"often wrapped in string".' },
              { number: 35, answer: { accepted: ['clay'] }, explanationHtml: '"mix powdered graphite ... with clay".' },
              { number: 36, answer: { accepted: ['softer'] }, explanationHtml: '"Conté could make the pencil harder or softer".' },
              { number: 37, answer: { accepted: ['cedar'] }, explanationHtml: '"Most pencils are still made from cedar today."' },
              { number: 38, answer: { accepted: ['roll'] }, explanationHtml: '"it doesn\'t roll off a desk".' },
              { number: 39, answer: { accepted: ['rubber', 'eraser'] }, explanationHtml: '"a patent for attaching a rubber to the end of a pencil".' },
              { number: 40, answer: { accepted: ['yellow'] }, explanationHtml: '"in North America, most pencils are still yellow".' },
            ],
          },
        ],
      },
    ],
  },

  writing: {
    durationSec: 3600,
    task1: {
      order: 1,
      minWords: 150,
      recommendedMin: 20,
      promptHtml:
        '<p>The chart below shows sales of books in three formats in one country between 2015 and 2023.</p><p>Summarise the information by selecting and reporting the main features, and make comparisons where relevant.</p>',
      chart: {
        chartType: 'bar',
        title: 'Book sales by format, 2015-2023 (millions of copies)',
        unit: 'million',
        categories: ['2015', '2017', '2019', '2021', '2023'],
        xAxisLabel: 'Year',
        yAxisLabel: 'Copies sold (millions)',
        series: [
          { name: 'Printed books', data: [190, 184, 181, 202, 188] },
          { name: 'E-books', data: [62, 55, 51, 60, 49] },
          { name: 'Audiobooks', data: [8, 12, 19, 31, 42] },
        ],
      },
    },
    task2: {
      order: 2,
      minWords: 250,
      recommendedMin: 40,
      promptHtml:
        '<p>Some people think that museums and art galleries should focus on displaying works from their own country. Others believe they should show works from many different cultures.</p><p>Discuss both these views and give your own opinion.</p>',
    },
  },
};
